### ISSUE TITLE
[BUG] DNS record update failed with 504 after about 2min but no exception was thrown

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/azure-libraries-for-net#1002]
**Describe the bug**
Sometimes ARM returns 504 Gateway Timeout after about 1-2min. However the library throws no exception so the caller is unable to know the operation actually fails.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Use Fiddler to inject **1min delay and 504 response** for DNS A record update request:

![image](https://user-images.githubusercontent.com/858914/76384035-b4ef9380-6398-11ea-9e3c-590d46148e5c.png)

Exported Fiddler rules:

```
<?xml version="1.0" encoding="utf-8"?>
<AutoResponder LastSave="2020-03-11T13:04:20.1331365+08:00" FiddlerVersion="4.6.20171.26113">
  <State Enabled="true" Fallthrough="true" UseLatency="false">
    <ResponseRule Match="EXACT:https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/dnsZones/example.com/A/foobar?api-version=2018-03-01-preview" Action="*delay:60000" Enabled="true" />
    <ResponseRule Match="EXACT:https://management.azure.com/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/dnsZones/example.com/A/foobar?api-version=2018-03-01-preview" Action="C:\Users\work\Desktop\Response.txt" Enabled="true" />
  </State>
</AutoResponder>
```

Response file content(Response.txt):
```
HTTP/1.1 504 Gateway Timeout
Content-Type: application/json; charset=utf-8

{"error":{"details":[],"code":"GatewayTimeout"}}
```

Run the code.

Here is the mock scenario:

![image](https://user-images.githubusercontent.com/858914/76384403-b2da0480-6399-11ea-9112-ef21ed6d7029.png)

***Code Snippet***

```csharp
var creds = new AzureCredentialsFactory().FromServicePrincipal(
    "x", "x", "x",
    AzureEnvironment.AzureGlobalCloud);
var restClient = RestClient.Configure()
    .WithEnvironment(creds.Environment)
    .WithCredentials(creds)
    .Build();

// Use Fiddler proxy
restClient.RootHttpHandler.Proxy = new WebProxy("http://localhost:8888", true);
restClient.RootHttpHandler.UseProxy = true;
restClient.RootHttpHandler.ServerCertificateCustomValidationCallback = (HttpRequestMessage r, X509Certificate2 c, X509Chain ch, SslPolicyErrors e) =>
{
    return true;
};

var azure = Azure.Authenticate(restClient, creds.TenantId)
    .WithSubscription("x");

var zone = azure.DnsZones.GetById("/subscriptions/x/resourceGroups/x/providers/Microsoft.Network/dnszones/example.com");
zone.Update()
    .DefineARecordSet("foobar")
    .WithIPv4Address("1.1.1.1")
    .Attach()
    .ApplyAsync().Wait();
```

**Expected behavior**
The library should throw an exception.

**Screenshots**

**Setup (please complete the following information):**
Windows
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
1.31.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by xccc-msft** [comment]
@ArchangelSDY For now, you could use below workaround. 
```csharp
Task<IDnsZone> task = zone.Update()
	.DefineARecordSet("foobar")
	.WithIPv4Address("1.1.1.1")
	.Attach()
	.ApplyAsync();

if (task == await Task.WhenAny(task, Task.Delay(30 * 1000)))
{
	var res = await task;
}
throw new TimeoutException();
```

**Comment by ArchangelSDY** [comment]
Thanks for looking into it. Two more questions:

* Is it a general issue or just for DNS operations?
* How do you get the magic number `30s`? Is it something hardcoded in SDK or actually up to caller?

**Comment by xccc-msft** [comment]
@ArchangelSDY It should be a general issue in SDK. The built-in retry count is 3 if no retry policy configuration from user end. For the situation you mentioned, it would happen when the responses are code 504 all the time. After that, no more retry action would take place. The potential fix is to throw exception from ClientRuntime side after retry count reduce to 0 and the last response still not a success response.
For 30s, it's just sample timeout. You can set a number works for your project.
