### ISSUE TITLE
How to create a CosmosDB account without replication?

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-libraries-for-net#1006]
**Query/Question**
The fluent API doesn't let me call `Create` or `CreateAsync` unless I configured a region for write replication (using `WithWriteReplication`) before. How do I create an account without replication?

```csharp
    var account = await azure.CosmosDBAccounts
        .Define(accountName)
        .WithRegion(region)
        .WithExistingResourceGroup(resourceGroupNames.Data)
        .WithDataModelSql()
        .WithSessionConsistency()
        .WithWriteReplication(region) // It's the only method I can call here, but I don't want that
        .CreateAsync();
```

***Why is this not a Bug or a feature Request?***
Maybe it's a bug, I don't know; it _looks_ like there's something missing in the fluent API. But maybe it's intentional and I'm just missing something.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: 1.31.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by thomaslevesque** [comment]
Apparently it works if I just specify the same region as in `WithRegion`, but it's not very intuitive.

**Comment by yungezz** [comment]
HI @ChenTanyi  could you pls help to have a look?

**Comment by ChenTanyi** [comment]
@thomaslevesque You can use `WithStrongConsistency` like https://github.com/azure/azure-libraries-for-net/blob/fa30e6d796d00b4c773b39120cfb94729b90839a/Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs#L159. For `SessionConsistency`, I think it always needs a location to write.

**Comment by thomaslevesque** [comment]
@ChenTanyi thanks. I don't really care about the consistency level, since I only have one location, but the API forces me to choose one, which was a bit confusing. If I choose Strong consistency, I don't have to specify a write location.

**Comment by ChenTanyi** [comment]
@thomaslevesque I'm not so sure about if there is default consistency for cosmos DB, but since all DB needs at least one location to write, I think the `WithWriteReplication` does not matter all actually.

**Comment by weidongxu-microsoft** [comment]
@ChenTanyi We might relax the creation part a bit. From portal we seems able to create the cosmos account without any write replication, and the default consistency is session. I think session consistency is still valid even if there is no write replication, since read replication also count in the consistency.

**Comment by ChenTanyi** [comment]
Yeah, I've checked the portal, maybe they use the location as default, we could use it as well.

**Comment by ChenTanyi** [comment]
@thomaslevesque The write replication cannot be removed due to the cosmos API, and I add a function `WithDefaultWriteReplication` for NET 1.33.0 (Released on 10 April).

**Comment by thomaslevesque** [comment]
@ChenTanyi maybe name it `WithDefaultWriteLocation` instead? It's a bit strange to have "replication" in the name when there isn't actually any replication. Otherwise, sounds good to me. Thanks!

**Comment by ChenTanyi** [comment]
@thomaslevesque Yes, it is not the replication for the first location. But due to the consistent, we cannot change it into write location, which will make large breaking change. And actually, its comment is "Sets a write location".
