### ISSUE TITLE
[QUERY]How to list metrics definition of application insights log-based metric?

### ISSUE THREAD

**Issue by imeya** [Azure/azure-libraries-for-net#1012]
**Query/Question**
How to list metrics definition of application insights log-based metric?

***Why is this not a Bug or a feature Request?***
Not sure if it's a bug.

**Setup (please complete the following information if applicable):**
 - OS: windows 10
 - IDE : vs 2017
 - Microsoft.Azure.Management.Fluent, version 1.31.1
 
**details**

I try to list all the metrics definition of application insights log-based metric, like the metric definition **Events**.

the code like below:

           //I get this value from azure portal with develop tool in edge browser.
            metric_namespace="microsoft.insights/components/kusto"
 
            foreach (var metricDefinition in azure.MetricDefinitions.ListByResource(resource_id,metric_namespace))
            {
                Console.WriteLine(metricDefinition.Name.Value);
            }

But it throws error, say the metric_namespace should be "microsoft.insights/components". If I specify this value, then it only lists the metrics definition of standard metrics.

**Comment by weidongxu-microsoft** [comment]
Hello service team,

Do we have some approach to get this metric definition? It is not in "microsoft.insights" namespace.

```
               "customEvents/count":{
                  "supportedAggregations":[
                     "sum"
                  ],
                  "displayName":"Events",
                  "supportedGroupBy":{
                     "all":[
                        "customEvent/name",
                        "operation/name",
                        "operation/synthetic",
                        "operation/syntheticSource",
                        "user/authenticated",
                        "application/version",
                        "client/type",
                        "client/model",
                        "client/os",
                        "client/city",
                        "client/stateOrProvince",
                        "client/countryOrRegion",
                        "client/browser",
                        "cloud/roleName",
                        "cloud/roleInstance"
                     ]
                  },
                  "defaultAggregation":"sum"
               }
```

**Comment by vgorbenko** [comment]
Log-based metrics are _specific to Application Insights_ and use a different API from Azure metrics. The API is described at https://dev.applicationinsights.io/documentation/Using-the-API/Metrics 

* Behind the scene, log-based metrics are translated into KQL queries that you can see [here](https://docs.microsoft.com/azure/azure-monitor/platform/app-insights-metrics). 
* More about the difference between log-based metrics and pre-aggregated metrics can be found [here](https://docs.microsoft.com/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics)

**Comment by imeya** [comment]
@vgorbenko , I know the api. I wonder if can we use sdk to query them?

**Comment by vgorbenko** [comment]
@imeya, you should be able to use https://docs.microsoft.com/dotnet/api/microsoft.azure.applicationinsights.applicationinsightsdataclient.getmetricsmetadatawithhttpmessagesasync?view=azure-dotnet

**Comment by imeya** [comment]
@vgorbenko , thanks. But I'm wondering, why we should use different sdk for that? It would be good if we can add metric_namespace="microsoft.insights/components/kusto".

**Comment by vgorbenko** [comment]
@imeya, the "microsoft.insights/components/kusto" is not really a namespace but rather a constant used inside of Metrics Explorer implementation, to indicate that the query layer should call the log-based metrics API for AppInsights instead of Azure-wide metrics API. Check [Supported metrics with Azure Monitor](https://docs.microsoft.com/azure/azure-monitor/platform/metrics-supported) for a list of available namespaces and metrics.
