### ISSUE TITLE
Implement .WithPlatformImage()

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-libraries-for-net#103]
I tried to use the API to create a managed disk based on a platform image, but the method does not exist (based on my reading of the code).  I wanted to customize an existing platform image, and the easiest way to do that is to start with a platform image.

I am refering to the API here: https://docs.microsoft.com/en-us/rest/api/compute/manageddisks/disks/disks-create-or-update for _Create a managed disk from a platform image_.

I was able to workaround the issue with the following code.

```csharp
  var imageId = String.Format("/subscriptions/{0}/providers/Microsoft.Compute/locations/{1}/publishers/{2}/ArtifactTypes/vmimage/offers/{3}/skus/{4}/versions/{5}",
        subId,
        Region.USSouthCentral.Name,
        "credativ",
        "Debian",
        "9",
        "latest");
        
    var disk = azure.Disks.Define("mydebian9md")
        .WithRegion(Region.USSouthCentral)
        .WithExistingResourceGroup("my-md00")
        // .WithPlatformDisk(imageId)
        .WithLinuxFromDisk(imageId);
 
    // override the implementation to get the correct JSON document generated.       
    dynamic d = disk;
    var creationData = new CreationData(DiskCreateOption.FromImage, null, new ImageDiskReference(imageId, null), null, null);
    d.Inner.CreationData = creationData;
```

**Comment by anuchandy** [comment]
Fluent layer intentionally hide this option. Once we create a managed disk using `FromImage` with a platform image as source, the only way to use that disk as OS Disk is via "Attach" option. When VM is created with "Attach" option platform will boot the VM as is, without specializing the VHD, this means user won't be able to set user credentials for the VM. At this point VM is un-usable. "FromImage" is used by compute resource provider internally as part of creation of VM with implicit managed disk.
