### ISSUE TITLE
Check if a resource supports tags

### ISSUE THREAD

**Issue by tony6636** [Azure/azure-libraries-for-net#1037]
**Question**
According to https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support, the list is quite extensive, so is it possible to check if a given resource supports tags ?

**Setup**
Version of the Library used: 
 - Microsoft.Azure.Management.Fluent v1.32.0
 - Microsoft.Azure.Management.ResourceManager.Fluent v1.32.0
 

 **Information Checklist**
- [x] Question Added
- [x] Setup information Added

**Comment by yungezz** [comment]
I don't think there's general interface to check if a resource supports tag

**Comment by xccc-msft** [comment]
@tony6636 We don't have APIs for checking tags availablity.
By checking [Tag related APIs](https://docs.microsoft.com/en-us/rest/api/resources/tags/createorupdateatscope) provided from Azure REST APIs, it looks you could create tags at scope level. The potential solution is to verify the error message when the resource doesn't support tags. For further usage, you may try [Azure .NET SDK](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/resources/Microsoft.Azure.Management.Resource/src/Generated/TagsOperationsExtensions.cs#L266).

**Comment by rthorn17** [comment]
There is no interface that can tell you if the resource supports tags.  Azure keeps the Tag support doc updated to show what is currently supported.  

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support
