### ISSUE TITLE
Unauthorised response when calling Graph API methods using local PFX file authentication

### ISSUE THREAD

**Issue by alanmk** [Azure/azure-libraries-for-net#104]
I'm currently unable to use Graph API functionality when authenticating via local PFX files. 

It looks like the problem's [here](https://github.com/Azure/azure-libraries-for-net/blob/367c89ff76a31016fa2ea5f278022fd3d9b0dc83/src/ResourceManagement/ResourceManager/Authentication/AzureCredentials.cs#L128) i.e. the `ProcessHttpRequestAsync `method of `AzureCredentials `is not passing the `ActiveDirectoryServiceSettings `object into `LoginSilentAsync`.

**Comment by hovsepm** [comment]
fix should be available in v1.7
