### ISSUE TITLE
[FEATURE REQ] Support for Azure Resource Graph

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#1042]
**Is your feature request related to a problem? Please describe.**
Would love to interact with Azure Resource Graph to query for resources

**Comment by tomkerkhove** [comment]
Is this supported already? If so, sorry about that but it was not clear in the docs.

**Comment by yungezz** [comment]
hi @tomkerkhove ResourceGraph isn't support.  Could you pls try Microsoft.Azure.Management.ResourceManager.Fluent

**Comment by tomkerkhove** [comment]
Does it give the same capability to query with a KSQL statement?

**Comment by yungezz** [comment]
Sounds like what you need is data plane operation. add @xccc-msft to help look at if there's data plane support for Resource Graph

**Comment by xccc-msft** [comment]
@tomkerkhove ResourceGraph is not supported in Fluent. You might want to use this [ResourceGraph SDK](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceGraph/) instead. And here is the [source code](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/resourcegraph/Microsoft.Azure.Management.ResourceGraph) for it.

**Comment by tomkerkhove** [comment]
Thanks!
