### ISSUE TITLE
[FEATURE REQ] Add BeginCreate to Virtual Machines

### ISSUE THREAD

**Issue by pbstrein** [Azure/azure-libraries-for-net#1043]
**Is your feature request related to a problem? Please describe.**
We want to create Virtual Machines and to poll the status of their creation without waiting for the VM to be completely provisioned. This can be done by the [Rest API](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/async-operations), but it is not supported in the Fluent SDK. 

**Describe the solution you'd like**
Implementing a BeginCreate for Virtual Machines would allow VMs to start creating, and letting the control be passed back to other services. An operation ID could be returned that could be used to check the status of the VM creation. This would follow what can be done with the Rest API, but be done through the C# SDK. 

**Describe alternatives you've considered**
We have considered using Deployments, as it has the BeginCreate functionality already created. However, it does not work great in our scenario because we are strictly working with VMs, and not many other resources, so using the SDKs directly would be the easiest/cleanest approach. 

**References**
This is related the following issues:
- https://github.com/Azure/azure-libraries-for-java/issues/1007
- https://github.com/Azure/azure-libraries-for-java/issues/8
- https://github.com/Azure/azure-sdk-for-net/issues/3411

**Comment by qub1n** [comment]
That would be really nice...

**Comment by weidongxu-microsoft** [comment]
In current SDK, there are a few options.

1. standard .NET async/await via `createAsync` method

E.g. batch call `createAsync` and collect the `Task`s, then call `Task.WhenAll` to collect the results.

2. call an inner method to only begin the create

E.g. `VirtualMachineInner vmInner = azure.VirtualMachines.Manager.Inner.VirtualMachines.BeginCreateOrUpdateAsync(rgName, vmName, new VirtualMachineInner()...).Result;`

Downside is `VirtualMachineInner` object is harder to configure.

---

Let me know if any of these would suit your need.

**Comment by pbstrein** [comment]
@weidongxu-microsoft 
Option 2, `VirtualMachineInner vmInner = azure.VirtualMachines.Manager.Inner.VirtualMachines.BeginCreateOrUpdateAsync(rgName, vmName, new VirtualMachineInner()...).Result` fits my needs for creating VMs. 

However, as mentioned I also need a polling option. Using `GetByResourceGroup` would not return any errors that occured in the middle of creation, only give the status of creation (eg `Created`, `Failed`, `InProgress`, etc.) Currently I have to make my own REST client to do polling actions from the result from `Azure-AsyncOperation` to get any errors that may have occurred during VM creation. (Otherwise, all errors would get lost due to async functionality.) This polling could be exposed in the Fluent SDK, instead of creating a seperate REST client. 

In general, if the functionality exists in the `Inner` to do "BeginCreate", why can't we add that as part of the general Fluent SDK API? It would contain all the information that the above mentioned function would return, and include the Azure-AsyncOperation to query later. Another option would be to return the "OperationId" as part of the request to be put into another Fluent SDK API to build up the operation status.

**Comment by weidongxu-microsoft** [comment]
@pbstrein 

The design of the SDK is to abstract customer away from all the complexity of the querying on the result. There is 5+ classes under [LRO](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/LRO), all purpose of which is to do this query correctly, for different operation and for different scenarios / response.

If your use case requires checking the result of the operation, I would suggest option 1. Maybe you can let us know what went wrong in option 1, maybe we can help.

If you stick to option 2, please aware that as mentioned, the situation could be very complicated.
Here is sample code to do this. It is for illustration purpose, and certainly not covering all cases:

```
    // send begin operation request
    AzureOperationResponse<StorageAccountInner> beginOperationResponse = azure.StorageAccounts.Manager.Inner.StorageAccounts.BeginCreateWithHttpMessagesAsync(resourceGroupName, name, new StorageAccountCreateParameters()
    {
        Location = "southcentralus",
        Kind = Kind.BlobStorage,
        AccessTier = AccessTier.Hot,
        Sku = new SkuInner()
        {
            Name = Microsoft.Azure.Management.Storage.Fluent.Models.SkuName.StandardLRS
        }
    }, null, CancellationToken.None).Result;

    // get operation query url
    //string operationUrl = response.Response.Headers.GetValues("Azure-AsyncOperation").FirstOrDefault();
    string operationUrl = beginOperationResponse.Response.Headers.GetValues("Location").FirstOrDefault();
    operationUrl = operationUrl.Replace(" ", "%20");
    HttpRequestMessage operationRequest = new HttpRequestMessage();
    operationRequest.Method = HttpMethod.Get;
    operationRequest.RequestUri = new Uri(operationUrl);

    // do something else, below is query code

    var rm = azure.ManagementClients.Where(c => c is IResourceManagementClient).DefaultIfEmpty(null).FirstOrDefault() as IResourceManagementClient;
    IAzureClient azureClient = (rm as IAzureClient);
    // send query request for operation status
    azureClient.Credentials.ProcessHttpRequestAsync(operationRequest, CancellationToken.None).Wait();
    HttpResponseMessage operationResponse = azureClient.HttpClient.SendAsync(operationRequest, CancellationToken.None).Result;
    string responseContent = operationResponse.Content.ReadAsStringAsync().Result;
    // check response code and body for status
```

The query URL could be in either `Location` header, or `Azure-AsyncOperation` header.

For test purpose it is async converted to sync. Naturally all is async method.

The begin operation could be completed directly (I think with 200 response), if there is light operation, or the resource is already there and no need to configure.

**Comment by pbstrein** [comment]
@weidongxu-microsoft 

I understand that most people don't need the polling of the operation (hence why it is abstracted away.) However, allowing a BeginCreate and a polling API would allow greater flexibility on how the SDK could be used (as an example, see my use case below). So my request is that we add a BeginCreate, which under the hood could do everything you showed above in Option 2. 

The following is my use case, explaining why I must rely on option 2 instead of option 1. 
I have two micro-services:
Microservice 1: Handles management of infrastructure by communicating with Microservice 2. 
Microservice 2: Handles provisioning/deletion of infrastructure using SDKs.
Because Microservice 1 is handling management of infrastructure, it needs to know the state of the VM (including operations to know what to poll). However, it delegates provisioning to Microservice 2. Option 1 does not allow Microservice 1 to have any insight into VM provisioning until it is finished (and if Microservice 2 crashed or any other issue, then Microservice 1 would never be able to find any errors or information about the VM.) Hence why option 2 is the only option that works in my scenario because it is the only option that gives flexibility to create resources async and hand information to other management microservices for later management. 

Here is a picture explaining my use case. 
![HighLevelApporach](https://user-images.githubusercontent.com/21132293/80000761-2ab04a00-8483-11ea-9ec8-6d7030a56502.jpg)

**Comment by pbstrein** [comment]
I noticed that https://github.com/Azure/azure-libraries-for-java/issues/1007 has a flag for v2. Is this feature only being planned for the Java SDK but not the .NET? If so, why is that?

**Comment by weidongxu-microsoft** [comment]
@pbstrein 

Thanks. I think I understand your use case. I assume you provision the resource in microservice2 and manage it in microservice1. I would assume that there is certain communication between the two, at least for request/notification.

One possible solution is to separate the begin operation and query operation, former happen in microservice2, latter happen in microservice1. Provided that there is certain approach to send a serialized object from 2 to 1.

Sample code:

```
// on microservice2, begin operation
            AzureOperationResponse<StorageAccountInner> beginOperationResponse = azure1.StorageAccounts.Manager.Inner.StorageAccounts.BeginCreateWithHttpMessagesAsync(resourceGroupName, name, new StorageAccountCreateParameters() 
            { 
                Location = "southcentralus",
                Kind = Kind.BlobStorage,
                AccessTier = AccessTier.Hot,
                Sku = new SkuInner()
                {
                    Name = Microsoft.Azure.Management.Storage.Fluent.Models.SkuName.StandardLRS
                }
            }, null, CancellationToken.None).Result;

// send beginOperationResponse object from 2 to 1

// on microservice1, query operation
            StorageManagementClient client2 = (azure2.StorageAccounts.Manager.Inner as StorageManagementClient);
            StorageAccountInner storageAccount = client2.GetLongRunningOperationResultAsync(beginOperationResponse, null, CancellationToken.None).Result.Body;
```

However note this is still kind of hack than a real solution.

---

The issue on Java https://github.com/Azure/azure-libraries-for-java/issues/1007 is only for expose the beginOperation, as the `BeginCreateWithHttpMessagesAsync` in sample code. And Java got very different async mechanism.
It uses RxJava or Reactor, which is lazy evaluation.

---

As you have noted, track2 .NET SDK is going to phase out the current track1 Fluent .NET SDK. But track2 SDK is not released yet.

And due to this situation, we are not likely to do big upgrade to current track1 SDK.

If it is new adoption, I would suggest try align it with new track2 SDK. (the hack above will definitely break on migration to track2)

cc @dingmeng-xue

**Comment by pbstrein** [comment]
@weidongxu-microsoft

Awesome! I didn't know there was a track2 SDK coming out. Is there a link to the track2 .NET SDK? If not, is there a link to the progress of the track2 .NET so I can watch when it will get released / know it's progress? I am working on a new adoption, so aligning with the new track2 would be best to start working on now,

In addition, are the basic capabilities that I am asking for (create a VM in microservice 2 and poll it's status in microservice 1) available in the track2 SDK? And could the "BeginCreate" feature I am asking for be put in the track2 SDK?

***

Yes, you understand my situation exactly. The solution you gave is what we are looking into doing. Good to know we were on the right track. We will continue down that route it until a "BeginCreate" functionality gets added (whether in track1 or track2).

**Comment by weidongxu-microsoft** [comment]
@pbstrein 

Track2 is not released, and I guess it would still take a few months. For details you can query on https://github.com/Azure/azure-sdk-for-net

Refer https://www.youtube.com/watch?v=0tKXe1wOqI8

Here is a before-preview sample code on Storage.
https://github.com/pakrym/azure-sdk-for-net/blob/pakrym/storage-management/sdk/storage/Azure.Management.Storage/samples/Program.cs

It appears that the begin/query is similarly separated to 2 methods, hence the approach might work there as well.
https://github.com/pakrym/azure-sdk-for-net/blob/pakrym/storage-management/sdk/storage/Azure.Management.Storage/src/Generated/Operations/StorageAccountsClient.cs#L336-L337

**Comment by nickzhums** [comment]
@pbstrein Thanks for your feedback on .NET SDK. Track 2 .NET SDK will be in public preview in end of May/early June timeline, we will publish annoucement on the github repo. You are very welcome to try it and give us feedback

**Comment by Drewm3** [comment]
Closing out old feature requests that have no engagement in last 12 months.
