### ISSUE TITLE
[QUERY]: Looking to create ScheduledQueryRules for log alerts

### ISSUE THREAD

**Issue by kazman71** [Azure/azure-libraries-for-net#1049]
Looking to programmatically add Kusto queries for scheduled log alerts and I can't figure out how this might be done.  I can see the AlertRules.Manager.Inner.ScheduledQueryRules object, but I can't seem to understand how to specify the query.  Any help would be appreciated.  

Thanks in advance,
James

**Comment by yungezz** [comment]
hi @weidongxu-microsoft do you have a quick answer? thanks

**Comment by weidongxu-microsoft** [comment]
@kazman71 

It is not supported as Fluent API.

You can invoke it directly by
```
azure.MetricDefinitions.Manager.Inner.ScheduledQueryRules.CreateOrUpdateAsync
```

**Comment by kazman71** [comment]
Thank you very much for the quick response - I will give it a try!

**Comment by kazman71** [comment]
@weidongxu-microsoft 

Is there any example code using the LogSearchRuleResourceInner object with this API?  I seem to be getting a serialization error during the CreateOrUpdateAsync based on the contract.   See the images below.  Could it be the period in the property names?


![image](https://user-images.githubusercontent.com/6991201/80248825-8adef180-8625-11ea-9359-70b2298903b2.png)

![image](https://user-images.githubusercontent.com/6991201/80248781-769af480-8625-11ea-96df-2af3350fb047.png)

**Comment by weidongxu-microsoft** [comment]
@kazman71 

The "dot" in the property name should be fine. It only means e.g. "properties.description" should be serialized to nested "description" under "properties", as in the sample.

Could you include the code of your configure and error stack?

Thanks.

**Comment by kazman71** [comment]
Thanks for the response.  I seem to have narrowed it down to the Action parameter of LogSearchRuleResourceInner .  When I create a new AlertingAction object and  make the CreateOrUpdateAsynCall it will fail with the message: "Error reading string. Unexpected token: StartObject. Path 'error.message', line 4, position 16."

If I query for an existing rule and use the action object returned from an already created rule the createorupdate will succeed.  Thanks for looking into it.  When I serialize the the the input object to json it is seems the same as when I query for an already existing alert's schema. 

Here is the code to create the log alert:
            var locationString = "centralus";    //// TBD

            var appInsightsResourceId = await GetValue(deployment.Variables.Environment, "applicationInsightsResourceId", logger);
            var kustoQuery = await GetValue<string>(deployment.Variables.Component, "alertQuery", logger);
            var resourceId = await GetValue<string>(deployment.Variables.Component, "resourceId", logger);
            var resourceIdList = new List<string>()
            {
            };

            var querySource = new Source(appInsightsResourceId, kustoQuery, resourceIdList, QueryType.ResultCount);
            querySource.Validate();

            var alertSeverityString = (int)await GetValue<System.Int64>(deployment.Variables.Component, "alertSeverity", logger);
            var alertSeverity = MapIntToAlertSeverity(alertSeverityString);

            var conditionalOperatorString = await GetValue<string>(deployment.Variables.Component, "conditionalOperator", logger);
            var conditionalOperator = MapStringToConditionalOperator(conditionalOperatorString);
            var thresholdValue = await GetValue<System.Int64>(deployment.Variables.Component, "thresholdValue", logger);

            var metricTriggerType = MetricTriggerType.Total;
            string metricColumn = null;
            var logMetricTrigger = new LogMetricTrigger(conditionalOperator, thresholdValue, metricTriggerType, null);

            var alertTrigger = new TriggerCondition(conditionalOperator, thresholdValue, logMetricTrigger);
            alertTrigger.Validate();

            var actionGroupResourceId = await GetValue(deployment.Variables.Environment, "actionGroupResourceID", logger);
            var actionGroupList = new List<string>()
            {
                actionGroupResourceId
            };

            var actionGroup = new AzNsActionGroup(actionGroupList, "", "");
            var throttlingInMin = 5;   //// TBD
            var action = new AlertingAction(alertSeverity, alertTrigger, actionGroup, null);
            action.Validate();

            var alertName = "KazRule001";
            var alertType = "microsoft.insights/scheduledqueryrules";

            var alertDescription = await GetValue<string>(deployment.Variables.Component, "alertDescription", logger);
            var alertEnabled = Enabled.True;
            var frequencyInMinutes = (int)await GetValue<System.Int64>(deployment.Variables.Component, "frequencyInMinutes", logger);
            var timeWindowInMinutes = (int)await GetValue<System.Int64>(deployment.Variables.Component, "timeWindowInMinutes", logger);

            var alertSchedule = new Schedule(frequencyInMinutes, timeWindowInMinutes);
            alertSchedule.Validate();

            try
            {
                var monitoringResourceGroupName = await GetValue(deployment.Variables.Environment, "monitoringResourceGroupName", logger);
                var queryRules = await azure.MetricDefinitions.Manager.Inner.ScheduledQueryRules.ListByResourceGroupAsync(monitoringResourceGroupName);
                var existingRule = queryRules.First();
                var testSource = new Source( existingRule.Source.DataSourceId, "requests greater", existingRule.Source.AuthorizedResources, existingRule.Source.QueryType);
                var testAction = (Microsoft.Azure.Management.Monitor.Fluent.Models.Action) new AlertingAction(alertSeverity, alertTrigger, actionGroup, null);
                var logAlertRule = new LogSearchRuleResourceInner(locationString, testSource, testAction, 
                                                                    null, alertName, alertType, 
                                                                    new Dictionary<string, string>(), alertDescription, alertEnabled, null, null, alertSchedule);
                logAlertRule.Validate();

                string output = JsonConvert.SerializeObject(logAlertRule, Formatting.None, new JsonPathConverter());
                string output2 = JsonConvert.SerializeObject(existingRule, Formatting.None, new JsonPathConverter());
                
                //var queryRuleCopy = await azure.MetricDefinitions.Manager.Inner.ScheduledQueryRules.CreateOrUpdateAsync(monitoringResourceGroupName, alertName, existingRule);
                var queryRuleNew = await azure.MetricDefinitions.Manager.Inner.ScheduledQueryRules.CreateOrUpdateAsync(monitoringResourceGroupName, alertName, logAlertRule);

                return queryRuleNew;
            }
            catch (Exception ex)
            {
                var test = ex.Message;
            }
            return null;

![image](https://user-images.githubusercontent.com/6991201/80423831-7a34b280-8895-11ea-9685-d66864a6006e.png)

**Comment by weidongxu-microsoft** [comment]
@kazman71 

This appears to be an error message like this:
```
{
  "error": {
    "code": "'properties.schedule.timeWindowInMinutes' was specified as 1, it should be a value between 5 and 2880.",
    "message": {
      "lang": "en-US",
      "value": "'properties.schedule.timeWindowInMinutes' was specified as 1, it should be a value between 5 and 2880."
    }
  }
}
```

But it is not handled correctly due to a faulty delegating handler in middle.

When testing, please try this to init Azure (avoid `Azure.Authenticate(credentials)...`).
```
            AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromFile(AUTH_FILE);

            RestClient restClient = RestClient
                .Configure()
                .WithEnvironment(AzureEnvironment.AzureGlobalCloud)
                .WithCredentials(credentials)
                .Build();

            IAzure azure = Azure.Authenticate(restClient, tenantId)
                .WithSubscription(subscriptionId);
```
which would bypass that faulty delegating handler.

After the resource being created correctly, you can discard this code and revert to usual init code (be aware as previous error message, some setting is acceptable, other is not).

Then you should be able to read the correct exception (should be an ErrorResponseException inside AggregateException), Response field of which would contain the error message from server.

Or you can print the log as
https://github.com/Azure/azure-libraries-for-net#logging

**Comment by kazman71** [comment]
Thank you very much!  I am all up and running now!

I appreciate the tie you took and the prompt answers.

James
