### ISSUE TITLE
[BUG] Diagnostic settings throwing NullReferenceException when dealing with subscription diagnostic settings

### ISSUE THREAD

**Issue by ni-reis** [Azure/azure-libraries-for-net#1062]
**Bug description**
I'm trying to use IAzure.DiagnosticSettings to define and create a diagnostic setting for a subscription resource (`/subscriptions/{subscriptionId}`). The current implementation reaches the HTTP request code; the request succeeds and the diagnostic setting gets created, however, when parsing the response, it fails to read the metrics (as they are null) and throws a NullReferenceException.

**Exception message and stack**
{"Object reference not set to an instance of an object."}
at Microsoft.Azure.Management.Monitor.Fluent.Models.DiagnosticSettingImpl.SetInner(DiagnosticSettingsResourceInner inner) in C:\\Users\\reisn\\work\\azure-libraries-for-net-master\\src\\ResourceManagement\\Monitor\\DiagnosticSettingImpl.cs:line 139

**To Reproduce**
You can authenticate to fluent client with a service principal and invoke the method to create a diagnostic setting for the subscription resource. Here is a script that does it, streaming logs to an event hub:

```
using Microsoft.Azure.Management.Fluent;
using Microsoft.Azure.Management.ResourceManager.Fluent;
using System.Threading.Tasks;

namespace TestProject
{
    class Program
    {
        private const string ClientId = "<CLIENT ID>";
        private const string ClientSecret = "<CLIENT SECRET>";
        private const string TenantId = "<TENANT ID>";
        private const string SubscriptionId = "<SUBSCRIPTION ID>";
        private const string SubscriptionResourceId = "/subscriptions/" + SubscriptionId;

        private const string AuthorizationRuleId = "<AUTHORIZATION RULE ID>";
        private const string EventHubName = "<EVENT HUB NAME>";

        static async Task MainAsync()
        {
            var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(
                ClientId, ClientSecret, TenantId, AzureEnvironment.AzureGlobalCloud);

            var fluentClient = Azure
                .Authenticate(credentials)
                .WithSubscription(SubscriptionId);

            await fluentClient.DiagnosticSettings
                .Define("myDiagnosticSetting")
                .WithResource(SubscriptionResourceId)
                .WithEventHub(AuthorizationRuleId, EventHubName)
                .WithLog("Administrative", 1)
                .CreateAsync();
        }

        static void Main(string[] args)
        {
            MainAsync().Wait();
        }
    }
}

```

**Expected behavior**
The expected behavior would be for the parse complete successfully and don't throw the exception.

**Screenshots**
![Diagnostic setting resource gets created](https://nireisstorage.blob.core.windows.net/images/diagnostic%20setting.PNG)
![Exception is thrown when creating object from response](https://nireisstorage.blob.core.windows.net/images/exception.PNG)

**Setup**
 - OS: Windows 10
 - IDE: Visual Studio 2019 Preview
 - Version of the Library used: I believe it was 1.33.0 (I'm not sure, as I downloaded the latest code version and used it locally).

**Additional context**
This might be by design, and, I'm not sure if the support for subscription diagnostic setting falls in the bug category or in the feature request category. I'll try to link a commit id that solves the issue :)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ni-reis** [comment]
I pushed a commit to my fork that deals with the issue - https://github.com/ni-reis/azure-libraries-for-net/commit/73d8125444faec6149e17a9d7764a9ff1aca0f63. I would like to know if it's ok to raise a PR for that. Thank you!

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls help to have a quick look at the contribution change  ni-reis@73d8125. ? thanks.

**Comment by weidongxu-microsoft** [comment]
@ni-reis 

The code looks good. Would you open a PR for it? Don't mind about CI, I would check the tests after the PR.

**Comment by ni-reis** [comment]
Thank you, @yungezz and @weidongxu-microsoft! I will open the PR for it.

I saw only a doc referring to collecting and analyzing Activity logs - https://docs.microsoft.com/en-us/azure/azure-monitor/platform/activity-log-collect , though the document directs to a legacy experience.

**Comment by weidongxu-microsoft** [comment]
@ni-reis 

After more dig-up, there is actually 2 different APIs.

One with generic `{resourceUri}` is from [diagnosticsSettings_API](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/diagnosticsSettings_API.json#L39)

And the one for subscription is from [subscriptionDiagnosticsSettings_API](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2017-05-01-preview/subscriptionDiagnosticsSettings_API.json#L39)

The complication is that response of 2 API is different (`DiagnosticSettingsResource` and `SubscriptionDiagnosticSettingsResource`, respectively). Hence it would be a better practice to put them to 2 different code flow (peferrable a `SubscriptionDiagnosticSettings` flow), instead of trying to share single code flow.

This will take more time. I will try work on it a bit later.

**Comment by ni-reis** [comment]
I see, so you mean that the ideal solution would creating something like
`IAzure.SubscriptionDiagnosticSettings`?

**Comment by weidongxu-microsoft** [comment]
Yes. One more complexity is that subscriptionDiagnosticsSettings_API only exist for [package-2019-11](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/readme.md#tag-package-2019-11) and later, while current code is using tag package-2019-06 (hence the code for subscription dignostics settings is not in SDK yet).

**Comment by ni-reis** [comment]
Got it. Is there any version upgrade in plan? After this, would the code be generated automatically (or at least some part of it)?

**Comment by weidongxu-microsoft** [comment]
We will try to upgrade the generated code next week (after which the inner API should be callable, e.g. `azure.DiagnosticSettings.Manager.Inner.SubscriptionDiagnosticSettings.CreateOrUpdateAsync`).

Is there any schedule on your part?

**Comment by ni-reis** [comment]
We can use a temporary work around, but we would need the feature by mid June.

**Comment by weidongxu-microsoft** [comment]
OK. We will schedule accordingly.

@yungezz

**Comment by ni-reis** [comment]
Sounds good. Thank you! 😃

**Comment by weidongxu-microsoft** [comment]
Next release scheduled on 12 June.
