### ISSUE TITLE
[QUERY] Get WebApp deployment info using the fluent management SDK?

### ISSUE THREAD

**Issue by sebader** [Azure/azure-libraries-for-net#1064]
**Query/Question**
Is there a way through the management SDK to get this deployment info for an App Service?
![image](https://user-images.githubusercontent.com/11445087/81830268-259f6180-953c-11ea-9f25-5cd97c7adf06.png)

***Why is this not a Bug or a feature Request?***
Maybe it will be a feature request if this is actually not possible.

**Setup (please complete the following information if applicable):**
 - OS: [e.g. iOS] Windows
 - IDE : [e.g. IntelliJ] VS
 - Version of the Library used 1.33
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
I think the API is not exposed yet. You can try
```
azure.WebApps.Inner.ListDeploymentsAsync(resourceGroupName, webappName)
```

**Comment by sebader** [comment]
thank you @weidongxu-microsoft ! this helps indeed! The only thing you need to do manually is to deserialize the `Message` string which contains the actual information about deployed BuildIds etc.

**Comment by sebader** [comment]
@weidongxu-microsoft do you want to make the missing part aroung the `Message` content into a feature request? otherwise I'm fine to close this one.

**Comment by weidongxu-microsoft** [comment]
@sebader

I see, the message is actually a JSON.

From service spec this message is just a string. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2019-08-01/WebApps.json#L20800-L20803

For now I think you had to de-serialize it by yourself.

**Comment by sebader** [comment]
ok got it. thanks!
