### ISSUE TITLE
[Question]How to create a KeyVaultManagementClient

### ISSUE THREAD

**Issue by wangfeichen** [Azure/azure-libraries-for-net#1065]
**Query/Question**
I tried update my KeyVault.Fluent SDK to newest SDK but got trouble when create a KeyVaultManagementClinet. Currently KeyVaultManagementClient required a `RestClient` not `ServiceClientCredentials`. And I have no idea how to get/create a RestClient.

```
var client = new KeyVaultManagementClient(restClinet);
```

***Why is this not a Bug or a feature Request?***
No idea how to create a KeyVaultManagementClient.

**Setup (please complete the following information if applicable):**
 - OS: win10
 - IDE : visual studio 2019
 - Version of the Library used: Microsoft.Azure.Management.KeyVault.Fluent.Models 1.33.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
sample code

```
            AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromFile(AUTH_FILE);
            RestClient restClient = RestClient.Configure()
                    .WithEnvironment(credentials.Environment)
                    .WithCredentials(credentials)
                    .Build();
```
