### ISSUE TITLE
[Bug] KeyVualtManagementClient Cannot Set Access Policy ?

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-libraries-for-net#1067]
**Describe the bug**
Use `KeyVualtManagementClient` set access policy wont work, and from portal the access policy is unknown status,
![image](https://user-images.githubusercontent.com/25993729/81904617-17158080-95f6-11ea-9405-74dd941c2434.png)

***Exception or Stack Trace***
{"Service request failed.\r\nStatus: 403 (Forbidden)\r\n\r\nContent:\r\n{\"error\":{\"code\":\"Forbidden\",\"message\":\"The user, group or application '';oid='';iss=https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/' does not have secrets set permission on key vault 'vault0512test;location=westus'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287\",\"innererror\":{\"code\":\"AccessDenied\"}}}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nServer: Microsoft-IIS/10.0\r\nx-ms-keyvault-region: westus\r\nx-ms-request-id: REDACTED\r\nx-ms-keyvault-service-version: 1.1.3.0\r\nx-ms-keyvault-network-info: conn_type=Ipv4;addr=167.220.255.73;act_addr_fam=InterNetwork;\r\nX-AspNet-Version: REDACTED\r\nX-Powered-By: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Thu, 14 May 2020 07:14:53 GMT\r\nContent-Length: 435\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\n"}

**To Reproduce**
1. git clone https://github.com/wantedfast/BugReport
2. open that project and specify required parameters, F5 to run. 

**Expected behavior**
Can set secret successfully. and in the portal access policy blade can see that access policy.
![image](https://user-images.githubusercontent.com/25993729/81906024-2990b980-95f8-11ea-9e63-e2db19cec7c4.png)

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@wantedfast Can you please share the code snippet how you define the access policy? Thanks.

**Comment by wantedfast** [comment]
@xccc-msft 
Code snippet below:
```
        private static VaultCreateOrUpdateParameters GetVaultCreateOrUpdateParameters(string tenantId, string location, string objectId)
        {
            var properties = new VaultProperties
            {
                TenantId = Guid.Parse(tenantId),
                Sku = new Sku(),
                AccessPolicies = new List<AccessPolicyEntry>(),
                CreateMode = CreateMode.Default
            };

            properties.AccessPolicies.Add(new AccessPolicyEntry
            {
                TenantId = properties.TenantId,
                ObjectId = objectId,
                Permissions = new Permissions
                {
                    Secrets = new SecretPermissions[] { SecretPermissions.Get, SecretPermissions.Set }
                }
            });

            return new VaultCreateOrUpdateParameters(location, properties);
        }
```

And this link can get my sample project: https://github.com/wantedfast/BugReport

**Comment by xccc-msft** [comment]
@wantedfast Can you check if this [sample](https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/KeyVault/ManageKeyVault.cs) helps?

**Comment by wantedfast** [comment]
@xccc-msft Yes, I do confirm that sample will work.  i just wondering if it's a bug or Is there something wrong of my sample code provided?

**Comment by xccc-msft** [comment]
@wantedfast You may capture the http requests both our sample and your sample code to check what's the difference.
