### ISSUE TITLE
The requested operation cannot be performed on this container because of a concurrent operation

### ISSUE THREAD

**Issue by korensiso** [Azure/azure-libraries-for-net#1070]
**Query/Question**
Recently, we are seeing the following error returned from the Azure fluent SDK as a result of the Azure REST API returned 409 (conflict Http return code) when we try to delete blob container:
The requested operation cannot be performed on this container because of a concurrent operation

The error message is pretty clear and helped us to understand the root of the problem in our code - we concurrently tried to delete the same container twice. 
The thing is that this buggy code already exists for a few versions of our product and we never saw it happen before, while now, we see it reproduce a lot. I would appreciate your help to understand if this is something that was changed recently in Azure backend or might be a change in the Azure SDK.

***Why is this not a Bug or a feature Request?***
This is a question about a behavior change.

**Setup (please complete the following information if applicable):**
 - OS: windows server 2016
 - IDE : Visual Studio 2019
 - Version of the Library used: 1.26.0

**Comment by blueww** [comment]
@korensiso 

Would you share the SDK name and SDK version for the Azure fluent SDK? So we can find the proper team to help you.
It would be better also share the sample code to repro the issue (hid credential), and the server request ID of the issue repro.

**Comment by blueww** [comment]
@weidongxu-microsoft,  @xccc-msft 
I see you have raise the latest 2 changes to Microsoft.Azure.Management.Storage.Fluent, would you please help to look at this issue?

**Comment by weidongxu-microsoft** [comment]
@blueww I think there is no change in SDK about the behavior. SDK generally just give same error as RP gives when it is 400+ (client error range).

SDK got some change on socket timeout and TaskCancelled in last couple of months, but it is not relate to this issue.

So my guess is that it is service behavior.

**Comment by blueww** [comment]
@korensiso 
If SDK has no change on this, would you please share the request ID for repro steps (sample code) for this?
Please also share the detail error reported from server, include the error message.

**Comment by amishra-dev** [comment]
Please reactivate with requested data if you are still facing this issue.
