### ISSUE TITLE
Outputs is always an empty collection when deploying a resource group

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-libraries-for-net#108]
I'm able to deploy a resource group using the SDK. However, my RG returns a set of outputs which are not shown in the object model (even after calling `Refresh()` on the deployment). I've tested the same ARM template through the Azure CLI and the outputs are correctly returned.

**Comment by isaacabraham** [comment]
Apologies, raised in error. It does come back, just as a JObject which was showing in FSI as an empty sequence for some reason.

**Comment by shreyagarwal1991** [comment]
> Apologies, raised in error. It does come back, just as a JObject which was showing in FSI as an empty sequence for some reason.

I am still seeing Outputs from DeploymentImpl as null.
