### ISSUE TITLE
Full MSAL integration + current user attributes

### ISSUE THREAD

**Issue by coreazure-jd** [Azure/azure-libraries-for-net#1081]
I am using the DeviceLogin flow for a custom CLI tool as I want requests to be made with the actual user's credentials and authorizations. The AzureCredentialsFactory.FromDevice login is suboptimal compared with the flows available in the MSAL libraries (AcquireTokenInteractive primarily) and the AzureCliCredentials.Create() is only using the Security Principal login (which is also quite fiddly).

I also then need access to the current user's ObjectId and EmailAddress (and other attributes) but cannot seem to get to the token credentials, they're buried in private members in the implementation.

Is there planned work to use the MSAL interactive login? And can the user credentials (or at least the non-sensitvie attributes be made available?)
Perceived Implementation:
1. AzureCredentialsFactory.InteractiveLogin calls AcquireTokenInteractive
2. Credential attributes (user email address, objectid, tenantid, subscriptions) exposed as a public property (say of the IAzure interface or by one of the Manager interfaces.

**Comment by yungezz** [comment]
hi  @coreazure-jd MSAL will be supported in new generation of .NET SDK which is in repo https://github.com/Azure/azure-sdk-for-net. The SDK will be preview soon. Add @nickzhums .

**Comment by coreazure-jd** [comment]
Thanks for the response. Forgive me if I feel too old to get excited at the prospect of one SDK/library being replaced by another one but I look forward to appreciating its benefits.
