### ISSUE TITLE
[BUG] User should be Use in Obsolete msg.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-libraries-for-net#1088]
Here

https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Domain/IResourceGroups.cs#L45

Has
        [Obsolete("User ContainAsync() instead.")]

Should be:

        [Obsolete("Use ContainAsync() instead.")]

azsdke2e

**Comment by yungezz** [comment]
https://github.com/Azure/azure-libraries-for-net/pull/1089

**Comment by weidongxu-microsoft** [comment]
Fixed by you :-)
https://github.com/Azure/azure-libraries-for-net/pull/1089

Thanks for the contribution.
