### ISSUE TITLE
[BUG] internal class AzureFirewallImpl in namespace Microsoft.Azure.Management.Network.Fluent has the code from line 1761-1764 mistaken. It shoul be: if (natRule.Protocols == null) { 	natRule.Protocols = new List<AzureFirewallNatRuleProtocol>(); } instead of if (networkRule.Protocols == null) { 	networkRule.Protocols = new List<AzureFirewallNetworkRuleProtocol>(); }

### ISSUE THREAD

**Issue by MohaRady** [Azure/azure-libraries-for-net#1091]
**Describe the bug**

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Thanks for the detailed info. Expect to be fixed in next version (1.34.1 if no major feature/fix).

**Comment by MohaRady** [comment]
Thank you
