### ISSUE TITLE
[BUG] Upgrade runtime version

### ISSUE THREAD

**Issue by Aequoris** [Azure/azure-libraries-for-net#1095]
The Microsoft.Azure.Management.ResourceManager.Fluent uses an old version of Microsoft.IdentityModel.Tokens.

If the customer is using the most recent version of Microsoft.IdentityModel.Tokens, this causes an error during restore.

The only way to solve is an explicit reference to the latest version of Microsoft.IdentityModel.Tokens in the customer project, which is not turnkey.

**Why it happens?**
Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.0 had an upper bound on the version number of Microsoft.IdentityModel.Tokens that excluded the most recent versions

**How to fix?**
Microsoft.Rest.ClientRuntime.Azure.Authentication has issued a patch relaxing the upper bound. They have released it as 2.4.1

To fix, goto the file
azure-libraries-for-net/src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.ResourceManager.Fluent.csproj

And alter the line
   ` <PackageReference Include="Microsoft.Rest.ClientRuntime.Azure.Authentication" Version="2.4.0" />`
to
    `<PackageReference Include="Microsoft.Rest.ClientRuntime.Azure.Authentication" Version="2.4.1" />`

**Expected behavior**
For a restore to happen, without throwing an error if any other projects use the most recent version of Microsoft.IdentityModel.Tokens

Thank you. :)

**Comment by sala91** [comment]
Bump!

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Could you take a look whether we should upgrade the dependency, or set a larger range on versions?

**Comment by xccc-msft** [comment]
According to the Microsoft.Rest.ClientRuntime.Azure.Authentication [2.4.1 fix](https://github.com/Azure/azure-sdk-for-net/pull/12897), I have created #1165 for the upgrade. We will update once it gets released. Thanks.
