### ISSUE TITLE
[QUERY] WindowsAzure.Storage.9.3.3 is a deprecated dependency - can we get it updated?

### ISSUE THREAD

**Issue by Tankzor** [Azure/azure-libraries-for-net#1097]
**Query/Question**
Hi team, similar to #625 bug report (I think)..

`Microsoft.Azure.Management.ContainerInstance.Fluent.1.34.0`, `Microsoft.Azure.Management.EventHub.Fluent.1.34.0`, `Microsoft.Azure.Management.Sql.Fluent.1.34.0` reference deprecated package `WindowsAzure.Storage.9.3.3`. 

It seems like it has been deprecated since October 2018.

Is an update to the maintained packages (`Azure.Storage.Blobs` etc..) planned? Or can we see if that can happen?

Cheers!

***Why is this not a Bug or a feature Request?***
Just asking about updating a dependency.

**Setup:**
 - Version of the Library: 1.34.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by yungezz** [comment]
hi @Tankzor .NET fluent libraries are in passive maintain mode, we'll not release new version unless critical security issue etc. The next generation of .NET SDKs is in preview, detail at https://github.com/Azure/azure-sdk-for-net#Management-New-Releases. cc @nickzhums .

**Comment by Tankzor** [comment]
Thanks @yungezz , I wasn't aware of that. Cheers :)
