### ISSUE TITLE
[BUG] Recreating an existing Function App generates a new file share

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-libraries-for-net#1105]
**Describe the bug**
I have a deployed Function App, on a consumption plan. WEBSITE_CONTENTSHARE points to a file share on the linked storage account.
When I recreate the Function App with the same settings, WEBSITE_CONTENTSHARE is forced to a new random value:

https://github.com/Azure/azure-libraries-for-net/blob/82aa32a8db867f4ef27ce376a3ee7210f9694bbd/src/ResourceManagement/AppService/FunctionAppImpl.cs#L150

Since this new file share is empty, the function app no longer works until I redeploy the code.

Apparently this is intentional, but doesn't make sense when redeploying an existing function app. And there's no way to work around the issue: if I explicitly specify a value for WEBSITE_CONTENTSHARE, it's overridden with the random value.

The only thing I can do is force the setting back to its original value after I recreate the resource...

***Exception or Stack Trace***
N/A

**To Reproduce**
Create a Function App with the code snippet below.
Deploy some code to it, ensure that it works.
Recreate the function app
=> The function no longer works. WEBSITE_CONTENTSHARE has been set to a new value and no points to a file share where the code is not deployed.

***Code Snippet***
```csharp
            var functionApp = await azure.AppServices.FunctionApps
                .Define(MakeResourceName("sync"))
                .WithRegion(deploymentOptions.Region)
                .WithExistingResourceGroup(resourceGroup)
                .WithNewConsumptionPlan()
                .WithExistingStorageAccount(storageAccount)
                .WithRuntimeVersion("3")
                .WithAppSettings(new Dictionary<string, string>
                {
                    ["AzureWebJobsDashboard"] = storageAccountConnectionString,
                    ["AzureWebJobsServiceBus"] = serviceBusConnectionString,
                    ["AzureWebJobsStorage"] = storageAccountConnectionString,
                    ["APPINSIGHTS_INSTRUMENTATIONKEY"] = appInsightsInstrumentationKey,
                    ["APPLICATIONINSIGHTS_CONNECTION_STRING"] = $"InstrumentationKey={appInsightsInstrumentationKey}",
                    ["FUNCTIONS_EXTENSION_VERSION"] = "~3",
                    ["FUNCTIONS_WORKER_RUNTIME"] = "dotnet",
                    ["WEBSITE_RUN_FROM_PACKAGE"] = "1"
                })
                .CreateAsync();
```

**Expected behavior**
It shouldn't override the existing value of WEBSITE_CONTENTSHARE

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS 2019
 - Version of the Library used: 1.34.0

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Next release would be 1.34.1

**Comment by thomaslevesque** [comment]
That was fast, thanks @weidongxu-microsoft!

**Comment by thomaslevesque** [comment]
Note: the code in my original message had another problem (not a bug in the SDK, just in my code): it creates a new consumption every time the function app is recreated. To avoid this, explicitly create an app service plan and use it explicitly in the function with `WithExistingAppServicePlan`. However there's no obvious way to explicitly create a new consumption plan (see #1107)
