### ISSUE TITLE
Add support for HTTPS Only on AppService/WebApp

### ISSUE THREAD

**Issue by asalvo** [Azure/azure-libraries-for-net#111]
There is a new setting for AppServices/WebApps under Custom domains called HTTPS Only. When enabled,  all HTTP traffic will be redirected to HTTPS. I would like to be able to set this using the Fluent API. 

![image](https://user-images.githubusercontent.com/164835/33531286-7e1ed5f8-d850-11e7-92a9-1c7253bc9ea8.png)

**Comment by luthus** [comment]
Any progress on this?

**Comment by yaohaizh** [comment]
@xccc-msft, please take a look at this issue and follow up with @weidongxu-microsoft for his previous work on support https.

**Comment by weidongxu-microsoft** [comment]
@asalvo @luthus

It is already supported. Please use `WithHttpsOnly()` when create/update the web app.
