### ISSUE TITLE
[BUG] Key Vault Secret.ListVersionsAsync() doesn't return an IEnumerable

### ISSUE THREAD

**Issue by SiobhanBaynes** [Azure/azure-libraries-for-net#1110]
**Describe the bug**
The sync version of Key Vault `secret.ListVersions()` correctly returns an `IEnumerable<ISecret>`.  However the async version returns a `Task<ISecret>`.  `ListVersionsAsync` always returns null when called.

***Exception or Stack Trace***
No exception is thrown.

**To Reproduce**
Create a Key Vault with a secret, create a console app, add the `Microsoft.Azure.Management.Fluent` library and then the code below.  Fill in the blanks from your service principal and Key Vault.

***Code Snippet***
```
public async Task GetVersions ()
{
	var keyVaultId = "<<KeyVaultResourceid>>";
	var azureCredentials = new AzureCredentialsFactory().FromServicePrincipal("<<ClientId>>","<<ClientSecret>>", "<<TenantId>>", AzureEnvironment.AzureGlobalCloud);
	var azure = Azure
		.Configure()
		.WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
		.Authenticate(azureCredentials)
		.WithSubscription("<<SubscriptionId>>");
	var vault = await azure.Vaults.GetByIdAsync(keyVaultId);
	var secret = (await vault.Secrets.ListAsync()).FirstOrDefault();
	var value = secret.ListVersions();
	var valueAsync = (await secret.ListVersionsAsync());
}
```

**Expected behavior**
I would expect the values in `value` and `valueAsync` to be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/9945953/88054538-77282600-cb55-11ea-8064-9458755405ed.png)
![image](https://user-images.githubusercontent.com/9945953/88054722-b8b8d100-cb55-11ea-83cc-902cd2a2b9d6.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - 1.34.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [ x] Repro Steps Added
- [ x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Would you take a look when you have time?

**Comment by xccc-msft** [comment]
@SiobhanBaynes Thanks for reporting this. I just created #1115 to fix this. Thanks.
