### ISSUE TITLE
Implement RestartPolicy for Container Instances

### ISSUE THREAD

**Issue by JimiSmith** [Azure/azure-libraries-for-net#112]
Container instances can now have a restart policy applied to them in the latest version of the REST API but I cannot see this exposed in the fluent interface. Is it possible to add this? Thanks

**Comment by milismsft** [comment]
+ @seanmck 
The restart policy option for container instances is currently available in Azure CLI only at this time. To enable it inside the Azure SDK for Java I will need an update to the Swagger spec which describes the new REST APIs; hopefully this will be available soon.

**Comment by milismsft** [comment]
Fix will be shipped in v1.7 version of the Fluent SDK
