### ISSUE TITLE
[BUG] WebApps.ListByResourceGroup and WebApps.ListByResourceGroupAsync does not return API web apps

### ISSUE THREAD

**Issue by gaclique** [Azure/azure-libraries-for-net#1120]
**Describe the bug**
API Web app services on azure are not being returned in these calls.  Standard web app services do come back without any issues. 

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
Create new API App service on Azure

***Code Snippet***
```
var allApps= await this.Portal.AppServices.WebApps.ListByResourceGroupAsync(resourceGroupName);

            foreach (var app in allApps.ToList())
            {
                _logger.Info($"Found {app.Name}");
            }
```

**Expected behavior**
API app service should be included in this list.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - VS 2019
 - 1.34

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@gaclique 

It might be caused by: the "kind" property is missing or does not contains "app" (there is another keyword "functionapp" in "kind" property, which belongs to FunctionApp).

If you can, would you paste a sample HTTP response here?
Logging can be enabled as https://github.com/Azure/azure-libraries-for-net#logging

**Comment by gaclique** [comment]
I have attached 2 files.  One is the response for an API app service and the other is the response log for a Web App service

[APIAppService.txt](https://github.com/Azure/azure-libraries-for-net/files/5035197/APIAppService.txt)
[WebAppService.txt](https://github.com/Azure/azure-libraries-for-net/files/5035198/WebAppService.txt)

**Comment by gaclique** [comment]
Additional logging attached.  It looks like the "kind" property is returning "api" instead of "app" for API Web service.

[ResponseLog.txt](https://github.com/Azure/azure-libraries-for-net/files/5035314/ResponseLog.txt)

**Comment by weidongxu-microsoft** [comment]
@gaclique 
Thanks. I see, it is the API app. We need a bit more internal investigate on whether we should put it as WebApp, or need a new class.

**Comment by weidongxu-microsoft** [comment]
From doc, there appears no different among the 2. We will include kind=api in list response.
