### ISSUE TITLE
[QUERY] Does Fluent SDK support multiple Availability Zones for VMSS?

### ISSUE THREAD

**Issue by TarekAljabban** [Azure/azure-libraries-for-net#1129]
**Query/Question**
Does Fluent SDK support multiple Availability Zones for VMSS?

***Why is this not a Bug or a feature Request?***
Not sure if this is supported or not . If the answer comes back as "not supported", I'll create a feature request. 

**Details**
 I want to create zone-redundant VMSS (i.e. deployed to multiple Availability Zones).

This is straightforward when done using [Portal, CLI or ARM template](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones).

But when trying to accomplish this with Fluent client, I cannot find a way to specify multiple availability zones. The closest thing I could find is [WithAvailabilityZone](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.fluent.virtualmachinescaleset.definition.iwithavailabilityzone.withavailabilityzone?view=azure-dotnet), but it allows only a single Availability Zone as a parameter.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help to check if this is supported?

**Comment by xccc-msft** [comment]
@TarekAljabban Please check the [implementation](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/implementation/VirtualMachineScaleSetImpl.java#L2290-L2301) of `withAvailabilityZone`. You may call it multiple times with different zone ids.

**Comment by TarekAljabban** [comment]
@xccc-msft this works. Thank you!
