### ISSUE TITLE
[BUG] Creating a function app, does not create _master and default key

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-libraries-for-net#1138]
**Describe the bug**
Currently, when provisioning a Function App via fluent sdk, the `_master` key and `default` Host keys are not created.

There is also no possibility to specify them. 

After creating also the function `GetMasterKey` fails with an exception.

**To Reproduce**
1. Create resource group
1. Create app service plan (linux)
1. Create storage account
1. Create managed identity
1. Create function app

***Code Snippet***
```
functionApp = azure.AppServices.FunctionApps
    .Define(functionAppName)
    .WithExistingAppServicePlan(appServicePlan)
    .WithExistingResourceGroup(resourceGroup)
    .WithExistingStorageAccount(storageAccount)
    .DefineDiagnosticLogsConfiguration()
        .WithWebServerLogging()
            .WithWebServerLogsStoredOnFileSystem()
            .WithLogRetentionDays(3)
            .WithDetailedErrorMessages(true)
            .WithFailedRequestTracing(true)
            .Attach()
    .DefineDiagnosticLogsConfiguration()
        .WithApplicationLogging()
            .WithLogLevel(Microsoft.Azure.Management.AppService.Fluent.Models.LogLevel.Error)
            .WithApplicationLogsStoredOnFileSystem()
            .WithDetailedErrorMessages(true)
            .WithFailedRequestTracing(true)
            .Attach()
    .WithoutPhp()
    .WithHttp20Enabled(true)
    .WithHttpsOnly(true)
    .WithWebAppAlwaysOn(true)
    .WithWebSocketsEnabled(true)
    .WithManagedIdentity(managedIdentity, true)
    .WithAppSettings(appSettings)
    .Create();
```

**Expected behavior**
The master and _default Host Key should be created, as it is when creating it via portal or cli.

**Screenshots**
* Via Fluent SDK
![image](https://user-images.githubusercontent.com/1763806/92240983-c59f4300-eebd-11ea-9406-65682f50c1d9.png)
* Via Portal / Azure Cli
![image](https://user-images.githubusercontent.com/1763806/92241129-05fec100-eebe-11ea-8cfa-e30c18ae45f3.png)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studion
 - 1.34

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yungezz** [comment]
hi @weidongxu-microsoft do you have a quick answer on is this a feature missing for bug?

**Comment by cmenzi** [comment]
Hi @yungezz @weidongxu-microsoft 

I figured out the issue. It's because of the storage account. I did 

```csharp
storageAccount = azure.StorageAccounts
    .Define(storageAccountName)
    .WithRegion(azureEnvironment.CloudRegion)
    .WithExistingResourceGroup(resourceGroup)
    .WithGeneralPurposeAccountKindV2()
    .WithAccessFromAzureServices()
    .WithOnlyHttpsTraffic()
    .WithBlobStorageAccountKind()
        .WithAccessTier(AccessTier.Hot)
    .WithBlobEncryption()
    .WithFileEncryption()
    .Create();
```

It seams that `WithAccessFromAzureServices` does not allow the function to create the required containers.

When I remove this, then it works.
