### ISSUE TITLE
[BUG] Operation returned an invalid status code 'NoContent'

### ISSUE THREAD

**Issue by cdifino** [Azure/azure-libraries-for-net#1139]
**Describe the bug**
When I call : Microsoft.Rest.Azure.CloudException at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperations+<DeleteByIdWithHttpMessagesAsync>d__10.MoveNext

I get a Cloud Exception error with the following message: 
Operation returned an invalid status code 'NoContent'

***Exception or Stack Trace***

ExceptionMessage | Operation returned an invalid status code 'NoContent'

 ExceptionStackTrace | at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperations.<DeleteByIdWithHttpMessagesAsync>d__10.MoveNext()    at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperationsExtensions.<DeleteByIdAsync>d__5.MoveNext()    at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsImpl.<DeleteByIdAsync>d__12.MoveNext()    at Microsoft.Substrate.EuclidCore.Azure.AADRoleAssignmentManager.<UnassignRoleAsync>d__9.MoveNext()    at Microsoft.Substrate.AI.Sandbox.SandboxProviders.MSITSandboxManagementService.<UnassignUserRoleAsync>d__9.MoveNext()    at Microsoft.Substrate.AI.Sandbox.SandboxProviders.BaseSandboxManagementService`1.<RemoveUserMemberFromSandboxAsync>d__35.MoveNext()    at Microsoft.Substrate.AI.Factory.NotificationsHelper.<RemoveUserMemberFromSandboxAsync>d__5.MoveNext()    at Microsoft.Substrate.AI.Factory.NotificationsHelper.<>c.<<SubscribeForNotifications>b__3_3>d.MoveNext()    at Microsoft.Substrate.AI.Workspace.WorkspaceMembersService.<DeleteAsync>d__11.MoveNext()    at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()    at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()    at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()    at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()    at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()    at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()    at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

ExceptionType | Microsoft.Rest.Azure.CloudException

**To Reproduce**
No steps to reproduce, seems like we are not handling correctly the return status code when calling the following function:
 this.azureConnection.AccessManagement.RoleAssignments.DeleteByIdAsync(roleAssignment.Id);

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 
 - Version of the Library used: 
Microsoft.Azure.Management.Fluent.1.9.1\lib\net452\Microsoft.Azure.Management.Fluent.dll 

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [ x] Setup information Added

**Comment by snaheth** [comment]
Hi @cdifino - Followed up with you to get your correlationId, subscriptionId, and resourceGroup info to look at this further. Thanks for getting back to me with it.

You're getting this 204 No Content status code when you're attempting to delete an already deleted roleAssignment - you sent out a request at T = 0 that returned at T = 4 with a 200 response, which is why a request (fired at T = 1) returns a 204.

We should do a better job by making this clearer in our documentation. From the message `ExceptionMessage | Operation returned an invalid status code 'NoContent'`, it's not clear to me if that's coming from your code or the .NET SDK. Currently, it looks like it's the latter so we'll work to get that fixed when we can confirm where it's happening.

**Comment by snaheth** [comment]
I found the [.NET SDK code](https://github.com/Azure/azure-sdk-for-net/blob/7939914c3a3b1a3616bbbff9926d4369e3dd567b/sdk/authorization/Microsoft.Azure.Management.Authorization/src/Generated/RoleAssignmentsOperations.cs#L220:#L253) which leads to this exception. Your best shot is to catch the CloudException, knowing that a 204 represents that that the RoleAssignment you're trying to delete does not exist (in your case, it's already been deleted).

Additional context on DELETE calls to ARM APIs:
A 200 (OK) is returned if the object exists and was deleted successfully. A 204 (NoContent) is returned if the resource does not exist and the request is well formed.
