### ISSUE TITLE
[FEATURE REQ] Add mapping from Region to Area

### ISSUE THREAD

**Issue by muiriswoulfe** [Azure/azure-libraries-for-net#1142]
**Is your feature request related to a problem? Please describe.**
We have a need to map Azure Regions to a smaller set of Azure Regions, while maintaining data locally as far as possible.

By way of example, assume that the input Azure Region can be any valid value while the output can be `USWest`, `EuropeNorth` or `EastAsia`. In this case, all Americas inputs would map to `USWest`, all European inputs would map to `EuropeNorth` and all Asian inputs would map to `EastAsia`. We can deal with other regions similarly, but I'm not including them here to simplify the description.

**Describe the solution you'd like**
A mapping from the [`Region`](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Region.cs) to an area would be great.

For instance, the first group of regions in `Region.cs` correspond to the Americas and it would be great to be able to retrieve that continent information programmatically, ideally through an `enum` value.

**Describe alternatives you've considered**
A workaround is to build a mapping dictionary locally. This will work for our needs now, but it will have maintainability issues as new regions added to Azure won't be possible to map until the dictionary is updated. Adding this directly into the `Region` class would mitigate this issue.

**Additional context**
I'm happy to implement this solution if the feature is approved.

I am aware that there is some ambiguity in how to implement this feature given the multiple mappings possible -- e.g. `USWest` could go to an `Americas` or `US` Region. Either would work for us, so two options would be to use the region determination from the Azure Region name or to use the groupings within the `Region` file. I acknowledge that there is probably no one size fits all here.

**Information Checklist**
- [X] Description Added
- [X] Expected solution specified

**Comment by yungezz** [comment]
hi @muiriswoulfe  .NET fluent SDK is in passive maintenance mode. There's new generation .NET SDK previewed at https://github.com/azurer/azure-sdk-for-net repo. cc @nickzhums for the ask on .NET SDK.

**Comment by weidongxu-microsoft** [comment]
@muiriswoulfe 

Actually you can make the mapping at runtime (so that it is always up-to-date), e.g. when your service start-up.

There is a REST API **`/subscriptions/{subscriptionId}/locations`** to return all currently supported locations/regions.

You want to check those with `metadata.regionType == "Physical"`, and group them by `metadata.geographyGroup` (US / Europe / Asia Pacific).

I've attached the current response of that REST API (it is JSON).
[locations.txt](https://github.com/Azure/azure-libraries-for-net/files/5281013/locations.txt)

**Comment by muiriswoulfe** [comment]
@weidongxu-microsoft: Thanks Weidong. That's perfect for our needs.

Based on this, I'm happy if you wish to close this feature request as Won't Fix. It would still be great to have this functionality available without a remote call though, so if it's still something you wish to consider, feel free to keep it Open.

**Comment by yungezz** [comment]
glad to see the solution works, close this now given we're not adding new features to .net fluent SDK.
