### ISSUE TITLE
[BUG] Unable to deploy docker image to the Web App with windows serviceplan

### ISSUE THREAD

**Issue by imranveliyev** [Azure/azure-libraries-for-net#1146]
**Describe the bug**
I need to deploy docker windows container image to the web app with windows service plan using c#.  Unable due to error:
"docker container settings only apply to linux app srvice plan".

**To Reproduce**
1. Create windows container image in acr
2. Deploy app using  Assembly Microsoft.Azure.Management.ResourceManager.Fluent library.
3. Proceed with   app.Update().WithPrivateDockerImage("acrname.azurecr.io/image:latest");

**Expected behavior**
Image deployed to the web app successfully.
It works with Linux and i expect the same in the case with windows service plan
![linuxsrcplan](https://user-images.githubusercontent.com/46125297/95327515-d7a14680-08ac-11eb-8b56-151144c872da.PNG)

**Screenshots**
![winsrcplan](https://user-images.githubusercontent.com/46125297/95327257-711c2880-08ac-11eb-80a7-ace97a0c7a21.PNG)

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : visual studio 2019
 - Version of the Library used: Microsoft.Azure.Management.ResourceManager.Fluent, Version=1.0.0.66

**Comment by imranveliyev** [comment]
It works with Linux and i expect the same in the case with windows service plan
![linuxsrcplan](https://user-images.githubusercontent.com/46125297/95327515-d7a14680-08ac-11eb-8b56-151144c872da.PNG)

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls help on this? thanks

**Comment by pagariyaalok** [comment]
Fluent .NET SDK 1.35.0 is released.
https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/1.35.0

**Comment by pagariyaalok** [comment]
Also .NET Fluent SDK is currently in a maintenance mode and will be deprecated in the future. The development focus has shifted to the newer generation of the .NET SDK which can be found here:
https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

For benefits using the new libraries, you can view this blog post:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/
