### ISSUE TITLE
[BUG] ResourceManagement Graph.RBAC Lookup Active Directory Group by Name Returns Incorrect Group

### ISSUE THREAD

**Issue by mikemassa84** [Azure/azure-libraries-for-net#1147]
**Describe the bug**
When using the Microsoft.Azure.Management.Graph.RBAC.Fluent library to retrieve an active directory group by name, an incorrect group is returned. For example, if looking up a group named "Foo", the api may return a group named "Bar" instead. In our case, we are searching for a group named "R&D - PA" but a group named "SG Bomgar Admins" is returned instead.

***Exception or Stack Trace***
No exception or stack trace.

**To Reproduce**
1. Setup multiple active directory groups in Azure Active Directory (we have hundreds).
  a. Create a group named SG Bomgar Admins and a group named R&D - PA.
2. Setup a project using the Microsoft.Azure.Management.Graph.RBAC.Fluent NuGet package.
3. Use code similar to that in the Code Snippet section to lookup group by name.

***Code Snippet***
Add the code snippet that causes the issue.

This is the code we are using to lookup group by name.
```C#
    Azure.Configure().WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic).Authenticate(creds);
    var adGroup = await _auth.ActiveDirectoryGroups.GetByNameAsync("R&D - PA").ConfigureAwait(false);
```
Looking at the method in [ActiveDirectoryGroupsImpl.cs](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Graph.RBAC/ActiveDirectoryGroupsImpl.cs), it seems to be returning the first group that is found without verifying the name of the group matches the name requested:

```C#
IEnumerable<ADGroupInner> inners = await Inner.ListAsync(string.Format("displayName eq '{0}'", name), cancellationToken);
if (inners == null || !inners.Any())
{
    return null;
}
return WrapModel(inners.First());
```

**Expected behavior**
Based on our code above, we expect the adGroup object to contain a group named R&D - PA.

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: Windows 10 (Also Windows Azure Functions)
 - IDE : Visual Studio 2019
 - Version of the Library used: 1.34.0

**Additional context**
We are able to work around the problem by loading all of the AD groups and looking up the group ourselves, however, loading all the groups is extremely slow. It takes between 35-40 seconds to complete. Once loaded though, the lookup is extremely fast.
```C#
// _adGroups is a IPagedCollection<IActiveDirectoryGroup>
_adGroups.Where(g => g.Name == groupName).FirstOrDefault();
```

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by xccc-msft** [comment]
@mikemassa84 You may try below as workaround
```csharp
await _auth.ActiveDirectoryGroups.Inner.ListAsync(string.Format("displayName eq '{0}'", name)).ConfigureAwait(false);
```

**Comment by mikemassa84** [comment]
> @mikemassa84 You may try below as workaround
> 
> ```cs
> await _auth.ActiveDirectoryGroups.Inner.ListAsync(string.Format("displayName eq '{0}'", name)).ConfigureAwait(false);
> ```

Unfortunately that does not work. You can see from the screenshot that there are groups returned from that call, but the one named R&D - PA is not present.
![image](https://user-images.githubusercontent.com/14846033/95881095-d3a67600-0d3d-11eb-8852-3615255ee717.png)

**Comment by xccc-msft** [comment]
@mikemassa84 What if you list all group without passing filter and verify if the expected group get returned? If so, we might need help from service team. Thanks.

**Comment by mikemassa84** [comment]
@xccc-msft I tried without the filter with the following code, but the results were the same. 100 items were returned and the group I am interested in, R&D - PA, was not one of them.

```c#
var test = await _auth.ActiveDirectoryGroups.Inner.ListAsync().ConfigureAwait(false);
var rad = test.FirstOrDefault(g => g.DisplayName == "R&D - PA");
```

Running the following code does return all the groups, including the one I need, however it takes between 35-40 seconds to execute:

```c#
// Following takes ~35-40 seconds
IPagedCollection<IActiveDirectoryGroup> _adGroups = await _auth.ActiveDirectoryGroups.ListAsync().ConfigureAwait(false);
// Following is very fast; groupName = "R&D - PA"
_adGroups.Where(g => g.Name == groupName).FirstOrDefault()
```

**Comment by mikemassa84** [comment]
Replacing the `&` with `%26` did work and the correct group named `R&D - PA` was returned.

Will the client library be updated to handle encoding special characters on behalf of the caller?

**Comment by xccc-msft** [comment]
@mikemassa84 We will plan to fix this and update once new version is released. Thanks.
