### ISSUE TITLE
[FEATURE REQ] Manage Azure Front Door using C SDK

### ISSUE THREAD

**Issue by CodeAsAnInfrastructureGuy** [Azure/azure-libraries-for-net#1158]
**Is your feature request related to a problem? Please describe.**
I can not seem to manage Azure Front Door under the Microsoft.Azure.Management.Fluent C# SDK.
It's not under it's own namespace and I cannot determine whether it's available under the Network namespace.

**Describe the solution you'd like**
I'd like to be able to manage Azure Front Door under the Microsoft.Azure.Management.Fluent C# SDK.

**Describe alternatives you've considered**
I've considered Microsoft.Azure.Management.FrontDoor, however documentation in how to get started isn't clear.

**Additional context**
No additional context can be provided.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by yungezz** [comment]
hi @CodeAsAnInfrastructureGuy .NET fluent SDK is deprecating, new generation .NET SDK is available at https://github.com/azure/azure-sdk-for-net.  Pls have a look at it. thanks.

**Comment by CodeAsAnInfrastructureGuy** [comment]
Thanks @yungezz. I'll have a look over there.
