### ISSUE TITLE
[BUG] The client '---' with object id '---' does not have authorization to perform action 'Microsoft.Management/managementGroups/Microsoft.Management/{managementGroup}/Microsoft.Blueprint/{AssignmentName}/write'

### ISSUE THREAD

**Issue by stinejohans1** [Azure/azure-libraries-for-net#1166]
**Describe the bug**
Trying to assign a blueprint using the BlueprintManagementClient. 

All settings transferred and equal to an existing powershell script that does the same. Powershell script works, using BlueprintManagementClient does not.

The principal ID logging in has owner-role on the management group. 

Same result when trying the identity set to "None" and "SystemAssigned"

***Exception or Stack Trace***
Microsoft.Rest.Azure.CloudException : The client '---' with object id '---' does not have authorization to perform action 'Microsoft.Management/managementGroups/Microsoft.Management/{managementGroup}/Microsoft.Blueprint/{AssignmentName}/write' over scope '/providers/Microsoft.Management/managementGroups/providers/Microsoft.Management/managementGroups/{managementGroup}/providers/Microsoft.Blueprint/blueprintAssignments' or the scope is invalid. If access was recently granted, please refresh your credentials.

**To Reproduce**
- Have a published blueprint definition in Azure
- Setup parameters
- Assign the blueprint using azure libraries for .net Microsoft.Azure.Management.Blueprint

***Code Snippet***
[Test]
    public async Task AssignBlueprint_ShouldAssignBlueprint()
    {
        try
        {
            string _domainName = "";
            string _servicePrincipalPass = "";
            string _servicePrincipalId = "";
            string _managementGroupId = "";
            BlueprintManagementClient _blueprintManagementClient;
            string _environment ="";
            string _blueprintName = "";
            string _resourceGroupName = "";
            string _location = "northeurope";
            string _tenantId = "";
            string _managedIdentityResourceGroupName = "";
            string _managedIdentityName = "";
            
            // Get credentials from Azure and initialize API client
            ServiceClientCredentials creds = ApplicationTokenProvider.LoginSilentAsync(_domainName, _servicePrincipalId, _servicePrincipalPass).Result;
            _managementGroupId = _appSettingManagementGroupId;
            _blueprintManagementClient = new BlueprintManagementClient(creds);
            var assignmentName = $"{_blueprintName}-ASSIGNMENT-{_environment}";
            var resourceGroupName = $"{_resourceGroupName}-{_environment}";

            var storageAccountName = $"somename{_environment.ToLower()}";
            var roleassignment = "";

            var publishedBlueprint =
                _blueprintManagementClient.PublishedBlueprints.ListInManagementGroup(_managementGroupId,
                    _blueprintName).OrderBy(p => p.Name).Last();

            Assert.IsNotNull(publishedBlueprint);
            var managedIdentityResourceGroupName = "";
            var managedIdentityName = "";

            string managedIdentityId = $"/subscriptions/{_subscriptionId}/resourceGroups/{managedIdentityResourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{managedIdentityName}"
            IDictionary<string, ParameterValue> parameters = new Dictionary<string, ParameterValue>
            {
                {"INPUT_Roleassignment_Owners", new ParameterValue(roleassignment)},
                {"INPUT_Location", new ParameterValue(_location)},
                {"INPUT_SA_Export_Name", new ParameterValue(storageAccountName)},
            };
            IDictionary<string, ResourceGroupValue> resourceGroups = new Dictionary<string, ResourceGroupValue>
            {
                {"ResourceGroupNameFromBlueprint", new ResourceGroupValue(resourceGroupName)}
            };

            var managedIdentity = new ManagedServiceIdentity("UserAssigned", null, _tenantId);
            managedIdentity.UserAssignedIdentities = new Dictionary<string, UserAssignedIdentity>{
            {
                managedIdentityId
                    , null
            }};

            var assignment = new Assignment
            {
                Location = _location,
                BlueprintId = publishedBlueprint.Id,
                DisplayName = assignmentName,
                Parameters = parameters,
                ResourceGroups = resourceGroups,
                Identity = managedIdentity
            };

            var createdAssignment = _blueprintManagementClient.Assignments.CreateOrUpdateInManagementGroup(
                $"/providers/Microsoft.Management/managementGroups/{_managementGroupId}", assignmentName,
                assignment);

            Assert.IsNotNull(createdAssignment);
        }
        catch (Exception e)
        {
            //todo
            throw;
        }
    }

**Expected behavior**
The blueprint to assign the assignment

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS Professional 2019
 - Microsoft.Azure.Management.Blueprint, Version="0.20.7-preview"

**Comment by weidongxu-microsoft** [comment]
This issue should be reported to https://github.com/Azure/azure-sdk-for-net/

This repo is for `Microsoft.Azure.Management.Fluent `

**Comment by stinejohans1** [comment]
Oh, sorry, I'll move it. Thank you.
