### ISSUE TITLE
Example for using low level libraries side by side with Fluent Libraries. 

### ISSUE THREAD

**Issue by asalvo** [Azure/azure-libraries-for-net#117]
In the readme, it says "Libraries are built on the lower-level, request-response style auto generated clients and can run side-by-side with auto generated clients."

I was hoping to find an example and/or best practices on how to use the Fluent API and low-level libraries side by side. My thought was that I would step down to the low level libraries when I needed to manage something currently unsupported by the Fluent API.

**Comment by hovsepm** [comment]
e.g. Using Azure Fluent Rollup package with autogenerated ResourceManager library
```
                    AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromFile(file);

                    var azure = Azure
                        .Configure()
                        .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                        .Authenticate(credentials)
                        .WithDefaultSubscription();

                    var client = new Microsoft.Azure.Management.ResourceManager.ResourceManagementClient(credentials);
                    client.SubscriptionId = credentials.DefaultSubscriptionId;
```
after these steps you will have authenticated azure manager instance from which you can use any flow and authenticated resource manager client instance.

**Comment by hovsepm** [comment]
Please reopen if you have more questions.
