### ISSUE TITLE
[BUG] Missing Apply or ApplyAsync from DNS UpdateXXX methods

### ISSUE THREAD

**Issue by j055** [Azure/azure-libraries-for-net#1174]
**Describe the bug**
The fluent library for DNS has missing Apply or ApplyAsync methods when trying to update DNS recordsets.

**To Reproduce**
Obtain Microsoft.Azure.Management.Fluent 1.36.0
Try to update an existing DNS recordset with metadata key, value pair.

***Code Snippet***
```
var mailZone = azure.DnsZones.GetByResourceGroup("dns", "example.co.uk");
await mailZone.Update().UpdateTxtRecordSet(record.Name).WithMetadata("MyId", "1234").ApplyAsync();
```

**Expected behavior**
Should be able to apply updates to DNS record sets.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - Version of the Library used: Microsoft.Azure.Management.Fluent 1.36.0

**Comment by yungezz** [comment]
hi @j055 thanks for reporting the issue. .NET fluent SDK is in passive maintenance mode, new generation of .NET SDK is available at https://github.com/azure/azure-sdk-for-net. Pls have a look at new SDK does it resolve the problem. thanks

**Comment by weidongxu-microsoft** [comment]
@j055 

Please do this (it need to get back one level for `Apply`):

```
            await mailZone.Update()
                .UpdateTxtRecordSet(record.Name)
                    .WithMetadata("MyId", "1234")
                    .Parent()
                .Apply();
```
