### ISSUE TITLE
[QUERY] Is there a way to identify the type of Cosmos DB account, and look at only Core SQL accounts?

### ISSUE THREAD

**Issue by daveoshinsky** [Azure/azure-libraries-for-net#1178]
ICosmosDBAccount describes each Cosmos DB account in a list of accounts. I don't see a simple way of identifying the type of account (Core SQL, Table API, Cassandra, Mongo DB, etc.).  As a result, I am using the ListSqlDatabases() method to list the Core SQL databases in each account.  If the account has at least one SQL database, it is assumed to be a Core SQL account.  If not, it is assumed to be some other kind of account.  Unfortunately, this algorithm eliminates Core SQL accounts that currently contain no SQL databases, which is problematic in some cases.  I see that the "Capabilities" list has "EnableMongo" for Mongo accounts, and "EnableTable" for Table API accounts.  It has no capabilities for Core SQL accounts.  DatabaseAccountOfferType looks promising, but the only value is "Standard" for all accounts.  Please suggest a reliable way of separating Core SQL accounts from other types of Cosmos DB accounts, other than looking at ListSqlDatabases().  Would the absence of any "Enable*" capabilities mean that that account is a Core SQL one?

**Comment by yungezz** [comment]
hi @ChenTanyi could you pls help to have a look? thanks

**Comment by MehaKaushik** [comment]
Unfortunately we have a complicated logic for this translation. The logic
is below:

When Communication Apikind = = globalDocumentDB
Then if no EnableApi capability exists then it is core sql account.
If EnableTable, EnableCasssandra, EnableGremlin exists then the respective
Apitype.

For mongo accounts, apiKind is MongoDb. EnableMongo if present then
indicates that serverVersion is 3.6.

**Comment by ChenTanyi** [comment]
@daveoshinsky As @MehaKaushik said, you can see the `With` operation in the [Source Code](https://github.com/Azure/azure-libraries-for-net/blob/5c44f73/src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs#L504-L552). You can use the same way as the setting logic for checking the Cosmos DB type.

**Comment by daveoshinsky** [comment]
Thanks @MehaKaushik , that logic appears to work.  Closing the issue.
