### ISSUE TITLE
[BUG] GalleryArtifactPublishingProfileBase is missing Source property in .Net SDK

### ISSUE THREAD

**Issue by cmbrose** [Azure/azure-libraries-for-net#1183]
**Describe the bug**
In the .Net SDK, the `Source` property of [GalleryArtifactPublishingProfileBase](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Compute/Generated/Models/GalleryArtifactPublishingProfileBase.cs) is missing. It appears to have been removed in [this PR](https://github.com/Azure/azure-libraries-for-net/commit/d14e34232dcda6641f228ea44c3c4944695c923e#diff-be9090f309d2e9fb9731a2eda144ca7523bc0ec02e55d9b30c670043ec722e2b) which updated the compute API version to 2019-03-01.

However, according to the ARM schema in the [PR that created version 2019-03-01](https://github.com/Azure/azure-resource-manager-schemas/pull/644/files#diff-b7b4d4d6d191242b1217e3c931c7b78d072d4625d81241f79dd88a6ef5164025), the property is still there and in fact [the Java SDK still has the property as well](https://github.com/praries880/azure-libraries-for-java/blob/7bd362349a099ab1f64209e2acf3e760304102be/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/GalleryArtifactPublishingProfileBase.java#L29).

This doesn't cause a runtime bug, but it is an undocumented breaking change in the .Net SDK and likely a bug in the auto-generation of the .Net source.

***Exception or Stack Trace***
N/A

**To Reproduce**
N/A

***Code Snippet***
N/A

**Expected behavior**
The `Source` property should exist in the `GalleryArtifactPublishingProfileBase` class in the .Net SDK

**Screenshots**
N/A

**Setup (please complete the following information):**
N/A

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@cmbrose 

It appears that "source" is not in latest specs https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/gallery.json#L2097-L2139

**Comment by cmbrose** [comment]
@weidongxu-microsoft - let me be a little more specific in what broke in the code :)

We're using `IComputeManagementClient.GalleryImageVersions.ListByGalleryImageAsync` which returns a set of `GalleryImageVersionInner`s. From that object we are referencing `GalleryImageVersionInner.PublishingProfile` which is of type `GalleryImageVersionPublishingProfile` which extends `GalleryArtifactPublishingProfileBase`.

Because the `Source` property was removed from `GalleryArtifactPublishingProfileBase` it was also removed from `GalleryImageVersionPublishingProfile` which has broken our code.

**Comment by weidongxu-microsoft** [comment]
@cmbrose 

Got your point.

For SDK, the specs in https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-12-01/gallery.json is the shared truth between customer and Azure compute service. When service removed the "source" property, we would assume they break it intentionally.

I think first we could check if "source" is actually in the response or not (if possible let us know if the "source" need some special config in image, or any image would have this property). If it actually in JSON response, it would be more likely service team removed it by mistake.

**Comment by cmbrose** [comment]
@weidongxu-microsoft thanks for the explanation - makes sense why it is gone from the SDK. Is there a way we can test if it is in the JSON response?

**Comment by weidongxu-microsoft** [comment]
@cmbrose 

You can enable logging and check the raw response JSON from server. https://github.com/Azure/azure-libraries-for-net#logging

From what I captured from the response, `source` is not there in `publishingProfile` (image created from managed disk).
However I saw a `source` property in `storageProfile`. Is it same as what you would expect in `publishingProfile`?

```
{
   "value":[
      {
         "name":"0.0.1",
         "id":"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg-weidxu/providers/Microsoft.Compute/galleries/sig1weidxu/images/image1/versions/0.0.1",
         "type":"Microsoft.Compute/galleries/images/versions",
         "location":"japaneast",
         "tags":{
            
         },
         "properties":{
            "publishingProfile":{
               "targetRegions":[
                  {
                     "name":"Japan East",
                     "regionalReplicaCount":1,
                     "storageAccountType":"Standard_LRS"
                  }
               ],
               "replicaCount":1,
               "excludeFromLatest":false,
               "publishedDate":"2020-12-21T02:20:32.4321627+00:00",
               "endOfLifeDate":"2020-12-30T16:00:00+00:00",
               "storageAccountType":"Standard_LRS"
            },
            "storageProfile":{
               "osDiskImage":{
                  "sizeInGB":30,
                  "hostCaching":"None",
                  "source":{
                     "id":"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/TANYI/providers/Microsoft.Compute/disks/voieorlskf"
                  }
               }
            },
            "provisioningState":"Succeeded"
         }
      },
      {
         "name":"0.0.2",
         "id":"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg-weidxu/providers/Microsoft.Compute/galleries/sig1weidxu/images/image1/versions/0.0.2",
         "type":"Microsoft.Compute/galleries/images/versions",
         "location":"westus2",
         "tags":{
            
         },
         "properties":{
            "publishingProfile":{
               "targetRegions":[
                  {
                     "name":"West US 2",
                     "regionalReplicaCount":1,
                     "storageAccountType":"Standard_LRS"
                  }
               ],
               "replicaCount":1,
               "excludeFromLatest":false,
               "publishedDate":"2020-12-21T02:37:41.8353999+00:00",
               "endOfLifeDate":"2020-12-30T16:00:00+00:00",
               "storageAccountType":"Standard_LRS"
            },
            "storageProfile":{
               "osDiskImage":{
                  "sizeInGB":30,
                  "hostCaching":"None",
                  "source":{
                     "id":"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/RG-WEIDXU/providers/Microsoft.Compute/disks/vm1weidxu_OsDisk_1_cadeacd5fde2431ca01298237773b39a"
                  }
               }
            },
            "provisioningState":"Succeeded"
         }
      }
   ]
}
```

**Comment by cmbrose** [comment]
@weidongxu-microsoft thanks for that info! I think we can close this one out in that case and I can follow up with the compute API owners as needed
