### ISSUE TITLE
[BUG] Key Vault accounts are created with Soft-Delete disabled, and can't find a way to enable soft deletion in the library

### ISSUE THREAD

**Issue by jrebagliatti** [Azure/azure-libraries-for-net#1184]
**Describe the bug**
According to [documentation](https://docs.microsoft.com/en-us/azure/key-vault/general/soft-delete-change), the ability to opt out of soft delete for Key Vault will be deprecated by the end of the year. However, I couldn't find in the documentation any way to configure soft deletion during KV creation using the Fluent SDK (version 1.36.1), and by default KV accounts are created with soft-delete disabled.
My concern is that our production code start to fail once the mentioned change is rolled out, and I can't find a way to prevent it.

***Exception or Stack Trace***
N/A

**To Reproduce**
Create a KV account using the ``Microsoft.Azure.Management.KeyVault.Fluent`` SDK

***Code Snippet***
```
            return await azure.Vaults
                .Define(subscription.KeyVaultName)
                .WithRegion(config.SubscriptionsKeyVaultsLocation)
                .WithExistingResourceGroup(subscription.ResourceGroup.Name)
                .DefineAccessPolicy()
                    .ForObjectId(servicePrincipalId)
                    .AllowSecretPermissions(SecretPermissions.Set, SecretPermissions.Get)
                    .Attach()
                .WithTag("organizationId", subscription.OrganizationId)
                .WithTag("subscriptionId", subscription.Id)
                .WithTag("environment", config.Environment)
                .CreateAsync();
```

**Expected behavior**
Unless there's an option to configure the soft-delete setting, the Key Vault account should be created with soft-delete enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/8695964/102257959-26421100-3eec-11eb-87d7-d17146345d71.png)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: .Net Core Microsoft.Azure.Management.KeyVault.Fluent version 1.36.1

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Please add `withSoftDeleteEnabled`.
