### ISSUE TITLE
Get Public IP of VM in ScaleSet

### ISSUE THREAD

**Issue by klyse** [Azure/azure-libraries-for-net#1185]
**Query/Question**
How can I get the public IP of each VM in a scale set?

```csharp
var _azure = Azure
            .Configure()
            .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
            .Authenticate(GetCredentials(credentials))
            .WithSubscription(credentials.Subscription);

var scaleSets = await _azure.VirtualMachineScaleSets.ListAsync(true, cancellationToken);

// example of how to get the private ip:
var privateIp = scaleSets.First().VirtualMachines.List().First().ListNetworkInterfaces().First().PrimaryPrivateIP;

// PrimaryPublicIp does not exist:
var publicIp = scaleSets.First().VirtualMachines.List().First().ListNetworkInterfaces().First().PrimaryPublicIP;
```
**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : JetBrains Rider
 - Version of the Library used:
    - Microsoft.Azure.Management.Fluent Version="1.36.1"

**Comment by weidongxu-microsoft** [comment]
@klyse 

There is a REST API https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#querying-the-public-ip-addresses-of-the-virtual-machines-in-a-scale-set
But it is not documented in specs so it will not show in SDK https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json

**Comment by klyse** [comment]
@weidongxu-microsoft Thanks for your quick response! Can we turn this Issue into a feature request? I think it would be nice that this is documented and supported.

**Comment by weidongxu-microsoft** [comment]
To service team:
Missing REST specs for
`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{vmScaleSetName}/publicipaddresses`
in compute spec https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json

Assuming service would continue support this REST, as documented at https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-networking#querying-the-public-ip-addresses-of-the-virtual-machines-in-a-scale-set

**Comment by klyse** [comment]
Here is a workaround in c#:

Types:
```csharp
public sealed record PublicIpConfiguration(IList<IpConfiguration> Value);

public sealed record IpConfiguration(string Name, string Id, string Etag, Properties Properties);

public sealed record Properties(string ProvisioningState, string ResourceGuid, string IpAddress, string PublicIPAddressVersion, string PublicIPAllocationMethod, string IdleTimeoutInMinutes, IpConfigurationId IpConfiguration);

public sealed record IpConfigurationId(string Id);
```

Call:
```csharp
var client = RestClient
    .Configure()
    .WithEnvironment(AzureEnvironment.AzureGlobalCloud)
    .WithCredentials(_credentials)
    .Build();

var url = $"https://management.azure.com/subscriptions/{_azure.SubscriptionId}/resourceGroups/{scaleSet.ResourceGroupName}/providers/Microsoft.Compute/virtualMachineScaleSets/{scaleSet.Name}/publicipaddresses?api-version=2017-03-30";

var request = new HttpRequestMessage(HttpMethod.Get, url);

client.Credentials.ProcessHttpRequestAsync(request, cancellationToken).GetAwaiter().GetResult();
var httpClient = new HttpClient();
var response = httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).GetAwaiter().GetResult();

var stream = await response.Content.ReadAsStringAsync(cancellationToken);
var output = JsonConvert.DeserializeObject<PublicIpConfiguration>(stream);
```

**Comment by avirishuv** [comment]
Will take a look at this.

**Comment by avirishuv** [comment]
@weidongxu-microsoft the API is documented in the NW spec here: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2020-08-01/vmssPublicIpAddress.json 

Hope this clarifies the question. Closing the issue, feel free to reopen if there are additional questions on this.

**Comment by dzmitry-lahoda** [comment]
when SDK with update will be released?

**Comment by dzmitry-lahoda** [comment]
I see - never, only with new SDK
