### ISSUE TITLE
[BUG] README.md -> Microsoft Azure Projects Contribution Guidelines -> 404 Error

### ISSUE THREAD

**Issue by p-bojkowski** [Azure/azure-libraries-for-net#1201]
![image](https://user-images.githubusercontent.com/74313141/106364464-7572c280-632f-11eb-94cf-08c71f200317.png)

![image](https://user-images.githubusercontent.com/74313141/106364467-7c99d080-632f-11eb-865a-d4d54994e7dd.png)

**Comment by p-bojkowski** [comment]
see: https://github.com/Azure/azure-sdk-for-c/issues/1101

**Comment by weidongxu-microsoft** [comment]
@p-bojkowski Thanks for the report. We will check internally which link is the best fit (https://opensource.microsoft.com/collaborate seems a bit too general),
