### ISSUE TITLE
Could not update TrafficManagerProfile Endpoint

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-libraries-for-net#121]
Following code does not update traffic manager profile:
```
tmp.Update().DefineAzureTargetEndpoint(name)
                        .ToResourceId(id)
                        .WithTrafficDisabled()
                        .WithRoutingPriority(11).Attatch().Apply();
```

Checked the code:

https://github.com/Azure/azure-libraries-for-net/blob/0e725531319775e348c21540c9a2c25000106c32/src/ResourceManagement/TrafficManager/TrafficManagerProfileImpl.cs#L111-L112

The following line will update the endpoint as expected:
```
await endpoints.CommitAndGetAllAsync(cancellationToken);
```

But then next line will reset it back, since 'Inner' contains the old state.
```
 ProfileInner profileInner = await Manager.Inner.Profiles.CreateOrUpdateAsync(ResourceGroupName, Name, Inner, cancellationToken);
```

**Comment by karataliu** [comment]
Putting 'CommitAndGetAllAsync' after 'SetInner' will do the fix, like 'CreateResourceAsync' does

**Comment by Denifia** [comment]
I've run into this issue too. Is anyone working on a PR for this? If not, I will.

**Comment by abharath27** [comment]
It's been more than 6 months since this issue was reported. Can someone look into this?

**Comment by hovsepm** [comment]
@karataliu @abharath27 I'm unable to repro. 
Could you upgrade to v1.11.1 and if you still hit it post here a sample code that fails?

Here is my working test code
```
var nestedProfile = azure.TrafficManagerProfiles.Define(nestedTmProfileName)
        .WithNewResourceGroup(rgCreatable)
        .WithLeafDomainLabel(nestedTmProfileDnsLabel)
        .WithPriorityBasedRouting()
        .DefineExternalTargetEndpoint("external-ep-1")
            .ToFqdn("www.gitbook.com")
            .FromRegion(Region.IndiaCentral)
            .Attach()
        .WithHttpsMonitoring()
        .WithTimeToLive(500)
        .Create();

var publicIpAddress = azure.PublicIPAddresses.Define(pipName)
        .WithRegion(region)
        .WithNewResourceGroup(rgCreatable)
        .WithLeafDomainLabel(pipDnsLabel)
        .Create();

var updatedProfile = nestedProfile.Update()
        .DefineAzureTargetEndpoint(azureEndpointName)
            .ToResourceId(publicIpAddress.Id)
            .WithTrafficDisabled()
            .WithRoutingPriority(11)
            .Attach()
        .Apply();


Assert.Equal(1, updatedProfile.AzureEndpoints.Count);
Assert.True(updatedProfile.AzureEndpoints.ContainsKey(azureEndpointName));        
```

**Comment by karataliu** [comment]
@hovsepm  Have you checked the traffic manager resource through portal? Was the endpoint really updated? Asserting locally should work since it is local state.

**Comment by hovsepm** [comment]
@karataliu thanks for catching it :) have the repro and should be able to add the fix for v1.13

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.

**Comment by abharath27** [comment]
@hovsepm 
The issue in the original issue was fixed, however, the WithoutEndPoint() function still doesn't update the TM profile
```
            trafficManagerProfile
                .Update()
                .WithoutEndpoint(DefaultEndPointName)
                .Apply();

```

**Comment by hovsepm** [comment]
@abharath27 I'll take a look to `WithoutEndpoint` part in this sprint.

**Comment by hovsepm** [comment]
@abharath27 thanks for catching the issue. I did another look and fixed the error that I've introduced during previous fix. Added more tests to make sure that now all the scenarios work correctly. The fix should be out in release 1.14 due beginning of August.

**Comment by hovsepm** [comment]
@abharath27 1.14 is out. Please upgrade your reference.

**Comment by abharath27** [comment]
@hovsepm Thanks for fixing this
