### ISSUE TITLE
[BUG] Public API published violates Microsoft Naming Conventions and is not consistent with the rest of the Framework

### ISSUE THREAD

**Issue by BrainSlugs83** [Azure/azure-libraries-for-net#1213]
**Describe the bug**

In reference to (but not limited to) the following two files: [AzureCredentialsFactory.cs](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs#L62), and [MSILoginInformation.cs](https://github.com/Azure/azure-libraries-for-net/blob/c66a608cf2e7026754edfa4fd781efabc49b49d0/src/ResourceManagement/ResourceManager/Authentication/MSILoginInformation.cs#L12)

I believe that using "MSI" as an all uppercase acronym is a violation of multiple Microsoft naming convention guidelines, and that the public API presented by these libraries is inconsistent with the rest of the framework and with Microsoft Design Guidelines in two ways:

1. In the "[General Naming Convention Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions)" subsection, it is states:
    ```
    ❌ DO NOT use any acronyms that are not widely accepted, and even if they are, only when necessary.
    ```
    While "MSI" is a widely accepted acronym, it is for a different technology (i.e. Microsoft Installer) -- but even if it were widely 
    accepted, it hardly seems necessary (maybe in the longer class names it's more necessary, but `FromMSI` is rather short).

    Also, I strongly urge you to specify in the comments what it actually stands for.  (Right now the comments just say things like "Type to hold MSI configuration", which at best seems to be not helpful, because it doesn't tell you what "MSI" means here -- but at worst it might be an incorrect comment, because the class is actually about login information, not configuration details. -- At any rate, looking at the source code alone, and intellisense comments this information is completely unknown.  Which is very inconsistent with the standards the rest of the .NET ecosystem lives by, and in my opinion, is not very developer friendly.)

2. Additionally the acronym is **cased** incorrectly; according to the "[Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)", only two letter acronyms can be upper cased (such as "IO"), anything longer than two letters needs to be PascalCased (i.e. things like "HTML" become "Html" "JSON" becomes "Json", and things like "MSI" should become "Msi".  This is a set-in-stone rule that the entire rest of the framework follows, and even most popular third party NuGet packages tend to follow. [Not to mention the Enterprise sector.])

    As an example, in this case, if the standard Microsoft .NET naming conventions are honored, the "FromMSI" method should at least become "FromMsi", and any class that starts with "MSI" (i.e. "MSILoginInformation" should become "MsiLoginInformation").

    Though I would recommend double checking the comments for each class to make sure they have correct information, and don't refer to the technology by an acronym; and shorter methods like "FromMsi" should expand the acronym so that it's obvious what it stands for to the everyday developer.

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new featuers. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:

We have also published a few blog posts on why we are doing this: https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/ https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by BrainSlugs83** [comment]
The links you provided seem to reiterate the validity of this bug:
```
A key piece of feedback we heard while talking with developers was that our APIs didn’t always feel idiomatic to the language. To fix that, we explicitly established as one of our core principles that the libraries we author should follow the patterns of that language.
```
I am specifically reporting that your library is violating the standard guidelines of the C# language (that have stood for over a decade and are widely accepted by the industry).

**Comment by weidongxu-microsoft** [comment]
@BrainSlugs83 

I believe in the new SDK, the related class will be called `ManagedIdentityCredential`.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/ManagedIdentityCredential.cs

As mentioned, this repo will not get any major changes in future. And personally I do not want to make any change that going to break current user, except maybe for security issues.

**Comment by BrainSlugs83** [comment]
Wow you responded so fast! (I was caught still making updates and edits when your response came through! 😅)

Anyway, I think we're on the same page now -- thanks for being patient with me -- the nature of my confusion was that I thought that this **WAS** the new beta codebase! 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️

(I see now that you made this claim in your initial response, but I missed that significance in my initial reading.)

Thank you for being patient with me and pointing me in the right direction. 🙂
