### ISSUE TITLE
[BUG] Azure Function App is created without WEBSITE_CONTENTAZUREFILECONNECTIONSTRING setting

### ISSUE THREAD

**Issue by pbelousov** [Azure/azure-libraries-for-net#1214]
**Describe the bug**

We are using Microsoft.Azure.Management.Fluent to create function apps, and starting from 1.37.0 the package doesn't add `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and `WEBSITE_CONTENTSHARE` configuration parameters. Seems it was because of [the following PR 1179](https://github.com/Azure/azure-libraries-for-net/pull/1179).

But because of this change, we could not deploy the app from Linux container and get "Azure Functions Runtime is unreachable".

After contaicting Microsoft Azure support team we've got the following response

> Generally, a function app on a premium plan requires an additional setting in the site configuration: WEBSITE_CONTENTAZUREFILECONNECTIONSTRING. However, WEBSITE_CONTENTSHARE is generated automatically when the site is first created. See below link for further details;
>  
> - https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code#create-a-function-app-1
>  
> I'd like to apologize concerning the misconstrued usage of the parameters for consumption and premium plans. The recommended approach is to ensure WEBSITE_CONTENTSHARE, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING & WEBSITE_RUN_FROM_PACKAGE values are set/available under the function app application settings. Soon, the official document (https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentazurefileconnectionstring) will be updated to reflect this recommendation. See below link for further details;
>  
> - https://github.com/MicrosoftDocs/azure-docs/issues/69467#issuecomment-768484873
> - https://stackoverflow.com/questions/65923068/website-contentazurefileconnectionstring-and-website-contentovervnet-required-fo
>  
> Furthermore, I have attached a link below to a Microsoft documentation below that would guide you on how to troubleshoot error: "Azure Functions Runtime is unreachable" should you encounter such error going forward.
>  
> - https://docs.microsoft.com/en-us/azure/azure-functions/functions-recover-storage-account#storage-account-application-settings-were-deleted

So it looks like these two settings (`WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and `WEBSITE_CONTENTSHARE`) are required for both (Consumption and Premium) plans and have to be added back.

**To Reproduce**

Just create a new Function App and check that these two settings are missed

**Expected behavior**

After Function App creation the following configuration parameters must be initialized.

Thank you in advance!

**Comment by weidongxu-microsoft** [comment]
@pbelousov 

Thanks for the report and the information. Which is the exact plan? I tried P2V1 and P3V1 on Portal but both does not have `WEBSITE_*` setting.

![image](https://user-images.githubusercontent.com/53292327/109589046-b2a3bd80-7b44-11eb-8ce4-ce221b08c767.png)

In my memory the `WEBSITE_*` setting is need for `Dynamic` (which is the basic consumption existing long time ago), and the new `ElasticPremium` (maybe added one or two years ago).

**Comment by pbelousov** [comment]
@weidongxu-microsoft, Ah, yes, you're right, we are using **Elastic**Premium plan. I've created a new Function App through Azure Portal and the app has these two `WEBSITE_*` settings. So yes, seems in the case of the ElasticPremium plan (not Premium one) these settings must be added.
What would you recommend for us - wait for the new version of the `Microsoft.Azure.Management.Fluent` package? or adding these settings manually for now?

**Comment by weidongxu-microsoft** [comment]
@pbelousov 

I will fix the bug, but since the SDK is in maintenance mode, next release will probably be weeks later.

If you create storage account before webapp, it should be easy for you to set the `WEBSITE_*` setting in code, with 1.37 (`withAppSetting(key, value)`).

Value of both key is the connection string of storage account, which is in format of `DefaultEndpointsProtocol=https;AccountName={0};AccountKey={1};EndpointSuffix={2}`, `AccountName` is storage account name, `AccountKey` is the access key from storage account (`StorageAccount.GetKeys`), `EndpointSuffix` would be `core.windows.net` for Azure global.

**Comment by pbelousov** [comment]
@weidongxu-microsoft  Perfect! Thank you for your help!

**Comment by weidongxu-microsoft** [comment]
@pbelousov 

Sorry, my mistake. `WEBSITE_CONTENTSHARE` should be a string with function app name as prefix (rest is random). https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentshare

It is used as name of file shared in the storage account (which contains the function app content).
