### ISSUE TITLE
Null reference error when passing Region to .WithLocation

### ISSUE THREAD

**Issue by chborl** [Azure/azure-libraries-for-net#1216]
**Describe the bug**
The following code throws a null exception
```csharp
var imageVersion = azureContext.AccessClient.GalleryImageVersions.Define(imageVersionName)
                            .WithExistingImage(sharedImageGallery.ResourceGroupName, queueItem.SharedImageGalleryName, imageDefinition.Name)
                            **.WithLocation(Region.USWest2)**
                            .WithSourceCustomImage(customImage)
                            .CreateAsync();
```

But when changed to use the different overload, below, it works
```csharp
  var imageVersion = azureContext.AccessClient.GalleryImageVersions.Define(imageVersionName)
                            .WithExistingImage(sharedImageGallery.ResourceGroupName, queueItem.SharedImageGalleryName, imageDefinition.Name)
                            **.WithLocation(Region.USWest2.ToString())**
                            .WithSourceCustomImage(customImage)
                            .CreateAsync();
```
Looking at the code repo, https://github.com/Azure/azure-libraries-for-net/blob/0dfd2bdafe45d197ceca2a3931d2bb8666242e5a/src/ResourceManagement/Compute/GalleryImageVersionImpl.cs#L296
the overload `[public GalleryImageVersionImpl WithLocation(string location)]()` returns `this`,
but overload `[public GalleryImageVersionImpl WithLocation(Region location)]` returns null. 

***Exception or Stack Trace***
Throws a null reference exception

**To Reproduce**
Replace the [test code here](https://github.com/Azure/azure-libraries-for-net/blob/0dfd2bdafe45d197ceca2a3931d2bb8666242e5a/Tests/Fluent.Tests/Compute/SharedGalleryImageTests.cs#L226) with ` .WithLocation(region.ToString())`

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Since all supplied parameters are correct, the method call should succeed as it does when region is passed as a string.

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Thanks very much for the bug report.
