### ISSUE TITLE
Deployment BeginCreate() does not set inner properties

### ISSUE THREAD

**Issue by jblackburn21** [Azure/azure-libraries-for-net#122]
I'm trying to call BeginCreate() on a deployment, and get the CorrelationId back for later use, but the code does not update the inner properties once the call completes.

Should it be updated to something like:

var i = Extensions.Synchronize(() => Manager.Inner.Deployments.BeginCreateOrUpdateAsync(resourceGroupName, Name, inner));

SetInner(i);

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
