### ISSUE TITLE
[BUG] VirtualMachineCustomImages.GetById returning incorrect HyperVGeneration value

### ISSUE THREAD

**Issue by chborl** [Azure/azure-libraries-for-net#1223]
**Describe the bug**
When using the GetById method of VirtualMachineCustomImages to retrieve a HyperVGeneration2 image, the object returned by the method has it incorrectly as HyperVGeneration1

***Exception or Stack Trace***
n/a

**To Reproduce**
Create a hypervgeneration 2 image and use `VirtualMachineCustomImages.GetById(imageResourceID);` to retrieve it. Check the HyperVGeneration value and it is gen1

***Code Snippet***

**Expected behavior**
the value of the property should be gen2

**Screenshots**

**Setup (please complete the following information):**

**Additional context**

**Information Checklist**

**Comment by weidongxu-microsoft** [comment]
Which version is the SDK?

**Comment by chborl** [comment]
@weidongxu-microsoft , it is version 1.37.0.

**Comment by chborl** [comment]
@weidongxu-microsoft , thanks for fixing this so quickly. Do you know how soon it will be available?

**Comment by weidongxu-microsoft** [comment]
@chborl 
Last release is a little more than one week ago. So next release will likely be a few weeks away.

This SDK is in maintenance mode, so release is not frequent.
