### ISSUE TITLE
[BUG] ArgumentNullException when creating a key vault in Azure Function

### ISSUE THREAD

**Issue by robwillis17** [Azure/azure-libraries-for-net#1225]
**Summary**
I've added a service bus triggered function to create a key vault for new tenants on our platform via the Microsoft.Azure.Management.Fluent library. 

The function runs fine locally and creates a new key vault within my MSDN subscription, however, when it's deployed into Azure and tries to create a Key Vault in our company test subscription it fails with an ArgumentNullException from Guid.Parse.

**Stack Trace**
Inner exception System.ArgumentNullException handled at CollectorFunctions.Proxies.KeyVaultProxy+<CreateKeyVault>d__9.MoveNext:
   at System.Guid.Parse (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultsImpl.WrapModel (Microsoft.Azure.Management.KeyVault.Fluent, Version=1.0.0.68, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultsImpl.Define (Microsoft.Azure.Management.KeyVault.Fluent, Version=1.0.0.68, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultsImpl.Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions.ISupportsCreating<Microsoft.Azure.Management.KeyVault.Fluent.Vault.Definition.IBlank>.Define (Microsoft.Azure.Management.KeyVault.Fluent, Version=1.0.0.68, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at CollectorFunctions.Proxies.KeyVaultProxy+<CreateKeyVault>d__9.MoveNext (CollectorFunctions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullCollectorFunctions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: D:\a\1\s\src\Server\CollectorFunctions\Proxies\IKeyVaultProxy.csCollectorFunctions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 86)

**Repro Steps**
The issue occurs when function is deployed to Azure and uses the functions Managed Service Identity (MSI) to try and create the Key Vault in our company test subscription. The MSI permissions were raised to Contributor and Owner on the Resource Group but still received the same error.
It works successfully locally when creating a key vault in my personal MSDN subscription using an .AzureAuth file.

**Sample Code**
The error occurs running the following statement which was taken from the ManageKeyVault example project linked from this repro. The supplied parameters all have valid values and the `resourceGroup `was looked up via `IAzure.ResourceGroups.GetByNameAsync(resourceGroupName)`.
```
await _azure.Vaults
      .Define(newKeyVaultName)
      .WithRegion(resourceGroup.Region)
      .WithExistingResourceGroup(resourceGroupName)
      .WithEmptyAccessPolicy()
      .CreateAsync();
```

**Expected behavior**
Key Vault should be created successfully

**Setup (please complete the following information):**
 - OS: Windows/Azure
 - IDE : Visual Studio
 - Version of the Library used: 1.37.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@robwillis17 
Would you try a later version? The latest is now 1.37.1

**Comment by robwillis17** [comment]
Sorry, that was a mistake, the version of the library being used should have been 1.37.0. 
I've updated it to 1.37.1 but still get the same error.

**Comment by weidongxu-microsoft** [comment]
@robwillis17 

It seems the "tenantId" is null. Please check your `AzureCredentials` object (could be a subclass of it), and see if it has non-null `TenantId` property. Usually `AzureCredentialsFactory` should have overload that provide this info into `AzureCredentials`.

**Comment by robwillis17** [comment]
@weidongxu-microsoft 
The MSI credentials are obtained from the `AzureCredentialsFactory ` using the approach below in the function app startup:

```
var credsFactory = new AzureCredentialsFactory(); 
var msiCreds = credsFactory.FromMSI(new MSILoginInformation(MSIResourceType.AppService), AzureEnvironment.AzureGlobalCloud);
```
I've taken a look at the AzureCredentials object that it generates and the `TenantId`, `ClientId `and `DefaultSubscriptionId `are all null.

However, after assigning the correct roles to the function app MSI in Azure the function app is able to successfully retrieve a list of existing key vaults, the current resource group and other details of other applications within the Resource Group via the Fluent Api using these credentials. 

Is this the correct approach for obtaining the credentials?

**Comment by weidongxu-microsoft** [comment]
@robwillis17 

The `tenantId` is used for creating vault. Most other features does not need the `tenantId`, but appears that vault needs it for creation.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1244-L1248
You can see it is among "required" properties.

**Comment by robwillis17** [comment]
@weidongxu-microsoft 
Thank you for your help, passing the `tenantId` via `credsFactory.FromMSI` resulted in the new Key Vault being successfully created.

I'm now getting a forbidden error (Similar to #971 ) when attempting to define an access policy on the new vault even though the MSI is currently in the Owner role for the entire Resource Group.

I need to investigate this issue further to see if I can find a solution, but if I cannot find a solution should it be raised as a new issue rather than added to this one?

**Comment by weidongxu-microsoft** [comment]
@robwillis17 

Access policy takes a few parameters.

`forObjectId` takes an object ID of user/service principal/etc., it should not require any additional permission if you know that object ID.

`forUser` or `forServicePrincipal` would require querying the AD for the object ID, and this would likely require ReadAll permission from AD to User or Application. However it seems quite hard to add that permission to MSI. Hence if you do it in MSI, you might likely need to stick to `forObjectId`.

**Comment by robwillis17** [comment]
@weidongxu-microsoft 

I updated the define access policy from `forServicePrincipal `to `forObjectId` and it resolved the permissions error. 
Thank you for your help.

**Comment by weidongxu-microsoft** [comment]
Glad that problem solved.
