### ISSUE TITLE
How do I set ClientId, ClientSecret and Issuer URL

### ISSUE THREAD

**Issue by NWessel** [Azure/azure-libraries-for-net#1238]
**Query/Question**
How does one go about adding the clientsecret?
I dont know how to persist what i try to do in lane 58-62.
![image](https://user-images.githubusercontent.com/9061380/118823699-75d0a280-b8b9-11eb-90e6-c99adac62dc5.png)

***Why is this not a Bug or a feature Request?***
It might be if it is not possible.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Microsoft.Azure.Management.Fluent - 1.37.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
This is probably a bug. It should be able to be provided at line 51-54.

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!
