### ISSUE TITLE
[BUG] GetPrimaryNetworkInterface does not have async overload and thus it cause performance issues

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-libraries-for-net#1241]
**Describe the bug**
Project using azure-libraries for .net is suffering by block threads because some calls are not try async calls.

For example method GetPrimaryNetworkInterface from file src/ResourceManagement/Compute/Domain/InterfaceImpl/VirtualMachineImpl.cs

Does not have async overload even if it is very easy to implement.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
No blocked threads, true async code
Please do review of the code and make all calls async if it can result to remote call.

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!
