### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by arjunblg75** [Azure/azure-libraries-for-net#1244]
**Query/Question**
The customer would like to know how to set the startup script via program for Fluent apps

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
```
var result = azure.WebApps.Manager.Inner.WebApps.UpdateConfigurationAsync("rg-weidxu1", "fa1weidxu",
new SiteConfigResourceInner()
{
AppCommandLine = "startup_command"
}).Result;
```
