### ISSUE TITLE
[BUG] Defining an Azure Firewall using WithAdditionalProperty() throws NullReferenceException

### ISSUE THREAD

**Issue by CodyBatt** [Azure/azure-libraries-for-net#1247]
**Describe the bug**
When defining an AzureFirewall resource using WithAdditionalProperty()/WithAdditionalProperties() method always results in a NullReferenceException because the Inner.AdditionalProperties member is null.

***Exception or Stack Trace***
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Management.Network.Fluent.AzureFirewallImpl.WithAdditionalProperty(String key, String value)
   at Microsoft.Azure.Management.Network.Fluent.AzureFirewallImpl.Microsoft.Azure.Management.Network.Fluent.AzureFirewall.Definition.IWithAdditionalProperty.WithAdditionalProperty(String key, String value)
```

**To Reproduce**
Run the code snippet.

***Code Snippet***
```
IAzure Az = GetAuthenticatedIAzureInstance();

var fwDefinition = Az.AzureFirewalls.Define("firewall")
    .WithNewResourceGroup("test-firewall", Region.USWest)
    // The next line throws
    .WithAdditionalProperty("Network.DNS.EnableProxy", "true");
```
**Expected behavior**
Expected that the additional property would be added to the definition of the firewall without an exception. I noticed in the portal that it isn't possible to set this property prior to firewall creation. If that's the intended behavior then the fluent API should exclude this method from Define() and only allow it for Update(). See additional context below.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used:
  Microsoft.Azure.Management.Fluent (1.37.1)

**Additional context**
I can work around this by creating the firewall and then updating it after it is created, for example:

```
var fw = await Az.AzureFirewalls.Define(FirewallName)
  .WithExistingResourceGroup(rg.Name)
  .WithRegion(rg.Region)
  .WithStandardSkuTier()
  .CreateAsync(CancelToken);
  
return await fw.Update()
  .WithAdditionalProperty("Network.DNS.EnableProxy", "true")
  .ApplyAsync(CancelToken);
```
This increases the time required to create the firewall.  

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by CodyBatt** [comment]
Well, this is fine but the preview SDK doesn't have all the functionality of the fluent SDK and it's still _**preview**_. This is a bug report, but if you aren't fixing bugs, you should state that so that people like me don't waste their time filing bugs that no one will look at. I've worked around both bugs I reported, so no need to fix, but if you put this information in the form, then people will know not to waste their time and your time.

**Comment by weidongxu-microsoft** [comment]
@CodyBatt

Sorry for the hard feeling. The disclaimer is mainly a notification to remind user that it is for their best interest to prepare migration to the new generation SDKs (which in the readme.md as well), as this SDK is likely not going to add new features.

We still fix bugs (particular this kind of NPE, which should not ever happen...). However the release could be pretty sparse.
