### ISSUE TITLE
How to mount Azure File shares using the Microsoft.Azure.Management.AppService.Fluent nuget

### ISSUE THREAD

**Issue by shivamgupta-msft** [Azure/azure-libraries-for-net#1253]
We were using the Microsoft.Azure.Management.AppService.Fluent nuget version 1.29.1 to mount azure file shares in the containers. This version had AzureStorageAccounts entry in SiteConfig class which enabled mounting azure file shares.

We have now updated the nuget to the latest version (1.37.1) but the AzureStorageAccounts property has been removed from this version.

Can someone let us know how to mount azure file shares using the latest nuget?

**Comment by weidongxu-microsoft** [comment]
@shivamgupta-msft 
Checked and `azureStorageAccounts` is removed from `SiteConfig`. Last seen in api-version=2018-02-01.

Does this API work? It is added in api-version=2018-02-01 and exists on all versions afterwards.
```
azure.WebApps.Manager.Inner.WebApps.UpdateAzureStorageAccountsAsync
```

Note that this SDK is going to be replace by track2 .NET mgmt SDK.

**Comment by shivamgupta-msft** [comment]
Thanks @weidongxu-microsoft , the above API worked.

**Comment by shivamgupta-msft** [comment]
@weidongxu-microsoft can you share some details around the usefulness of "track2 .NET mgmt SDK" and when is it planned to be released.

**Comment by weidongxu-microsoft** [comment]
@shivamgupta-msft 

Here is the notification from PM

> For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
> https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/
> 
> We have also published a few blog posts on why we are doing this:
> https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/
> 
> With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

The first batch of the new track2 .NET SDK preview is expected to be available at this week or the next. It should appear as updated here https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

However appservice (or web) is not in the first batch.
