### ISSUE TITLE
[BUG] `GetMasterKeyAsync` is unable to deserialize the response for Azure Function App

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#1259]
**Describe the bug**
`GetMasterKeyAsync` is unable to deserialize the response for Azure Function App

***Exception or Stack Trace***
- **Message**: "Unable to deserialize the response."
- **InnerException**: `{"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."}`
- **Content**: `<!DOCTYPE html>\n<html>\n<head>\n    <title>Your Azure Function App is up and running.</title>\n    <style type=\"text/css\">\n {...omitted but default function page...}` 

This happens to some Azure Function Apps but not to all.

**To Reproduce**
1. Run code below

***Code Snippet***
```csharp
var applicationId = Configuration["activeDirectory:application:id"];
var applicationSecret = Configuration["activeDirectory:application:secret"];
var subscriptionId = Configuration["activeDirectory:subscription"];
var tenantId = Configuration["activeDirectory:tenant"];

var azureCredentials = new AzureCredentialsFactory()
    .FromServicePrincipal(applicationId, applicationSecret, tenantId, AzureEnvironment.AzureGlobalCloud);

var azure = Microsoft.Azure.Management.Fluent.Azure.Authenticate(azureCredentials)
    .WithSubscription(subscriptionId);

var functionApps = await azure.AppServices.FunctionApps.ListAsync();
var functionApp = functionApps.SingleOrDefault(functionApp => functionApp.Name == functionAppName);
if (functionApp == null)
{
    throw new ApplicationException($"Could not find a function application with name {functionAppName}");
}

return await functionApp.GetMasterKeyAsync();
```

**Expected behavior**
Master key is provided

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : Visual Studio
 - Version of the Library used: v1.37.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by tomkerkhove** [comment]
This seems to be working fine for Window, but not for Linux.

**Comment by weidongxu-microsoft** [comment]
It likely already fixed in this PR https://github.com/Azure/azure-libraries-for-net/pull/1228

However since the SDK is in maintenance mode and new SDK is soon getting out (which will replace this one), we haven't released a version of that fix.

Will try to check next release schedule. But probably going to be next month.

**Comment by weidongxu-microsoft** [comment]
@tomkerkhove
1.38.0 released.

**Comment by tomkerkhove** [comment]
Thank you!
