### ISSUE TITLE
README.md has broken link

### ISSUE THREAD

**Issue by sergiygetlin** [Azure/azure-libraries-for-net#1277]
Section "Help and Issues" has broken link which returns 404. 

Link below doesn't work:
To enable Http message tracing in your code please check https://github.com/Azure/autorest/blob/master/docs/client/tracing.md#tracing

**Comment by weidongxu-microsoft** [comment]
Thanks for notification. I will update it soon. Should be this section https://github.com/Azure/azure-libraries-for-net#logging

Note that there is new SDKs available as preview.
