### ISSUE TITLE
Fluent libraries are pinned to a single version of ADAL

### ISSUE THREAD

**Issue by stankovski** [Azure/azure-libraries-for-net#128]
Fluent libraries are pinned to a single version of ADAL via Microsoft.Rest.ClientRuntime.Azure.Authentication making it impossible to use them with any other package that relies on ADAL

**Comment by hovsepm** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/3787

**Comment by hovsepm** [comment]
fixed in Fluent SDK v1.6
