### ISSUE TITLE
IWebApp.GetPublishingProfileAsync() returns null for user/pass when WithFtpsState(FtpsState.FtpsOnly)

### ISSUE THREAD

**Issue by daveaglick** [Azure/azure-libraries-for-net#1300]
**Describe the bug**
Sometime last week we stopped being able to get username and password credentials for FTP publishing through the fluent API using `IWebApp.GetPublishingProfileAsync()`. The `IPublishingProfile.FtpUsername` and `IPublishingProfile.FtpPassword` are now both coming back as `null`. It's worth noting that this has worked reliably for at least a year on the exact same web apps until this week.

I was able to track the different back to the use of `WithFtpsState(FtpsState.FtpsOnly)` when creating an app. For a newly created app without that setting, I could successfully continue to get credentials via `IWebApp.GetPublishingProfileAsync()`. However, with a brand new app with the `WithFtpsState(FtpsState.FtpsOnly)` setting, `IWebApp.GetPublishingProfileAsync()` exhibits the new `null` username and password behavior.

I've also been able to confirm that the publishing profile, including working username and password, can still be obtained via the REST API using the "/providers/Microsoft.Web/sites/[app name]/publishxml" endpoint. That suggests this is a problem either with the endpoints used by the `GetPublishingProfileAsync()` method or the method itself in situations where `FtpsOnly` is turned on.

***Exception or Stack Trace***
No exception is produced, only `null` `IPublishingProfile.FtpUsername` and `IPublishingProfile.FtpPassword`

**To Reproduce**
Call `IWebApp.GetPublishingProfileAsync()` on a web app with `WithFtpsState(FtpsState.FtpsOnly)`.

***Code Snippet***
```
var azure = Microsoft.Azure.Management.Fluent.Azure
    .Configure()
    .Authenticate(credentials)
    .WithSubscription(subscriptionId);
var webapp = await Azure.WebApps.GetByResourceGroupAsync("rg", "appname");
var profile = await webapp.GetPublishingProfileAsync();
profile.FtpUsername.Dump(); // null
profile.FtpPassword.Dump(); // null
```

**Expected behavior**
A valid username and password for FTP publishing is returned.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : None (run from `dotnet run`)/tested in LINQPad as well
 - Version of the Library used: `Microsoft.Azure.Management.Fluent` 1.38.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

Note that I have worked around this problem for our own purposes using the XML publishing profile which still returns expected results.

**Comment by vlkuznet** [comment]
This line of code contains RegEx that leads to the failure: [(https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/PublishingProfileImpl.cs#L20](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/PublishingProfileImpl.cs#L20)

Specifically, it matches a publishUrl prefix of ftp://

` publishUrl=\"ftp://([^\"]+)`

When the App Service FTPS only attribute is enabled, a url with prefix ftp**s**:// is returned. The inclusion of the 's' causes the regex not to match

Sample publish profiles off my app with FTP mode set to "FTPS Only" and "All Allowed", respectively:

FTPS Only: 
`<publishData>
...
<publishProfile profileName="nameofmyapp- FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-stamp.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="nameofmyapp\$nameofmyapp" userPWD="password_removed" destinationAppUrl=http://nameofmyapp.azurewebsites.net SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink=http://windows.azure.com webSystem="WebSites"><databases /></publishProfile>
...
</publishData>`

All Allowed:
`<publishData>
...
<publishProfile profileName="nameofmyapp - FTP" publishMethod="FTP" publishUrl=ftp://waws-prod-stamp.ftp.azurewebsites.windows.net/site/wwwroot ftpPassiveMode="True" userName="nameofmyapp\$nameofmyapp" userPWD="password_removed" destinationAppUrl=http://nameofmyapp.azurewebsites.net SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink=http://windows.azure.com webSystem="WebSites"><databases /></publishProfile>
...
</publishData>`

**Comment by weidongxu-microsoft** [comment]
@daveaglick @vlkuznet
Thanks for the report and diagnostic. I will fix it in code, but we do not have a schedule on next release as this lib is in maintenance. 

A quick workaround is to call 
```
Azure.WebApps.Manager.Inner.WebApps.ListPublishingProfileXmlWithSecretsAsync
```
and parse the XML.

New user is recommended to switch to https://aka.ms/azsdk/dotnet/mgmt (webapp is not released there yet).
