### ISSUE TITLE
[QUERY] While working on Activitylogs using Azure Sdk JAVA.

### ISSUE THREAD

**Issue by yashaswi90** [Azure/azure-libraries-for-net#1309]
**Query/Question**
Hi,
Please help me in resolving this issue which I am getting while trying to access activity log using Azure sdk.

**I want to fetch the activity log for particular resource id and get the caller details using java azure sdk.**

2022-05-05 10:30:44.940 ERROR 6928 --- [onPool-worker-2] c.azure.identity.ClientSecretCredential  : Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: java.util.Collections$SingletonList cannot be cast to java.lang.String
2022-05-05 10:30:44.940 ERROR 6928 --- [onPool-worker-2] c.a.c.implementation.AccessTokenCache    : Failed to acquire a new access token.

 TokenCredential tokenCredential = new DefaultAzureCredentialBuilder()
                    .build();

            DefaultAzureCredential defaultCredential = new DefaultAzureCredentialBuilder()
                    .tenantId(System.getenv("AZURE_TENANT_ID"))
                    .build();

            final AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);

AzureResourceManager azureResourceManager = AzureResourceManager
                    .configure()
                    .withLogLevel(HttpLogDetailLevel.BASIC)
                    .authenticate(tokenCredential, profile)
                    .withDefaultSubscription();

            PagedIterable<EventData> logs = azureResourceManager.activityLogs().defineQuery()
                    .startingFrom(OffsetDateTime.now().minusDays(24))
                    .endsBefore(OffsetDateTime.now())
                    .withAllPropertiesInResponse()
                    .filterByResourceGroup("rgrp-name")
                    .execute();
            for (EventData event : logs) {
                System.out.println("\tCaller: " + event.caller());
                System.out.println("\tCorrelationId: " + event.correlationId());
                System.out.println("\tSubscriptionId: " + event.subscriptionId());
            }

I am using above code but it is not allowing me to get the event data.

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
The repo is .NET

See https://aka.ms/azsdk/java/mgmt, try to update all libs to latest (e.g. mgmt to 2.14.0, azure-identity to 1.5.0)

**Comment by yashaswi90** [comment]
@weidongxu-microsoft i am facing issue with the azure SDK for activitylog api.
Please provide the link where I can raise my issue for getToken() call for scopes is failing.

**Comment by weidongxu-microsoft** [comment]
Here https://github.com/Azure/azure-sdk-for-java/issues

But anyway, try latest version first. And report issue would still require you fill in the SDK version you are using.

**Comment by yashaswi90** [comment]
@weidongxu-microsoft i am using spring cloud azure starter version 4.0.0
Azure resource manager 2.10.0
Spring cloud axure starter 4.0.0
Spring cloud service 4.0.0
Azure-mgmt-monitor 1.20.1

**Comment by weidongxu-microsoft** [comment]
It is possible for you to have maven print the `azure-identity` and `azure-core` version?

See https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/resourcemanager#dependency-management

**Comment by weidongxu-microsoft** [comment]
`azure-mgmt-monitor` is the old lib. Is it possible for you to remove it from the project?

**Comment by yashaswi90** [comment]
Maven :-
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
        <relativePath/> 
    </parent>
    <groupId>com.msci</groupId>
    <artifactId>usercostanalysis</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>usercostanalysis</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud-azure.version>4.0.0</spring-cloud-azure.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure</artifactId>
            <version>1.16.0</version>
        </dependency>
   
     
       

        
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>11.0.1</version>
        </dependency>
  

        <dependency>
            <groupId>net.sf.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>2.3</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-common</artifactId>
            <version>12.15.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-starter-storage-blob</artifactId>
            <version>4.0.0</version>
        </dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
			<version>12.15.0</version>
		</dependency>
        
        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager</artifactId>
            <version>2.10.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.4.1</version>
        </dependency>

        
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>4.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by yashaswi90** [comment]
Hi @weidongxu-microsoft 

Still I am getting below error:- 
2022-05-05 15:31:23.084 ERROR 12124 --- [onPool-worker-9] c.azure.identity.ClientSecretCredential  : Azure Identity => ERROR in getToken() call for scopes [https://management.core.windows.net//.default]: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'fc24acc2-dfb5-4eb8-8d21-d1cbda1bcc56'.
Trace ID: 1d71406a-fedd-425b-9357-4872cad1ef00
Correlation ID: cd583b46-ea53-4241-a4ef-1075cffa94b6
Timestamp: 2022-05-05 10:01:22Z
2022-05-05 15:31:23.084 ERROR 12124 --- [onPool-worker-9] c.a.c.implementation.AccessTokenCache    : Failed to acquire a new access token.



<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
        <relativePath/> 
    </parent>
    <groupId>com.msci</groupId>
    <artifactId>usercostanalysis</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>usercostanalysis</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>1.8</java.version>
        <spring-cloud-azure.version>4.0.0</spring-cloud-azure.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure</artifactId>
            <version>1.16.0</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-identity</artifactId>
            <version>1.4.1</version>
        </dependency>

        <dependency>
            <groupId>com.azure.resourcemanager</groupId>
            <artifactId>azure-resourcemanager</artifactId>
            <version>2.10.0</version>
        </dependency>
   

        <dependency>
            <groupId>net.sf.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>2.3</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>4.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

Below is my service class:-

  final AzureProfile profile = new AzureProfile(AzureEnvironment.AZURE);
            TokenCredential tokenCredential = new DefaultAzureCredentialBuilder()
                    .authorityHost("https://login.microsoftonline.com/common/oauth2/authorize")
                    .build();
            AzureResourceManager azureResourceManager = AzureResourceManager
                    .configure()
                    .withLogLevel(HttpLogDetailLevel.BASIC)
                    .authenticate(tokenCredential, profile)
                    .withDefaultSubscription();

            PagedIterable<EventData> logs = azureResourceManager.activityLogs().defineQuery()
                    .startingFrom(OffsetDateTime.now().minusDays(24))
                    .endsBefore(OffsetDateTime.now())
                    .withAllPropertiesInResponse()
                    .filterByResourceGroup("rgrp-dva2-it-costanalysisreport")
                    .execute();
            for (EventData event : logs) {
                System.out.println("\tCaller: " + event.caller());
                System.out.println("\tCorrelationId: " + event.correlationId());
                System.out.println("\tSubscriptionId: " + event.subscriptionId());
            }


What is wrong in that?

**Comment by yashaswi90** [comment]
Thanks @weidongxu-microsoft issue is resolved with the dependencies that you said to remove and add.
