### ISSUE TITLE
[QUERY] Get Role Assignment for an ObjectId

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-libraries-for-net#1316]
**Query/Question**
What is the dotnet implementation of `Get-AzRoleAssignment -ObjectId <objectId>`?

***Why is this not a Bug or a feature Request?***
There's clearly a PowerShell way to do it and it calls an API somewhere, but I'm not sure how to do it in c#.

I tried to use `azure.AccessManagement.RoleAssignments.Inner.ListForResourceWithHttpMessagesAsync()` from the `Microsoft.Azure.Management.Graph.RBAC.Fluent` package (version 1.38.1), but that doesn't seem correct to me and also fails with `this.Client.SubscriptionId cannot be null` even though other API calls with the same client (`azure`) work fine.
 
Short: How can I list all the Azure RBAC Role Assignments for a given object (managed identity / user assigned identity)?

**Comment by weidongxu-microsoft** [comment]
@davidobrien1985 
It is a defect that subscriptionId not set to the Client.

You can use this:
```
            var resourceAssignments = azure.AccessManagement.RoleAssignments.Inner.ListForScopeAsync(
                "/subscriptions/<subscriptionId>", 
                new ODataQuery<RoleAssignmentFilter>(p => p.PrincipalId == "<objectId>")).Result;
```

Please make plan to migrate to https://aka.ms/azsdk/dotnet/mgmt

**Comment by davidobrien1985** [comment]
@weidongxu-microsoft thanks, that's helpful.
Do you have an example to do this with the new SDKs? I initially tried it with the new one but couldn't figure it out.

**Comment by weidongxu-microsoft** [comment]
@davidobrien1985 
They have yet to publish it. It should be `Azure.ResourceManager.Authorization` in https://github.com/Azure/azure-sdk-for-net/pull/29075

**Comment by davidobrien1985** [comment]
@weidongxu-microsoft ah okay, so it's not yet available. We'll keep an eye on it. Thanks!
