### ISSUE TITLE
[FEATURE REQ] add a clear deprecation warning to the README

### ISSUE THREAD

**Issue by riezebosch** [Azure/azure-libraries-for-net#1330]

**Comment by weidongxu-microsoft** [comment]
Thanks. It should happen on Sept. I am waiting the deprecation on NuGet package, before updating the readme.

**Comment by weidongxu-microsoft** [comment]
nuget package is marked as deprecated, e.g. https://www.nuget.org/packages/Microsoft.Azure.Management.Compute.Fluent/
