### ISSUE TITLE
[FEATURE REQ] FunctionApp key management

### ISSUE THREAD

**Issue by JDECOMBE** [Azure/azure-libraries-for-net#1337]
Hi,

**Is your feature request related to a problem? Please describe.**
Yes. I'd like to be able to work with the master keys and the system keys of a FunctionApp in C#.

**Describe the solution you'd like**
A set of methods exposed via the IFunctionApp interface to set / create or delete master and system keys. 
Such methods exist right now but this is limited to function keys (`IFunctionApp.AddFunctionKeyAsync` and `IFunctionApp.RemoveFunctionKeyAsync` ).

**Additional context**
I'm guessing this is possible since Azure CLI expose this logic via the  `az functionapp keys set` and `az functionapp keys delete` commands.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
This lib is deprecated. Please migrate https://aka.ms/azsdk/dotnet/mgmt

**Comment by JDECOMBE** [comment]
Oh.. Sorry about that, thanks for the information !
