### ISSUE TITLE
[BUG] QueryResourceAsync causing error if used with TimeRange of QueryTimeRange(Datetime, Datetime)

### ISSUE THREAD

**Issue by egressyk** [Azure/azure-libraries-for-net#1348]
**Describe the bug**
Using **MetricsQueryClient.QueryResourceAsync()** with option **TimeRange** of **QueryTimeRange(startTime, endTime)** causes and error, opposed to TimeRange of QueryTimeRange(duration).

***Exception or Stack Trace***
'Detected invalid time interval input: 2023-11-15T10:12:25.4174057 01:00/2023-11-15T11:12:25.4174057 01:00, supported Iso 8601 time interval format: (Datetime/Datetime, Datetime/Duration, Duration/Datetime, Duration)
Status: 400 (Bad Request)
ErrorCode: BadRequest

```
at Azure.Monitor.Query.MetricsRestClient.<ListAsync>d__7.MoveNext()
at Azure.Monitor.Query.MetricsQueryClient.<QueryResourceAsync>d__13.MoveNext()
```

**To Reproduce**

```
var metricsQueryClient = new MetricsQueryClient(new DefaultAzureCredential());
var endTime = DateTimeOffset.Now;
var startTime = endTime.AddHours(-1);

var resourceId = <someAppServiceResourceId>;
var metricsNames  = new List<string> { "HttpResponseTime" };
var options = new MetricsQueryOptions
{
    Aggregations = { MetricAggregationType.Average },
    Granularity = TimeSpan.FromMinutes(1),
    TimeRange = new QueryTimeRange(startTime, endTime)
};

var result = await metricsQueryClient.QueryResourceAsync(resourceId, metricsNames, options);
```

**Expected behavior**
Receive the same result as if used with

```
var options = new MetricsQueryOptions
{
    Aggregations = { MetricAggregationType.Average },
    Granularity = TimeSpan.FromMinutes(1),
    TimeRange = new QueryTimeRange(TimeSpan.FromHours(1))
};
```

**Setup (please complete the following information):**
 - Windows 10
 - VisualStudio
 - Azure.Monitor.Query 1.2.0

**Additional context**
It seems like the "+" gets lost from the DateTimeOffset string: 2023-11-15T10:12:25.4174057 01:00

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by weidongxu-microsoft** [comment]
This lib was deprecated in 2022
https://github.com/Azure/azure-libraries-for-net#this-repository-was-deprecated-in-september-2022

And this lib does not include "Azure.Monitor.Query". It is there https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.Query
Would you open issue there? I seems not able to move this issue to that repo.
