### ISSUE TITLE
Fluent SDK: listing Cosmos accounts not implemented

### ISSUE THREAD

**Issue by JadedATB** [Azure/azure-libraries-for-net#145]
IAzure.CosmosDBAccounts.ListByResourceGroupAsync()
IAzure.CosmosDBAccounts.ListByResourceGroup()
IAzure.CosmosDBAccounts.ListAsync()

As of version 1.4.1, all three of these methods are still throwing NotImplementedExceptions.  

IAzure.CosmosDBAccounts.List() returns an enumeration, but throws a NotImplementedException whenever you attempt to access the values.

I don't currently see a way to list available Cosmos accounts.

**Comment by mikefayer** [comment]
Version 1.6 is the same situation.

**Comment by milismsft** [comment]
Should be fixed by PR https://github.com/Azure/azure-libraries-for-net/pull/331
