### ISSUE TITLE
Wrapper for getting all resources by group/tag?

### ISSUE THREAD

**Issue by kierenj** [Azure/azure-libraries-for-net#180]
I'm looking to retrieve a list of all resources in a given resource group.  At the moment the only way I've found is:

`(IAzure).MetricDefinitions.Manager.ResourceManager.GenericResources.ListByResourceGroupAsync(group.Name)`

Is that the recommended way to go?

Also: feel a bit weird asking a usage question in Issues.  If you want to redirect me somewhere better/more appropriate, I'll be happy to close this one up! Thanks!

**Comment by hovsepm** [comment]
you should be able to access `.Manager.ResourceManager.GenericResources.` and then all the methods through any operation group under. e.g. 
`(IAzure).VirtualMachines.Manager.ResourceManager.GenericResources`
`(IAzure).NetworkInterfaces.Manager.ResourceManager.GenericResources`
etc.
You can also create a resource group manager directly.

We did not see much benefits of exposing a GenericResources directly from the IAzure interface. Fluent models are based on a specific resource type and we group the functionality of that type in the operation groups. Sorry if this sounds confusing :).

**Comment by kierenj** [comment]
That's fine, not going to argue like I understand all the use-cases as well as you guys!  I'll keep doing as I'm doing..

**Comment by MisinformedDNA** [comment]
@hovsepm So is there a non-fluent API to access instead?

**Comment by shahabhijeet** [comment]
Non Fluent alternative is
Using [Microsoft.Azure.Management.ResourceManager](
https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager/2.0.0-preview)
ResourceManagementClient.Resources.ListByResourceGroupWithHttpMessagesAsync

**Comment by MisinformedDNA** [comment]
I notice that there are no non-prerelease versions. Is this something that will be coming in the near future?
