### ISSUE TITLE
CosmosDB account creation never returns

### ISSUE THREAD

**Issue by mikefayer** [Azure/azure-libraries-for-net#185]
As of version 1.6. I never let CreateAsync go for more than 5 minutes or so. I can see that the account is quickly correctly created as specified in the code, even though the code never returns.

**Comment by milismsft** [comment]
@mikefayer how long does it take for the same operation to be completed via the Azure Portal?

**Comment by mikefayer** [comment]
Kinda ambiguous... when I create a test account in the portal it took around 3 minutes until the "completed" notification popped up, while the account was actually visible in the RG in under a minute.

**Comment by milismsft** [comment]
@mikefayer I cannot reproduce this issue on my side; can you give me some additional info about what kind of account you are creating, any particular settings etc? If you are adding replications to your CosmosDB account the SDK will keep pooling until all the replications are available and will it not return until such. Depending on where the replications are requested this can take a lot more than 5 minutes.
