### ISSUE TITLE
UserKubeConfigContent and AdminKubeConfigContent return empty arrays.

### ISSUE THREAD

**Issue by JonJam** [Azure/azure-libraries-for-net#197]
Hi, 

I am trying to get the kube config context of an existing Azure Kubernetes cluster using version 1.6 of the SDK.

When I inspect the context properties they are both empty, am I doing anything wrong?

```C#
var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(
  "CLIENTID",
 "CLIENTSECRET",
  "TENANT",
  AzureEnvironment.AzureGlobalCloud);

string aksName = "AKS_NAME";

IAzure azure = Azure.Authenticate(credentials).WithDefaultSubscription();

IKubernetesCluster kubernetesCluster = azure.KubernetesClusters.GetByResourceGroup("RESOURCE_GROUP", aksName);
var b = kubernetesCluster.UserKubeConfigContent;
var c = kubernetesCluster.AdminKubeConfigContent;
```

**Comment by milismsft** [comment]
Hi @JonJam, this is a known service side issue which was addressed in the latest version (v1.7.0) of the Java management libraries for AKS. The service no longer returned the Kube.Config content as part of the resource payload and it required another specific API call to retrieve it.
Please let me know if the latest version of the library works for you.

**Comment by JonJam** [comment]
Hi @milismsft, is that including the C# SDK?

As the latest nuget version is 1.6 https://www.nuget.org/packages/Microsoft.Azure.Management.ContainerService.Fluent/

**Comment by milismsft** [comment]
Yes; the release for the .Net v1.7 goes out today.

**Comment by JonJam** [comment]
Oh cool thanks @milismsft. I will look out for it :)

**Comment by hovsepm** [comment]
v1.7 is out. Please create a new bug with the version reference if it still occurs.
