### ISSUE TITLE
Azure class in Microsoft.Azure.Management.Fluent has too many dependencies

### ISSUE THREAD

**Issue by kblooie** [Azure/azure-libraries-for-net#200]
Based on the ReadMe, the simplest way to authenticate is with the `Azure` class:

`IAzure azure = Azure.Authenticate(credFile).WithDefaultSubscription();`

I could only reference that class when adding `Microsoft.Azure.Management.Fluent`, which has a dependency to every other Fluent package. It seems excessive that I have to add dependencies for all fluent projects when I only want to use Dns.Fluent.

Shouldn't the dependency be inversed (all sub projects take a dependency on a core project)?

Am I doing something wrong?

Jonathan

**Comment by hovsepm** [comment]
Rollup client (aka Azure class) is just a convenience layer and you should be able to create just a manager of the package that you need (dns). Here is the example how we create it https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Azure.Fluent/Azure.cs#L518 ,

**Comment by kblooie** [comment]
Thanks for the link and explanation! That's exactly what I was hoping for. As a newcomer to your fluent api, I think it would be helpful to add this to your auth documentation. 

Thanks again
