### ISSUE TITLE
Incorrect ManagementEndpoint for GermanCloud

### ISSUE THREAD

**Issue by deepakverma** [Azure/azure-libraries-for-net#203]
ResourceManagerEndpoint for German cloud should be "https://management.core.microsoftazure.de/" instead of   "https://management.core.cloudapi.de",

current:
   AzureEnvironment.AzureGermanCloud = new AzureEnvironment()
      {
        AuthenticationEndpoint = "https://login.microsoftonline.de/",
        ResourceManagerEndpoint = "https://management.microsoftazure.de/",
        ManagementEndpoint = "https://management.core.cloudapi.de",
        GraphEndpoint = "https://graph.cloudapi.de/",
        StorageEndpointSuffix = ".core.cloudapi.de"
      };

With the current URL in the sdk it would throw the following exception
Unhandled Exception: Microsoft.Rest.Azure.CloudException: The access token has been obtained from wrong audience or resource 'https://management.core.microsoftazure.de/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.cloudapi.de/','https://management.microsoftazure.de/'.

**Comment by hovsepm** [comment]
@deepakverma I do not see that endpoint in dev guide here https://docs.microsoft.com/en-us/azure/germany/germany-developer-guide#endpoint-mapping 
Was it changed recently?

**Comment by hovsepm** [comment]
Closing as won't fix as there is no response for a while.
