### ISSUE TITLE
Updating tags in a resource group

### ISSUE THREAD

**Issue by devszr** [Azure/azure-libraries-for-net#204]
I'm using the following method to update an existing tag on a resource group. I'm not sure why, but the tag value doesn't seem to get updated. It looks like the Java SDK is able to update the tag with the same method.

azure.ResourceGroups.GetByName('myRG').Update().WithTag("existing-tag", "newVal").Apply();

The above method works for adding a new tag though.

**Comment by jengstro2** [comment]
Ok. The Tag(s). So Microsoft has new vocabulary where Delete is synonym for WithoutTag 😏 
Also Update means -> "Create only", like you were wondering

Here is "update" example.
```
azureAPIConn.ResourceGroups.GetByName("yourResGroup").Update().WithoutTag("JaskaJokunen").Apply();
azureAPIConn.ResourceGroups.GetByName("yourResGroup").Update().WithTag("JaskaJokunen",newTagValue").Apply();
//Showing res group active tags
azureAPIConn.ResourceGroups.GetByName("yourResGroup").Tags;

```

**Comment by yaohaizh** [comment]
Close this issue as fluent SDK using this naming convention for deleting.
