### ISSUE TITLE
How to provision Application Insights

### ISSUE THREAD

**Issue by wis3guy** [Azure/azure-libraries-for-net#210]
I know
* that it is possible to create an Application Insights resource using an ARM template (json)
* that currently Application Insights resources are not natively supported
* that i can create resources using the `GenericResources` property on the `ResourceManager`

My question is, how do i create an Application Insights resource using the generic resources route? I struggle to map this:

```json
{
  "name": "string",
  "type": "microsoft.insights/components",
  "apiVersion": "2015-05-01",
  "location": "string",
  "tags": {},
  "kind": "string",
  "properties": {
    "Application_Type": "string",
    "Flow_Type": "Bluefield",
    "Request_Source": "rest",
    "HockeyAppId": "string",
    "SamplingPercentage": integer
  }
}
```
> Taken from: https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/components

to something like this:

```c#
var insights = ResourceManager
    .Configure()
    .Authenticate(credentials).WithSubscription(azure.SubscriptionId)
    .GenericResources.Define($"{pfx}-ai")
    .WithRegion(region)
    .WithExistingResourceGroup(rg)
    .WithResourceType("microsoft.insights/components")
    .WithProviderNamespace("tbd") // TODO
    .WithPlan("tbd") // TODO
    .WithApiVersion("tbd") // TODO
    .WithProperties(new {}) // TODO
    .Create();
```

My goal is to provision this resource and set the `APPINSIGHTS_INSTRUMENTATIONKEY` on all of the subsequently created App Services and Function Apps.

Some guidance would be much appreciated.

**Comment by wis3guy** [comment]
I figured it out myself. Leaving this comment for future reference.

```c#
var insights = ResourceManager
    .Configure()
    .Authenticate(credentials).WithSubscription(azure.SubscriptionId)
    .GenericResources.Define($"{options.Prefix}-ai")
    .WithRegion(options.Region)
    .WithExistingResourceGroup(rg)
    .WithResourceType("components")
    .WithProviderNamespace("microsoft.insights")
    .WithoutPlan()
    .WithApiVersion("2015-05-01")
    .WithParentResource("")
    .WithProperties(new
    {
        Application_Type = "web"
    })
    .Create();

var token = ((JObject) insights.Properties)["InstrumentationKey"];

var instrumentationKey = token?.Value<string>() ?? string.Empty;
```

**Comment by luthus** [comment]
It doesn't look like the properties are passed to the API if an anonymous object is used. 

The following works though:
`
var insights = ResourceManager
                                .Configure()
                                .Authenticate(credentials).WithSubscription(azure.SubscriptionId)
                                .GenericResources.Define($"{options.Prefix}-ai")
                                .WithRegion(options.Region)
                                .WithExistingResourceGroup(rg)
                                .WithResourceType("components")
                                .WithProviderNamespace("microsoft.insights")
                                .WithoutPlan()
                                .WithApiVersion("2015-05-01")
                                .WithParentResource("")
                                .WithProperties(new Dictionary<string, string>()
                                {
                                    { "Application_Type", "other"}
                                })
                                .Create();
`

Using a strongly typed object works too. 

`
public class ApplicationInsightsProperties
{
        public string Application_Type { get; set; }
 }
`

`
var insights = ResourceManager
                                .Configure()
                                .Authenticate(credentials).WithSubscription(azure.SubscriptionId)
                                .GenericResources.Define($"{options.Prefix}-ai")
                                .WithRegion(options.Region)
                                .WithExistingResourceGroup(rg)
                                .WithResourceType("components")
                                .WithProviderNamespace("microsoft.insights")
                                .WithoutPlan()
                                .WithApiVersion("2015-05-01")
                                .WithParentResource("")
                                .WithProperties(new ApplicationInsightsProperties
                                {
                                    Application_Type = "other"
                                })
                                .Create();
`

**Comment by wis3guy** [comment]
@luthus Wow that is a great catch. I (clearly) only tested with my desired outcome ... which happened to be the default behavior.
