### ISSUE TITLE
Symbols not archived for microsoft.azure.management.keyvault.fluent

### ISSUE THREAD

**Issue by prasethu** [Azure/azure-libraries-for-net#219]
We're depending on this package in Visual Studio but the binary doesn't seem to have been archived.

This issue tracks the request to archive symbols for every release since otherwise it would be out of tenet compliance.

//cc: @AArnott

**Comment by AArnott** [comment]
To be clear: we need symbols archived such that http://symweb and Watson can find them long-term.

**Comment by hovsepm** [comment]
@prasethu @AArnott I'll work on the fix for the nearest release which should be out early next week.

**Comment by hovsepm** [comment]
Ok so this tasks seems to be completely unrelated to nuget.org symbols and will not be available by the next week.

**Comment by AArnott** [comment]
I'm not sure what you mean. What has nuget.org to do with symbols? We just need the PDB file associated with the DLL that you make available on nuget.org to be archived.

**Comment by hovsepm** [comment]
@prasethu @AArnott I've published symbols to public symbol server for version v.1.10. Could you try it out and see if your request is fully addressed?

**Comment by hovsepm** [comment]
Fixed for all builds starting from v1.13
