### ISSUE TITLE
Provide validation or enums for Service Level Tiers

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#23]
Currently all service level tiers, such as database tiers, are all strings.

It is currently very hard to build applications to validate input for these things.
Are there plans to introduce enums or validation components which we can use to validate input on?

I'm aware of classes such as `DatabaseEditions` but these are not really helping since we need to check each property of these classes instead of having a `TryParse` on an enum.

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by hovsepm** [comment]
@milismsft I believe this is something that you are working on, right?

**Comment by milismsft** [comment]
Yes, this will be addressed in the coming update.

**Comment by hovsepm** [comment]
Release 1.7 is out. Please create a new bug if this issue will still be valid.

**Comment by tomkerkhove** [comment]
Awesome, thank you!
