### ISSUE TITLE
Fix issue with usage of "catch (AggregateException ex)" in core classes

### ISSUE THREAD

**Issue by milismsft** [Azure/azure-libraries-for-net#233]
ResourceManager\Core\GroupableResources.cs
`            catch (AggregateException ex) when ((ex.InnerExceptions[0] as CloudException).Response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return null;
            }
`
We need to iterate rather than relying on first item to be of CloudException type.

**Comment by hovsepm** [comment]
fixed in release v1.10
