### ISSUE TITLE
Exception creating event hub named "requests"

### ISSUE THREAD

**Issue by JadedATB** [Azure/azure-libraries-for-net#242]
Since 3/22, attempting to create an event hub named "requests" has been failing with an InternalServerError.

Example code:

        private static async Task Test(IAzure azure)
        {
            IResourceGroup resourceGroup = await azure.ResourceGroups.Define("Rg-Test-EventHub")
                .WithRegion("South Central US")
                .CreateAsync();

            IEventHubNamespace ehNamespace = await azure.EventHubNamespaces.Define("eh-segment-test-ussc-dev")
                .WithRegion("South Central US")
                .WithExistingResourceGroup(resourceGroup)
                .CreateAsync();

            await azure.EventHubs.Define("requests")
                .WithExistingNamespace(ehNamespace)
                .WithPartitionCount(4)
                .WithRetentionPeriodInDays(2)
                .CreateAsync();
        }

The Define/CreateAsync statement consistently throws a Microsoft.Azure.Management.EventHub.Fluent.Models.ErrorResponseException, with the message: "Operation returned an invalid status code 'InternalServerError'"

Any other name I've tried works fine... Are there specific names that are reserved/disallowed?

**Comment by serkantkaraca** [comment]
Thanks for reporting the issue. I will try to find out what is going on and then update the thread.

**Comment by serkantkaraca** [comment]
I was able to reproduce the issue. I will provide more details today after completing investigation.
