### ISSUE TITLE
Need an API to list all Connections in the subscriptions

### ISSUE THREAD

**Issue by sai-manoj-kumar** [Azure/azure-libraries-for-net#254]
Is there an API to list all Connection objects in a given subscription?

**Comment by hovsepm** [comment]
@sai-manoj-kumar could you point to the swagger spec that describes Connection feature? We have implementation of https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2016-06-01/subscriptions.json spec and it does not seems to have anything in that area.

**Comment by sai-manoj-kumar** [comment]
@hovsepm Thanks for pointing me to the repository of the specs. Couldn't find it from documentation.

It shouldn't be part of subscriptions spec. It should be part of Network RP. Essentially, there should be a spec under the below folder like connection.json
[https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable/2015-06-15](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/network/resource-manager/Microsoft.Network/stable/2015-06-15)

**Comment by hovsepm** [comment]
@sai-manoj-kumar are you talking about this? https://github.com/Azure/azure-rest-api-specs/blob/3b0a560e2e0e4b9945f749eb3dd6319600434b8d/specification/network/resource-manager/Microsoft.Network/stable/2018-02-01/examples/VirtualNetworkGatewayConnectionsList.json#L13

**Comment by sai-manoj-kumar** [comment]
@hovsepm It has the RG as its parameter. So, I think it doesn't get all the connections in the subscription. Isn't so?

**Comment by hovsepm** [comment]
yeah you are right it will limit the scope to the RG.

**Comment by yaohaizh** [comment]
Close this as the connection is not available on subscription side.
