### ISSUE TITLE
Adding an SSL certificate to Application Gateway

### ISSUE THREAD

**Issue by lenala** [Azure/azure-libraries-for-net#257]
From Bharath:
"       I’m trying to add an SSL certificate to Application gateway using the Azure management library in C#. 
To add a backend authentication certificate, I can do:
```
                    appGateway
                        .Update()
                        .DefineAuthenticationCertificate(certificateName)
                        .FromBase64(certificateContents)
                        .Attach();
```

But I don’t have a “FromBase64” or “FromFile” method on “DefineSslCertificate” using which I can add contents to the certificate object:
```
                    appGateway
                        .Update()
                        .DefineSslCertificate(certificateName)
                        .Attach();
```
Is this a known issue?
I looked at the [sample](https://github.com/Azure-Samples/application-gateway-dotnet-manage-application-gateways/blob/master/Program.cs) program on github and it does not try to create an SSL cert object and instead adds the cert using WithSslCertificateFromPfxFile method."

**Comment by hovsepm** [comment]
fixed in release v.1.10
