### ISSUE TITLE
Forced setting of random value of WEBSITE_CONTENTSHARE makes Fluent resource management unusable for Azure Functions

### ISSUE THREAD

**Issue by johnbirdau** [Azure/azure-libraries-for-net#265]
Refer https://github.com/Azure/azure-libraries-for-net/blob/0ada4e3ea2055f6a2aa61e71c605923b9e9ecbab/src/ResourceManagement/AppService/FunctionAppImpl.cs#L145 and https://github.com/Azure/azure-libraries-for-net/blob/0ada4e3ea2055f6a2aa61e71c605923b9e9ecbab/src/ResourceManagement/AppService/FunctionAppImpl.cs#L146

According to Microsoft documentation, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE are only required for dynamic functions (ie consumption plans).

However this code is forcing their usage even if the Azure Function is in a App Service Plan.

Regardless, due to considerations outlined in articles like
https://nascent.blog/2017/05/31/azure-function-app-deployment-slots-arm-template/
https://nascent.blog/2017/06/27/azure-functions-slots-arm-templates-snags-2-redeploy-causes-unwanted-swap/#solution
and the fact that we want to include Azure Resource provisioning with our code releases (ensures environment immutability, and uses ARM/Resource lookup to find correct keys/links to other resources for app and connection string settings) we want to use these settings.

The big issue is that we cannot disable or override this random setting behaviour via the Fluent APIs (for the production slot - bizarrely it is supported on the staging slot).

The impact is that on running the Fluent provisioning on existing Function Apps during re-deployment, the application code (and the API secret we use for clients to connect to the function, which is stored in the storage account also due to the desired AzureWebJobsSecretStorageType="Blob" app setting) is lost. Causing client short term outage (due to code in production slot disappearing during deployment) and client medium term outage (due to the Function App keys being regenerated, requiring upstream client connection string changes)

In particular, if line 146 above only set the value if the client did not already set the app setting explicitly, then it could be usable. That is, I would like to be able to state `.WithStickyAppSetting("WEBSITE_CONTENTSHARE", "production")` and `.WithStickyAppSetting("WEBSITE_CONTENTSHARE", "staging")`

This showstopper line unfortunately means I have had to revert to raw ARM templates. 👎

**Comment by weidongxu-microsoft** [comment]
@johnbirdau 

This should be sovled with https://github.com/Azure/azure-libraries-for-net/issues/485

After 1.26, WEBSITE_CONTENTSHARE and WEBSITE_CONTENTSHARE will no longer be populated for app service plans (Basic, Standard, Premium).

AzureWebJobsDashboard and AzureWebJobsStorage would still be populated with connection key (but I think they would stay same as long as storage account key is not reset).

**Comment by yaohaizh** [comment]
Close the issue as it had been addressed.  Feel free to re-open if still exists.
