### ISSUE TITLE
AzureEnvironment should provider parse method or Name field

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-libraries-for-net#266]
AzureEnvironment should provide a parse method or Name field.

If Name field is present, user could iterator through KnownEnvironments and find expected environment.

For now, neither is available, Develop has to match each environment type.

```
public static AzureEnvironment(string environmentName)
```

**Comment by hovsepm** [comment]
Merged. Fix will be available in release 1.10 due next week.
