### ISSUE TITLE
Bug: ListByResourceAsync returns null, ListByResource doesn't

### ISSUE THREAD

**Issue by bjornsallarp** [Azure/azure-libraries-for-net#272]
Reason is async method has incorrect result model. Check:
Microsoft.Azure.Management.Monitor.Fluent.IMetricDefinitions
Microsoft.Azure.Management.Monitor.Fluent.MetricDefinitionsImpl

ListByResource returns IReadOnlyList<IMetricDefinition> (Correct)
ListByResourceAsync return Task<Microsoft.Azure.Management.Monitor.Fluent.IMetricDefinition> (Incorrect)

Was introduced in commit 50bfca37073542c609a063500a381a6c589a588e

It's super simple/quick fix

**Comment by hovsepm** [comment]
Thanks for catching this :). I'll make sure fix will go out with release 1.9

**Comment by hovsepm** [comment]
Fixed. Will be available in v1.9 due this week,

**Comment by hovsepm** [comment]
@bjornsallarp FYI release 1.9 is out.
