### ISSUE TITLE
IWithManagedServiceIdentity / WithManagedServiceIdentity() for App Service

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-libraries-for-net#28]
Looking at the code I can see that this is only available in Compute.Fluent - but not for eg AppService which per the announcement should also support MSI. Is this going to be available soon or am I really limited to ARM?

**Comment by martinsawicki** [comment]
not supported yet

**Comment by hovsepm** [comment]
MSI functionality for AppService is available from Release 1.7
