### ISSUE TITLE
Custom Token credentials unsupported for Graph APIs

### ISSUE THREAD

**Issue by prerakpradhan** [Azure/azure-libraries-for-net#284]
In the current 1.9.1 version, a rest client can be created using token credentials in the following way:
```
var client = RestClient
                    .Configure()
                    .WithEnvironment(AzureEnvironment.AzureGlobalCloud)
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                    .WithCredentials(new AzureCredentials(new TokenCredentials(authToken), tenantId, AzureEnvironment.AzureGlobalCloud))
                    .Build();
var authenticatedClient = Azure.Authenticate(client, tenantId);
```
However if we were to use this authenticated client to make a call like below, it currently fails
` var activeDirectoryApplication = await authenticated.ActiveDirectoryApplications.GetByNameAsync(appName).ConfigureAwait(false);`

The above call fails with the following stack:
`Unknown error occured in put: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.    
at System.ThrowHelper.ThrowKeyNotFoundException()    
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)    
at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__26.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- `

I think this is happening because the AzureCredentials constructor does the following when you create it:
`        public AzureCredentials(ServiceClientCredentials credentials, string tenantId, AzureEnvironment environment)
            : this(tenantId, environment)
        {
            credentialsCache[new Uri(Environment.ManagementEndpoint)] = credentials;
        }`

Notice how it uses Environment.ManagementEndpoint by default and does not allow the user to graph endpoint instead of the management endpoint. This I believe later causes the stack above on any Graph Endpoint related operations.

Fix should allow the user to specify graph vs managmentEndpoitn and also throw a more user friendly error in case the user tries to user a management authenticated client for graph operations

**Comment by hovsepm** [comment]
Will be available in release v1.10
