### ISSUE TITLE
The latest api-version 2018-03-31 is not returning UsageDetail.BillableQuantity property value

### ISSUE THREAD

**Issue by divyeshgohil85** [Azure/azure-libraries-for-net#295]
The latest api-version 2018-03-31 is not returning UsageDetail.BillableQuantity property value in  https://management.azure.com//subscriptions/{subscriptionid}/providers/Microsoft.Consumption/usageDetails endpoint

It is documented here
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.consumption.models.usagedetail.billablequantity?view=azure-dotnet#Microsoft_Azure_Management_Consumption_Models_UsageDetail_BillableQuantity

**Comment by hovsepm** [comment]
@divyeshgohil85  please reopen this bug in Spec repo here https://github.com/Azure/azure-rest-api-specs/ 

Fluent SDK never had implementation for Consumption library. Did you try using auto-generated library - https://www.nuget.org/packages/Microsoft.Azure.Management.Consumption?

**Comment by divyeshgohil85** [comment]
@hovsepm I tried using fluent library https://www.nuget.org/packages/Microsoft.Azure.Management.Consumption.Fluent

**Comment by hovsepm** [comment]
@divyeshgohil85 we will deprecate that package in favor of autogenerated one that I've pointed you above. The issue with Fluent Beta version of the library is that we did not regenerate it from the latest service spec for a long time and that is why there may be some gaps in functionality.
