### ISSUE TITLE
[Azure Container Instances] GetLogContentAsync parameters order

### ISSUE THREAD

**Issue by ejadib** [Azure/azure-libraries-for-net#296]
The [GetLogContentAsync ](
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ContainerInstance/ContainerGroupsImpl.cs#L106) method expect the `containerName` parameter first and then the `containerGroupName`  parameter, however, the underlying code ([ListAsync](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ContainerInstance/Generated/ContainerLogsOperationsExtensions.cs#L48)) that ends up being called expects first the `containerGroupName `and then the `containerName` (which I think is the right order).

The problem is that the caller of the ListAsync method is sending the parameter in the wrong order, meaning in the order that are being sent which is not the order expected (e.g [here](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ContainerInstance/ContainerGroupsImpl.cs#L108))

**Comment by milismsft** [comment]
Fixed in https://github.com/Azure/azure-libraries-for-net/pull/331
