### ISSUE TITLE
IRedisCache has no fluent methods for linkedServers/firewallRules?

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-libraries-for-net#303]
Based on feedback from someone else I was just reviewing the Microsoft.Azure.Redis.Management.Fluent package, and found surprisingly that while it has support for the linkedServers/firewallRules via RedisManagementClient, there seems to be no way to get to those things from the IRedisCaches/IRedisCache interfaces.

i.e. you can do this
var x = caches.GetById(id).AsPremium().ListPatchSchedules();

but not these
var x = caches.GetById(id).AsPremium().ListLinkedServers();
var x = caches.GetById(id).ListFirewallRules(); // note, firewall rules no longer requires premium SKU

**Comment by hovsepm** [comment]
@TimLovellSmith all 3 issues for Redis Fluent planned for v1.11 are moved to v1.12. LMK if this blocks any of your customers.

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
