### ISSUE TITLE
IRedisCache WithSubnet(string subnetId)

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-libraries-for-net#305]
It could be goodness for WithSubnet() to have an overload that takes (string subnetId) instead of (INetwork nw, string subnetName) just so that you aren't forced to fetch the subnet details in order to create the cache.

**Comment by hovsepm** [comment]
Thanks for all 3 issues :) I'll try to fit the fixes in the next release - EOM.

**Comment by hovsepm** [comment]
fixed in https://github.com/Azure/azure-libraries-for-java/pull/445

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
