### ISSUE TITLE
Updating KeyVault fails due to missing SoftDelete setting

### ISSUE THREAD

**Issue by veikkoeeva** [Azure/azure-libraries-for-net#315]
It appears the examples that update KeyVault fail at https://github.com/Azure/azure-libraries-for-net/tree/master/Samples/Sql fail due to `SoftDelete` not set. More precisely, the error message is
> "The provided Key Vault uri ‘https://tenant.vault.azure.net/keys/database/guid’ is not valid. Please ensure the vault has the right Recovery Level other than ‘Purgeable’.'",

as describred at http://www.bradleyschacht.com/bring-your-own-key-to-azure-sql-database-tde/ in section `Troubleshooting`. It doesn't appear there is currently a setting for this.

Related to https://github.com/Azure/azure-libraries-for-net/issues/309.

The libraries and their versions:
- Microsoft.Azure.KeyVault, version 2.3.2
- Microsoft.Azure.Management.Fluent, version 1.9.1
- WindowsAzure.Storage, version 9.1.1

**Comment by veikkoeeva** [comment]
Further notes, it appears `IVault` should define ` bool EnabledSoftDelete { get; }` as are other similar features enabled. There is a workaround to allow updates by writing something along the lines
```
IVault vault = await azure.Vaults.Define(VaultName)
    .WithRegion(region)
    .WithExistingResourceGroup(resourceGroup)
        .DefineAccessPolicy()
        .ForObjectId(sqlServer.SystemAssignedManagedServiceIdentityPrincipalId)
        .AllowKeyAllPermissions()
        .AllowKeyPermissions(KeyPermissions.WrapKey, KeyPermissions.UnwrapKey, KeyPermissions.Get, KeyPermissions.List)
    .Attach()
        .DefineAccessPolicy()
        .ForServicePrincipal(credentials.ClientId)
        .AllowKeyAllPermissions()
    .Attach()
    .CreateAsync(default, multiThreaded: true).ConfigureAwait(false);

await vault.Manager.Inner.Vaults.CreateOrUpdateAsync(resourceGroup.Name, vault.Name, new VaultCreateOrUpdateParametersInner
{
    Location = region.Name,
    Properties = new VaultProperties
    {
        TenantId = Guid.Parse(credentials.TenantId),
        AccessPolicies = vault.AccessPolicies.Select(i => new AccessPolicyEntry(Guid.Parse(credentials.TenantId), credentials.ClientId, i.Permissions)).ToList(),
        EnableSoftDelete = true,
        EnabledForDeployment = true
    }
}).ConfigureAwait(false);
```
which updates the values in the vault. The problem that follows is that the example on assigning the values to SQL Server (taken from the samples linked) will fail with 403 Forbidden. The adding of keys will succeed if one doesn't make the `.CreateOrUpdateAsync` call and restarts the application making the requests.

The code from the samples:
```
var keyBundle = await keyVaultClient.CreateKeyAsync(vault.VaultUri, "somekey", JsonWebKeyType.Rsa, keyOps: new[]
{
   JsonWebKeyOperation.Wrap, JsonWebKeyOperation.Unwrap
}).ConfigureAwait(false);
 string keyUri = keyBundle.Key.Kid;
string serverKeyName = $"{VaultName}_somekey_{keyUri.Substring(keyUri.LastIndexOf("/") + 1)}";
var sqlServerKey = await sqlServer.ServerKeys.Define().WithAzureKeyVaultKey(keyUri).CreateAsync().ConfigureAwait(false);
```

**Comment by milismsft** [comment]
@veikkoeeva Thank you so much for reporting this issue. I have a fix for this and we will release it in the next couple weeks.

Meanwhile if you are looking for a work around after the Lay vault is created you can try to set the "soft delete" property via the "Inner" property then call "Update()" on the Key Vault object. Here's the simplified code sequence:

`
IVault vault = await azure.Vaults.Define(VaultName)
.....
    .Create();
vault.Inner.Properties.EnableSoftDelete = true;
vault.Update()
    .Apply();
`

**Comment by veikkoeeva** [comment]
@milismsft Thanks! Your tip is better than the one I sketched, it avoids the eception in `.CreateKeyAsync` call after the `.CreateOrUpdateAsync`.

**Comment by milismsft** [comment]
@veikkoeeva I'm glad to hear it helped :-)
The full fix is in code review and should be part of the next release.

**Comment by yaohaizh** [comment]
Close this as fixed.
