### ISSUE TITLE
UpgradeToGeneralPurposeAccountKindV2 in Storage should be a method

### ISSUE THREAD

**Issue by JREndeanMSFT** [Azure/azure-libraries-for-net#316]
https://github.com/Azure/azure-libraries-for-net/blob/7972de7a8443e55ab3e8f7bf2639ffd6d594fa49/src/ResourceManagement/Storage/Domain/InterfaceImpl/StorageAccountImpl.cs#L658

All other APIs for Create and Update are built around method calls.

**Comment by hovsepm** [comment]
fix will be shipped in v1.10.
