### ISSUE TITLE
AKS Failing to create cluster

### ISSUE THREAD

**Issue by andtii** [Azure/azure-libraries-for-net#323]
Using the Fluent Api to create new cluster in fails with error: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.

Using the WithLatestVersion() method

**Comment by andtii** [comment]
Aha ok and i cant create using a working version because of this https://github.com/Azure/azure-libraries-for-net/issues/324 so its like a dead end ;)

**Comment by milismsft** [comment]
@andtii You can work around this by force casting to the next stage in the create definition:

`                IKubernetesCluster kubernetesCluster = ((Microsoft.Azure.Management.ContainerService.Fluent.KubernetesCluster.Definition.IWithLinuxRootUsername) azure.KubernetesClusters.Define(aksName)
                    .WithRegion(region)
                    .WithNewResourceGroup(rgName)
                    .WithVersion(KubernetesVersion.KUBERNETES_1_8_2))
                    .WithRootUsername(rootUserName)
                    .WithSshKey(sshPublicKey)
                    .WithServicePrincipalClientId(servicePrincipalClientId)
                    .WithServicePrincipalSecret(servicePrincipalSecret)
                    .DefineAgentPool("ap")
                        .WithVirtualMachineCount(1)
                        .WithVirtualMachineSize(ContainerServiceVirtualMachineSizeTypes.StandardD1V2)
                        .Attach()
                    .WithDnsPrefix("dns-" + aksName)
                    .Create();
`

**Comment by milismsft** [comment]
@andtii PR https://github.com/Azure/azure-libraries-for-net/pull/321 adds a new override which allows the user to specify any Kubernetes version as a string input.
