### ISSUE TITLE
In CosmosDb the maxIntervalInSeconds and maxStalenessPrefix parameters are reversed

### ISSUE THREAD

**Issue by JREndeanMSFT** [Azure/azure-libraries-for-net#325]
https://github.com/Azure/azure-libraries-for-net/blob/86d223bcc241e1268c87aa686ded6652b98ee872/src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs#L196
<br/>
Setting a BoundedStalenessConsistency fails validation due to the following:<br/>
`private void SetConsistencyPolicy(Models.DefaultConsistencyLevel level, int maxIntervalInSeconds, long maxStalenessPrefix)`
<br/>
should be
<br/>
`private void SetConsistencyPolicy(Models.DefaultConsistencyLevel level, long maxStalenessPrefix, int maxIntervalInSeconds)`
<br/><br/>
Additionally
`public CosmosDBAccountImpl WithBoundedStalenessConsistency(int maxStalenessPrefix, int maxIntervalInSeconds)`
<br/>should be<br/>
`public CosmosDBAccountImpl WithBoundedStalenessConsistency(long maxStalenessPrefix, int maxIntervalInSeconds)`
<br/><br/>
Note the change from `int` to `long`

**Comment by milismsft** [comment]
This was fixed in version 1.11.1
