### ISSUE TITLE
Possible improvement to error message when ServicePrincipalLoginInformation is not initialized

### ISSUE THREAD

**Issue by linitram** [Azure/azure-libraries-for-net#326]
If the ServicePrincipalLoginInformation object is not properly initialized, as shown in the example below:

            var credentials = new ServicePrincipalLoginInformation();
            var azureCredentials = new AzureCredentials(credentials, tenantId, AzureEnvironment.AzureGlobalCloud);
            var authenticated = Azure.Authenticate(azureCredentials);
            var principals = authenticated.ServicePrincipals.List();

Customer would get the following exception:

{System.ArgumentException: Array may not be empty or null. Parameter name: rawData    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)    at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__19.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__25.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Azure.Management.Graph.RBAC.Fluent.ServicePrincipalsOperations.<ListWithHttpMessagesAsync>d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Azure.Management.Graph.RBAC.Fluent.ServicePrincipalsOperationsExtensions.<ListAsync>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)    at Microsoft.Azure.Management.Graph.RBAC.Fluent.ServicePrincipalsImpl.List()    at FunctionApp1.Function1.Run(TimerInfo myTimer, TraceWriter log) in C:\test\FunctionApp1\FunctionApp1\Function1.cs:line 31    at lambda_method(Closure , Function1 , Object[] )    at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments)    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__9.MoveNext()} | System.ArgumentException

It would be nice if our parameters validation can be improved and a more direct error message is given, so that it can be easier for customer to fix the code. 

            var credentials = new ServicePrincipalLoginInformation
            {
                ClientId = clientId,
                ClientSecret = clientSecret
            };
            var azureCredentials = new AzureCredentials(credentials, tenantId, AzureEnvironment.AzureGlobalCloud);
            var authenticated = Azure.Authenticate(azureCredentials);
            var principals = authenticated.ServicePrincipals.List();

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
