### ISSUE TITLE
Error getting a list of CosmosDB account

### ISSUE THREAD

**Issue by garybushey** [Azure/azure-libraries-for-net#329]
When I try to get a list of CosmosDB accounts using:

IEnumerable<ICosmosDBAccount> cosmosDBs = azure.CosmosDBAccounts.ListByResourceGroup(resourceGroupId)

I get an error stating "The method or operation is not implemented".  Any ideas?  I am using V1.10.0 of Microsoft.Azure.Managmentment.CosmosDB.Fluent

**Comment by milismsft** [comment]
@garybushey Looks like we forgot to add the proper implementation for this method. I'll fix it before the next release.

Meanwhile can you try as a work around calling the async version of the function?

**Comment by garybushey** [comment]
Looks like the async method has the same issue.  I can get a list by using the .List() method however when I try to do a foreach to get each entry I also get the same error message

**Comment by JadedATB** [comment]
This was reported (Issue #145) for v1.4.1.

**Comment by milismsft** [comment]
Fix added to PR https://github.com/Azure/azure-libraries-for-net/pull/331 and should be available in v1.11.0
