### ISSUE TITLE
ManagementEnpoint values look wrong for German and US Govt clouds

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-libraries-for-net#33]
(Per some recent comments I made on AzureEnvironment.cs changes @hovsepm.) They should be 'management.core.xxx'. And you might as well fix the spelling of this property name while you're at it.

**Comment by hovsepm** [comment]
Issue is related to `ManagementEnpoint` values.

**Comment by hovsepm** [comment]
Fixed. Will be shipped in v.1.4
