### ISSUE TITLE
AzureEnvironment values are inconsistent 

### ISSUE THREAD

**Issue by benPearce1** [Azure/azure-libraries-for-net#341]
The values being provided in the AzureEnvironment class are inconsistent with the values being provided by `Get-AzureEnvironment`.

In particular, the StorageEndpointSuffix value will not work when being provided to the constructor in Microsoft.WindowsAzure.Storage.CloudStorageAccount and results in a URI parser error due to the leading period.
Also, the name on the default Azure Cloud is inconsistent with `Get-AzureEnvironment`

**Comment by hovsepm** [comment]
I've fixed the leading period issue. For env name - won't fix due for now because it will be a breaking change.

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
