### ISSUE TITLE
Unable to set Augmented Rules on Network Security Groups

### ISSUE THREAD

**Issue by pecjag** [Azure/azure-libraries-for-net#343]
It does not appear to be possible to set Augmented Rules in Network Security Groups:
https://azure.microsoft.com/en-us/updates/agumented-rules-ga-nsg/

There should be a way to set a CSV list of IP addresses and port ranges.
THanks

**Comment by pecjag** [comment]
It looks like the SecurityRuleInner class already supports:
sourcePortRanges
destinationPortRanges
sourceAddressPrefixes
destinationAddressPrefixes

so I think this should just require the following methods to be added to class NetworkSecurityRuleImpl:
`
internal NetworkSecurityRuleImpl ToPortRanges(string[] ranges)
internal NetworkSecurityRuleImpl FromPortRanges(string[] ranges)
internal NetworkSecurityRuleImpl ToAddresses(string[] cidrs)
internal NetworkSecurityRuleImpl FromAddresses(string[] cidrs)

`

Plus the Update methods in NetworkSecurityRuleImpl.

Thanks

**Comment by pecjag** [comment]
@lenala Do you have any estimates when this may be addressed?

**Comment by lenala** [comment]
@pecjag will be available in next release.

**Comment by pecjag** [comment]
Thanks @lenala . I have been trying to find if releases are done on a regular schedule.... Are you able to indicate an approximate date when this will be available?

**Comment by hovsepm** [comment]
Fix is merged. Release 1.13 should be out on nuget mid next week.

**Comment by pecjag** [comment]
Thanks for the updates!

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
