### ISSUE TITLE
Missing DefineContainerInstance().WithDnsNameLabel() 

### ISSUE THREAD

**Issue by ImageQC** [Azure/azure-libraries-for-net#346]
Azure CLI has supported az container create --dns-name-label since beginning of the year - see link. This isn't too surprising as container groups with a public IP that don't have a dns name label aren't much use. That's to say the use case for being able start-up and shutdown servers for relatively short periods falls apart unless you have a DNS to access them rather than an IP that changes with each created instance.

Unfortunately DefineContainerInstance().WithDnsNameLabel("mylabel") doesn't seem to have been implemented in the latest version of Microsoft.Azure.Management.Fluent (1.10.0, May 9th 2018). When is this method scheduled for implementation? It would be good to get some idea of its priority.

https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create

**Comment by milismsft** [comment]
@ImageQC The DNS is not set at the container instance level but at the container group level; all the container instances within the same container group share the same DNS. Can you please check:

`containerGroups.Define("cg")
....
.WithDnsPrefix("dnsPrefix")
.Create()
`

It's an optional settings so you need to specify it after you were done with all the required settings.

**Comment by ImageQC** [comment]
Thanks for the swift response. This seems to work:


`                string aciName = SdkContext.RandomResourceName("acisample", 20);
                string rgName = SdkContext.RandomResourceName("rgACI", 15);
                string containerImageName = "seanmckenna/aci-hellofiles";
                string dnsPrefix = "ne555";

                string shareName = SdkContext.RandomResourceName("fileshare", 20);
                string volumeMountName = "aci-helloshare";

                IContainerGroup containerGroup = azure.ContainerGroups
                    .Define(aciName)
                    .WithRegion(Region.EuropeWest)
                    .WithExistingResourceGroup(rgName)
                    .WithLinux()
                    .WithPublicImageRegistryOnly()
                    .WithNewAzureFileShareVolume(volumeMountName, shareName)
                        .DefineContainerInstance(aciName)
                        .WithImage(containerImageName)
                        .WithExternalTcpPort(80)
                        .WithVolumeMountSetting(volumeMountName, "/aci/logs/")
                        .Attach()
                        .WithDnsPrefix(dnsPrefix)
                        .WithRestartPolicy(ContainerGroupRestartPolicy.Never)
                    .Create();`
