### ISSUE TITLE
Uniqueness of  Azure Container WithDnsPrefix(dnsPrefix)

### ISSUE THREAD

**Issue by ImageQC** [Azure/azure-libraries-for-net#352]
When I create an Azure Container how can I ensure the uniqueness of my dnsPrefix? That's to say is it possible to register a dnsPrefix name "ibm" so others cannot use it? This is likely to become an issue as these container become more common.

**Comment by milismsft** [comment]
@ImageQC Unfortunately there's no container instance API currently that can ensure the DNS is unique.

@yangl900 Do you know if it is possible to add one as part of the next API version for the ACI?

**Comment by hovsepm** [comment]
Closed as by design for now.
