### ISSUE TITLE
Get service principal fails when service principal has multiple keys with the same name

### ISSUE THREAD

**Issue by LockTar** [Azure/azure-libraries-for-net#356]
We tried this with v1.10 and updated it to 1.11.1 but still with the samen result.

When we get the details of a service principal, we get an error `An item with the same key has already been added`.
We use the code: `azure.ActiveDirectoryApplications.GetByNameAsync(name);`

We found the issue around this. Our service principals has multiple keys with the same name.
If we remove one key it succeeds. So the problem is with **multiple keys** with the **same name**.

**Comment by hovsepm** [comment]
@LockTar fix has been merged. Will be shipped as part of release 1.13 due around mid-July.

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
