### ISSUE TITLE
App Service certificate upload has stopped working

### ISSUE THREAD

**Issue by martincostello** [Azure/azure-libraries-for-net#371]
I have an Azure function I use to upload LetsEncrypt certificates issued by my DNS provider to Azure blob storage, and then another which uploads it to Azure App Service ready to be bound manually later.

I used to achieve this with this code:

```csharp
await application
    .Update()
    .DefineSslBinding()
        .ForHostname(hostName)
        .WithPfxCertificateToUpload(fileName, password)
        .WithSniBasedSsl()
         .Attach()
    .ApplyAsync();
```

However, sometime in the last 3 months or so since the last LetsEncrypt certificate renewal this is now failing with a `Microsoft.Rest.Azure.CloudException` being thrown with the message `No certificate thumbprint provided.`.

Based on [this comment](https://github.com/Azure/azure-libraries-for-net/issues/56#issuecomment-335958896) I updated the code to the below to achieve the same aim, which works:

```csharp
await application.Manager.AppServiceCertificates
    .Define(string.Format("{0}##{1}#", thumbprint, application.Region.Name))
    .WithRegion(application.Region)
    .WithExistingResourceGroup(application.ResourceGroupName)
    .WithPfxFile(fileName)
    .WithPfxPassword(password)
    .CreateAsync();
```

The PR to apply this fix to my code was martincostello/azure-functions#9.

Has something changed in the Azure management APIs that caused this to stop working? Was it an accident that it ever worked?

**Comment by umnex** [comment]
Gentlemen, Any update or work around?

 I am getting the same error when trying to create SSL binding for a host name, the wildcard SSL is already uploaded. I just need to setup an SSL binding.

**Comment by ChenTanyi** [comment]
@martincostello @umnex @gerwim Is there still problem? I have tested it successfully in new SSL, updating SSL and self-signed SSL (all from LetsEncrypt).

Maybe the service side has fixed this bug. If there is still problem, feel free to reopen it.

Thanks.
