### ISSUE TITLE
Cannot set tags on function update

### ISSUE THREAD

**Issue by kevineger** [Azure/azure-libraries-for-net#372]
## Repro steps

- Deploy a function (with a name longer than 24 characters), ie:
```
var functionApp = azure.AppServices.FunctionApps.GetById("some-id-here");
var deployment = functionApp
  .Deploy()
  .WithPackageUri("some-blob-here")
  .WithExistingDeploymentsDeleted(true)
  .Execute();
```
- Update the function setting tag(s), ie:
```
functionApp
  .Update()
  .WithTag("PackageUpdateDate", deployment.EndTime.ToString())
  .Apply();
```

### Actual behaviour

The update fails and a seemingly incorrect exception is thrown: `Microsoft.Rest.ValidationException: 'accountName' exceeds maximum length of '24'.`.

### Expected behaviour

Tag is set on the function and the update succeeds.

Edit: Added information highlighting the deployed function app to update must have a name > 24 characters.

**Comment by hovsepm** [comment]
Closing this bug as non-repro.

**Comment by jianghaolu** [comment]
Re open to investigate.

**Comment by kevineger** [comment]
I think it's because the function app name is longer than 24, not sure why it's looking at that. When I use a function app with name < 24 it works.

**Comment by kevineger** [comment]
For example:

- "FunkyFunk" works. 
- "IAmAFuncitonNameThatIsLonger" does not work.

**Comment by kevineger** [comment]
Works in 4.6.2

**Comment by kevineger** [comment]
No. As it turns out the underlying issue is that `StorageAccount` gets lost after creation. So subsequent GETs on the Function App don't include `StorageAccount` and the `Update` validation fails.

**Comment by kevineger** [comment]
@jianghaolu is working towards a fix and will reference this issue in the PR. Until then, the workaround is to retrieve the function app as an `IWebApp` - it doesn't validate `StorageAccount` on `Update`.

**Comment by hovsepm** [comment]
Should be fixed. Please open a new issue if you hit this in v1.16.1 or higher.
