### ISSUE TITLE
Delays due to creating Azure Container Instances and Azure Credentials

### ISSUE THREAD

**Issue by ImageQC** [Azure/azure-libraries-for-net#378]
Azure/azure-sdk-for-net have suggested the following issue is something for the .NET Fluent SDK team... 

A call to SdkContext.AzureCredentialsFactory.FromServicePrincipal() can take 5 seconds or more to return. Is there an async version or other way to invoke it that would free the thread whilst it waits for the Azure service to do its stuff? Further, the creation of an Azure Container Instance takes > 2mins and although it is async this still means my Azure Function often takes > 2mins to complete. Would it be possible to return immediately with some sort of ID and then post an event (via Azure EventGrid) when the server is up and running?

- PackageReference` Include="Microsoft.Azure.Management.Fluent" Version="1.11.1"
- PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.0-beta5"
- PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.0-beta5"
- PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.4.1"
- PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.0.0-beta1"
- PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13"
- PackageReference Include="System.Data.SqlClient" Version="4.4.0-preview1-25305-02"

```
AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(classifierSecPrincipalId, classifierSecPrincipalKey, classifierTenantId, AzureEnvironment.AzureGlobalCloud);

var azure = Azure.Configure().WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic).Authenticate (credentials).WithDefaultSubscription();

var containerGroup = await azure.GetResult().ContainerGroups
.Define(containerName)
.WithRegion(Region.EuropeWest)
.WithExistingResourceGroup(resourceGroupName)
.WithLinux()
.WithPublicImageRegistryOnly()
.WithoutVolume()
.DefineContainerInstance(containerName)
  .WithImage(classifierImage)
  .WithExternalTcpPort(80)
  .WithCpuCoreCount(cpuCount)
  .WithMemorySizeInGB(memoryGb)
  .Attach()
.WithDnsPrefix(dnsPrefix)
.WithRestartPolicy(ContainerGroupRestartPolicy.OnFailure)
.CreateAsync();
```

**Comment by hovsepm** [comment]
Regarding FromServicePrincipal Async version - we do not have it in the current implementation. I'll check if it can be added in the future releases.

**Comment by hovsepm** [comment]
@ImageQC I've checked the code of `FromServicePrincipal` here https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Authentication/AzureCredentialsFactory.cs#L77 and this should be an instant operation - just creates a simple object in memory.

Could you provide more details or run some kind of profiler that can identify the real bottleneck of the call?

**Comment by ImageQC** [comment]
I'll try to get something for you next week.

**Comment by hovsepm** [comment]
@ImageQC were you able to get a repro of this issue?

**Comment by hovsepm** [comment]
Closing as no repro.
