### ISSUE TITLE
Retrieving the tags for a function app does not work

### ISSUE THREAD

**Issue by kevineger** [Azure/azure-libraries-for-net#389]
## Repro steps

- Retrieve the tags for a function app (that already has tags - verify in portal), ie:
```
var tags = functionApp.Tags;
```
### Actual behaviour

Tags is an empty collection.

### Expected behaviour

Tags is a collection containing all the tags as listed in the portal for the function being retrieved.

**Comment by kevineger** [comment]
Works in 4.6.2

**Comment by hovsepm** [comment]
I believe this was fixed in one of the latest releases. Please open a new issue if you hit this in v1.16.1 or higher.
