### ISSUE TITLE
Invalid phpVersion error when creating web app

### ISSUE THREAD

**Issue by purduebretty** [Azure/azure-libraries-for-net#392]
This issue started about a week ago where we will occasionally receive the error 'invalid phpVersion' when creating a webapp using Microsoft.Azure.Management.AppService.Fluent 1.9. (.NET 4.6.1 app)

Code used for app creation:
```
var webApp = azure.WebApps.Define(appName)
                .WithExistingWindowsPlan(plan)
                .WithExistingResourceGroup(resourceGroup)
                .WithPythonVersion(PythonVersion.Off)
                .WithAppSettings(settings)
                .WithConnectionString(xxx)
                .WithTag("PR", resourceGroup.Split('-').Last())
                .WithPhpVersion(PhpVersion.Off)
                .WithWebSocketsEnabled(enableWebsockets)
                .CreateAsync();
```
We don't use php on our site, so it should be set to off, and when I inspect the API call being made it uses 'null' as the phpVersion value.

This behavior appears to be intermittent as we create 5 different websites using this code and it may fail randomly for 1 of them, and which website fails also appears to be random.

**Comment by purduebretty** [comment]
It appears to be related to this issue.  https://github.com/Azure/azure-powershell/issues/6635  However as I'm using the SDK, I don't know of any way to pass an empty string for the phpVersion parameter so the workaround would not work for me.

**Comment by hovsepm** [comment]
@purduebretty fix has been merged. Will be shipped as part of release 1.13.

**Comment by purduebretty** [comment]
Great to hear.  I put a fix in my code to retry if this occurs and will update to v 1.13 when made available.  Thx.

**Comment by hovsepm** [comment]
Release 1.13 is out. Please upgrade your references.
