### ISSUE TITLE
Microsoft.Azure.Management.Monitor.Fluent does not depend on Microsoft.Azure.Management.Fluent

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#402]
`Microsoft.Azure.Management.Monitor.Fluent` does not depend on `Microsoft.Azure.Management.Fluent` which is required for authentication.

**Comment by hovsepm** [comment]
@tomkerkhove `Microsoft.Azure.Management.Fluent` is a roll-up package. No package should take dependency on it. Could you explain your scenario?

**Comment by tomkerkhove** [comment]
Yes, I found that out yesterday. I was looking for the package that contained the authentication logic which is not pulled in when only using `Microsoft.Azure.Management.Monitor.Fluent`.

**Comment by hovsepm** [comment]
It is in `Microsoft.Azure.Management.ResourceManager.Fluent` which Monitor depends on.

**Comment by tomkerkhove** [comment]
I've had another look and I'm not sure if the above statement is correct.

When I removed `Microsoft.Azure.Management.Fluent` it was not able to find `IAzure` nor `Azure`.
After that I checked from which package it came and is clearly coming from `Microsoft.Azure.Management.Fluent`:

![screenshot_1](https://user-images.githubusercontent.com/4345663/43035207-ce5660f4-8ceb-11e8-9fd5-80491c7132fd.png)

**Comment by hovsepm** [comment]
`IAzure` is a rollup client interface that exposes managers from each Fluent library e.g. Compute, Network. For example if you want to use only Monitor client you can reference just `Microsoft.Azure.Management.Monitor.Fluent`, create an instance of MonitorManager class and then get access to Fluent layers from that instance. I hope this makes our internal architecture a little bit clearer :)

**Comment by tomkerkhove** [comment]
That's right and how I use it but from what I've seen `IAzure` is not available when pulling in `Microsoft.Azure.Management.Monitor.Fluent`?

I must be missing something obvious because I feel like a moron :)

**Comment by hovsepm** [comment]
`IAzure` only exist in `Microsoft.Azure.Management.Fluent` package. And it is a facade for a Manager class in each client package (Compute.Fluent, Netowork.Fluent, Monitor.Fluent etc). In other words on the example of Monitor.Fluent package - Monitor has MonitorManager class which exposes ActivityLogs functionality. Fluent rollup package (which is `Microsoft.Azure.Management.Fluent`) has IAzure interface that exposes ActivityLogs facade that is basically `Monitor.Fluent.MonitorManager.ActivityLogs` feature.
