### ISSUE TITLE
How to add a PasswordCredential to a IActiveDirectoryApplication

### ISSUE THREAD

**Issue by LockTar** [Azure/azure-libraries-for-net#414]
I have an existing application with some password credentials. How can I add a new password credential?

If I use below code, all the password credentials of the application are removed and only the specified one is left over...

    await application
      .Update()
        .DefinePasswordCredential(availableKeyName)
        .WithPasswordValue(key)
        .WithStartDate(utcNow)
        .WithDuration(duration)
        .Attach()
      .ApplyAsync();

Using version 1.13

Thanks

**Comment by LockTar** [comment]
Hi any suggestion on this? Is this a bug? Am I using it wrong?

**Comment by hovsepm** [comment]
@LockTar Release 1.15.1 is out. Please upgrade your references.
