### ISSUE TITLE
reading secrets from KeyVault with Microsoft.Azure.Services.AppAuthentication

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-libraries-for-net#428]
Hi,

I've just did a console app to read a secret from key vault and it took 24 seconds to retrieve the value. Is it normal? Here's the code:

```
static void Main(string[] args)
        {
            Console.WriteLine(DateTime.Now);
            Console.WriteLine(GetValue().Result);
            Console.WriteLine(DateTime.Now);
            Console.Read();
        }

        static async Task<string> GetValue()
        {
            AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();

            var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));

            var secret = await keyVaultClient.GetSecretAsync("https://{mykeyvault}.vault.azure.net/secrets/apiKey")
                .ConfigureAwait(false);

            return secret.Value;
        }
```

**Comment by hovsepm** [comment]
@thdotnet what library are you using to communicate with KeyVault server? Could you provide Nuget id and assembly version?

**Comment by hovsepm** [comment]
@thdotnet if it is this one - https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.1.0-preview - then please open the issue in the SDK repo https://github.com/Azure/azure-sdk-for-net . The nuget page for each package should have a `Project Site` link that should take you the the correct github repo.

**Comment by thdotnet** [comment]
Hi,

it's not the preview one. Here's the packages.config:

<?xml version="1.0" encoding="utf-8"?>
```
<packages>
  <package id="Microsoft.Azure.KeyVault" version="3.0.0" targetFramework="net462" />
  <package id="Microsoft.Azure.KeyVault.WebKey" version="3.0.0" targetFramework="net462" />
  <package id="Microsoft.Azure.Services.AppAuthentication" version="1.0.3" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.14.2" targetFramework="net462" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.11" targetFramework="net462" />
  <package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.12" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net462" />
</packages>
```

**Comment by hovsepm** [comment]
the library "Microsoft.Azure.Services.AppAuthentication" (all the versions) is located in https://github.com/Azure/azure-sdk-for-net  github repository. Please reopen this bug there - https://github.com/Azure/azure-sdk-for-net/issues 

This repository hosts only Fluent SDK sources - all the libraries in nuget.org that has package ID=`Microsoft.Azure.Management.*.Fluent`.
