### ISSUE TITLE
Microsoft.Insight Provider Bug

### ISSUE THREAD

**Issue by aidanhl** [Azure/azure-libraries-for-net#430]
Hello,

I believe I have found a bug in the MonitorManagementClient.ListBySubscriptionWithHttpMessagesAsync() function. The request is making a call using provider "Microsoft.Insight", as seen here:

https://github.com/Azure/azure-libraries-for-net/blob/a1a0d2faecadb4f3fca03b2c17505b90972ffaa6/src/ResourceManagement/Monitor/Generated/MetricAlertsOperations.cs#L95

Running ListBySubscriptionWithHttpMessagesAsync() produces the error code "InvalidResourceNamespace" with message "The resource namespace 'Microsoft.Insight' is invalid".

Looking through my Azure resource providers I only see a "Microsoft.Insight**s**" available (it is enabled). In addition Referencing docs https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/listbyresourcegroup it appears also to be using Microsoft.Insight**s**. 

From that, I believe there is a bug within this function due to the provider being called "Microsoft.Insight" not "Microsoft.Insight**s**". Is this accurate, or am I perhaps missing something.

Cheers.

**Comment by hovsepm** [comment]
@aidanhl  Release 1.15.1 is out. Please upgrade your references.
