### ISSUE TITLE
Cannot Create VM from ImageReference

### ISSUE THREAD

**Issue by nicolasgaraza** [Azure/azure-libraries-for-net#431]
Hi Guys,

I'm trying to create a VM from an existing Image on the marketplace, in this case SQL Express, but I'm failing miserably. 
Currently my code looks something like 

```
public static IVirtualMachine CreateWindowsSQL(IAzure azure, string rgName, string vmName, INetworkInterface networkInterface, INetworkInterface environmentNetWork)
        {
        
            var image = azure.VirtualMachineImages.GetImage(Region.USWest, "MicrosoftSQLServer", "SQL2016SP2-WS2016", "Express", "13.1.900310");


            return azure.VirtualMachines
            .Define(vmName)
                .WithRegion(Region.USWest)
                .WithExistingResourceGroup(rgName)
                .WithExistingPrimaryNetworkInterface(networkInterface)
                .WithSpecificWindowsImageVersion(image.ImageReference)
                //.//WithSpecializedOSDisk(azure.Disks.Manager.)
                //.WithPopularWindowsImage(KnownWindowsVirtualMachineImage.WindowsServer2012R2Datacenter)
                .WithAdminUsername("iamadmin")
                .WithAdminPassword("strongpassword")

                // .WithSize(VirtualMachineSizeTypes.BasicA0)
                .WithExistingSecondaryNetworkInterface(environmentNetWork)
                .Create();
        }

```

The error I'm getting is `Changing property 'imageReference' is not allowed."` can you help me with this?

Thanks!!

**Comment by anuchandy** [comment]
do you already have a vm with the same name in the given resource group? if so this operation will be an update on that vm and changing vm's os image is not allowed.

**Comment by nicolasgaraza** [comment]
Yes, it was that!! I was expecting to have another type of error since I'm doing a `Create()`

**Comment by ulflunde** [comment]
I had the same issue, and your answer resolved it!

Azure should consider changing the error message from "Changing property imageReference is not allowed" to something like "Name specified with '--name' is already in use", so people can understand what they are doing wrong!
