### ISSUE TITLE
C# Updating VM Tags not functioning

### ISSUE THREAD

**Issue by caz3542** [Azure/azure-libraries-for-net#448]
Updating a VM Tags via the C# client using version 1.14 is not executing as expected. 

Repo Instructions:

```
var vm = _azure.VirtualMachine.ListByResouceGroup("name").... //simplified
vm.Update()
.WithTag("NewTag","NewValue")
.Apply();
```

Via Fiddler I can see the client creating a PATCH request but the TAGS property being sent to the management api has not been updated. The currently applied value (pre-updated value) is resubmitted. The same holds for removing of tags via .WithoutTag() and .WithTags()

Modification of other values (Sizing, Disk, Network Card etc.) all work as expected and is clearly visible in the patch document and updates are functioning correctly.

- UPDATE

Update - downgrading to Version 1.13 of the library creates a POST request (vs. Patch in 1.14) and this is executing as expected.

-UPDATE - 08/30/2018

Issue remains in Version 1.15.1

**Comment by hovsepm** [comment]
@caz3542 1.16 is published to nuget. Please update your references.
