### ISSUE TITLE
Azure VMAccessExtension ApplyAsync() is not working using Fluent SDK C#

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-libraries-for-net#452]
Hello Team,

I am facing a strange issue when I am deploying a VM in Azure. I am not able to add an extension when using ApplyAsync(). But the same code works for Apply(). Am I missing anything or is this an SDK issue?

```C#
i_virtualMachine.Update()
                        .DefineNewExtension(windowsVmAccessExtensionName)
                            .WithPublisher(windowsVmAccessExtensionPublisherName)
                            .WithType(windowsVmAccessExtensionTypeName)
                            .WithVersion(windowsVmAccessExtensionVersionName)
                            .WithMinorVersionAutoUpgrade()
                            .WithProtectedSetting("username", username)
                            .WithProtectedSetting("password", password)
                        .Attach()
                        .ApplyAsync();
```
Thanks in advance.

**Comment by hovsepm** [comment]
@naveenkumarmca  what is the Fluent SDK version?

**Comment by anuchandy** [comment]
@naveenkumarmca just double checking: are you awaiting on the above call and are you sure your application is not exiting before completion of all async calls?

**Comment by naveenkumarmca** [comment]
@hovsepm v1.11.1

**Comment by naveenkumarmca** [comment]
@anuchandy This is not an application issue. This is an issue with Azure side wherein it does not recognize the ApplyAsync() call. Code executes perfectly fine, but on the Azure it does not reflect anything.

**Comment by hovsepm** [comment]
@naveenkumarmca could you provide a network payload? (e.g. using Fiddler). I assume that you do use  `await` in front of the async calls, right?

**Comment by hovsepm** [comment]
Closing as non-repro. Please open a new issue if you hit this in v1.16.1 or higher.
