### ISSUE TITLE
Thread-safety and memory leak bug in Fluent API Region class

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-net#46]
_From @Eldar1205 on August 27, 2017 14:49_

I looked in _fluent_ branch at source code of [Region](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/ResourceManager/Region.cs) class and noticed a thread-safety bug and a memory leak bug due to usage of static regions dictionary. The thread-safety bug is that public _Create_ method can call private constructor which adds an item to the static dictionary - user can call _Create_ in parallel with different regions not already in the dictionary causing parallel mutation of the dictionary, which isn't a thread-safe operation. The second issue is that this same mutation of the dictionary can cause a memory leak if user has bug that constantly uses new unknown locations. I suggest to solve both by initializing the dictionary once in static constructor with all well-known regions, and when _Create_ calls the private constructor for unknown region the private constructor won't manipulate the static regions dictionary. The _Equals_ and _GetHashCode_ implementations already support that, they don't assume each region instance is in the dictionary.

_Copied from original issue: Azure/azure-sdk-for-net#3628_

**Comment by milismsft** [comment]
@RikkiGibson will this be something we can address/fix in the Runtime?

**Comment by RikkiGibson** [comment]
I might be missing something but I don't see how the runtime relates to this.

Up to date link to Region file: https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Region.cs

I think what @Eldar1205 has suggested in the original issue will be a good fix.

**Comment by RikkiGibson** [comment]
In Java the Region class is also kept in the Azure libraries, not the runtime.

https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java

It seems to have a similar problem--let's just not cache instances of user-defined regions as it seems like kind of an imperceptible optimization anyway.

**Comment by weidongxu-microsoft** [comment]
Address concurrency first.

Memory leak is certainly possible, if incorrectly used. But the whole ENUM classes inherit from ExpandableStringEnum got same problem.
