### ISSUE TITLE
Finding Applications and Service Principals by ApplicationId

### ISSUE THREAD

**Issue by bloudraak** [Azure/azure-libraries-for-net#460]
I'm using the fluent API to authenticate a service principal that has full read/write access to the directory and numerous subscriptions.  Given that I only have an application id or client id, I'd like to search for the application and service principal in the directory that I use to authenticate against so I can give it access to Key Vault and other resources I'm about to create. 

We never reference service principals or applications by its object id or name.

Neither the following works:

```
string tenantId = "example.onmicrosoft.com";
string clientId = "ead0153a-1234-1234-1234-123456789f98";
string clientSecret = "passsword";

 ServicePrincipalLoginInformation information = new ServicePrincipalLoginInformation();
 information.ClientId = clientId;
 information.ClientSecret = clientSecret;
 AzureCredentials credentials = new AzureCredentials(information, tenantId, AzureEnvironment.AzureGlobalCloud);
var authenticated = Azure.Authenticate(credentials);
var thisApplication = authenticated.ActiveDirectoryApplications.GetById(clientId);
var thisServicePrincipal = authenticated.ServicePrincipals.GetById(clientId);
```

Shouldn't there be a method on both `authenticated.ActiveDirectoryApplications` and `authenticated.ServicePrincipals` to `FindByApplicationId`? 

The only workaround I have today is to List all the applications, and search for one where the `app.ApplicationId` matches the `clientId`. This is very inefficient and extremely slow (it takes minutes) when you have thousands of applications and service principals in the directory. 

Is there another way to do this?

**Comment by bloudraak** [comment]
This is the code I'm currently using to find an application and service principal by the application id:

```
var authenticated = Azure.Authenticate(credentials);
Console.WriteLine($"Searching for application `{clientId}` in tenant `{tenantId}`");
var thisApplications =
    from app in authenticated.ActiveDirectoryApplications.List()
    where app.ApplicationId == clientId
    select app;
var thisApplication = thisApplications.Single();

Console.WriteLine($"Searching for service principals `{clientId}` in tenant `{tenantId}`");
var thisServicePrincipals =
    from sp in authenticated.ServicePrincipals.List()
    where sp.ApplicationId == clientId
    select sp;
var thisServicePrincipal = thisServicePrincipals.Single();
```

**Comment by bloudraak** [comment]
Searching for a single service principal page by page, took around 2 minutes, 6 seconds.  Each page takes approx 6 seconds.   

Here's the code:
```
Console.WriteLine($"Fetching a page of service principals from tenant `{tenantId}`");
IServicePrincipal thisServicePrincipal = null;
var servicePrincipals = authenticated.ServicePrincipals.ListAsync(false).Result;
while (servicePrincipals != null)
{
    thisServicePrincipal = servicePrincipals.FirstOrDefault(sp => sp.ApplicationId == clientId);
    if (thisServicePrincipal != null)
    {
        Console.WriteLine($"Found service principal in tenant `{tenantId}`");
        break;
    }

    Console.WriteLine($"Fetching the next page of service principals from tenant `{tenantId}`");
    servicePrincipals = servicePrincipals.GetNextPageAsync().Result;
}
```

**Comment by jmahosky** [comment]
@bloudraak same issue with the java SDK, so just wanted to thank you for the API filter workaround!

**Comment by xccc-msft** [comment]
@bloudraak @jmahosky As this issue was posted long ago, I'm not sure if you are still facing this issue. I'm able to do that with below code
```
string clientId = "ead0153a-1234-1234-1234-123456789f98";
var thisApplication = authenticated.ActiveDirectoryApplications.GetByName(clientId);
var thisServicePrincipal = authenticated.ServicePrincipals.GetByName(clientId);
```
The `GetByName` method in latest version could help on this. Please feel free to upgrade your SDK version if it is not there in the one you are using.

**Comment by xccc-msft** [comment]
Close this as `GetName` works in this case. Please feel free to reopen if any issue persist.
