### ISSUE TITLE
Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by michaeljdresser** [Azure/azure-libraries-for-net#464]
We are currently looking into Azure Functions which requires both of the below packages, but there appears to be a conflict between Microsoft.AzureServices.AppAuthentication and Microsoft.Azure.Management.Fluent.

They both use Microsoft.IdentityModel.Clients.ActiveDirectory, AppAuthtication uses 3.14.2 and the Fluent uses 3.14.0.

Could the Fluent api be updated to use 3.14.2 or is there another work around?

Thanks

Michael.

**Comment by hovsepm** [comment]
what is your target framework?

**Comment by hovsepm** [comment]
and also which version of Fluent SDK are you using? V1.15.1 is referencing following ADAL libraries:
```
.NETFramework 4.5.2
Microsoft.IdentityModel.Clients.ActiveDirectory (= 2.28.3)

.NETFramework 4.6.1
Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.14.0 && < 4.0.0)

.NETStandard 1.4
Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.14.0 && < 4.0.0)
```
so our dependency is 3.14.0 or higher. 

BTW what runtime of the Azure Functions are you using? V1?

**Comment by michaeljdresser** [comment]
We are using Visual Studio to write the function and the error we are seeing is occurring when running the function in the Azure Emulator. Were using v1 of the Azure runtime, and we are targeting .NETFramework 4.6.1.

Microsoft.Azure.Management.Fluent 1.15.1
Microsoft.AzureServices.AppAuthentication 1.0.3

We have written a very simple functions to recreate the issue with the following code: I've removed any sensitive details :)

`

            var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal("ClientId",
                "ClientSecret",
                "TenantId",
                AzureEnvironment.AzureGlobalCloud);

            var ManageAzure = Azure.Authenticate(credentials).WithSubscription("SubscriptionId");

            var appResourceId = "Get From WebApp -> Properties -> Resource ID";

            var webapp = ManageAzure.WebApps.GetById(appResourceId);

            //Set App Setting Key and Value
            webapp.Update()
                .WithAppSetting("test", "123456789")
                .Apply();
`

The exception is throw when 'ManageAzure.WebApps.GetById(appResourceId)' is called with the following details.

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'

If we remove the Microsoft.AzureServices.AppAuthentication package the function works as expected.

Thanks

Michael.

**Comment by michaeljdresser** [comment]
I just put the same code into a Console application and a V2 Function with the same two packages and code works. So clearly this isn't a conflict, it's something to do with V1 Azure Function or it's emulator.
