### ISSUE TITLE
Need to add support for ATM Multivalue routing type

### ISSUE THREAD

**Issue by jsukhabut** [Azure/azure-libraries-for-net#476]
Need to add support for ATM Multivalue routing methods and Subnet routing methods

https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-configure-multivalue-routing-method

https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-routing-methods

**Comment by hovsepm** [comment]
Release 1.16.1 is out. Please upgrade your references. Please open a new issue if you will hit same/new errors.
