### ISSUE TITLE
RetryDelegatingHandler memory leak

### ISSUE THREAD

**Issue by vmendi** [Azure/azure-libraries-for-net#478]
We are seeing a memory leak when using the Fluent SDK that seems to match this bug:

https://github.com/Azure/azure-sdk-for-net/pull/4067

The PR is already merged in the normal Azure SDK. Should it also be fixed in the Fluent SDK?

**Comment by vmendi** [comment]
Any idea on what we can do as a workaround in the mean time?

**Comment by hovsepm** [comment]
@vmendi we are on the final stages of testing a new ClientRuntime 2.3.15 and a fix in Fluent Core classes. It should be out next week as release 1.16.1.

**Comment by vmendi** [comment]
Alright, thanks!

**Comment by hovsepm** [comment]
Release 1.16.1 is out. Please upgrade your references. Please open a new issue if you will hit same/new errors.
