### ISSUE TITLE
Cannot deploy webapp to virtual application

### ISSUE THREAD

**Issue by alesandrino** [Azure/azure-libraries-for-net#480]
I have tried hard and searched the web and samples for clues, but have not been able to get this done.
Is it not supported to deploy webapps to virtual applications, or am simply missing something?
```csharp
webApp.Deploy()
  .WithPackageUri(packageUri + saToken)
  .WithSetParameter("IIS Web Application Name", $"Default Web Site/application")
  .WithExistingDeploymentsDeleted(true)
  .Execute();
```

**Comment by LevioConseils** [comment]
Any answer here?  I'd like to deploy to virtual app too.  I tried

WithSetParameter("DeployIisAppPath", "nameoftheapp/vdir")

without success, it's still deploying to wwwroot.

**Comment by alesandrino** [comment]
I already forgot about this request. We are now using Kudu to achieve this and it works well. Basically uploading the app as a ZIP, extracting it to a new directory and finally updating the virtual application so that it points to the new app directory.

**Comment by yaohaizh** [comment]
Close this as the user uses alternative. @alesandrino feel free to reopen this if you meet any issue using fluent SDK. Thanks.
