### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by rhavlick** [Azure/azure-libraries-for-net#486]
Hello,

  There are a few broken links on: https://github.com/Azure/azure-libraries-for-net#databases-and-storage in the SQL databases and storage section:

Restore and recover SQL databases
Get SQL Database metrics
Manage SQL Database Failover Groups
Manage SQL Server DNL aliases
Manage SQL secrets (Server Keys) in Azure Key Vault
Manage SQL Virtual Network Rules

Thanks

**Comment by yaohaizh** [comment]
@xccc-msft please fix this on the sample code generation.

**Comment by xccc-msft** [comment]
@rhavlick We have updated in master branch. Thanks for reporting this.
