### ISSUE TITLE
SQL Failover Group sample has a broken link in the readme.md file

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-net#487]
"Manage SQL Database Failover Groups" under [Databases and Storage](https://github.com/Azure/azure-libraries-for-net#databases-and-storage ) -> 404

However sample exists and can be viewed here https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/Sql/ManageSqlFailoverGroups.cs 

samples.json should be fixed.

**Comment by yaohaizh** [comment]
Close this as duplicate with 

https://github.com/Azure/azure-libraries-for-net/issues/486
--

**Comment by xccc-msft** [comment]
Close this as updated in master.
