### ISSUE TITLE
PremiumSSD functionality.

### ISSUE THREAD

**Issue by robwafle** [Azure/azure-libraries-for-net#488]
Hi.  I was able to write some code that generalizes and captures a VM to a managed image on Azure using this fluent library!  I'm so excited!  This is pretty awesome!

However, I have three small challenges I'd like some help with.

1) I can't figure out how to specify a PremiumSSD storageProfile when I create my managed image in any way.  The way I'm using is FromVirtualMachine().  Here's my current code block.
`    var newManagedImage = azure.VirtualMachineCustomImages.Define(newManagedImageName)
                    .WithRegion(sourceVm.Region)
                    .WithNewResourceGroup(managedImageResourceGroup)
                    .FromVirtualMachine(vmToCapture)
                    .Create();
`
2) I can't figure out how to deploy with a PremiumSSD disk from classic storage.  
  a) I'd like to have this option to keep infrequently used images around at lowest cost.
  b) This works with ARM without issue.  So, I can create an ARM template to do this, but I'd like to use the fluent API to do this.

3)  When I checked out the 1.16.0 hash (fb77cce3dae11ba4ca562d358c74193a7064021c) to try and see if I can add this functionality and submit a PR, I get 21 CS0579 errors building this with VS 2017 15.8.7: 
    Error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyDescriptionAttribute' attribute (1, 1)
    Error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute (1, 1)

I understand this is probably unrelated but if I can get this to build I'd love to contribute.

**Comment by hovsepm** [comment]
@robwafle we have a special section on configuring your devbox for development and contribution here https://github.com/Azure/azure-libraries-for-net#prerequisites 

for **PremiumSSD** I'll let @anuchandy guide you through VM world.

**Comment by robwafle** [comment]
Thanks @hovsepm!  Hi @anuchandy is creating a Premium Managed disk indeed missing functionality, or am I missing something?

**Comment by robwafle** [comment]
Hi @hovsepm and @anuchandy, I've made some progress.  I am trying to build now, but I am getting a few errors regarding missing files within my "restoredPackages" folder.  

The packages appear to be restored, I have 15 folders at: S:\azure-libraries-for-net\restoredPackages:
`
   Directory: S:\azure-libraries-for-net\restoredPackages


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/15/2018  10:42 AM                microsoft.azure.keyvault.core
d-----       10/15/2018  10:42 AM                microsoft.data.services.client
d-----       10/15/2018  10:42 AM                microsoft.identitymodel.clients.activedirectory
d-----       10/15/2018  10:42 AM                microsoft.identitymodel.logging
d-----       10/15/2018  10:42 AM                microsoft.identitymodel.tokens
d-----       10/15/2018  10:42 AM                microsoft.rest.clientruntime
d-----       10/15/2018  10:42 AM                microsoft.rest.clientruntime.azure
d-----       10/15/2018  10:42 AM                microsoft.rest.clientruntime.azure.authentication
d-----       10/15/2018  10:42 AM                newtonsoft.json
d-----       10/15/2018  10:42 AM                system.componentmodel.eventbasedasync
d-----       10/15/2018  10:42 AM                system.dynamic.runtime
d-----       10/15/2018  10:42 AM                system.linq.queryable
d-----       10/15/2018  10:42 AM                system.net.networkinformation
d-----       10/15/2018  10:42 AM                system.net.requests
d-----       10/15/2018  10:42 AM                system.threading.overlapped
`

`"S:\azure-libraries-for-net\build.proj" (CreateNugetPackage target) (1) ->
(CategorizeProjects target) ->
  S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: The "SDKCategorizeProjects" task failed unexpectedly. [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: System.AggregateException: One or more errors occurred. ---> Microsoft.Build.Exceptions.InvalidProjectFileException: The
 imported project "S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> decla
ration is correct, and that the file exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL\ADAL.PCL.csproj [S:\azure-libraries-for-net
\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object ) [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    --- End of inner exception stack trace --- [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) [S:\azure-libraries-for-net\
build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) [S:\azure-librari
es-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.Wait() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions par
allelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) [S:\azure-libraries-for-
net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOption
s, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body) [S:\azure-libraries-for-net\
build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.GetLoadedProjectList(IEnumerable`1 projList) [S:\azure-li
braries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.GetProjectData(List`1 projectList, ConcurrentBag`1 suppor
tedProjectBag) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.Categorize() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.Execute() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [S:\azure-libraries
-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [S:\azure-libraries-for-net\build.pr
oj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: ---> (Inner Exception #0) Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "S:\azure-librari
es-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL\ADAL.PCL.csproj [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<--- [S:\azure-libraries-f
or-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:  [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: ---> (Inner Exception #1) Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "S:\azure-librari
es-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL.Android\ADAL.PCL.Android.csproj [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<--- [S:\azure-libraries-f
or-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:  [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: ---> (Inner Exception #2) Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "S:\azure-librari
es-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL.iOS\ADAL.PCL.iOS.csproj [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<--- [S:\azure-libraries-f
or-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:  [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: ---> (Inner Exception #3) Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "S:\azure-librari
es-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL.WinRT\ADAL.PCL.WinRT.csproj [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<--- [S:\azure-libraries-f
or-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:  [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: ---> (Inner Exception #4) Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "S:\azure-librari
es-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL.CoreCLR\ADAL.PCL.CoreCLR.csproj [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<--- [S:\azure-libraries-f
or-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:  [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018: ---> (Inner Exception #5) Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "S:\azure-librari
es-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\build\ADAL.Net.settings.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the fil
e exists on disk.  S:\azure-libraries-for-net\restoredPackages\microsoft.identitymodel.clients.activedirectory\3.14.0\src\src\ADAL.PCL.Desktop\ADAL.PCL.Desktop.csproj [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at Microsoft.WindowsAzure.Build.Tasks.SDKCategorizeProjects.<>c__DisplayClass94_0.<GetLoadedProjectList>b__0(ITaskIte
m proj) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1() [S:\azure-libraries-for-n
et\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvoke() [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask) [S:\azure-libraries-for-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<--- [S:\azure-libraries-f
or-net\build.proj]
S:\azure-libraries-for-net\tools\SdkBuildTools\targets\common.targets(330,5): error MSB4018:  [S:\azure-libraries-for-net\build.proj]`

**Comment by hovsepm** [comment]
@robwafle 
First, let's check that your environment is good to go. Please doublecheck that you follow the following steps:
1. Run `PrepareFluentRelease.ps1` in the `tools` folder with some non-existent fluent SDK version (e.g. `PrepareFluentRelease.ps1 1.17.18`. 
2. To build packages locally you need to open VS2017 developer cmd and in the root folder of your cloned repository run `msbuild build.proj /t:CreateNugetPackage /p:SkipTests=true`. (keep in mind that to be able to build you need first run `msbuild build.proj` without any parameter).
3. Copy content of `binaries\packages` folder to your local nuget feed folder (or add this location to your nuget feeds). Keep in mind that you also should have default nuget package location e.g. `https://api.nuget.org/v3/index.json` in your nuget feeds (you can find that easily in VS options). 
4. Reference your custom Fluent SDK nuget packages from the local feed in the test solution. 

LMK if that does not work.

**Comment by robwafle** [comment]
Hi @hovsepm thanks so much for your reply!

I apologize, I was running out the door when I wrote this message and left out a few details.

Regarding step #1: I was able to get through that yesterday without issue.  I should have mentioned that.  Thanks for mentioning it though I didn't initially find this and was updating the .csproj manually to start. I was very pleased when I found it.

Regarding step #2: I was running this command: `msbuild build.proj /t:CreateNugetPackage` but I was running it in a random powershell window.  I switched to the developer command prompt and added `/p:SkipTests=true` that didn't seem to help.  Same errors.   I should have also mentioned that I'm trying to build this hash/tags:  1fb77cce3 (HEAD -> master, tag: Fluent-v1.16, origin/master, origin/HEAD) Release 1.16.0 (#473)`  Do you have any ideas?   

Regarding step #3, thanks I was expecting the nuget package to just land in the folder.  Where will this binaries\packages folder be?  Is the binaries folder at the root level?  I guess since step 2 fails for me I don't see this folder just yet.

Regarding step #4, very much looking forward to it!

Thanks again for all your help!

**Comment by hovsepm** [comment]
@robwafle 
`binaries\packages` folder should appear in the root folder of your cloned repo.  but let's go from the start and have a fresh clone (or clean up your fork with `git clean -dfx` first - keep in mind that all uncommited changes will be erased).

here is the complete guide for you after cloning:
1 Open elevated VS 2017 command prompt
2 Navigate to repository root directory
3 Execute MsBuild.exe build.proj (this will pull all the build related tools needed to build the repo)
4 Skip verification for the dlls with Fluent SDK dev key
  Sn -Vr *,31bf3856ad364e35

now you are ready to run the steps from the above (will just copy them here):
1. Run in PS cmd window `PrepareFluentRelease.ps1` in the `tools` folder with some non-existent fluent SDK version (e.g. `.\PrepareFluentRelease.ps1 1.17.18`. 
2. To build packages locally you need to open VS2017 developer cmd and in the root folder of your cloned repository run `msbuild build.proj /t:CreateNugetPackage /p:SkipTests=true`. (keep in mind that to be able to build you need first run `msbuild build.proj` without any parameter).
3. Copy content of `binaries\packages` folder to your local nuget feed folder (or add this location to your nuget feeds). Keep in mind that you also should have default nuget package location e.g. `https://api.nuget.org/v3/index.json` in your nuget feeds (you can find that easily in VS options). 
4. Reference your custom Fluent SDK nuget packages from the local feed in the test solution.

**Comment by robwafle** [comment]
Hi @hovsepm!  It built (with 876 warnings), but it built!!! 

I swear (up, up, down, down, left, right, left and right again) that I didn't do anything other than the above other than opening and trying to build in visual studio, but thanks for recommend that I start over!

I now have 104 folders in restoredPackages (including .tools) folder.  So, perhaps something is up with the logic to perform the nuget restore during the msbuild vs with visual studio.

I'm in the middle of a long running test capturing a vm so I can't get to step 4 right now, but I'm sure it will be no issue.

Thanks again!

Rob

**Comment by hovsepm** [comment]
@robwafle Congrats! :) Yeah... we have a lot of warnings...

you should use binaries from `binaries\packages` folder in your solution not restoredPackages...

**Comment by robwafle** [comment]
Yes, of course.  I copied them to the tools\LocalNugetFeed as expected.

**Comment by hovsepm** [comment]
1. `git clean -dfx`
2. `MsBuild.exe build.proj`
3. `msbuild build.proj /t:CreateNugetPackage /p:SkipTests=true`

Step number 2 downloads build dependencies and targets. Step number 1 cleans those files :)

**Comment by yaohaizh** [comment]
Close this issue as the problem has been addressed.
