### ISSUE TITLE
Expose HasInner() on IHasInner interface?

### ISSUE THREAD

**Issue by rvanmaanen** [Azure/azure-libraries-for-net#491]
Hi,

I'm trying to get the metric definitions of a resource. The statement I wrote is the following:

`var metricDefinitions = await azure.MetricDefinitions.Inner.ListAsync(resourceId).ConfigureAwait(false);`

This results in a NotImplementedException. I traced it back to this code: https://github.com/Azure/azure-libraries-for-net/blob/0ea10a867c2e759bb05a929726cd7b18c20b0a6b/src/ResourceManagement/Monitor/MetricDefinitionsImpl.cs

What is clear there is that the Inner **property** is throwing a NotImplementedException, but there is an Inner **method** which does return the IMetricDefinitionsOperations object I'm trying to reach. Is this on purpose, should the Inner method be part of the IHasInner interface or should this property just be implemented properly? If not, can you please elaborate as to why it is build like this and what would be the correct way to reach the MetricDefinitions?

**Comment by hovsepm** [comment]
@rvanmaanen in short, Inners are a "backdoor" path to the functionality that is available but not fully implemented in the Fluent layers. 

Please take a look to the sample that we provide for MD here https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/Monitor/QueryMetricsAndActivityLogs.cs#L60 . Here is a code snippet from it:
```
foreach (var metricDefinition in azure.MetricDefinitions.ListByResource(storageAccount.Id))
{
    // find metric definition for Transactions
    if (metricDefinition.Name.LocalizedValue.Equals("transactions", StringComparison.OrdinalIgnoreCase))
    {
        // get metric records
        var metricCollection = metricDefinition.DefineQuery()
            .StartingFrom(recordDateTime.AddDays(-7))
            .EndsBefore(recordDateTime)
            .WithAggregation("Average")
            .WithInterval(TimeSpan.FromMinutes(5))
            .WithOdataFilter("apiName eq 'PutBlob' and responseType eq 'Success' and geoType eq 'Primary'")
            .Execute()
```
we do provide async versions for both `ListByResource` and `Execute` methods above.

**Comment by rvanmaanen** [comment]
I fell back on using the MonitorManagementClient, which really is too bad because it would have been nice not to need yet another client.
