### ISSUE TITLE
Azure Monitor - Determining what aggregation interval to use

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#495]
I'm currently working on [Promitor](https://http://promitor.io) which is scraping the Azure Monitor API for metrics based on a configuration file.

As part of an Azure Monitor query an interval needs to be defined in order to specify the metrics granularity such as:
```csharp
 var metricQuery = metricDefinition.DefineQuery()
                .StartingFrom(recordDateTime.AddDays(-5))
                .EndsBefore(recordDateTime)
                .WithAggregation(metricAggregation.ToString())
                .WithInterval(TimeSpan.FromMinutes(5));
```

However, depending on the metric this is different and the value needs to be exact.
Otherwise you will have exceptions like these:
> Invalid time grain duration: PT3M, supported ones are: 00:01:00,00:05:00,00:15:00,00:30:00,01:00:00,06:00:00,12:00:00,1.00:00:00

This brings me with a few questions:
- What is the best approach to ensure that these are correct? Is that to check the ["Metric Availabilities"](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.monitor.models.metricdefinition.metricavailabilities?view=azure-dotnet) for a specific metric and verify that it's present?
- Are they really different for every metric or is there an enum that can help us with this?

**Comment by hovsepm** [comment]
@anirudhcavale could you help here?

**Comment by anirudhcavale** [comment]
@hovsepm, @tomkerkhove : The metric granularity enums are PT1M PT5M PT15M PT30M PT1H PT6H PT1D. Most metrics support all of these granulartires.
However there are some exceptions, a few metrics only support PT5M, or only support PT1H and higher.
As you guessed @tomkerkhove the only way to know is to call "Metric Availabilities".

**Comment by tomkerkhove** [comment]
Thanks for the quick help @anirudhcavale so there is no enum that covers this, however it makes sense if not every service is using the same granularities.

I'm going to close this as this answers my question, thank you!

**Comment by anirudhcavale** [comment]
Unfortunately not, we expect the exact granularity to be provided.

**Comment by tomkerkhove** [comment]
Too bad, thanks for the info!
