### ISSUE TITLE
Service principal sign-on URL used as display name

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-libraries-for-net#497]
The signature of `IServicePrincipals.Define(string name)` suggests the string argument becomes the display name for the new service principal. However, this code:
```cs
await Azure.Configure().Authenticate(_credentials)
    .ServicePrincipals
    .Define("my-service-principal")
    .WithNewApplication("http://sign-on-url")
    .CreateAsync();
```
produces this POST:
```
{
  "availableToOtherTenants": false,
  "displayName": "http://sign-on-url",
  "homepage": "http://sign-on-url",
  "identifierUris": [
    "http://sign-on-url"
  ],
  "replyUrls": [
    "http://sign-on-url"
  ]
}
```
and the new principal's name is in fact the URL passed to `WithNewApplication()`.

**Comment by chlowell** [comment]
@hovsepm is there a timeline for shipping the fix?

**Comment by hovsepm** [comment]
@chlowell currently planned to be out next week.

**Comment by hovsepm** [comment]
v1.17 is out. Please upgrade your reference.
