### ISSUE TITLE
Mismatch in constructor arguments in the chain from FunctionEnvelopeInner upwards

### ISSUE THREAD

**Issue by rvanmaanen** [Azure/azure-libraries-for-net#508]
So, situation: Trying to write unittests and wanting to mock the final call in this chain:

Azure client -> WebApps -> Inner -> ListFunctionsAsync

This isn't easy in the first place, because ListFunctionsAsync is (as well as many others) an extension method. **Question:** Why is this? Now I have to create a wrapper around the client, which implements a custom interface that exposes the same functionality, but now it's mockable.

Next up, the return value of the mocked call. Ofcourse nothing easy here with an IPage interface, but at least it's an interface so I can work with that, fine. The actual object I want to return is of type "FunctionEnvelopeInner". When constructing this class and passing in the correct parameters like Id/Name/Type/Location, things get messy again. If you inspect the object after instantiating, you'll see the following values for these properties:

Id -> Location
Name -> Id
Type -> Name
Location -> Type
Type -> null

**Bug:** I did some inspecting of the code, it appears the constructor arguments are getting mixed up somewhere halfway the chain:

### FunctionEnvelopeInner : ProxyOnlyResourceInner

public FunctionEnvelopeInner(string id = default(string), string name = default(string), string type = default(string), string kind = default(string), string functionAppId = default(string), string scriptRootPathHref = default(string), string scriptHref = default(string), string configHref = default(string), string secretsFileHref = default(string), string href = default(string), object config = default(object), IDictionary<string, string> files = default(IDictionary<string, string>), string testData = default(string)) : base(id, name, type, kind)

### ProxyOnlyResourceInner : Resource

public ProxyOnlyResourceInner(string id = default(string), string name = default(string), string type = default(string), string kind = default(string)) : `base(id, name, type)`

### Resource : ProxyResource (new location parameter here?)

public Resource(`string location, string id = default(string), string name = default(string), string type = default(string)`, IDictionary<string, string> tags = default(IDictionary<string, string>)) : base(id, name, type)

###  ProxyResource : Rest.Azure.IResource		

public ProxyResource(string id = default(string), string name = default(string), string type = default(string))

**Comment by rvanmaanen** [comment]
Think this was introduced here: https://github.com/Azure/azure-libraries-for-net/commit/5a9cf8c9bd440b499e45e702d6ee99dda086372c#diff-aab8c0ba10488a88c31e87e395ac733c

**Comment by yaohaizh** [comment]
Fixed as we exposed function envelope.
