### ISSUE TITLE
Missing dotnet monitor sample for autoscale

### ISSUE THREAD

**Issue by pppchris** [Azure/azure-libraries-for-net#512]
https://github.com/Azure-Samples/monitor-dotnet-autoscale-based-on-performance

Link to sample code is throwing a 404 error.

**Comment by hovsepm** [comment]
@pppchris we will fix it in the future release. In the meanwhile you can browse that sample in our repo here  https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/Monitor/AutoscaleSettingsBasedOnPerformanceOrSchedule.cs 

BTW all the samples can be viewed here - https://github.com/Azure/azure-libraries-for-net/blob/master/Samples

**Comment by yaohaizh** [comment]
Close as the sample is correctly showing up now.
