### ISSUE TITLE
Specifying proxy credentials

### ISSUE THREAD

**Issue by danports** [Azure/azure-libraries-for-net#517]
I'm working behind a corporate proxy that requires authentication. When I try to do something simple like this to create a resource group, I get a HTTP 407 (Proxy Authentication Required) error: `azure.ResourceGroups.Define(groupName).WithRegion(location).Create()`

I was able to work around the issue with this nasty piece of work: 
```
var client = azure.ManagementClients.OfType<ResourceManagementClient>().First();
var restClient = (RestClient) client.GetType().GetField("_restClient", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(client);
restClient.RootHttpHandler.DefaultProxyCredentials = CredentialCache.DefaultCredentials;
```

Is there a better (i.e. supported) way to do this? I searched the documentation to no avail. Thanks!

**Comment by richardacre** [comment]
Seconded. This is a blocking issue for us

**Comment by qub1n** [comment]
What about this?

https://github.com/Azure/azure-libraries-for-net/issues/284

**Comment by weidongxu-microsoft** [comment]
It can be done in 2 steps: create RestClient (and configure it with Proxy) first, then create Azure using this RestClient, as such

```
            AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromFile(AUTH_FILE);

            RestClient restClient = RestClient.Configure()
                    .WithEnvironment(credentials.Environment)
                    .WithCredentials(credentials)
                    .Build();

            restClient.RootHttpHandler.DefaultProxyCredentials = CredentialCache.DefaultCredentials;

            IAzure azure = Azure.Authenticate(restClient, credentials.TenantId)
                .WithDefaultSubscription();
```

Reference https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Azure.Fluent/Azure.cs#L699

**Comment by yaohaizh** [comment]
@weidongxu-microsoft , @xccc-msft , please confirm this issue and enhance our example for this scenario if possible. Thanks.

**Comment by xccc-msft** [comment]
Close this as [example using proxy in authentication](https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md#using-proxy-in-authentication) got added in release version 1.28.0

**Comment by danports** [comment]
@xccc-msft Great, thank you!
