### ISSUE TITLE
AcessTokenNotFound is misspelled

### ISSUE THREAD

**Issue by nschonni** [Azure/azure-libraries-for-net#527]
Should be Ac**c**essTokenNotFound but I'm not sure if you can make that change now

**Comment by hovsepm** [comment]
@anuchandy this is in `azure-libraries-for-net\src\ResourceManagement\ResourceManager\Authentication\MSILoginException.cs`. Please consider fixing it in the major version change.

**Comment by yaohaizh** [comment]
Close this as fixed.
