### ISSUE TITLE
ARM template deployment does not work when WithParameters property is used

### ISSUE THREAD

**Issue by thered121** [Azure/azure-libraries-for-net#536]
So I've been fighting with this for a few days.  I'm attempting to deploy an ARM template with a parameters file using the following code
``` 
IDeployment deploy = azure.Deployments.Define("myDeployment")
.WithExistingResourceGroup("myResourceGroup")
.WithTemplate(template)
.WithParameters(parameters)
.WithMode(DeploymentMode.Incremental)
.Create();
```

But I keep getting 

> The request content was invalid and could not be deserialized: 'Could not find member 'storageAccountName' on object of type 'DeploymentParameterDefinition'. Path 'properties.parameters.parameters.storageAccountName', line 184, position 29.'.

Both template and parameters are read in from files and passed as Json strings (I did try passing as JObjects but got the same error).  Passing the ARM template seems fine since passing it and an empty WithParameters results in an error complaining the parameters have no values.  I've tried both with and without the schema and contentVersion in the parameters file and it looks like it isn't expecting those to be specified.  I found an similar issue over in the azure-sdk-for-net repo from 2016 but the fixes there aren't working.  Here is  the parameters file
```
{
    "parameters": {
      "storageAccountName": {
        "value": "myStorage"
      },
      "storageLocation": {
        "value": "eastus"
      },
      "tagDeveloperValue": {
        "value": "me"
      },
      "tagOwnerValue": {
        "value": "myOwner"
      },
      "tagEnvValue": {
        "value": "Non-Prod"
      },
      "workspaceResourceId": {
        "value": "/subscriptions/subguid/resourceGroups/myresourcegroup/providers/Microsoft.OperationalInsights/workspaces/myworkspace"
      }
    }
  }
```
Any ideas on what I might be doing wrong?

**Comment by thered121** [comment]
So after forking the repo and building a local copy to debug with I figured out what was wrong.  The parameters template not only doesn't need the schema and contentVersion but the parameters object is unnecessary as well.  The working parameters file looks like as follows
```
{
     "storageAccountName": {
        "value": "myStorage"
      },
      "storageLocation": {
        "value": "eastus"
      },
      "tagDeveloperValue": {
        "value": "me"
      },
      "tagOwnerValue": {
        "value": "myOwner"
      },
      "tagEnvValue": {
        "value": "Non-Prod"
      },
      "workspaceResourceId": {
        "value": "/subscriptions/subguid/resourceGroups/myresourcegroup/providers/Microsoft.OperationalInsights/workspaces/myworkspace"
      }   
  }
```
Is this how it's supposed to look for use in the WithParameters call?  From all the sample parameter files I've found they all contain the schema, contentVersion and parameters objects.

**Comment by fuocor** [comment]
Thanks for this. I've been fighting with it for 2 days

**Comment by yaohaizh** [comment]
This is the right behavior for the argument. You can find the https://github.com/Azure/azure-rest-api-specs/blob/09b8b6fbcb865ac6e3b6f6712d05cc99d02d8517/specification/resources/resource-manager/Microsoft.Resources/stable/2019-08-01/resources.json#L4090
