### ISSUE TITLE
"No-Wait" support when creating AKS clusters

### ISSUE THREAD

**Issue by kblooie** [Azure/azure-libraries-for-net#545]
When creating an AKS cluster, using code similar to the example (https://github.com/Azure-Samples/aks-dotnet-manage-kubernetes-cluster/blob/master/Program.cs), the task returned by CreateAsync looks like it's waiting for the entire provisioning process to complete before returning. Creating a cluster with 10 nodes takes around half an hour. It's not realistic to await that long in a web or queue based system.

I would prefer to make the request with an option similar to --no-wait in the cli, then poll until the provisioning process has completed. 

I see there's a IKubernetesCluster.ProvisioningState property, but I'm not seeing any options on IContainerServiceManager similar to --no-wait. Is this not possible?

**Comment by praries880** [comment]
@kblooie We will investigate the suggestoin and update the issue on how we decide to proceed.

**Comment by yaohaizh** [comment]
@ChenTanyi please take a look at this issue, whether it is a bug?

**Comment by ChenTanyi** [comment]
@kblooie You could use `**.IsCompletedSuccessfully` to poll the provisioning process as well as `.IsCanceled`, `.IsCompleted` and `.IsFaulted`

like:
```csharp
var createAsync = azure.***.CreateAsync();
while (true)
{
    Console.WriteLine(createAsync.IsCompletedSuccessfully);
    Thread.Sleep(1000);
}
```

**Comment by yaohaizh** [comment]
Close this as no more input for the case. @kblooie feel free to re-open if the issue still persists on your side. Thanks.
