### ISSUE TITLE
Cannot list tags of the subscription

### ISSUE THREAD

**Issue by Cosebdd** [Azure/azure-libraries-for-net#552]
There is no possibility to list subscription's tags, despite the fact that it's possible through PowerShell and Rest API:
/subscriptions/{subId}/tagNames endpoint for Rest API and 
Get-AzureRmTag cmdlet in PowerShell

Would be really nice to support it, as for now user is only able to list tags using the ResourceGroups property of the IAzure interface

**Comment by praries880** [comment]
@Cosebdd  You can use the flunt lite SDK to list the tags in a subscription. [Here is the call](https://github.com/Azure/azure-sdk-for-net/blob/master/src/SDKs/Resource/Management.ResourceManager/Generated/TagsOperations.cs#L846) that will do it for you.

Do let us know if this is not what you are looking for.

**Comment by Cosebdd** [comment]
@praries880, ok, it might work. But I thought about something available from the IAzure interface, because your solution is basically just a generated client for the Azure REST API

**Comment by praries880** [comment]
@Cosebdd The repo that is just autogenerated stuff from the REST API spec is the [.net sdk repo](https://github.com/Azure/azure-sdk-for-net). What we call Fluent Light.

This repo is for more complex tasks that generally involve more than a couple of steps to accomplish using the autogenerated SDK.
