### ISSUE TITLE
403 returning while trying to delete a user from AD

### ISSUE THREAD

**Issue by NikitHern** [Azure/azure-libraries-for-net#554]
Hi
While developing an app i have faced an issue:
`await _azure
                .ActiveDirectoryUsers
                .DeleteByIdAsync(userId);`
does not delete user and does not throw any exception, while in the fiddler i can see:
![image](https://user-images.githubusercontent.com/21967237/50005552-d60ddc80-ffbb-11e8-89ea-7416a235536d.png)
the response code is 403.
In the graph api documentation
https://docs.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0
stands that for deletion the application must have 
User.ReadWrite.All or Directory.AccessAsUser.All rights, but my application has both of them.
![image](https://user-images.githubusercontent.com/21967237/50005678-3bfa6400-ffbc-11e8-8e5c-6e0325f5c49e.png)

Could anyone provide a solution to this case?

**Comment by jianghaolu** [comment]
Your application is missing permissions to acess Windows Azure Active Directory. Not delegated permissions, but application permissions.

![image](https://user-images.githubusercontent.com/2320445/53848563-adb5ce80-3f69-11e9-942b-f0bfff3a814f.png)

**Comment by yaohaizh** [comment]
@NikitHern Do you have any update on this issue? Does the issue resolved?

**Comment by yaohaizh** [comment]
Close this as not replied from the end user.
