### ISSUE TITLE
There is no example for MonitorClient's replacement MonitorManagementClient

### ISSUE THREAD

**Issue by ccic** [Azure/azure-libraries-for-net#558]
I want to monitor Web App's CPU & Memory usage. I found this example https://github.com/Azure-Samples/monitor-dotnet-multidimensional-metrics-api/blob/master/Program.cs, but the MonitorClient class is not found when I refer Microsoft.Azure.Management.Monitor.Fluent 1.18.0.

I found there is a breaking change in latest SDK version, which said "the client **MonitorClient** does not exist anymore. Only the client **MonitorManagementClient** remains and it exposes all the operations of the SDK".

My question is how can I quickly migrate from MonitorClient to MonitorManagementClient, is there any example?

**Comment by hovsepm** [comment]
you can get ManagementClient directly from the MonitorManager. e,g,
```
IMonitorManager monitorManager = null;
// do you authentication etc.
IMonitorManagementClient mgmClient = monitorManager.Inner;
```

**Comment by hovsepm** [comment]
Closing as resolved.

**Comment by RaduVulpescu** [comment]
Hello, I want to use the MonitorManagerClient too, but I don't know how to pass the credentials to the RestClient builder used for the monitor manager.

For now, my code looks like this:
```
var creds = ???

var restClient = RestClient.Configure()
     .WithBaseUri("https://management.azure.com")
     .WithCredentials(creds)
     .Build();

var monitorManager = MonitorManager.Authenticate(restClient, subscriptionId);
```

How should the `creds` variable look like?

Thank you!

**Comment by weidongxu-microsoft** [comment]
You can load from file via
`AzureCredentials credentials = SdkContext.AzureCredentialsFactory.FromFile(AUTH_FILE);`

**Comment by RaduVulpescu** [comment]
Thank you @weidongxu-microsoft ! Your reference was very helpful in solving my issue.
