### ISSUE TITLE
Adding a certificate to the library which isn't bound to a host name

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-net#56]
_From @ajit-kolathur on May 9, 2017 22:4_

Hi,

We use a certificate for client certificate authentication, the cert needs to be installed but it isn't bound to any host name. I noticed that the management library doesn't support adding a certificate which isnt bound to a host name. The azure portal supports this by having two separate features, adding a certificate and binding a certificate. Are there plans to support simple install of cert without biding?

Thanks

_Copied from original issue: Azure/azure-sdk-for-net#3190_

**Comment by hovsepm** [comment]
_From @Dona278 on September 6, 2017 15:27_

@ajit-kolathur Have you tried add a certificate to an existing web app using:
```csharp
// webApp: IWebApp
// certificate: X509Certificate2
await webApp.Manager.AppServiceCertificates
                    .Define(string.Format("{0}##{1}#", certificate.Thumbprint, webApp.Region.Name))
                    .WithRegion(Region.EuropeWest)
                    .WithExistingResourceGroup(webApp.ResourceGroupName)
                    .WithPfxByteArray(certificateBytes)
                    .WithPfxPassword(certificatePass)
                    .CreateAsync();
```

**Comment by xccc-msft** [comment]
@ajit-kolathur as this issue was created long ago, I wanted to check if you are still facing issue of adding the certificate without binding?

**Comment by xccc-msft** [comment]
As no response, and we could be able to add certificate with existing web app via latest SDK, close this for now. Please feel free to reopen if any issue persist.
