### ISSUE TITLE
Adding subnets with mixed case names to Cosmos DB firewall results in errors

### ISSUE THREAD

**Issue by abharath27** [Azure/azure-libraries-for-net#562]
Consider this scenario:
1. I want to restrict a cosmos DB account to accept traffic from a subnet "Subnet1". I use Fluent to call `_cosmosDBAccount.Update().WithVirtualNetwork(virtualNetworkId, "Subnet1").Apply()`. This works as expected.
2. If I call `_cosmosDBAccount.Update().WithVirtualNetwork(virtualNetworkId, "Subnet1").Apply()` again,  it adds a new entry to the [this.virtualNetworksMap](https://github.com/Azure/azure-libraries-for-net/blob/84eb2e66a1e1d7db3bcc504a35843115688866b7/src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs#L473) dictionary. The dictionary now has 2 entries with keys "subnet1" and "Subnet1", so .Apply() creates 2  firewall rules on the cosmos db.
3. Now when I call `_cosmosDBAccount.Update().WithVirtualNetwork(virtualNetworkId, "Subnet1").Apply()` for the third time, Fluent tries to instantiate the firewall object, it fails with the error "An item with the same key has already been added" because of [this](https://github.com/Azure/azure-libraries-for-net/blob/84eb2e66a1e1d7db3bcc504a35843115688866b7/src/ResourceManagement/CosmosDB/CosmosDBAccountImpl.cs#L526)

We need to be consistent with casing.

**Comment by hovsepm** [comment]
@abharath27 could you provide some more details why would you add same Virtual Network several times to the same cosmos account? I just want to understand your scenario better to make sure we will have a proper fix here.

**Comment by hovsepm** [comment]
Fixed and shipped in v1.19

**Comment by abharath27** [comment]
Just to add more details on why we're adding the same virtual network several times: Our team created a C# console app that reads an inventory file and provisions/updates all the Azure resources in several environments (Dev/Staging/Prod). This app is configured to run in our Azure Devops pipeline each time someone checks in a change to the inventory or the code.
