### ISSUE TITLE
KeyVault define access policy - ForObjectId vs. ForServicePrincipal

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-libraries-for-net#579]
this may be a documentation exercise but we would like to understand the reasons for an exception we are getting when setting up KV with access policy "for service principal" vs "for object id" - of the AD App Service principal - which works

```
DefineAccessPolicy()
                    .ForObjectId(_testConfig.TargetIdentityObjectId) - works
                    .ForServicePrincipal(appId) - does not
```

attempting to use ForServicePrincipal with app id (or the object id for that matter) gives us rbac graph exception with the underlying response containing - it seems some form of graph query is being performed (but that being different authority would require different token)???

{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"requestId":"f2178900-51df-4ce3-9da7-4baf87a00cc3","date":"2019-01-21T22:58:27"}}

ForObjectId with the object id of the **service principal** however does work

What is the difference between these two flows?

**Comment by VaclavK** [comment]
this may be a documentation exercise but we would like to understand the reasons for an exception we are getting when setting up KV with access policy "for service principal" vs "for object id" - of the AD App Service principal - which works
```
DefineAccessPolicy()
                    .ForObjectId(_testConfig.TargetIdentityObjectId) - works
                    .ForServicePrincipal(appId) - does not
```

attempting to use ForServicePrincipal with app id (or the object id for that matter) gives us rbac graph exception with the underlying response containing  - it seems some form of graph query is being performed (but that being different authority would require different token)???

{"odata.error":{"code":"Authentication_MissingOrMalformed","message":{"lang":"en","value":"Access Token missing or malformed."},"requestId":"f2178900-51df-4ce3-9da7-4baf87a00cc3","date":"2019-01-21T22:58:27"}}

ForObjectId with the object id of the **service principal** however does work

What is the difference between these two flows?

**Comment by praries880** [comment]
@VaclavK  Can you kindly specify the package versions you are using?

Can you also share the stack trace?
