### ISSUE TITLE
Remove Sync method generation from AutoRest.Fluent generator. 

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-libraries-for-net#59]
_From @hovsepm on April 4, 2017 17:59_

_Copied from original issue: Azure/azure-sdk-for-net#3026_

**Comment by hovsepm** [comment]
_From @martinsawicki on October 11, 2017 20:38_

sounds reasonable

**Comment by RikkiGibson** [comment]
`--csharp.sync-methods=none` in the gulpfile may help here.

https://github.com/Azure/autorest/blob/master/docs/user/cli.md

**Comment by hovsepm** [comment]
@RikkiGibson if it works we need to update our gulp file to use that.

**Comment by RikkiGibson** [comment]
Looks like `--csharp.sync-methods=none` is already in the gulpfile in master. Regenerating doesn't result in any sync methods showing in the diff, and removing the flag causes those sync methods to be generated, so I think we're all good here.
