### ISSUE TITLE
[Feature Req]User Assigned MSI from Fluent SDK Microsoft.Azure.Management.AppService.Fluent 

### ISSUE THREAD

**Issue by navdixit** [Azure/azure-libraries-for-net#601]
**Is your feature request related to a problem? Please describe.**
We are using Fluent SDK Microsoft.Azure.Management.AppService.Fluent (ref: https://github.com/Azure/azure-libraries-for-net) for creating Azure functions. We are planning to use “user assigned” MSI for functions apps. When we followed the [documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fapp-service%2Foverview-managed-identity%23adding-a-user-assigned-identity-preview&data=02%7C01%7Cnavdixit%40microsoft.com%7C7d29361292644085230908d6946ff069%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636859605828494405&sdata=%2F6ROa2ZmWb5ta0vEr6Tap%2FksSzgCrM8aQQsCwJ55zi4%3D&reserved=0), couldn’t find an option to assign “user assigned MSI” to a functions app using Fluent library.

**Describe the solution you'd like**
 I was able to see an option for system assigned MSI using WithSystemAssignedManagedServiceIdentity. It will be great if we get something like WithUserAssignedManagedServiceIdentity.

**Describe alternatives you've considered**
Currently no alternative is planned.

**Additional context**
It seems fluent sdk has dependency on swagger update. Related issue is filed at  https://github.com/Azure/azure-rest-api-specs/issues/5237

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by nickzhums** [comment]
Closing the issue as it should be fixed
