### ISSUE TITLE
Can we use MSI with Azure Authentication ?

### ISSUE THREAD

**Issue by sowsan** [Azure/azure-libraries-for-net#602]
Not seeing an option to leverage MSI with Azure Authentication Fluent API. https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#mgmt-auth 

Any idea is this possible ?

**Comment by praries880** [comment]
@sowsan  We do support MSI. Can you look at [this sample](https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/Asset/documentdb-dotnet-todo-app/src/DocumentDBRepository.cs#L84) and see if it helps you?

**Comment by sowsan** [comment]
@praries880 thank you. I will have a look.

**Comment by nickzhums** [comment]
@sowsan Closed this issue as the sample is provided, feel free to re-open the issue :)
