### ISSUE TITLE
[BUG] BuiltInRoles.AzureCosmosDbAccountContributor seems wrong

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-libraries-for-net#621]
The role is defined as: `public static readonly BuiltInRole AzureCosmosDbAccountContributor = Parse("Azure Cosmos DB Account Contributor");`

But code like this throws an exception for a null object:

    await user
        .Update()
        .WithNewRole(BuiltInRole.AzureCosmosDbAccountContributor, target.Id)
        .ApplyAsync();

Instead, consider using Parse("**DocumentDB Account Contributor**") instead.

`var role = BuiltInRole.Parse("DocumentDB Account Contributor");` works properly during role assignments

This is also in line with the documentation here: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-cosmos-db

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.
