### ISSUE TITLE
[BUG] WithTrafficForwarding[From/To]RemoteNetwork seems to be backwards

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-libraries-for-net#623]
WithTrafficForwardingFromRemoteNetwork and WithTrafficForwardingToRemoteNetwork seem to be doing things backwards.

    await network
        .Peerings
        .Define("remote-network")
        .WithRemoteNetwork(remoteNetwork)
        //.WithTrafficForwardingFromRemoteNetwork()
        .WithTrafficForwardingToRemoteNetwork() // these are backwards - SDK bug?!?
        .WithGatewayUseOnRemoteNetworkStarted()
        .CreateAsync();

I have two networks.  "**network**" and "**remoteNetwork**".

I want traffic forwarding from **remoteNetwork -> network**, but not vice versa.

In my SDK call, I would think that "WithTrafficForwardingFromRemoteNetwork" is what I want.  But it results in the opposite of what I want.  Instead, "WithTrafficForwardingToRemoteNetwork" gives me the outcome I want, even though the name of the method seems to say it'll do the opposite of what I want.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by qub1n** [comment]
I have similar bug here:

I need to create peering from A to B, not the otherwise

            await networkA.Peerings.Define(peeringName)
                .WithRemoteNetwork(networkB)
                .CreateAsync(cancellationToken);
        
This piece of code creates peering in both directions. I cannot find a way how to create one-direction peering. I can do it in Azure portal. Is there such a possibility?
