### ISSUE TITLE
Microsoft.Azure.Management.ContainerInstance.Fluent references the deprecated WindowsAzure.Storage

### ISSUE THREAD

**Issue by SaltyDH** [Azure/azure-libraries-for-net#625]
**Describe the bug**
The description on NuGet says that we should switch to using The storage specific packages as of Version 9.4. See: https://www.nuget.org/packages/WindowsAzure.Storage/

However when also importing Microsoft.Azure.Management.Fluent (v1.20.0), the dependency Microsoft.Azure.Management.ContainerInstance.Fluent package still references the WindowsAzure.Storage package.

Because the namespaces for CloudFileClient are still the same in both assemblies, I am unable to resolve the ambiguous reference.

***Exception or Stack Trace***
N/A

**To Reproduce**
Import as NuGet package references
1. Microsoft.Azure.Management.Fluent (v1.20.0)
2. Microsoft.Azure.Storage.File (v9.4.2)

Attempt to utilise CloudFileClient.

***Code Snippet***
N/A

**Expected behavior**
I should be able to use the latest packages together in the same project

**Screenshots**
n/A

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS2017

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by praries880** [comment]
@iscai-msft Can you take a look at this issue?

**Comment by LTA-Thinking** [comment]
+1ing. The old version of WindowsAzure.Storage is causing a component governance issue for us as it imports an old version of Microsoft.Data.OData that has known issues. It looks like ContainerInstance, EventHub, and SQL all reference this package.

**Comment by yaohaizh** [comment]
@ChenTanyi could you help take a look at this issue?

**Comment by ChenTanyi** [comment]
@SaltyDH I've tested for latest Microsoft.Azure.Storage.File(v11.1.0) and Microsoft.Azure.Management.Fluent (v1.26.0), and it works. Maybe Storage File has been fixed.

We will discuss to update the dependencies.

**Comment by SaltyDH** [comment]
Thanks @ChenTanyi.

I can see a commit from 7 months ago for v10 which changed the namespaces on these classes so I suspect the issue is resolved. I haven't specifically tested these packages together because we ended up changing our solution structure to work around this problem rather than wait.
