### ISSUE TITLE
ActivityLogs.DefineQuery() BadRequest startTime

### ISSUE THREAD

**Issue by Mi1an** [Azure/azure-libraries-for-net#629]
I don´t understand why startTime can´t accept format from DateTime.Now. I download sample for metrics and activity log and there is same DateTime.Now as input parameter.

`var logs = azureAuthentication.ActivityLogs.DefineQuery().StartingFrom(DateTime.Now.AddDays(-7)).EndsBefore(DateTime.Now).WithAllPropertiesInResponse().Execute();`

Microsoft.Azure.Management.Monitor.Fluent.Models.ErrorResponseException: 'Operation returned an invalid status code 'BadRequest''

[https://imgur.com/kHnBIgR](https://imgur.com/kHnBIgR)
[https://imgur.com/ztsdBgL](https://imgur.com/ztsdBgL)

 - OS: Windows 10
 - IDE : Vistual Studio 2017 ver. 15.9.10
 - Version of the Library used: 1.20.0

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by hovsepm** [comment]
duplicate of https://github.com/Azure/azure-libraries-for-net/issues/511

**Comment by Mi1an** [comment]
I used UtcNow from thread #511 and it is working. 

Thanks!
