### ISSUE TITLE
'Authorization' header is missing with Certificate Credentials when creating KeyVault

### ISSUE THREAD

**Issue by spazard1** [Azure/azure-libraries-for-net#63]
Full disclosure, I am a Microsoft employee on the Azure team. (alias styackel).

I'm getting an odd exception when attempting to use a management certificate to authenticate when creating a key vault.

It is giving me this exception: 
`Authentication failed. The 'Authorization' header is missing.
   at Microsoft.Azure.Management.KeyVault.Fluent.VaultsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()`
etc.

Shouldn't the authorization header not be needed in this case, or am I missing something?

```
var managementCertificate = EncryptionUtils.GetCertificateFromStore(this.ManagementCertificateThumbprint);

using (var client = new KeyVaultManagementClient(new CertificateCredentials(managementCertificate)))
{
	client.SubscriptionId = this.SubscriptionId;

	var result = client.Vaults.CreateOrUpdateAsync(this.ResourceGroupName, this.KeyVaultName, new VaultCreateOrUpdateParametersInner
	{
		Properties = new VaultProperties
		{
			Sku = new Sku() { Name = SkuName.Standard },
			EnabledForDeployment = true,
			EnabledForDiskEncryption = true,
			EnabledForTemplateDeployment = true,
			AccessPolicies = new List<AccessPolicyEntry>()
			{
				new AccessPolicyEntry()
				{
					ApplicationId = Guid.Parse(this.AadApplicationId),
					TenantId = Guid.Parse(this.AadApplicationId),
					Permissions = new Permissions() { Certificates = new List<string>() {"all"}, Keys = new List<string>() {"all"}, Secrets = new List<string>() {"all"} },
					ObjectId = ""
				}
			}
		},
		Location = this.ResourceGroupLocation
	}).Result;
}
```

**Comment by hovsepm** [comment]
Talked through IM - @spazard1 is trying to use Fluent libraries to work with ASM (aka RDFE) which is not supported by design.

**Comment by joymon** [comment]
May be the below link will help you to get TokenBasedCredential from certificate associated with AD App.
https://github.com/Azure/azure-sdk-for-net/issues/4103
