### ISSUE TITLE
[BUG] Virtual network rules can not be updated

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-libraries-for-net#631]
An existing Cosmos DB cannot update virtual networking rules.

The API allows for it:  `cosmos.Update().WithVirtualNetworkRules(...)`

But it is ignored and any existing rules are dropped, instead.

See: https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/34690507-virtual-network-rules-to-cosmos-db-arm-template

There's a bug in the underlying deployment system.  If "Locations" is not specified, then the deployment still succeeds but virtual networking rules die.  I posted a workaround there using ARM templates.  But there doesn't seem to be any call I can make while updating it using the azure management libraries to include Location, so I'm suffering from the same bug.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by praries880** [comment]
@joshlang We will investigate this and try to get to the bottom of the issue.

In the meanwhile, will it be possible for you to turn on the debug logs for this case and share them with us.

**Comment by joshlang** [comment]
I don't know how to turn on "debug logs".

You can see Microsoft internal support request 119012621000241 from Jan 28 2019 for more information, though.

**Comment by nickzhums** [comment]
@joshlang Please let us know if you are still facing the issue

**Comment by joshlang** [comment]
I have long ago moved onto different solutions.  If you think this is fixed, feel free to close the issue of course.  I have no way to test now.
