### ISSUE TITLE
[FEATURE REQ] List all activity logs in selected time period

### ISSUE THREAD

**Issue by Mi1an** [Azure/azure-libraries-for-net#634]
I want to list all activity logs (from example last 24h.) and then search in this list for specific names, actions, resources and so on... Problem what I have now is when I get first VM from 100 in foreach loop I need to load data from activity log by resource (name of first VM). In last VM (100/100) in foreach loop I can get new activity logs or lost latest activity logs because every cycle of foreach loop will load new activity logs due to new (actual) DateTime.

I´d like to have some method like: 
azureAuthentication.ActivityLogs.DefineQuery().StartingFrom( DateTime.UtcNow.AddDays(-1)).EndsBefore(DateTime.UtcNow).WithAllPropertiesInResponse().**Everything()**.Execute(); or **GetAllLogs()**

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by praries880** [comment]
@Mi1an We need to look into the feature request to see what work is involved in this. Will keep the issue posted with updates as wee gather more information on this.

**Comment by Mi1an** [comment]
I realized that this can be simply resolved in code and this function is no needed at all.
