### ISSUE TITLE
[BUG] Wrong encryption status returned for encrypted VM's data disks

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-libraries-for-net#636]
See https://github.com/Azure/azure-libraries-for-java/issues/712

**Comment by praries880** [comment]
validated that we do not need the fix in .net. The implementation is already correct :
https://github.com/Azure/azure-libraries-for-net/blob/6c9c6cf1a4d1c69b542866c1944c1e105fe201e5/src/ResourceManagement/Compute/WindowsVolumeEncryptionMonitorImpl.cs#L135
