### ISSUE TITLE
[BUG] Subsequent role assignments PUT to the first role assignment's URI

### ISSUE THREAD

**Issue by joshlang** [Azure/azure-libraries-for-net#637]
Consider this code:

```
public static async Task Grant(
    this IServicePrincipal user,
    BuiltInRole role,
    string objectId
    )
{
    try
    {
        await user
            .Update()
            .WithNewRole(role, objectId)
            .ApplyAsync();
    }
    catch (AggregateException e) when ((e.InnerException as CloudException)?.Response.StatusCode == HttpStatusCode.Conflict)
    {
    }
}
```

For a single user (service principal for VMSS), I call this `Grant` method multiple times to grant access to several different resources.

But I get a CONFLICT error after the first request.  On examining e.InnerException.Request.RequestUri, I see that it's issuing a PUT request to the **first** resource I called `Grant` on, instead of using the objectId I actually pass in.

I try to work around it by using .Manager/.Inner properties, but those happen to throw NotImplementedExceptions, so I'll have to hunt for other solutions.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.
