### ISSUE TITLE
[BUG] Cannot DefineSslBinding WithExistingCertificate

### ISSUE THREAD

**Issue by Suchiman** [Azure/azure-libraries-for-net#640]
**Describe the bug**
Trying to add an SSL binding with an existing certificate to a domain results in a Bad Request because the SDK does not send the Thumbprint.

***Exception or Stack Trace***
```json
{
    "Code": "BadRequest",
    "Message": "No certificate thumbprint provided.",
    "Target": null,
    "Details": [
        {
            "Message": "No certificate thumbprint provided."
        },
        {
            "Code": "BadRequest"
        },
        {
            "ErrorEntity": {
                "ExtendedCode": "04025",
                "MessageTemplate": "No certificate thumbprint provided.",
                "Parameters": [],
                "Code": "BadRequest",
                "Message": "No certificate thumbprint provided."
            }
        }
    ],
    "Innererror": null
}
```

***Code Snippet***
```csharp
var prodApp = azure.AppServices.WebApps.GetByResourceGroup("Resource", "AppName");
var app = prodApp.DeploymentSlots.GetByName("StagingSlotName");
string fqdn = "test.domain.de";
string thumbprint = "...";

await app
    .Update()
        .DefineSslBinding()
            .ForHostname(fqdn)
            .WithExistingCertificate(thumbprint)
            .WithSniBasedSsl()
            .Attach()
    .ApplyAsync();
```

Produces 4 requests, the last one producing the bad request looks like
```
PUT https://management.microsoftazure.de/subscriptions/REDACTED/resourceGroups/Resource/providers/Microsoft.Web/sites/AppName/slots/StagingSlotName?api-version=2018-02-01 HTTP/1.1
x-ms-client-request-id: REDACTED
accept-language: en-US
Authorization: Bearer REDACTED
User-Agent: FxVersion/4.7.3324.0 OSName/Windows OSVersion/6.2.9200.0 Microsoft.Azure.Management.AppService.Fluent.WebSiteManagementClient/1.20.0.0 MacAddressHash/REDACTED
Content-Type: application/json; charset=utf-8
Host: management.microsoftazure.de
Content-Length: 2231
Expect: 100-continue

{
  "properties": {
    "enabled": true,
    "hostNameSslStates": [
      ...	
      {
        "name": "test.domain.de",
        "sslState": "SniEnabled",
        "toUpdate": true
      }
    ],
	...
  }
}
```

**Expected behavior**
The request should include the thumbprint specified via the fluent interface to not result in this error.

**Setup (please complete the following information):**
 - OS: Windows 10 Enterprise 1803
 - IDE : VS2019
 - Version of the Library used: 1.20.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by praries880** [comment]
@Suchiman 
The way this call [works](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/AppService/HostNameSslBindingImpl.cs#L144) is that it will list all the certs in the resource group and then pick on e where the name/thumbprint matched what you specified.

Can you validate that the resource group has a cert with the name/thumbprint that you passed in? Since the logs you sent does not have any section for the cert, I'm thinking that there was no cert with the thumbprint/name you specified in the RG.

**Comment by Suchiman** [comment]
@praries880 Actually i was iterating the certificates myself using `var certificates = azure.AppServices.AppServiceCertificates.List();`, searching for a certificate that matches the hostname i'm trying to bind. But first i had to workaround [this](https://github.com/Azure/azure-libraries-for-net/issues/51#issuecomment-480297352) known, nearly 2 year old bug...
Everything is inside a single resource group however.

**Comment by Suchiman** [comment]
@praries880 i have identified the culprit. the workaround i did propose [here](https://github.com/Azure/azure-libraries-for-net/issues/51#issuecomment-480297352) was causing an exception when calling `ListByResourceGroupAsync` which was apparently silently swallowed by the SDK.

Unless you want to improve the error handling there, this issue can be closed.

**Comment by nickzhums** [comment]
@Suchiman Thanks for your comment. We will close this issue for now and add improving error handling to our backlog. Feel free to re-open the issue.
