### ISSUE TITLE
Support for MultipleResourceMultipleMetricCriteria in Monitor

### ISSUE THREAD

**Issue by fabianmaciel** [Azure/azure-libraries-for-net#654]
MultipleResourceMultipleMetricCriteria is missing from Microsoft.Azure.Management.Monitor.

According to [https://docs.microsoft.com/en-us/rest/api/monitor/metricalerts/createorupdate], the generated HTTP request for _odata.type MultipleResourceMultipleMetricCriteria_ must also include:

- properties.targetResourceRegion	
- properties.targetResourceType

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by daveknowles** [comment]
Hi, Is there any update on when this is going to be fixed/supported?

**Comment by yaohaizh** [comment]
@weidongxu-microsoft could you help check whether we have updated this after update swagger spec?

**Comment by weidongxu-microsoft** [comment]
@daveknowles

We are updating monitor to latest swagger in this sprint (1.27 https://github.com/Azure/azure-libraries-for-net/pull/791). I will add some test case for MultipleResourceMultipleMetricCriteria and update you.

**Comment by daveknowles** [comment]
Great stuff, thanks for the update guys!

**Comment by weidongxu-microsoft** [comment]
Support in 1.27 (Oct. 11)

Sample code
https://github.com/Azure/azure-libraries-for-net/blob/master/Tests/Fluent.Tests/Monitor/MonitorTests.cs#L614 (`WithMultipleTargetResources`)
