### ISSUE TITLE
[BUG] Storage tags are not created in version 1.22.0

### ISSUE THREAD

**Issue by megel** [Azure/azure-libraries-for-net#655]
**Describe the bug**
Storage Tags are not created in **Version 1.22.0 (Verison 1.21.0 is OK)**

***Code Snippet***
```csharp
var customerTags = new Dictionary<string, string>
                {
                    ["ID"]          = customer.Id,
                    ["Customer"]    = customer.Name,
                    ["CustomerId"]  = customer.TenantId,
                    ["Owner"]       = ConfigurationManager.AppSettings["Tags_Owner"],
                    ["Description"] = ConfigurationManager.AppSettings["Tags_Description"]
                };
var storageId = "...";
var storage = await azure.StorageAccounts
                    .Define(storageId)
                    .WithRegion("westeurope")
                    .WithExistingResourceGroup("MyResourceGroup")
                    .WithSku(StorageAccountSkuType.Standard_LRS)
                    .WithGeneralPurposeAccountKindV2()
                    .WithTags(customerTags)
                    .CreateAsync();
```

**Result: (Not Working)**
![image](https://user-images.githubusercontent.com/15800069/57213594-989c0100-6fe7-11e9-846a-d97060840a35.png)
![image](https://user-images.githubusercontent.com/15800069/57213852-558e5d80-6fe8-11e9-8e67-8bcc5dde1b0c.png)

**Result: (Working)**
![image](https://user-images.githubusercontent.com/15800069/57213556-7dc98c80-6fe7-11e9-8a07-c6c4f170a5dd.png)
![image](https://user-images.githubusercontent.com/15800069/57213995-c2095c80-6fe8-11e9-8ce4-2b0938364292.png)

**Expected behavior**
Tags are created / assigned like in Version 1.21.0

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @iscai-msft

**Comment by xenalite** [comment]
I can confirm this is still reproducible in 1.23.0.
