### ISSUE TITLE
Key Vault: Support for setting certificate permissions 

### ISSUE THREAD

**Issue by luthus** [Azure/azure-libraries-for-net#67]
Are there currently any plans for adding this? 

Currently I can see AllowKeyPermissions, AllowKeyAllPermissions, AllowSecretPermissions and AllowSecretAllPermissions when defining the access policy.

**Comment by martinsawicki** [comment]
future work

**Comment by jbrads** [comment]
You can work around this after KeyVault create with something like this..

```
 // Select by ApplicationId, TenantId or ObjectId would be better, but this is just an example
var accessPolicy = vault.AccessPolicies.First();

accessPolicy.Permissions.Certificates = new List<string> { "all" };
await vault.Update().WithAccessPolicy(accessPolicy).ApplyAsync(ct);

```

**Comment by jianghaolu** [comment]
This will be added in the next release coming end of the month.
