### ISSUE TITLE
DNS A Record pointing to Public IP

### ISSUE THREAD

**Issue by draganb-pw** [Azure/azure-libraries-for-net#673]
Trying to create an A record in Azure DNS zone pointing to Azure Public IP resource. Haven't found a way in .Net libraries. Anyone has an idea?

This connection between DNS and PIP works in Azure portal. I need to to it programmatically.

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by rohinkoul** [comment]
@draganb-pw what version of SDK/API are you using?

**Comment by KarenHammons** [comment]
@draganb-pw if you're still experiencing this issue, can you please let us know?

**Comment by yaohaizh** [comment]
Please take a look at this so see how we can use the SDK to support this operation? Thanks.

**Comment by nickzhums** [comment]
@draganb-pw Let us know if you are still experiencing this issue after you've tried the comments above :)

**Comment by yaohaizh** [comment]
Close it as supported.
