### ISSUE TITLE
[BUG] Use PremiumLRS storage without a Storage Account.

### ISSUE THREAD

**Issue by DYNSOL** [Azure/azure-libraries-for-net#674]
**Describe the bug**
There is a bug that if you select 

`.WithLatestWindowsImage("MicrosoftWindowsServer", "WindowsServer", "2016-Datacenter")`

then you can't use 

`.WithOSDiskStorageAccountType(StorageAccountTypes.PremiumLRS)`

The only way around it, is add to a storage account by doing this:

`.WithNewStorageAccount(storageAccount)`

However, if i change the `.WithLatestWindowsImage("MicrosoftWindowsServer", "WindowsServer", "2016-Datacenter")` to `.WithPopularLinuxImage(KnownLinuxVirtualMachineImage.UbuntuServer14_04_Lts)` then i don't need to use a storage account and it works great!

***Exception or Stack Trace***
N/A

**To Reproduce**

Example in code snippet below.

***Code Snippet***
Add the code snippet that causes the issue.

`azure.VirtualMachines
                    .Define(vmName)
                    .WithRegion(location)
                    .WithExistingResourceGroup(rgName)
                    .WithExistingPrimaryNetworkInterface(networkInterface)
                    .WithLatestWindowsImage("MicrosoftWindowsServer", "WindowsServer", "2016-Datacenter")                    
                    .WithAdminUsername("azureuser")
                    .WithAdminPassword("#####")
                    .WithComputerName(vmName)
                    .WithSize(vmSize)
                    .WithOSDiskName(vmName + "-osdisk")
                    .WithTag("Environment", "Dev")                  
                    .WithOSDiskStorageAccountType(StorageAccountTypes.PremiumLRS)                    
                    .WithOSDiskCaching(CachingTypes.ReadWrite)
                    .WithOSDiskSizeInGB(128)
                    .Create();`

**Expected behavior**

To be able to use PremiumLRS storage without a Storage Account.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS2017
 - Version of the Library used: latest

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
As I checked, the sequence of the API is calling should be 
                        .WithLatestWindowsImage("MicrosoftWindowsServer", "WindowsServer", "2016-Datacenter")
                        .WithAdminUsername(userName)
                        .WithAdminPassword(password)
                        .WithComputerName(windowsVmName)
                        **.WithOSDiskStorageAccountType(StorageAccountTypes.PremiumLRS)**
                        .WithSize(VirtualMachineSizeTypes.StandardD3V2)
                        .WithOSDiskName(windowsVmName + "-osdisk")
                        .WithTag("Environment", "Dev")

                        .WithOSDiskCaching(CachingTypes.ReadWrite)
                        .WithOSDiskSizeInGB(128)
                        .Create();


As checked, same order required for Linux.  @praries880 Is this by design or we should provide the order as the user requested?

**Comment by DYNSOL** [comment]
Sorry - been inactive for a while. @yaohaizh i'm still unable to create the vm if i use `.WithOSDiskStorageAccountType(StorageAccountTypes.x)`

it works fine without specifiying Osdisk storage Account Type and it defaults to Standards LRS. It's like it's treating it as un-managed disks therefore a Storage Account is required.

**Comment by yaohaizh** [comment]
Will take a look

**Comment by yaohaizh** [comment]
@DYNSOL  which version of the SDK that you are using?

**Comment by Drewm3** [comment]
Closing this issue due to no response for several months.
