### ISSUE TITLE
Why was the v1.18 tag / release removed?

### ISSUE THREAD

**Issue by david-jarman** [Azure/azure-libraries-for-net#682]
**Query/Question**
Why was the v1.18 tag / release removed?

***Why is this not a Bug or a feature Request?***

**Setup (please complete the following information if applicable):**
 
 **Information Checklist**

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
@david-jarman, not sure. Is there any specified API from Fluent 1.18? Would suggest the latest version if possible. Thanks.

**Comment by david-jarman** [comment]
I was just curious. Just wanted to make sure it wasn't pulled for security concerns.

**Comment by yaohaizh** [comment]
Thanks. I'm not sure either. But for now, I would close this issue. Feel free to reopen it if you have any concerns.
