### ISSUE TITLE
[BUG] Network Security Groups that use Application Security Groups

### ISSUE THREAD

**Issue by toutougabi** [Azure/azure-libraries-for-net#684]
**Describe the bug**
I have NSGs that have some rules that use Application Security Groups.

Even if I don't touch anything close to the ASG any update to the NSG fails because the ASG are not properly serialized to JSON

***Exception or Stack Trace***
Add the exception log and stack trace if available
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.securityRules[7].properties.sourceApplicationSecurityGroups[0]."
      },
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.securityRules[8].properties.sourceApplicationSecurityGroups[0]."
      },
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.securityRules[9].properties.sourceApplicationSecurityGroups[0]."
      }
    ]
  }
}

If you check the request body, you can clearly see that when it came to serialize the sourceApplicationSecurityGroups, it serialized nothing and therefore causing the whole NSG update to fail.

{
        "properties": {
          "protocol": "*",
          "sourcePortRange": "*",
          "destinationPortRange": "445",
          "sourceAddressPrefixes": [],
          "sourceApplicationSecurityGroups": [
            {}
          ],
          "destinationAddressPrefix": "*",
          "destinationAddressPrefixes": [],
          "sourcePortRanges": [],
          "destinationPortRanges": [],
          "access": "Allow",
          "priority": 320,
          "direction": "Inbound",
          "provisioningState": "Succeeded"
        },
        "name": "Management-SMB",
        "etag": "W/\"b9c1a497-def5-4513-b70b-bc7779f338ce\"",
        "id": "/subscriptions/<subID>/resourceGroups/<rg id>/providers/Microsoft.Network/networkSecurityGroups/<nsg>/securityRules/Management-SMB"
      }

**To Reproduce**
Have an NSG with at least 1 rule using an ASG and try to update the NSG

**Expected behavior**
At least make NSG work if they use ASG, better would be to fix serialization of the ASG so we can use them

**Setup (please complete the following information):**
 - OS: W10
 - IDE : 2019
 - Version of the Library used : latest

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by toutougabi** [comment]
any news on this ?

**Comment by yaohaizh** [comment]
@toutougabi Will look into this issue starting from today. Let you if anything found. Thanks.

**Comment by yaohaizh** [comment]
@toutougabi  Could you provide the code snippet that calling NSG & ASG?

**Comment by yaohaizh** [comment]
@toutougabi do you still follow this issue? Could you provide more information for us to track the issue/problem here?  
1. Which lib that you are using. 
2. If possible, could you provide some code samples?

**Comment by yaohaizh** [comment]
Close this issue as it is not active for a long time. @toutougabi feel free to re-open the issue if you have any more issues.
