### ISSUE TITLE
Unable to retrieve a list of LongTerm Backups for a specific Azure SQL Database

### ISSUE THREAD

**Issue by Sandmann-cs1** [Azure/azure-libraries-for-net#689]
Hello 

I try to retrieve a list of available LongTerm backups for a specific Azure SQL database.
I'm using the Latest C# nuget Package (version 1.22.2) ,call the following method :

**ISqlManagementClient.BackupLongTermRetentionPolicies.ListByDatabaseAsync**

and then get the following Error : 

**Error Microsoft.Rest.Azure.CloudException: Configure long term retention policy with azure recovery service vault and policy is no longer supported. Please submit request with the new flexible retention policy**

Am I doing something wrong, is this no longer supported or is this a bug ?

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by aamalvea** [comment]
This LTR backup API is no longer supported and there is a new one for you touse. @pixia Please advise customer on the new LTR backup API

**Comment by pixia** [comment]
Please refer to https://www.nuget.org/packages/Microsoft.Azure.Management.Sql for latest versions. Azure has switched to Az Module (see https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-2.4.0).

**Comment by jeroenterheerdt** [comment]
Closing this issue. @Sandmann-cs1 do not hesitate to respond if you need help.

**Comment by jeroenterheerdt** [comment]
@kurtzeborn please close this issue.
