### ISSUE TITLE
[QUERY] Should we be able to assign a user-assigned managed identity to a web app?

### ISSUE THREAD

**Issue by JadedATB** [Azure/azure-libraries-for-net#690]
**Query/Question**
Should this functionality be working now (v1.22.2)?  If so, how can I get it to work?  Here is what I've tried:

await webApp.Update()
                .WithUserAssignedManagedServiceIdentity()
                .ApplyAsync();

webApp.Inner.Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.UserAssigned, tenantId, msi.Inner.PrincipalId.ToString());
                    webApp.Inner.Identity.UserAssignedIdentities = new Dictionary<string, ManagedServiceIdentityUserAssignedIdentitiesValue>();
                    ManagedServiceIdentityUserAssignedIdentitiesValue v = new ManagedServiceIdentityUserAssignedIdentitiesValue(msi.Inner.PrincipalId.ToString());
                    webApp.Inner.Identity.UserAssignedIdentities.Add(msiName, v);
                    await webApp.Update()
                        .ApplyAsync();

I've tried a few different things, but haven't gotten it to work yet.  From this code, I'm getting a BadRequest:

{"error":{"code":"FailedIdentityOperation","message":"Identity operation for resource '/subscriptions/******/resourceGroups/*****/providers/Microsoft.Web/sites/*****' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{\"error\":{\"code\":\"BadRequest\",\"message\":\"The request format was unexpected : Request requires identities to be assigned.\"}}'.'."}}

***Why is this not a Bug or a feature Request?***
Aside from the WithUserAssignedManagedServiceIdentity() call, this exists in Inner, so not sure if it's actually fully implemented..

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by weidongxu-microsoft** [comment]
This should do (assume you already have a Managed Identity created, if not, you can go `WithNewUserAssignedManagedServiceIdentity`)

```
webApp.Update()
    .WithExistingUserAssignedManagedServiceIdentity(azure.Identities.GetByResourceGroup(RESOURCE_GROUP, MANAGED_IDENTITY))
    .Apply();
```

**Comment by weidongxu-microsoft** [comment]
I assumed that I've answered your question. Re-open it if you have more to ask.

**Comment by satifulla-fi** [comment]
I am trying to update existing user assigned managed identity to azure automation account and I get the same error.
failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"The request format was unexpected : Request requires identities to be assigned."}}'.'.
