### ISSUE TITLE
Is it possible to move resources using fluent azure client?

### ISSUE THREAD

**Issue by sarajang** [Azure/azure-libraries-for-net#691]
**Query/Question**
Is it possible to move resources using fluent azure client?

***Why is this not a Bug or a feature Request?***
I am not sure if it already exists.

**Setup (please complete the following information if applicable):**
NA
 
 **Information Checklist**
NA

**Comment by ankushbindlish2** [comment]
ResourceManager

                .Configure()

                .Authenticate(AzureCredentials)

                .WithSubscription(TestParameters.SubscriptionId.ToString())

                .ResourceManager

                .Inner

                .Resources

                .MoveResourcesAsync("sourceRG", new ResourcesMoveInfoInner()

                {

                    TargetResourceGroup = "destinationRG"

                });

**Comment by kurtzeborn** [comment]
This question appears to have been answered so I'm closing the issue.  Please reopen if more followup is needed.
