### ISSUE TITLE
[FEATURE REQ] update Eventhub to use the latest swagger specs

### ISSUE THREAD

**Issue by praries880** [Azure/azure-libraries-for-net#702]
Even though the latest API version is still https://github.com/Azure/azure-rest-api-specs/tree/master/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2017-04-01, it has some changes in it form the last time we updated EventHub.
We need tp update eventhub to use tle latest rest specs.

Ref : https://github.com/Azure/azure-libraries-for-java/issues/757

**Comment by yaohaizh** [comment]
The eventhub swagger API has been updated.
