### ISSUE TITLE
[FEATURE REQ] Support for VMSS and HUB Licensing

### ISSUE THREAD

**Issue by pppchris** [Azure/azure-libraries-for-net#704]
Add support to enable and disable HUB Licensing for Virtual Machine Scale Sets. It is support for standard Virtual Machines but option is not available for VMSS.

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by Drewm3** [comment]
This is available by setting the licenseType property in [VirtualMachineScaleSetVMProfile](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate#virtualmachinescalesetvmprofile).
