### ISSUE TITLE
[FEATURE REQ] Auto-Shutdown on VMS

### ISSUE THREAD

**Issue by bernie-g** [Azure/azure-libraries-for-net#707]
On the actual azure portal you can configure Auto Shutdown times for the VM, but I don't see any way to do this in the API. Is this even possible at all?

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @yaohaizh

**Comment by yaohaizh** [comment]
The swagger spec doesn't have any spec about auto shutdown? @praries880, in this case, where can I direct this issue to?

**Comment by yaohaizh** [comment]
Issue moved to [Azure/azure-rest-api-specs #6533](https://github.com/Azure/azure-rest-api-specs/issues/6533) via [**ZenHub**](https://www.zenhub.com/)

**Comment by AmirKehtarian** [comment]
@bernie-g 
It looks like the link below is useful for automatically shutting down and start up VMS
https://learn.microsoft.com/en-us/rest/api/dtl/virtual-machines/list-applicable-schedules?tabs=HTTP
