### ISSUE TITLE
[FEATURE REQ] Fluent SDK does not expose HTTPS Load Balancer probes

### ISSUE THREAD

**Issue by VaclavK** [Azure/azure-libraries-for-net#711]
**Is your feature request related to a problem? Please describe.**

At the moment when LB rule is linked to HTTPS probe, only resource id is available and additional call has to be made with resource manager client - http and tcp probes are however available when listing LB rules via fluent

**Describe the solution you'd like**
support/return all probe types

**Describe alternatives you've considered**
at the moment we use resource manager to obtain the definition (however interestingly enough I have to target 2019-04-01 API not 2019-05-01)

**Additional context**
using latest fluent version

**Comment by praries880** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @yaohaizh

**Comment by VaclavK** [comment]
I should also note that the same is on definition side of things - e.g. 
```
.DefineHttpProbe($"{testApi1}-probe")
                .WithRequestPath("/Probe")
                .WithPort(1111)
```

there is no DefineHttpsProbe

**Comment by yaohaizh** [comment]
@VaclavK, the feature has been supported on the latest fluent lib. Please have a try. I'm closing this issue now. If you meet anything using the API, please feel free to re-open this issue or log an issue for new problems. Thanks.
