### ISSUE TITLE
[BUG] error CS7069: Reference to type 'ListContainerItemsInner' claims it is defined in 'Microsoft.Azure.Management.Storage.Fluent', but it could not be found

### ISSUE THREAD

**Issue by pinaki1234** [Azure/azure-libraries-for-net#716]
**Describe the bug**
I am trying to create an instance of StorageManagementClient:

StorageManagementClient storageMgmtClient = new StorageManagementClient(_restClient)

***Exception or Stack Trace***
error CS7069: Reference to type 'ListContainerItemsInner' claims it is defined in 'Microsoft.Azure.Management.Storage.Fluent', but it could not be found

**To Reproduce**
Add a reference to:
Microsoft.Azure.Management.Storage.Fluent
Microsoft.Azure.Management.Storage.Fluent.Models

***Code Snippet***
public void ListStorageAccounts(List<SubscriptionDTO> subscriptions)
        {
            foreach (SubscriptionDTO sub in subscriptions)
            {
                _azure = AzureFactory.GetAzureInstance(sub.Id).Azure;
                var storageAccounts = _azure.StorageAccounts;

                //Get the restclient
                //Passing all empty credentials to enable it to take default values
                var _restClient = _clientFactory.GetRestClient("", "", "");
                //Create the storage management instance
                StorageManagementClient storageMgmtClient = new StorageManagementClient(_restClient) { SubscriptionId = sub.Id }; //Actual error is here
                var rgs = _azure.ResourceGroups.ListAsync();
                //List all the resource groups under the subscription
                foreach (var rGroup in _azure.ResourceGroups.List())
                {
                    //List all the storage accounts by the specific RGB
                    var _accountslist = storageAccounts.ListByResourceGroup(rGroup.Name.ToString());

                    if (_accountslist != null)
                    {
                        foreach (var storageAccount in _accountslist)
                        {
                            ListContainerItemsInner _listContainers;
                            _rGroup = rGroup.Name.ToString();
                            _storageAccount = storageAccount.Name.ToString();
                            Console.WriteLine(_rGroup);
                            Console.WriteLine(_storageAccount);
                            _listContainers = storageMgmtClient.BlobContainers.ListAsync(_rGroup, _storageAccount).Result; //Practically blows up here - bubbled exception is Method not found: 'Microsoft.Azure.Management.Storage.Fluent.IBlobContainersOperations Microsoft.Azure.Management.Storage.Fluent.StorageManagementClient.get_BlobContainers()'.

                        }
                    }

                }
            }
        }

**Expected behavior**
It should give a list of containers

**Screenshots**
NA

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS 2017 Professional Version 15.9.13
 - Version of the Library used:
Microsoft.Azure.Management.Storage.Fluent 10.0.0.60

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yaohaizh** [comment]
Hi @pinaki1234 Do you use fluent API or management API from https://github.com/Azure/azure-sdk-for-net?

**Comment by yaohaizh** [comment]
@pinaki1234 , i'll close this since there is no update in the long time. 

Mostly, this issue is about refer to the right libs, either fluent lib or .net management lit. 

Feel free to open the issue if you have any issues.
