### ISSUE TITLE
[FEATURE REQ] Add pricing API for Virtual machines

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-libraries-for-net#718]
**Is your feature request related to a problem? Please describe.**
If I am creating VM in Azure portal I can see pricing estimations. I would like to have this information available in azure-libraries-for-net, so I can programmatically create for example the cheapest VM with 2 GB RAM in the give region.

**Describe the solution you'd like**
Receive price estimations in the SKU API, I already CPU, RAM, disk info.

**Describe alternatives you've considered**
We are hardcoding the pricing priorities, it is not nice, it can differs by region.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X] Description Added
- [ X] Expected solution specified

**Comment by maggiepint** [comment]
Hi,

Thanks for the feedback. We have routed this issue to the appropriate team for follow up.

**Comment by yaohaizh** [comment]
A service logged for tracking this issue. Thanks.

**Comment by mjconnection** [comment]
First, thank you for reaching out to the Microsoft team.  Other customers have found this helpful 
 https://docs.microsoft.com/en-us/azure/billing/billing-usage-rate-card-overview.

You will want to look at the Rate card API section of the documentation on this page.  Please let us know if this doesn't address your request.

**Comment by qub1n** [comment]
That is what I was looking for, thanks.
