### ISSUE TITLE
[QUERY] Request tags per resource URI

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#719]
Is there a way to request the tags linked to a resource based on its uri? 

I couldn't find this in the docs, sorry if I looked over it.

**Comment by yaohaizh** [comment]
@tomkerkhove  How is your code snippet looks like?  For the resource object, it should have associated Tags property.

**Comment by tomkerkhove** [comment]
That is correct, I've noticed you can do the following:
```csharp
var serviceBusNamespace = _authenticatedAzureSubscription.ServiceBusNamespaces.GetById("sample");
var armTags = serviceBusNamespace.Tags;
```

However, I need to be able to access the tags based on resource URI given our application does not want to use a switch to get a given resource and call "Tags" property on it.

This would also allow us to use this approach for all Azure resources, not only the ones supported by the SDK.

Is that possible?

**Comment by yaohaizh** [comment]
Use the ResourceManager.GenericResources.GetById(...)

Example: 
https://github.com/Azure/azure-libraries-for-net/blob/2e418c9259ac00e006efe02007cb1f939ffac2cf/Tests/Fluent.Tests/ResourceManager/GenericResourcesTests.cs#L31

**Comment by tomkerkhove** [comment]
I gave it a try by doing:
```csharp
_authenticatedAzureSubscription.ServiceBusNamespaces.GetById("subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.ServiceBus/namespaces/<instance>");
```

However, it gives me the following issue:
> Get just by resource group and name is not supported. Please use other overloads.

Am I missing something?

**Comment by tomkerkhove** [comment]
Stacktrace:
```
   at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourcesImpl.GetInnerByGroupAsync(String groupName, String name, CancellationToken cancellation)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetByResourceGroupAsync(String groupName, String name, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetByIdAsync(String id, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetById(String id)
   at Promitor.Integrations.AzureMonitor.AzureMonitorClient.QueryMetricAsync(String metricName, AggregationType aggregationType, TimeSpan aggregationInterval, String resourceId, String metricFilter) in C:\Code\GitHub\promitor\src\Promitor.Integrations.AzureMonitor\AzureMonitorClient.cs:line 78
```

**Comment by yaohaizh** [comment]
```csharp
                    resource = genericResources.Get(rgName,
                        resource.ResourceProviderNamespace,
                        resource.ParentResourceId,
                        resource.ResourceType,
                        resource.Name,
                        resource.ApiVersion);
```

**Comment by tomkerkhove** [comment]
This is not possible as I don't have all this info, I just have a resourceId.

I could interpret the whole resourceId to get all the info but it defeats the purpose of having resourceIds and `_resourceManager.GenericResources.GetByIdAsync`.

**Comment by tomkerkhove** [comment]
Any chance this is going to be added @yaohaizh 	?

**Comment by tomkerkhove** [comment]
Ping @yaohaizh.

@adamconnelly had a look in meantime as well and found a couple of blockers for us as well: https://github.com/tomkerkhove/promitor/issues/599#issuecomment-544174851

**Comment by yaohaizh** [comment]
@tomkerkhove, would like to support here.  @xccc-msft  will work on this and see whether we can support this in this release. 

Meanwhile, if you need us support more features as listed blocked, you log issues here so we can track them better and support in timely manner. Thanks.

**Comment by tomkerkhove** [comment]
Awesome, thanks guys!

**Comment by xccc-msft** [comment]
@tomkerkhove Definitely we could support GetAsync method if you need that. But for api-version, that's a mandatory parameter in a [Resource Get call](https://docs.microsoft.com/en-us/rest/api/resources/resources/get). Please check if it's possible for you to get api-version from your side.

**Comment by tomkerkhove** [comment]
That's a big hard because when using this approach it inherently means that we don't know the resource type and thus can't determine what API version to use. Also, that's a lot of bookkeeping to do to keep these up to date.

I'm wondering - Since we don't have to do that for the other operations, why do we have to do it for this operation?

**Comment by xccc-msft** [comment]
@tomkerkhove It should be wrong configuration from swagger side. We will try to fix this in current/next sprint. Before that, please just clarify again what features you need besides the GetAsync method. Thanks.

**Comment by tomkerkhove** [comment]
If I can do a GetAsync based on a resource URI which gives me the tags I'm happy! It sounds like that's what you're adding so that would be good enough for us, thanks!

**Comment by xccc-msft** [comment]
@tomkerkhove The [PR](https://github.com/Azure/azure-rest-api-specs/pull/7753) for this changed has been merged to swagger. We will update once it gets consumed in Fluent APIs. Thanks.

**Comment by tomkerkhove** [comment]
Awesome, thank you very much!

**Comment by xccc-msft** [comment]
@tomkerkhove Here is update for this issue. I have created #970 to add GetAsync method as you requested. Please feel free to review if the changes work for you. 

And for ApiVersion, here is detailed info why it's in method signature. In Azure, there are different types of resources, which are owned by different resource providers. It's easy to find out different resource providers with their own API version, such as [Cdn GET](https://docs.microsoft.com/en-us/rest/api/cdn/profiles/get)/[Resource GET](https://docs.microsoft.com/en-us/rest/api/resources/resources/get). What the GenericResources do is to allow customers to access any resource in a generic manner when they know which API version to use.

Here are two options for you to request tags per resource URI:
- Use GenericResources
```csharp
string id = "/subscriptions/GUID/resourceGroups/resource"; 
string myTagValue = resourceManager.GenericResources.Get(
                        ResourceUtils.GroupFromResourceId(id),
                        ResourceUtils.ResourceProviderFromResourceId(id),
                        ResourceUtils.ParentResourcePathFromResourceId(id),
                        ResourceUtils.ResourceTypeFromResourceId(id),
                        ResourceUtils.NameFromResourceId(id),
                        resourceManager.Inner.ApiVersion)
                        .Tags["MyTag"];
```
If the ID of resource is from another resource provider, you should initialize related manager and replace the API version here. For example, if you request a resource of CdnProfile, you should init a instance of cdnManager and put cdnManager.Inner.ApiVersion here.
- Use Azure client
```csharp
string myTagValue = azure.CdnProfiles.GetById("cdnResourceId").Tags["MyTag"]; 
```
If you know which type of resource you request for, you can use Azure client to fetch the resource directly. The good thing here is that you don't need to worry about the API version any more.

Hope the above info helps.

**Comment by tomkerkhove** [comment]
Thanks for the explanation!

So if I get it correctly, #970 removes the burden of doing what you are doing in the first example, is that correct?

**Comment by adamconnelly** [comment]
@xccc-msft just a small comment on this. In the library, you know the version of all of the resource types that you support, so to make what @tomkerkhove is trying to do in Promitor possible, would you not be able to add a utility method to get an API version from the type of resource we're requesting. That would mean we could do something like:

```csharp
var id = "/subscriptions/GUID/resourceGroups/resource"; 
var resourceType = ResourceUtils.ResourceTypeFromResourceId(id);
var resourceVersion = ResourceUtils.ResourceVersionFromType(resourceType);
```

Where `ResourceVersionFromType()` could lookup a dictionary generated from the resource types that you support in the library:

```csharp
// Generated based on the current API versions used by the library
private static readonly IDictionary<string, string> _apiVersions = new Dictionary<string, string>
{
    { "AvailabilitySet", "2017-12-01"},
    { "LoadBalancer": "2017-10-01" },
    ...
};

public static string ResourceVersionFromType(string resourceType)
{
    return _apiVersions[resourceType];
};
```

You could even alter your PR to automatically do this lookup so that we could just call `GenericResources.GetByIdAsync(resourceId)`.

In our use-case, we don't actually care what API version we're using (if I understand things correctly), so using the latest version that this library supports for each type is fine.

**Comment by tomkerkhove** [comment]
That would be a good addition indeed!

But from looking at the PR it looks like I don't have to worry about API version anymore since it's becoming an optional parameter now, right @xccc-msft ?

**Comment by xccc-msft** [comment]
@tomkerkhove Please check below for what's new in the PR:
- First, I add GetAsync method
- Second, I make the API version as optional. If you don't enter the API version, it will internally pick API version from resource manager client. If it fails, you might find options of the valid API versions from exception logs, which provided from resource provider side.

@adamconnelly Thanks for the comment. Actually here are some concerns to have such dictionary/utility:
- More than one API version will work when calling GenericResources service.
- Azure Resource Management allows people to access any resource in generic manner when they know which version to use.

At this moment, I think it would be better if you could prepare such dictionary/utility from your end.

**Comment by tomkerkhove** [comment]
Thanks, sounds like what we need!

**Comment by adamconnelly** [comment]
I'm probably just missing something because I'm not mega familiar with using the Azure API directly / this library, but if I understand it correctly, the change that @xccc-msft has made means that if no `ApiVersion` is supplied, the code will fall back to using https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Generated/ResourceManagementClient.cs#L126 (i.e. "2019-08-01").

My question is, will this ApiVersion work for all resource types supported by the library? If so then the change is exactly what we need, but if not then it's not going to work properly since we'll get errors back from the API about using an invalid ApiVersion for certain resources.

I might be misunderstanding something though.

**Comment by xccc-msft** [comment]
@adamconnelly @tomkerkhove 
I just add [new lines](https://github.com/Azure/azure-libraries-for-net/pull/970/commits/a6d21f27cf244e11da24579479ba61ca57ff3d84) as per your comments. For now, the coverage of this map is not 100%. 
The answer is you may fail when using this when you request certain type of resource which is not supported yet through our SDK. When you get errors, you may find the valid API version in the logs, which returned by service.

**Comment by adamconnelly** [comment]
@xccc-msft that sounds perfect. Thanks for taking that into account!

I'll leave Tom to answer your question since he's got more knowledge of Promitor than me.

**Comment by tomkerkhove** [comment]
LGTM, thanks!

> Additionally, can I ask if the resource ID is the only info you have from your end?

Yes, that is correct indeed!

**Comment by xccc-msft** [comment]
@tomkerkhove @adamconnelly 
Here is update with [new lines](https://github.com/Azure/azure-libraries-for-net/pull/970/commits/e7b448c051c5044c39f54ba1d6980042f47af113) to revise how we can get API versions from Providers. Thanks @weidongxu-microsoft for sharing the observation. 
```csharp
string id= "resource/id/format/data";
string resourceProvider = ResourceUtils.ResourceProviderFromResourceId(id);
var provider = resourceManager.Providers.GetByName(resourceProvider);
```
In the provider, you can find a list of `ProviderResourceType`. In each of them, you can find a list of API versions. In the SDK, now we add a method to find default API version, which we take from the first element from API version list. If you want to validate some specific version, you can just go through the list and compare. Now it should work for all types of resources. Please feel free to let me know if you have any questions.

**Comment by adamconnelly** [comment]
@xccc-msft I've left a comment on your PR. The overall approach looks fine, but I've got a small performance concern with the way the changes are implemented at the moment. I'm sure you'll know better than me whether my concern is valid or not. Thanks again for working on this!

**Comment by tomkerkhove** [comment]
Looks good to me, will give it a try and provide feedback based on that!

I presume this will be in new package version, right?

**Comment by tomkerkhove** [comment]
Ha, it's probably already being shipped 🎉

**Comment by yaohaizh** [comment]
@tomkerkhove let us know if you have any issue for using. I'm closing this issue now.
