### ISSUE TITLE
[FEATURE REQ] Support setting poolAllocationMode in Batch accounts

### ISSUE THREAD

**Issue by xenalite** [Azure/azure-libraries-for-net#722]
**Is your feature request related to a problem? Please describe.**
I cannot set poolAllocationMode property on Batch account when creating it via Fluent API.

```
var batchAccount = _context.Azure
                .BatchAccounts
                .Define(_resourceNames.BatchAccount)
                .WithRegion(_options.Region)
                .WithExistingResourceGroup(ResourceGroupName)
                .WithTags(_tags)
                .Create();
```

**Describe the solution you'd like**
Add .WithPoolAllocationMode(UserSubscription) method to the fluent API.

**Describe alternatives you've considered**
Azure SDK method of creating Batch account exists. Pool allocation mode can only be set at creation time, not update time.

**Additional context**
- Microsoft.Azure.Management.Batch.Fluent 1.23.0
- Microsoft.Azure.Management.Batch 8.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by maggiepint** [comment]
Hi, thanks for sending us this feedback. We have routed to the appropriate team for follow-up.

**Comment by bgklein** [comment]
@weshaggard historically the Batch team does not manage its own fluent libraries. The request makes sense if someone from the core team wants to take it on.

**Comment by matthchr** [comment]
Microsoft.Azure.Management.Batch.Fluent is deprecated - you should use Microsoft.Azure.Management.Batch instead.
