### ISSUE TITLE
[QUERY] How do I call Azure Instance Metadata service from a virtual machine?

### ISSUE THREAD

**Issue by manalotoj** [Azure/azure-libraries-for-net#730]
**Query/Question**
How do I call [Azure Instance Metadata service](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#instance-api) from a virtual machine using the fluent sdk?

**Comment by qub1n** [comment]
I am missing this in fluent SDK as well. It would be nice to implement it.

 We had to implemented it by ourselves.

**Comment by yaohaizh** [comment]
I'm afraid this is not doable at this time. These REST calling are exposed yet from the swagger.  
A swagger issue is logged here: https://github.com/Azure/azure-rest-api-specs/issues/4408
You can thumb up that issue for more attention, thanks. 

I would close this one. Let me know if there is any other issue.
