### ISSUE TITLE
[BUG] IStorageAccount.Tags is empty when account has tags.

### ISSUE THREAD

**Issue by jstutson** [Azure/azure-libraries-for-net#732]
**Describe the bug**
Retrieving IStorageAccounts via azure.StorageAccounts.List() or GetById() results in IStorageAccount instance with a Tags dictionary that is always empty.  The storage account being retrieved has Tags.

Might be related to: https://github.com/Azure/azure-libraries-for-net/issues/552

**To Reproduce**
Have at least one storage account with Tags.
Retrieve the storage account using any of the Azure.StorageAccounts getters.
I am authenticated as my azure AD user via Azure CLI, and I'm the owner of the subscription that I'm querying.  

***Code Snippet***
`IEnumerable<IStorageAccount> storageAccounts = azure.StorageAccounts.List();`

**Expected behavior**
storageAccount.Tags should not be empty.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS 2017
 - Version of the Library used: 
Microsoft.Azure.Management.ResourceManager.Fluent v1.23.0

**Comment by kurtzeborn** [comment]
Thanks for opening this issue!  I'm routing it to the correct team for followup.

CC: @yaohaizh

**Comment by yaohaizh** [comment]
@jstutson This issue should have been fixed on the latest v1.24.2 version. Could you try it on the latest lib version, thanks.

**Comment by yaohaizh** [comment]
The issue has been fixed. @jstutson feel free to re-open this issue if still happen on your side. Thanks.
