### ISSUE TITLE
[FEATURE REQ] Upgrade Microsoft.Azure.Management.ResourceManager.Fluent to use Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.0

### ISSUE THREAD

**Issue by kkamperschroer** [Azure/azure-libraries-for-net#736]
**Is your feature request related to a problem? Please describe.**
We are having issues using this library due to it's indirect dependency on Microsoft.IdentityModel.Clients.ActiveDirectory >= 3.14.0 && < 4.0.0.

This happens through Microsoft.Rest.ClientRuntime.Azure.Authentication: https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Microsoft.Azure.Management.ResourceManager.Fluent.csproj

**Describe the solution you'd like**
Upgrade Microsoft.Rest.ClientRuntime.Azure.Authentication to 2.4.0, which allows for newer versions of Microsoft.IdentityModel.Clients.ActiveDirectory: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/Microsoft.Rest.ClientRuntime.Azure.Authentication.csproj#L49

**Describe alternatives you've considered**
Alternatives are using other outdated libraries because we cannot upgrade.

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by weidongxu-microsoft** [comment]
Fluent.Unit.Tests -> Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.0 -> Microsoft.IdentityModel.Clients.ActiveDirectory (>= 4.3.0 && < 6.0.0) 
 Fluent.Unit.Tests -> Microsoft.Rest.ClientRuntime.Azure.TestFramework 1.7.4 -> Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.14.0 && < 4.0.0).	Fluent.Tests	D:\github\azure-libraries-for-net\Tests\Fluent.Tests\Fluent.Tests.csproj	1	

Latest ClientRuntime.Azure.TestFramework 1.7.6 still ask < 4.0.0, while Microsoft.Rest.ClientRuntime.Azure.Authentication ask > 4.3.0.

I will add 4.3.0 into AzSdk.test.reference.props.

**Comment by weidongxu-microsoft** [comment]
Also it requires Microsoft.Rest.ClientRuntime > 2.3.19 so ClientRuntime is also upgraded to 2.3.19.

**Comment by weidongxu-microsoft** [comment]
Fixed.
