### ISSUE TITLE
[FEATURE REQ] Support configuring subnet delegation

### ISSUE THREAD

**Issue by xenalite** [Azure/azure-libraries-for-net#738]
**Is your feature request related to a problem? Please describe.**
I cannot add a subnet delegation during subnet creation.

**Describe the solution you'd like**
```
virtualNetworkCreatable
  .WithAddressSpace(addressSpace)
  .DefineSubnet(subnetName)
  .WithAddressPrefix(addressSpace)
  .WithExistingNetworkSecurityGroup(nsg)
  .WithDelegation("Microsoft.Web/serverFarms")
  .Attach()
```

**Describe alternatives you've considered**
This functionality is not available in Fluent APIs, Inner management client or event in Azure SDK management client `Microsoft.Azure.Management.Network v5.0.0`.
The only way I can think of at the moment is to create a generic sub-resource.

**Additional context**
- Microsoft.Azure.Management.Network.Fluent 1.23.0
- Microsoft.Azure.Management.Network v5.0.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by maggiepint** [comment]
Thanks for this feature request. I've routed to the appropriate team for follow-up.

**Comment by allegradomel** [comment]
@xenalite, 
Thanks for bringing this to our attention - we're looking into it and will update soon.

**Comment by rtaylor72** [comment]
Any update on this?
