### ISSUE TITLE
[BUG] Unable to create NAT rules in load balancer

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-libraries-for-net#740]
**Describe the bug**
I'm unable to create a NAT rule while creating a load balancer. I can create the load balancer itself without issue, including explicitly defining a front-end, back-end, HTTP probes, TCP probes and successfully save that. However, when attempting to then update that with at NAT rule, I get an error indicating that the new NAT rule referenced by the frontend was not found - well, clearly, because I'm trying to create it.

***Exception or Stack Trace***

> Resource /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Network/loadBalancers/My_LoadBalancer/inboundNatRules/my_natRule referenced by resource /subscriptions/<subscriptionId>/resourceGroups/<resourceGroup>/providers/Microsoft.Network/loadBalancers/My_LoadBalancer/frontendIPConfigurations/myFrontend was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.

**To Reproduce**
Execute the following snippet. I attempted to replace each of my variables with primitives for this example. In my own project, the first block runs successfully and I can see the expected output in the Azure Portal. The second await block throws the above exception.

***Code Snippet***
```
var myLb = await _azure.LoadBalancers.Define("MyLoadBalancer")
	.WithRegion("East US 2")
	.WithExistingResourceGroup("myResourceGroup)
	.DefineInboundNatPool("inboundNatPoolName")
	.WithProtocol(TransportProtocol.Tcp)
	.FromExistingSubnet(vnet, "mySubnetName") //Reference your VNET
	.FromFrontendPortRange(50000,60000)
	.ToBackendPort(4567)
	.Attach()
	//Define the LB SKU
	.WithSku(LoadBalancerSkuType.Standard)
	//Explicitly define the front-end
	.DefinePrivateFrontend($"my_lbFrontend")
	.WithExistingSubnet(vnet, "mySubnetName") //Your VNET again
	.WithPrivateIPAddressStatic($"10.0.0.4")
	.Attach()
	//Explicitly define the back-end
	.DefineBackend("myLbBackendName")
	.Attach()
	//Define the HTTP probe
	.DefineHttpProbe("myHttpProbeName")
	.WithRequestPath("/")
	.WithIntervalInSeconds(5)
	.WithNumberOfProbes(2)
	.WithPort(6488)
	.Attach()
	//Define the TCP probe
	.DefineTcpProbe("myTcpProbeName)
	.WithPort(6489)
	.WithIntervalInSeconds(5)
	.WithNumberOfProbes(2)
	.Attach()
	//Define another probe
	.DefineTcpProbe("myOtherTcpProbeName")
	.WithPort(9999)
	.WithIntervalInSeconds(5)
	.WithNumberOfProbes(2)
	.Attach()
	.CreateAsync(cancellationToken);

//This runs fine up to this point on my system. The exception is thrown after this next piece:
await collectLb.Update()
	//Define the NAT rule for my other app
	.DefineInboundNatRule("my_natRule")
	.WithProtocol(TransportProtocol.Tcp)
	.FromExistingSubnet(vnet, "mySubnet") //VNET again
	.FromFrontendPort(9999)
	.ToBackendPort(9999)
	.WithIdleTimeoutInMinutes(5)
	.Attach()
	.ApplyAsync(cancellationToken);
//Exception thrown on the above
```

**Expected behavior**

I would expect that I would be able to create the NAT rule on my load balancer without incident.

**Setup (please complete the following information):**
 - OS: Windows 10 Professional x64
 - IDE : Visual Studio 2019 Professional
 - Version of the Library used
Microsoft.Azure.Management.Fluent - v1.23.0
Microsoft.Azure.Management.ResourceManager.Fluent - v1.23.0

**Additional context**
In case there was just something odd about updating the response from the initial create, I've also attempted to do a specific retrieval of this load balancer before doing an update, but encounter the same exception.

Happy to provide further context if necessary.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kurtzeborn** [comment]
Thanks for opening this bug!  I'm routing it to the appropriate team for follow up.

**Comment by weidongxu-microsoft** [comment]
Create of inbound-net-rule would fail if there is inbound-net-pool created as such.

However I am not sure whether the inbound-net-pool is done correctly or not. Usually inbound-net-pool is created with VMSS, instead of stand-alone.

**Comment by weidongxu-microsoft** [comment]
@WhitWaldo Would you delibrate more about your use case?

Load balancer with inbound-nat-pool is used with virtual mathine scale set (VMSS), with auto generated nat-rule keeping track of scaling of the VMSS.

On contrary, load balancer with inbound-nat-rule is used with usual virtual machine (or a set of usual virtual machines).

Top of that, the backend pool is configured quite differently for this 2 use cases.

I am not sure whether it is valid to mix this 2 kinds of use cases within one load balancer.

PS, sample inbound-net-pool/inbound-net-rule with a VMSS:
```
>az network lb inbound-nat-pool list --lb-name vmss2weidxulb
[
  {
    "backendPort": 3389,
    "enableFloatingIp": false,
    "enableTcpReset": false,
    "etag": "W/\"b7277a0e-f767-4073-9360-499848c8466b\"",
    "frontendIpConfiguration": {
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Network/loadBalancers/vmss2weidxulb/frontendIPConfigurations/LoadBalancerFrontEnd",
      "resourceGroup": "rg-weidxu"
    },
    "frontendPortRangeEnd": 50119,
    "frontendPortRangeStart": 50000,
    "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Network/loadBalancers/vmss2weidxulb/inboundNatPools/natpool",
    "idleTimeoutInMinutes": 4,
    "name": "natpool",
    "protocol": "Tcp",
    "provisioningState": "Succeeded",
    "resourceGroup": "rg-weidxu",
    "type": "Microsoft.Network/loadBalancers/inboundNatPools"
  }
]

>az network lb inbound-nat-rule list --lb-name vmss2weidxulb
[
  {
    "backendIpConfiguration": {
      "applicationGatewayBackendAddressPools": null,
      "applicationSecurityGroups": null,
      "etag": null,
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Compute/virtualMachineScaleSets/vmss2weidxu/virtualMachines/2/networkInterfaces/vmss2weidxuNic/ipConfigurations/vmss2weidxuIpConfig",
      "loadBalancerBackendAddressPools": null,
      "loadBalancerInboundNatRules": null,
      "name": null,
      "primary": null,
      "privateIpAddress": null,
      "privateIpAddressVersion": null,
      "privateIpAllocationMethod": null,
      "provisioningState": null,
      "publicIpAddress": null,
      "resourceGroup": "rg-weidxu",
      "subnet": null,
      "virtualNetworkTaps": null
    },
    "backendPort": 3389,
    "enableFloatingIp": false,
    "enableTcpReset": false,
    "etag": "W/\"b7277a0e-f767-4073-9360-499848c8466b\"",
    "frontendIpConfiguration": {
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Network/loadBalancers/vmss2weidxulb/frontendIPConfigurations/LoadBalancerFrontEnd",
      "resourceGroup": "rg-weidxu"
    },
    "frontendPort": 50002,
    "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Network/loadBalancers/vmss2weidxulb/inboundNatRules/natpool.2",
    "idleTimeoutInMinutes": 4,
    "name": "natpool.2",
    "protocol": "Tcp",
    "provisioningState": "Succeeded",
    "resourceGroup": "rg-weidxu",
    "type": "Microsoft.Network/loadBalancers/inboundNatRules"
  },
  {
    "backendIpConfiguration": {
      "applicationGatewayBackendAddressPools": null,
      "applicationSecurityGroups": null,
      "etag": null,
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Compute/virtualMachineScaleSets/vmss2weidxu/virtualMachines/3/networkInterfaces/vmss2weidxuNic/ipConfigurations/vmss2weidxuIpConfig",
      "loadBalancerBackendAddressPools": null,
      "loadBalancerInboundNatRules": null,
      "name": null,
      "primary": null,
      "privateIpAddress": null,
      "privateIpAddressVersion": null,
      "privateIpAllocationMethod": null,
      "provisioningState": null,
      "publicIpAddress": null,
      "resourceGroup": "rg-weidxu",
      "subnet": null,
      "virtualNetworkTaps": null
    },
    "backendPort": 3389,
    "enableFloatingIp": false,
    "enableTcpReset": false,
    "etag": "W/\"b7277a0e-f767-4073-9360-499848c8466b\"",
    "frontendIpConfiguration": {
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Network/loadBalancers/vmss2weidxulb/frontendIPConfigurations/LoadBalancerFrontEnd",
      "resourceGroup": "rg-weidxu"
    },
    "frontendPort": 50003,
    "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Network/loadBalancers/vmss2weidxulb/inboundNatRules/natpool.3",
    "idleTimeoutInMinutes": 4,
    "name": "natpool.3",
    "protocol": "Tcp",
    "provisioningState": "Succeeded",
    "resourceGroup": "rg-weidxu",
    "type": "Microsoft.Network/loadBalancers/inboundNatRules"
  }
]
```

**Comment by WhitWaldo** [comment]
@weidongxu-microsoft 
Essentially, I was looking to avoid using an ARM template to set up the same and instead attempting to use the .NET management library.

In this case, I would have created the networking first (per the above code) prior to creating the VMSS since the latter would have a dependency on the former, thus the stand-alone portions.

While I'm no longer exposing this port externally and thus cannot look at what I wound up doing via ARM, the larger issue here for me is that the library allowed and guided me to this configuration despite it not being something you think should be accurate (thus the exception, I expect).

**Comment by weidongxu-microsoft** [comment]
@WhitWaldo 
Got your point. So your goal is to create load balancer over VMSS via .NET management library. We will find a solution and put to sample (if the solution is not intuitive), and optionally adjust API to make it more apparent.

**Comment by xccc-msft** [comment]
Hi @WhitWaldo could you please share more details with exception logs for analyzing this issue? Thanks.

**Comment by yaohaizh** [comment]
@WhitWaldo could you provide exception details or http  REST call logs for us to diagnose?

**Comment by WhitWaldo** [comment]
@yaohaizh Unfortunately, I don't appear to have a versioned copy of this solution and this particular piece has been substantially rewritten. The only thing I can point you to is the original ticket up there.
