### ISSUE TITLE
[FEATURE REQ] Richer support for VMSS custom extension settings

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-libraries-for-net#741]
**Is your feature request related to a problem? Please describe.**
When creating a virtual machine scale set, the current fluent API for adding custom extensions allows me to specify protected and public settings, either as a single key/value pair or as a dictionary. Unfortunately, some examples, such as those used by Service Fabric nest these public settings, as in the following example from their ARM template:

```
{
	"name": "[concat(parameters('vmNodeType0Name'),'_ServiceFabricNode')]",
	"properties": {
		"type": "ServiceFabricNode",
		"autoUpgradeMinorVersion": true,
		"protectedSettings": {
			"StorageAccountKey1": "[listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('supportLogStorageAccountName')),'2015-05-01-preview').key1]",
			"StorageAccountKey2": "[listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('supportLogStorageAccountName')),'2015-05-01-preview').key2]"
		},
		"publisher": "Microsoft.Azure.ServiceFabric",
		"settings": {
			"clusterEndpoint": "[reference(parameters('clusterName')).clusterEndpoint]",
			"nodeTypeRef": "[parameters('vmNodeType0Name')]",
			"dataPath": "D:\\\\SvcFab",
			"durabilityLevel": "Bronze",
			"enableParallelJobs": true,
			"nicPrefixOverride": "[parameters('subnet0Prefix')]",
			"certificate": {
				"thumbprint": "[parameters('certificateThumbprint')]",
				"x509StoreName": "[parameters('certificateStoreValue')]"
			}
		},
		"typeHandlerVersion": "1.1"
	}
}
```

Today, I don't see a way to create that list of public settings using the existing custom extension API in these management libraries.

**Describe the solution you'd like**
I'd instead like the option to provide a JSON serialized object to the API that would already handle all the necessary nesting required. For those that can use a string-based key/value pair, the option remains, but for those that want to do something more elaborate, we have that option to handle it independently and pass it in as an already-formed string. Ideally, this would be an option to pass into either the protected or public settings.

**Describe alternatives you've considered**
I can do these nested extension configurations with an ARM template, as indicated in the sample template above (pulled from an ARM template generated from the Azure portal, no changes made).

**Additional context**
Unless the current string-based key/value pair entry supports entering boolean values as "true" or "false", they also aren't supported in the current fluent management API.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by Drewm3** [comment]
Closing old issues with nobody assigned to them.
