### ISSUE TITLE
Infinite Loop when receiving a 400:BadRequest updating AppService Hostname Bindings

### ISSUE THREAD

**Issue by oatsoda** [Azure/azure-libraries-for-net#744]
Updating an AppService Hostname binding which fails due to a 400:BadRequest causes an infinite loop.  This is using a custom third-party domain.

No Exception is logged, it just hangs/loops forever.

    var site = await client.AppServices.WebApps.GetByIdAsync(appServiceResourceId);
    await site.Update()
        .DefineHostnameBinding()
        .WithThirdPartyDomain(domain)
        .WithSubDomain(hostname)
        .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
        .Attach()
        .ApplyAsync();

Screenshot of Application Insights telemetry:

![image](https://user-images.githubusercontent.com/3919587/61704533-cf0e3000-ad3b-11e9-8d57-ee668233b09e.png)
ad-infinitum...

The REST endpoints it is calling are:

> PATCH /subscriptions/{sub}/resourceGroups/{resgrp}/providers/Microsoft.Web/sites/{appservice} (returns 200)
> PUT /subscriptions/{sub}/resourceGroups/{resgrp}/providers/Microsoft.Web/sites/{appservice}/hostNameBindings/{fqdn-thirdparty} (returns 400)

(in this specific case, the 400 is caused by the DNS CNAME not having been set up yet.  I have seen it for other reasons also, though)
 
Running on:
Azure Functions
NetCore 2.2

Correcting the mistake to avoid the 400:BadRequest and everything works fine.

**Comment by oatsoda** [comment]
I've realised that I have a retry policy enabled, but I don't see why it would be retrying a 400, or why it would be retrying the PATCH also...

        m_RetryPolicy = new ExponentialBackoffRetryStrategy(
             6,
             TimeSpan.FromMilliseconds(1000),
             TimeSpan.FromMilliseconds(30000),
             TimeSpan.FromMilliseconds(1000)
             );

        public IAzure GetClient()
        {
            return Azure
                .Configure()
                .WithRetryPolicy(new RetryPolicy(new HttpStatusCodeErrorDetectionStrategy(), m_RetryPolicy))
                .Authenticate(m_AzureCredentials)
                .WithDefaultSubscription();
        }

**Comment by maggiepint** [comment]
Thanks for this feedback - I have routed to the appropriate team for follow up.

**Comment by ChenTanyi** [comment]
@oatsoda Sorry for late reply. The infinite loop has been fixed in v1.27.2. You can try a version after it. Thanks!
If you still meet the problem, feel free to re-open it.
