### ISSUE TITLE
How to expand the OS Disk

### ISSUE THREAD

**Issue by Matt-Westphal** [Azure/azure-libraries-for-net#748]
**Query/Question**
We are creating VMs but they need to have an OS disk greater than 127GB. I believe we have the code correct but it throws exceptions and we can't find any samples that are doing the same thing

***Why is this not a Bug or a feature Request?***
Here's the code that we're using. Looks like it should work but it throws and exception with the message: "Cannot resize disk GPVERISIZE2_OSDisk while it is attached to running.. ". We have set break points to confirm that the powerstate is stopped so we aren't sure where to go with this next.

IAzure azure = azureBuilder.LoginAzure(SubscriptionID);

IVirtualMachine vm = azure.VirtualMachines.GetByResourceGroup(labContext.ResourceGroupName, vmName);

IDisk disk = azure.Disks.GetById(vm.OSDiskId);
vm.PowerOff();

var powerState = vm.PowerState;
disk.Update().WithSizeInGB(200).Apply();
vm.Start();

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : Visual Studio 2019
 - Version of the Library used: 1.20.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Query Added
- [x] Setup information Added

**Comment by yaohaizh** [comment]
Could you try `vm.Deallocate()` to see whether this fit your requirement? Thanks.

**Comment by Gary-Peluso** [comment]
Thank you.  That fixes it.  I noticed the tooltip doc for Deallocate() says "shuts down the VM and releases resources."

**Comment by yaohaizh** [comment]
Yep, power off & deallocate have some differences. Make sure you understand the deallocate meaning (which might release publish/internal IP, some resources) and make sure this API will impact your business. Thanks. You can find more info from the web about difference.
