### ISSUE TITLE
[BUG] Outputs for DeploymentImpl are empty and never set

### ISSUE THREAD

**Issue by shreyagarwal1991** [Azure/azure-libraries-for-net#751]
**Describe the bug**
The issue is that after calling CreateAsync on a Arm template deployment, the return object always has empty Outputs even though same template has outputs in powershell execution.

I went through your code and seems like you execute the code to create, but never process the response in order to set the Outputs or even the ProvisioningState.

**To Reproduce**
Use simple code like the following with a template that has Outputs defined. 

***Code Snippet***
var deployment = await client.Deployments
                        .Define(deploymentName)
                        .WithExistingResourceGroup(input.ResourceGroupName)
                        .WithTemplate(input.TemplateJson)
                        .WithParameters(input.ParametersJson)
                        .WithMode(DeploymentMode.Incremental)
                        .CreateAsync();

**Expected behavior**
Expect the return object to have Outputs filled in.

**Setup (please complete the following information):**
 Windows/VS

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x ] Bug Description Added
- [ x ] Repro Steps Added
- [ x ] Setup information Added

**Comment by yaohaizh** [comment]
This has been fixed on the latest SDK and will close it now. Feel free to re-open it if still persist.
