### ISSUE TITLE
[FEATURE REQ]Expose SqlDatabaseInner and listSqlDatabase in CosmosDB

### ISSUE THREAD

**Issue by yaohaizh** [Azure/azure-libraries-for-net#752]
This is still wrap in inner, need expose them.
 https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/CosmosDB/Generated/DatabaseAccountsOperations.cs#L2659

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-libraries-for-net/pull/756
