### ISSUE TITLE
Intermittent exception with the error message - "The operation was canceled"

### ISSUE THREAD

**Issue by huajunzhao** [Azure/azure-libraries-for-net#763]
Hi,
We used the below code to deployment the ARM template, but intermittently saw the exception caught with the error message - “the operation was cancelled”, 

 public async Task<ProvisionStageOutput> Run()
        {
            string errorMessage = string.Empty;
            var status = TestStepStatus.Succeeded;
            string type = "arm-template";
            var provisionStageOutput = new ProvisionStageOutput();

            try
            {
                var r = await CheckResourceProvider();
                if (r != null)
                {
                    provisionStageOutput.Resources.Add(r);
                    return provisionStageOutput;
                }

                logHelper.Information("Deploying ARM template...");
                var armTemplateString = File.ReadAllText(Path.Combine(context.TestRunContext.CurrentDirectory, "Templates", context.TemplateName));
                var templateJson = JObject.Parse(armTemplateString);
                await context.TestRunContext.AzureClient.Deployments.Define(context.DeploymentName)
                        .WithExistingResourceGroup(context.ResourceGroup)
                        .WithTemplate(templateJson)
                        .WithParameters(templateParams)
                        .WithMode(DeploymentMode.Incremental)
                        .CreateAsync();
            }
            catch (CloudException ex)
            {
                logHelper.Error(ex.Response.Content);
                errorMessage = ex.Response.Content;
                status = TestStepStatus.Failed;
                provisionStageOutput.Resources.Add(new ProvisonStepOutput()
                {
                    Id = Id,
                    Status = status,
                    ErrorMessage = errorMessage,
                    ResourceGroup = context.ResourceGroup
                });
                return provisionStageOutput;
            }
            catch (Exception ex)
            {
                logHelper.Error(ex.Message);
                errorMessage = ex.Message;
                status = TestStepStatus.Failed;
                provisionStageOutput.Resources.Add(new ProvisonStepOutput()
                {
                    Id = Id,
                    Status = status,
                    ErrorMessage = errorMessage,
                    ResourceGroup = context.ResourceGroup
                });
                return provisionStageOutput;
            }

            var deployment = await context.TestRunContext.AzureClient.Deployments.GetByResourceGroupAsync(context.ResourceGroup, context.DeploymentName);
            if (deployment != null)
            {
                var operations = await deployment.DeploymentOperations.ListAsync();
                foreach (var dp in operations)
                {
                    if (dp.TargetResource != null)
                    {
                        if (dp.StatusMessage != null)
                        {
                            errorMessage = dp.StatusMessage.ToString();
                        }

                        TestStepStatus ts;
                        if (Enum.TryParse(dp.ProvisioningState, true, out ts))
                        {
                            status = ts;
                        }
                        else
                        {
                            status = TestStepStatus.InComplete;
                        }

                        provisionStageOutput.Resources.Add(new ProvisonStepOutput()
                        {
                            Id = dp.TargetResource.Id,
                            Status = status,
                            ErrorMessage = errorMessage,
                            ResourceGroup = context.ResourceGroup,
                            ResourceName = dp.TargetResource.ResourceName,
                            ResourceType = dp.TargetResource.ResourceType,
                            Type = type
                        });
                    }
                }
            }
            return provisionStageOutput;
        }

I can see 2 cases:
-	The deployment was successful
-	No any deployment in the resource group.

Nuget package:

microsoft.azure.management.fluent 1.22.2

For your investigation:
Subscription Id: dfba1966-11a1-444b-a6bf-10f70f247a4e
Resource Group: RVT_10_201908132132325855, RVT_11_201908132132324295 - there is no any deployment 
We don't have the resource group with a successful deployment now.

Could you please help check the log in your back-end if there's any issue or if there's is any bug in the above code?

Thanks,
Kevin

**Comment by weidongxu-microsoft** [comment]
Hello @huajunzhao 

If possible would you provide a sample of the template, or a simplifed version? We'd like to know what is involved in the deployment.

Also would you enable the log (`Azure.Configure().WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)...`) and send us the failed operation (you can redact the json if necessary)?

E.g. here is log from my operation (success):

```
Request: PUT https://management.azure.com/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourcegroups/rg-weidxu/providers/Microsoft.Resources/deployments/deployment-weidxu?api-version=2017-05-10
  headers:
    x-ms-client-request-id : a5268906-7e97-40e4-80d6-5bb306e1a7c7
    Accept-Language : en-US
    Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNTY1OTQ1NTYxLCJuYmYiOjE1NjU5NDU1NjEsImV4cCI6MTU2NTk0OTQ2MSwiYWlvIjoiNDJGZ1lIQzY3K3d1azg3dXdQTExyYXo2dUUwSEFBPT0iLCJhcHBpZCI6IjVhZTE1NmQ0LTJhMTAtNDdkYy1hNWM3LTg5ZmE0Y2QzMTNjZSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0Ny8iLCJvaWQiOiI0NzRkMTlhZi0yYzgxLTQ3ODYtOTYyMi1lNTYyNWYyNjBiNWMiLCJzdWIiOiI0NzRkMTlhZi0yYzgxLTQ3ODYtOTYyMi1lNTYyNWYyNjBiNWMiLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJ1dGkiOiJrMDZRWHhhZHdVaXVKUFNYeklBTEFBIiwidmVyIjoiMS4wIn0.4rjpl7cdEHMutn-B9v03bFMuePof_Qg8VM1aR20MnNzwyJopEz45JsUL5J1MF3dLk5b5kDg-AIUwhksmyh4LEJCvwHaynGt6iaLQPgdyUBLhRa4Rux1hCEK0W6Wg7ugQTsza1o5I7fkv-LVuLq9mpCnI7tFu4ZQx8vMqLkLC3lWVYB3wrRSbD9wD8cgw_4bQGBnonOJ_qVG54kN4pY4G5R6ZUsRKmjHftPr3ZYxZCWTBpITgsRUZJ6UGUBTkcItcAEfpula9mdgJprDh-9OK_Bre2_N0eRmKKOhfajEqmw44HY3bpm9ITfxdGlW2NAC8Pz2pH76uXY2-exUg8XO1YA
    User-Agent : FxVersion/4.6.27817.01 OSName/Windows OSVersion/Microsoft.Windows.10.0.18362. Microsoft.Azure.Management.ResourceManager.Fluent.ResourceManagementClient/1.0.0.60 MacAddressHash/5b986dbc01e2cd9262cdc8765199485ab440ab932e80985aff873a3788750edd
  body: {
  "properties": {
    "template": {
      "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
      "contentVersion": "1.0.0.1",
      "parameters": {
        "storageName": {
          "type": "string"
        }
      },
      "variables": {},
      "resources": [
        {
          "type": "Microsoft.Resources/deployments",
          "apiVersion": "2018-05-01",
          "name": "storageDeployment",
          "resourceGroup": "rg-weidxu",
          "properties": {
            "mode": "Incremental",
            "template": {
              "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "parameters": {},
              "variables": {},
              "resources": [
                {
                  "type": "Microsoft.Storage/storageAccounts",
                  "apiVersion": "2017-10-01",
                  "name": "[parameters('storageName')]",
                  "location": "eastus",
                  "kind": "StorageV2",
                  "sku": {
                    "name": "Standard_LRS"
                  }
                }
              ],
              "outputs": {}
            }
          }
        }
      ],
      "outputs": {}
    },
    "parameters": {
      "storageName": {
        "value": "saweidxu"
      }
    },
    "mode": "Incremental"
  }
}
Response:
  headers:
    Cache-Control : no-cache
    Pragma : no-cache
    Azure-AsyncOperation : https://management.azure.com/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourcegroups/rg-weidxu/providers/Microsoft.Resources/deployments/deployment-weidxu/operationStatuses/08586356610202403611?api-version=2017-05-10
    x-ms-ratelimit-remaining-subscription-writes : 1199
    x-ms-request-id : 6f3d93e5-932d-46c6-9a23-8183d7b85383
    x-ms-correlation-request-id : 6f3d93e5-932d-46c6-9a23-8183d7b85383
    x-ms-routing-request-id : SOUTHEASTASIA:20190816T085750Z:6f3d93e5-932d-46c6-9a23-8183d7b85383
    Strict-Transport-Security : max-age=31536000; includeSubDomains
    X-Content-Type-Options : nosniff
    Date : Fri, 16 Aug 2019 08:57:49 GMT
{
  "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Resources/deployments/deployment-weidxu",
  "name": "deployment-weidxu",
  "properties": {
    "templateHash": "2942478700203039005",
    "parameters": {
      "storageName": {
        "type": "String",
        "value": "saweidxu"
      }
    },
    "mode": "Incremental",
    "provisioningState": "Accepted",
    "timestamp": "2019-08-16T08:57:47.8832105Z",
    "duration": "PT2.6459581S",
    "correlationId": "6f3d93e5-932d-46c6-9a23-8183d7b85383",
    "providers": [
      {
        "namespace": "Microsoft.Resources",
        "resourceTypes": [
          {
            "resourceType": "deployments",
            "locations": [
              null
            ]
          }
        ]
      }
    ],
    "dependencies": []
  }
}


Request: GET https://management.azure.com/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourcegroups/rg-weidxu/deployments/deployment-weidxu/operations?api-version=2017-05-10
  headers:
    x-ms-client-request-id : 3747ec21-4b8c-481c-a82f-26b6dfe06976
    Accept-Language : en-US
    Authorization : Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNTY1OTQ0OTEzLCJuYmYiOjE1NjU5NDQ5MTMsImV4cCI6MTU2NTk0ODgxMywiYWlvIjoiNDJGZ1lGaHVWdkl4NkU1VjZhRW05YS9HdXc5NEFBQT0iLCJhcHBpZCI6IjVhZTE1NmQ0LTJhMTAtNDdkYy1hNWM3LTg5ZmE0Y2QzMTNjZSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0Ny8iLCJvaWQiOiI0NzRkMTlhZi0yYzgxLTQ3ODYtOTYyMi1lNTYyNWYyNjBiNWMiLCJzdWIiOiI0NzRkMTlhZi0yYzgxLTQ3ODYtOTYyMi1lNTYyNWYyNjBiNWMiLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJ1dGkiOiJZQUlFeUx5TzBraWdRS1hxMldZREFBIiwidmVyIjoiMS4wIn0.HUITefqO0BkV-E1jJZkeYgKAay2CSz0ar84lCmBbPnQLt4-Zd6vAvII3o_eCAFKR8QtP5Kzs-4yRqQpZ_aIb2qXlTGpqD2VBtvP_AtHVBh3TpuuDcOculVwXECJG58uxGVBp84P8T57CaGAV3gDCqLcwbB6czNnaQzVH1Lom9M6__t_aZzjb74tDZU89TDF96N-Pu_DCa2UVxDCU17IsEla6D5oYWf5MM0jGVmymwPswNGRQDhqQCa5zwp2KI0HyGSuMv0V_n8YV0eKfu1YXUcN959q_BfLBpwchX4rI-Kt9nKZnUPU5QAvxvr9aVHqacxfuTXb7xZulkjWY_QrDsg
    User-Agent : FxVersion/4.6.27817.01 OSName/Windows OSVersion/Microsoft.Windows.10.0.18362. Microsoft.Azure.Management.ResourceManager.Fluent.ResourceManagementClient/1.0.0.60 MacAddressHash/5b986dbc01e2cd9262cdc8765199485ab440ab932e80985aff873a3788750edd
Response:
  headers:
    Cache-Control : no-cache
    Pragma : no-cache
    x-ms-ratelimit-remaining-subscription-reads : 11990
    x-ms-request-id : f6788c98-d8aa-4dc3-a43c-681278512ccb
    x-ms-correlation-request-id : f6788c98-d8aa-4dc3-a43c-681278512ccb
    x-ms-routing-request-id : SOUTHEASTASIA:20190816T084805Z:f6788c98-d8aa-4dc3-a43c-681278512ccb
    Strict-Transport-Security : max-age=31536000; includeSubDomains
    X-Content-Type-Options : nosniff
    Date : Fri, 16 Aug 2019 08:48:04 GMT
{
  "value": [
    {
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Resources/deployments/deployment-weidxu/operations/1843754B82F2C11B",
      "operationId": "1843754B82F2C11B",
      "properties": {
        "provisioningOperation": "Create",
        "provisioningState": "Succeeded",
        "timestamp": "2019-08-16T08:47:50.200511Z",
        "duration": "PT46.5816041S",
        "trackingId": "2fd85393-a0b2-4d3d-9f59-e038521af391",
        "serviceRequestId": "d08247d8-6323-4970-8488-89629459251b",
        "statusCode": "OK",
        "targetResource": {
          "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Resources/deployments/storageDeployment",
          "resourceType": "Microsoft.Resources/deployments",
          "resourceName": "storageDeployment"
        }
      }
    },
    {
      "id": "/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/rg-weidxu/providers/Microsoft.Resources/deployments/deployment-weidxu/operations/08586356616687141623",
      "operationId": "08586356616687141623",
      "properties": {
        "provisioningOperation": "EvaluateDeploymentOutput",
        "provisioningState": "Succeeded",
        "timestamp": "2019-08-16T08:47:50.3102408Z",
        "duration": "PT0.0488248S",
        "trackingId": "2eeeb5cd-10a9-407a-8d47-213d3bc378c9",
        "statusCode": "OK",
        "statusMessage": null
      }
    }
  ]
}
```

**Comment by huajunzhao** [comment]
We just use the arm templates from  https://github.com/Azure/azure-quickstart-templates 

Are there any deployment log in your end you can investigated?

**Comment by huajunzhao** [comment]
I can repro the issue even locally now, and the exception caught.

The inner exception is 
ErrorCode 995
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.

Do you have any insights?

**Comment by yaohaizh** [comment]
@huajunzhao 
Could you attach your stack trace here? 

And if possible, could you open the log options as @weidongxu-microsoft mentioned, and paste the raw REST request information for us to diagnose.

**Comment by huajunzhao** [comment]
Today it happens earlier at CheckResourceProvider before calling the below

await context.TestRunContext.AzureClient.Deployments.Define(context.DeploymentName)
                    .WithExistingResourceGroup(context.ResourceGroup)
                    .WithTemplate(templateJson)
                    .WithParameters(templateParams)
                    .WithMode(DeploymentMode.Incremental)
                    .CreateAsync();

below the code  of the CheckResourceProvider()


        private async Task<ProvisonStepOutput> CheckResourceProvider()
        {
            var rm = context.TestRunContext.AzureClient.ManagementClients.Where(c => c is IResourceManagementClient).DefaultIfEmpty(null)
                .FirstOrDefault() as IResourceManagementClient;
            if (rm == null)
            {
                logHelper.Error("Cannot get ResourceManagementClient.");

                return new ProvisonStepOutput()
                {
                    Id = Id,
                    Status = TestStepStatus.Failed,
                    ErrorMessage = "Cannot get ResourceManagementClient.",
                    ResourceGroup = context.ResourceGroup,
                };
            }
            else
            {
                var providers = (await rm.Providers.ListWithHttpMessagesAsync()).Body;

                // TODO: Check version
                var rs =
                    from inner in providers
                     from value in inner.ResourceTypes
                     select $"{inner.NamespaceProperty}/{value.ResourceType}".ToLower();
                var rsSet = new HashSet<string>(rs);
                var armTemplateString = File.ReadAllText(Path.Combine(context.TestRunContext.CurrentDirectory, "Templates", context.TemplateName));
                dynamic result = Newtonsoft.Json.JsonConvert.DeserializeObject(armTemplateString);
                foreach (var resource in result.resources)
                {
                    try
                    {
                        string x = resource.type;
                        if (!rsSet.Contains(x.ToLower()))
                        {
                            logHelper.Error($"Resource type {x} is not registered.");
                            return new ProvisonStepOutput()
                            {
                                Id = Id,
                                Status = TestStepStatus.Failed,
                                ErrorMessage = $"Resource type {x} is not registered.",
                                ResourceGroup = context.ResourceGroup,
                            };
                        }
                        else
                        {
                            logHelper.Debug($"Resource type {x} is registered.");
                        }
                    }
                    catch (RuntimeBinderException)
                    {
                        // Ignored deliberately
                    }
                }
            }

            return null;
        }

The Error message: The operation was canceled.
Inner exception: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.
Call Stack:
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ProviderRegistrationDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.UserAgentDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ProvidersOperations.ListWithHttpMessagesAsync(Nullable`1 top, String expand, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.DCValidation.TestRunner.Core.TestSteps.DeployTemplateStep.CheckResourceProvider() in C:\Workspace\onebranch\AzureGlobal-DCValidation2\src\TestRunner\TestRunner.Core\TestSteps\DeployTemplateStep.cs:line 147
   at Microsoft.Azure.DCValidation.TestRunner.Core.TestSteps.DeployTemplateStep.Run() in C:\Workspace\onebranch\AzureGlobal-DCValidation2\src\TestRunner\TestRunner.Core\TestSteps\DeployTemplateStep.cs:line 42

@yaohaizh

**Comment by weidongxu-microsoft** [comment]
At present (2019 Aug. 19th), it takes /prividers API several minutes to get response. Previously it took only about 10 seconds.

Currently try to unblock via setting a longer timeout in HttpClient.
`(rm as IAzureClient).HttpClient.Timeout = TimeSpan.FromMinutes(5);`

Endpoint is `GET https://management.azure.com/subscriptions/89545946-408f-41c7-8a4c-2f094f25fc2d/providers?api-version=2017-05-10`
`az provider list` is similar on CLI (api-version=2018-05-01 instead). And it also take a few read timeout and retry to finally get response after about 5 minutes.

Service team please take a look.

**Comment by weidongxu-microsoft** [comment]
[provider_list.log](https://github.com/Azure/azure-libraries-for-net/files/3514195/provider_list.log)

Log of `az provider list` failed after retries.

**Comment by weidongxu-microsoft** [comment]
Service seems back to normal.

**Comment by jjxtra** [comment]
Seeing this on Linux but not Windows with azure tables insertorreplace requests... weird...
