### ISSUE TITLE
Add the namespace selection in Monitor Metric List method

### ISSUE THREAD

**Issue by PerninManon** [Azure/azure-libraries-for-net#773]
I'm not able to list Monitor Metrics that are on a specific metric namespace. For example, some Application Insights metrics are available in Monitor into the metric namespace "Azure.ApplicationInsights".

For now, the method "ListByResourceAsync" in MetricDefinitionsImpl set the metricnamespace to null. It's not possible to choose the namespace. (https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Monitor/MetricDefinitionsImpl.cs#L45) 

Would it be possible to update this method in order to be able to select the namespace we want ?

**Comment by Dalubash** [comment]
@selvasingh Routing to the owner for this SDK.

**Comment by weidongxu-microsoft** [comment]
@PerninManon Thanks for the feedback. We are updating monitor lib in this sprint for 1.27. I will try to cover this issue as well.

**Comment by weidongxu-microsoft** [comment]
support in 1.27 (Oct. 11th)
