### ISSUE TITLE
[BUG] Property DestinationAddressPrefixes in NetworkSecurityRuleImpl class returns source prefixes instead of destination ones

### ISSUE THREAD

**Issue by oldnavy1989** [Azure/azure-libraries-for-net#786]
**Describe the bug**
Property DestinationAddressPrefixes in NetworkSecurityRuleImpl class returns source prefixes instead of destination ones.
https://github.com/Azure/azure-libraries-for-net/blob/df9f29daa4116fd7e5c403635c8634d5d4b4ea4a/src/ResourceManagement/Network/NetworkSecurityRuleImpl.cs#L96

**Expected behavior**
Expected to get destination address prefixes

**Comment by ChenTanyi** [comment]
Will fix in 1.27.0
