### ISSUE TITLE
Exists something like Azure Region "ID"?

### ISSUE THREAD

**Issue by MiroslavVanicky** [Azure/azure-libraries-for-net#795]
Hi,

when listing regions using Microsoft.Azure.Management.ResourceManager.Fluent.Core it provide s list of regions containing Name="**westcentralus**", DisplayName="**US West Central**".

I am reading Azure RateCard prices from JSON stream (https://docs.microsoft.com/en-us/previous-versions/azure/reference/mt219005(v=azure.100)). JSON contains info about region this way: "MeterRegion": "**US West Central**". It looks like some "display name", not some region "id". 

**Is there anything like global Azure region ID?**
Name="**westcentralus**" looks like it is some king of ID, but is it something Microsoft/Azure official?

Thank You

**Comment by weidongxu-microsoft** [comment]
`Name="westcentralus"` should be fine.

In this repository, you can refer to `Microsoft.Azure.Management.ResourceManager.Fluent.Core.Region`.
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Region.cs

**Comment by MiroslavVanicky** [comment]
Name="westcentralus" looks like usable region identificator. It is kind of "only yours" identificator, nothing officialy globally accepted by Microsoft? 

Because RateCard data contains other region identification ("US West Central").

**Comment by weidongxu-microsoft** [comment]
It is resource region used for almost all of Azure.

However MeterRegion in billing/comerce could be different.

You might want to raise issue on doc github https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/billing/billing-usage-rate-card-overview.md

Currently this repo does not support RateCard feature.

**Comment by MiroslavVanicky** [comment]
Thank You
