### ISSUE TITLE
Not all regions listed in Microsoft.Azure.Management.ResourceManager.Fluent.Core.Region

### ISSUE THREAD

**Issue by MiroslavVanicky** [Azure/azure-libraries-for-net#796]
Hi,

when looking into Microsoft.Azure.Management.ResourceManager.Fluent.Core.Region there are public fields for regions (eg, public static readonly Region USWest2 = new Region("westus2")).

Why are there some regions missing, eg Switzerland regions? (List is not beeing synchronized with current Azure regions?)

Thank You

**Comment by weidongxu-microsoft** [comment]
Fixed in 1.27.1, to be released on Oct. 25th.
