### ISSUE TITLE
ACI Fluent API does not support --secrets and --secrets-mount-path

### ISSUE THREAD

**Issue by CoenraadS** [Azure/azure-libraries-for-net#798]
Using AZ CLI I can make ACI containers with a tmpfs mount using `--secrets` and `--secrets-mount-path`

**Describe the solution you'd like**
I would like to do the same via fluent API. Bonus if you also add `--no-wait`

**Comment by ChenTanyi** [comment]
Hi @CoenraadS , we have checked about this feature. 

The `WithSecrets` API could be found in https://github.com/Azure/azure-libraries-for-net/blob/ab4c3de1af051d0f70093445dcac76df262184b0/src/ResourceManagement/ContainerInstance/Domain/ContainerGroup/Definition/IDefinition.cs#L998
Could you take a look whether it meets your requirement? We would implement the `WithSecretsMountPath` later.

You could use `CreateAsync` or `ApplyAsync` to do a creation or updating asynchronously in background like `--no-wait`.

**Comment by CoenraadS** [comment]
Thanks I will check again. I don't attach volumes which is maybe why I couldn't find it. In the CLI it doesn't require a volume, it is a tmpfs ramdisk after all.

As for `CreateAsync`, it waits until the container is provisioned (which can take a long time, and it throws exception if provisioning failed), while I feel `--no-wait` doesn't do this (but can't verify its behavior)

**Comment by ChenTanyi** [comment]
For `CreateAsync`, it doesn't wait for the deployment completed. You can check if it is completed whenever you want, like:
![image](https://user-images.githubusercontent.com/15213781/65409489-6e25d580-de1a-11e9-944d-d245825ef2c9.png)

Actually, since it is running in another thread, you should better not end the program before it complete. Otherwise, it may behave differently due to some deployment having not sent to service. 

I think `--no-wait` also sends the deployment in background and doesn't return the result. (I didn't use it, may be wrong.)

**Comment by nickzhums** [comment]
@CoenraadS Does the comments above resolve your issue? Let us know. Thanks

**Comment by ChenTanyi** [comment]
@CoenraadS Maybe there are some mistakes in my `--no-wait` explanation.
There is no `--no-wait` in Fluent API now.
As a work around, it can be used as:
```csharp
// Normal Create
            azure.KubernetesClusters.Define(aksName)
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .WithLatestVersion()
                .WithRootUsername(username)
                .WithSshKey(sshKey)
                .WithServicePrincipalClientId(credentials.ClientId)
                .WithServicePrincipalSecret(clientSecret)
                .DefineAgentPool(agentPoolName)
                    .WithVirtualMachineSize(Microsoft.Azure.Management.ContainerService.Fluent.Models.ContainerServiceVMSizeTypes.StandardD2V2)
                    .WithAgentPoolVirtualMachineCount(1)
                    .WithVirtualNetwork(virtualNetwork.Id, akssubnetName)
                    .Attach()
                .WithDnsPrefix(dnsPrefixName)
                .DefineNetworkProfile
                    .WithNetworkPlugin(NetworkPlugin.Azure)
                    .Attach()
                .CreateAsync();


// Create with --no-wait
            var aks = azure.KubernetesClusters.Define(aksName)
                .WithRegion(region)
                .WithExistingResourceGroup(rgName)
                .WithLatestVersion()
                .WithRootUsername(username)
                .WithSshKey(sshKey)
                .WithServicePrincipalClientId(credentials.ClientId)
                .WithServicePrincipalSecret(clientSecret)
                .DefineAgentPool(agentPoolName)
                    .WithVirtualMachineSize(Microsoft.Azure.Management.ContainerService.Fluent.Models.ContainerServiceVMSizeTypes.StandardD2V2)
                    .WithAgentPoolVirtualMachineCount(1)
                    .WithVirtualNetwork(virtualNetwork.Id, akssubnetName)
                    .Attach()
                .WithDnsPrefix(dnsPrefixName)
                .DefineNetworkProfile
                    .WithNetworkPlugin(NetworkPlugin.Azure)
                    .Attach();

            var inner = (aks as IKubernetesCluster).Inner;

            azure.KubernetesClusters.Inner.BeginCreateOrUpdateAsync(rgName, aksName, inner).Wait();
```
