### ISSUE TITLE
[FEATURE REQ] create service bus subscription with sessions enabled

### ISSUE THREAD

**Issue by ElectiveRob** [Azure/azure-libraries-for-net#799]
**Is your feature request related to a problem? Please describe.**
It is not possible to create a service bus subscription with session enabled

**Describe the solution you'd like**
The API should support service bus sessions when creating subscriptions

**Comment by xccc-msft** [comment]
Hi @ElectiveRob, we will plan to implement this feature.

**Comment by xccc-msft** [comment]
Hi @ElectiveRob you should be able to create service bus subscription with sessions enabled via current .net SDK. We have implemented APIs as _WithSession()/WithoutSession()_ for service bus subscription creation.

If you want to enable session during creation:
`var subscription = topic.Subscriptions
                         .Define(subscriptionName)
                         .WithSession()
                         .WithDefaultMessageTTL(new TimeSpan(0, 20, 0))
                         .Create();`

If you want to enable session after creation:
`subscription.Update().WithSession().Apply();`

If you wan to disable session after creation:
`subscription.Update().WithoutSession().Apply();`

**Comment by yaohaizh** [comment]
The issue is already supported. Let us know if you have further question regarding service bugs. Thanks.
