### ISSUE TITLE
[FEATURE REQ] Unmanaged disk support

### ISSUE THREAD

**Issue by Mi1an** [Azure/azure-libraries-for-net#806]
I want to create snapshots on unmanaged disks (vhds) but thats not possible now. I would like to get possibility to create snapshot by diskUri.
I know it´s possible to create managed disk snapshots but these snapshots are problematic when you need fast promoting. Fastest promoting is snapshots on unmanaged disks.

**Comment by siriusk-MSFT** [comment]
Hi - Refer to the following doc for instructions to create snapshot for unmanaged disk (vhd): https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-snapshots

**Comment by Mi1an** [comment]
Thank you for doc. Glad to hear that it is possible.
