### ISSUE TITLE
[BUG] Unable to cancel operation, await hangs after cancellation requested

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-libraries-for-net#807]
**Describe the bug**

The following code tries to update vmss to 1 instance and cancel the operation after 15 seconds. After the cancellation requested, await hangs.

```
var vmss = await azure.VirtualMachineScaleSets.GetByResourceGroupAsync("myresourcegroup","myvmss");
var timeoutCts = new CancellationTokenSource(TimeSpan.FromSeconds(15));
await vmss.Update().WithCapacity(1).ApplyAsync(timeoutCts.Token);
```

I looked at the problem. It looks the same cancellationtoken is used in the following continue task which is supposed to set the taskCompletionSource. But the cancellationtoken also cancels the continue task so taskCompletionSource is never set.

https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/Core/ResourceActions/Creatable.cs#L52

                CreatorTaskGroup.ExecuteAsync(cancellationToken, multiThreaded).ContinueWith(
                    (task) =>
                            {
                                if (task.Exception != null)
                                {
                                    taskCompletionSource.SetException(task.Exception.InnerExceptions);
                                }
                                else
                                {
                                    IFluentResourceT thisResource = this as IFluentResourceT;
                                    if (thisResource == null)
                                    {
                                        taskCompletionSource.SetException(new InvalidOperationException("Internal Error: Expected 'of type' '" + typeof(IFluentResourceT) + "', but got '" + this.GetType().Namespace + "'"));
                                    }
                                    else
                                    {
                                        taskCompletionSource.SetResult(thisResource);
                                    }
                                }
                            },
                    cancellationToken,
                    TaskContinuationOptions.ExecuteSynchronously,
                    TaskScheduler.Default);

**Comment by weidongxu-microsoft** [comment]
Fixed in 1.27. To be released on Oct. 11th.
