### ISSUE TITLE
ActiveDirectoryApplications fails with .WithAvailableToOtherTenants(true) 

### ISSUE THREAD

**Issue by huajunzhao** [Azure/azure-libraries-for-net#809]
We want to create or update the AAD application to support the multiple tenants

When i use this api to create or update AAD application with WithAvailableToOtherTenants(true), it always give the exception with "Bad Request" 

await ActiveDirectoryApplications
                .Define(name)
                .WithSignOnUrl("https://cis-aadapp-rp/" + name)
                .WithAvailableToOtherTenants(true)
                .CreateAsync();
await ActiveDirectoryApplications.Update()
                .WithAvailableToOtherTenants(true)
                .ApplyAsync();

I saw a similar issue https://github.com/Azure/azure-libraries-for-net/issues/542 but the solution with WithIdentifierUr did work for me.

Can you please help confirm and help me know how to make this work?

Thanks,
Kevin

**Comment by huajunzhao** [comment]
@loarabia,  any update?

**Comment by weidongxu-microsoft** [comment]
@huajunzhao Thanks for the feedback. We will investigate in a day or two. Fix might take longer depends on the scope of the issue.

**Comment by weidongxu-microsoft** [comment]
@huajunzhao
The exception hides the actual cause of the error (sorry for that, the exception handling should be improved). At present you can add logging (https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-concepts?view=azure-dotnet#logs-and-tracing) to tell the cause. Response could be something like this:
```
{
  "odata.error": {
    "code": "Request_BadRequest",
    "message": {
      "lang": "en",
      "value": "Host name in property identifierUris is not on any verified domain of the company or its subdomain."
    },
    "requestId": "246ff538-af3f-4389-91c4-34ddeabd36da",
    "date": "2019-09-29T01:23:58",
    "values": [
      {
        "item": "PropertyName",
        "value": "identifierUris"
      },
      {
        "item": "PropertyErrorCode",
        "value": "HostNameNotOnVerifiedDomain"
      }
    ]
  }
}
```

One common cause is this error "**Host name in property identifierUris is not on any verified domain of the company or its subdomain.**". If so, please check guide e.g. https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/domains-manage

I have tested and I can successfully create the ActiveDirectoryApplication with verified custom domain (ours like AzureSDKTeam.onmicrosoft.com).

**Comment by nickzhums** [comment]
@huajunzhao Are you still experiencing this issue? Let us know, thanks

**Comment by huajunzhao** [comment]
@nickzhums  It can be closed now. Thanks.
