### ISSUE TITLE
[QUERY] Deploying ACI with GPU resources

### ISSUE THREAD

**Issue by hristokgj** [Azure/azure-libraries-for-net#818]
**Query/Question**
Is it possible to create an azure container instance with [GPU ](https://docs.microsoft.com/nl-nl/azure/container-instances/container-instances-gpu)resources using the `Microsoft.Azure.Management.ContainerInstance` library?

***Why is this not a Bug or a feature Request?***
I am not sure if it is possible to do it with `Microsoft.Azure.Management.Fluent v1.26.1` libraries and I could not find a tutorial.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : Visual Studio 2017
 - Version of the Library used: Microsoft.Azure.Management.Fluent v1.26.1
 
 **Information Checklist**
- [x] Query Added
- [x] Setup information Added

**Comment by ChenTanyi** [comment]
@hristokgj 
here is an example for create with gpu resource (you need to set some string or int by yourself)
```
azure.ContainerGroups.Define("")
    .WithRegion("")
    .WithNewResourceGroup("")
    .WithLinux()
    .WithPublicImageRegistryOnly()
    .WithEmptyDirectoryVolume("")
    .DefineContainerInstance("")
        .WithImage("")
        .WithExternalTcpPort(1)
        .WithGpuResource(1, GpuSku.K80)
        .WithCpuCoreCount(1)
        .WithMemorySizeInGB(2)
        .Attach()
    .Create();
```
