### ISSUE TITLE
What about Azure Backup

### ISSUE THREAD

**Issue by soulseak** [Azure/azure-libraries-for-net#84]
Will there be support for Azure Backup Management in the Future?
Getting all backup items and theyr restore points
Restoring backup Points
Triggering new Backups etc.

**Comment by martinsawicki** [comment]
eventually, yes, but exact timing TBD.

**Comment by renutz** [comment]
+1

**Comment by mathieu-benoit** [comment]
@martinsawicki @hovsepm  @selvasingh, just curious, any update on this? Thanks.

**Comment by praries880** [comment]
@lmazuel / @selvasingh Can you guys chime in here?

**Comment by lmazuel** [comment]
Hello,
Azure backup is covered by recovery services packages:
https://www.nuget.org/packages/Microsoft.Azure.Management.RecoveryServices
https://www.nuget.org/packages/Microsoft.Azure.Management.RecoveryServices.Backup

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.recoveryservices.backup?view=azure-dotnet


We don't plan to add support for this in the fluent layer, and questions about using the direct C# SDK should be asked on:
https://github.com/Azure/azure-sdk-for-net

Thanks, do not hesitate for additional questions!
