### ISSUE TITLE
Clearer support for how to authenticate with User Assigned Managed Identity

### ISSUE THREAD

**Issue by apilosofms** [Azure/azure-libraries-for-net#840]
## Problem
Today I spent ages trying to get auth to work with a User Assigned Managed Identity. The problem was that I was not specifying the identity ID when creating the `MSILoginInformation`. That's fine when using a Managed Service Identity, but apparently not with a User Assigned one.

However, there's no way to know that; the API doesn't guide you in the right direction because a constructor which takes an ID doesn't exist.

## Recommended solution
Consider methods like this in `MSILoginInformation` (possibly renamed to `ManagedIdentityInformation`):
- `MSILoginInformation.FromManagedServiceIdentity()`
- `MSILoginInformation.FromUserAssignedIdentityByClientId(string clientId)`
- `MSILoginInformation.FromUserAssignedIdentityByObjectId(string objectId)`
- `MSILoginInformation.FromUserAssignedIdentityByResourceId(string resourceId)`

Along with those, remove the default ctor if possible.
It might make more sense to move these methods one level up, to something like `AzureCredentialsFactory`.

## Alternatives
You could make ctor overloads to hint to the user that there are other bits of information that might be required - but there are two complications:
- The overloads would use the same inputs (single string), requiring some hoop jumping.
- Not as clear to the user which to use.

Either way, as long as it's obvious to the user that using a User Assigned Managed Identity requires extra info (unlike a Managed Service Identity), that's all that's required. Have them fall into the pit of success...

**Comment by yaohaizh** [comment]
@apilosofms thanks for reporting this!
