### ISSUE TITLE
[BUG] ICosmosDBAccount ListKeys returns null PrimaryReadonlyMasterKey

### ISSUE THREAD

**Issue by Digmaster** [Azure/azure-libraries-for-net#842]
**Describe the bug**
When fetching keys from a CosmosDB account the readonly keys are null, the non-readonly keys are correct.

***Exception or Stack Trace***
When running the below, a NullPointerException is thrown (due to the ToSecureString method) when readOnly is true. When readOnly is false, the keys are successfully returned. The PrimaryReadonlyMasterKey is null.

            IDatabaseAccountListKeysResult result = account.ListKeys();

            if (readOnly)
            {
                return Tuple.Create(
                    result.PrimaryReadonlyMasterKey.ToSecureString(),
                    result.SecondaryReadonlyMasterKey.ToSecureString());
            }
            else
            {
                return Tuple.Create(
                    result.PrimaryMasterKey.ToSecureString(),
                    result.SecondaryMasterKey.ToSecureString());
            }

**To Reproduce**
Fetch the keys of a CosmosDB account, then look at the readonly keys.

***Code Snippet***
            IDatabaseAccountListKeysResult result = account.ListKeys();
            Assert.IsNotNull(result.PrimaryReadonlyMasterKey);

**Expected behavior**
The readonly keys correctly populated in the ListKeysResult object

**Setup (please complete the following information):**
 - OS: Windows 2016
 - IDE : Visual Studio (built using MSBuild 14.9)
 - Version of the Library used: 1.27.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by yaohaizh** [comment]
@weidongxu-microsoft  could you take a look at this issue?

**Comment by weidongxu-microsoft** [comment]
@Digmaster 

Issue acknowledged. Cause appears to be deserialization in base class.

For workaround one can call
`IDatabaseAccountListReadOnlyKeysResult result = account.ListReadOnlyKeys();`
to retrieve read-only keys.

**Comment by Digmaster** [comment]
@weidongxu-microsoft I'm really sorry about that, turns out my commit to increment the version missed our scheduled build by a couple minutes, so we _were_ running an older version. Just tested with 1.27.0 and I can verify that the keys were successfully fetched. I'm closing the issue as it's now fixed.
