### ISSUE TITLE
[FEATURE REQ] Support low-priority VMs in fluent APIs

### ISSUE THREAD

**Issue by cao934** [Azure/azure-libraries-for-net#846]
**Is your feature request related to a problem? Please describe.**
Yes, Azure announced the availability of low-priority VMs a while ago. Looks like it is also available in swagger specification of Azure SDK, and azure CLI (az vm create, or az vmss create). This is the property in Model/VirtualMachine.cs:

        /// <summary>
        /// Gets or sets specifies the priority for the virtual machine.
        /// &amp;lt;br&amp;gt;&amp;lt;br&amp;gt;Minimum api-version:
        /// 2019-03-01. Possible values include: 'Regular', 'Low'
        /// </summary>
        [JsonProperty(PropertyName = "properties.priority")]
        public string Priority { get; set; }

**Describe the solution you'd like**
We need the option to specify VirtualMachinePriorityType with VM/VMSS fluent APIs.

**Describe alternatives you've considered**
We are using fluent APIs extensively to create VMs and/or VMSS. We will have to migrate to use swagger specification to generate client code to perform those tasks, and lose the benefit of fluent APIs.

**Additional context**
We are developing big data analytics services that spin off clusters with azure VMs for customers to perform big data compute. The performance and COGS are our main concerns. Our service will be released to Public Preview (Ignite) on Nov 4, 2019. With only a couple of weeks left, we can't migrate to swagger spec to enable low-prio VMs. This would be a nice feature to save our COGS if low priority VMs can be enabled with fluent APIs.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by yaohaizh** [comment]
@cao934 This has already been supported https://github.com/Azure/azure-libraries-for-java/blob/133ce466c9c5e4c60332fc1d8e557ea3c3b4e827/azure-mgmt-compute/src/main/java/com/microsoft/azure/management/compute/VirtualMachine.java#L1657

Please let us know if you have any additional requirements besides the provided API. Thank.

**Comment by weidongxu-microsoft** [comment]
Support for VMSS is already supported via `WithLowPriorityVirtualMachine`.

Support for VM is in progress as PR https://github.com/Azure/azure-libraries-for-net/pull/845/files. It is scheduled for 1.27.1 on Oct. 25th.

There is a workaround before 1.27 as:
```
            var vmToCreate = azure.VirtualMachines.Define(vmName)
                .WithRegion(Region.USEast)
                .WithExistingResourceGroup(rgName)
                .WithNewPrimaryNetwork("10.0.0.0/28")
                .WithPrimaryPrivateIPAddressDynamic()
                .WithoutPrimaryPublicIPAddress()
                .WithPopularLinuxImage(KnownLinuxVirtualMachineImage.UbuntuServer16_04_Lts)
                .WithRootUsername(userName)
                .WithRootPassword(password)
                .WithSize(VirtualMachineSizeTypes.StandardD1V2);
            (vmToCreate as IVirtualMachine).Inner.Priority = VirtualMachinePriorityTypes.Low;
            vmToCreate.Create();
```
Line `(vmToCreate as IVirtualMachine).Inner.Priority = VirtualMachinePriorityTypes.Low;`.

**Comment by cao934** [comment]
Thanks for the workaround provided! We can used it for now, and move to the new API once released.

**Comment by yaohaizh** [comment]
Feature merged, will be released by the end of this week.
