### ISSUE TITLE
[FEATURE REQ]Support ephemeral OS disk with azure fluent API

### ISSUE THREAD

**Issue by cao934** [Azure/azure-libraries-for-net#847]
**Is your feature request related to a problem? Please describe.**
Yes, Azure announced the availability of ephemeral OS disk lately (https://azure.microsoft.com/en-us/updates/azure-ephemeral-os-disk-now-generally-available/). It is already available in swagger spec.
        /// <summary>
        /// Gets or sets specifies the ephemeral Disk Settings for the
        /// operating system disk used by the virtual machine.
        /// </summary>
        [JsonProperty(PropertyName = "diffDiskSettings")]
        public DiffDiskSettings DiffDiskSettings { get; set; }

**Describe the solution you'd like**
We need the ability to use ephemeral OS disk with fluent APIs.

**Describe alternatives you've considered**
We are developing big data analytics solutions by spinning off clusters with azure VMs on the fly to allow customers to perform big data compute. We are using normal OS disk/VHDs. Being able to use ephemeral disks will allow us to reduce COGS significantly.

**Additional context**
We will be releasing our services in Ignite (Nov 4). This feature will allows us to reduce COGS.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by cao934** [comment]
The DiffDiskSettings is in Microsoft.Compute\Models\OSDisks.cs.

**Comment by weidongxu-microsoft** [comment]
It should be already supported, via `WithEphemeralOSDisk`. Sample usage could be found at https://github.com/Azure/azure-libraries-for-net/blob/master/Tests/Fluent.Tests/Compute/VirtualMachineManagedDiskOperationsTests.cs#L599

**Comment by cao934** [comment]
What is the version that has this support? I have 1.27 installed, but don't see this api.

**Comment by yaohaizh** [comment]
https://github.com/Azure/azure-libraries-for-net/pull/827. PR was merged, also targeting 1.27.1

**Comment by weidongxu-microsoft** [comment]
@cao934 Sorry I mistaken the code merged after 1.27 as released.

**Comment by cao934** [comment]
No problem. We can use the workaround for now, and move to the new API once it is available. Thanks!

**Comment by yaohaizh** [comment]
Close it as this is supported.
