### ISSUE TITLE
[FEATURE REQ] Ability to create metric alerts with time aggregation of count

### ISSUE THREAD

**Issue by NBMladenov** [Azure/azure-libraries-for-net#861]
**Is your feature request related to a problem? Please describe.**
The current Azure Metric Alerts API is unable to create various metric alerts which only support the aggregation type *count*.

**Describe the solution you'd like**
An extension to the enum *MetricAlertRuleTimeAggregation* to support *Count*.

**Describe alternatives you've considered**
Currently we've been creating/defining alerts via the Azure Portal and ARM templates respectively although we're wanting to move into a more robust solution via the Azure Metric Alerts API.

**Additional context**
The response received when attempting to create these types of alerts:
![image](https://user-images.githubusercontent.com/21137582/67614149-3a681200-f803-11e9-8587-8e15376d170a.png)
As well as the current definition within *MetricAlertRuleTimeAggregation*:
![image](https://user-images.githubusercontent.com/21137582/67614249-4d7be180-f805-11e9-8db1-2d9e5a538001.png)
And the latest version of Azure Management API:
![image](https://user-images.githubusercontent.com/21137582/67614257-66849280-f805-11e9-9388-66c612d4872c.png)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified

**Comment by yaohaizh** [comment]
@weidongxu-microsoft Please take a look at this issue. Thanks.

**Comment by weidongxu-microsoft** [comment]
@NBMladenov
Sorry for my late reply. I will try to fix it in this sprint (Nov. 16).

If you want to be unblocked right now, you can try to use below code snippt to create a Count type:
`MetricAlertRuleTimeAggregation count = MetricAlertRuleTimeAggregation.Parse("Count");`

**Comment by weidongxu-microsoft** [comment]
Fixed in 1.28, to be released on Nov. 16.
