### ISSUE TITLE
[QUERY] How to access all tenants and subscriptions with a single login in Azure Management SDK

### ISSUE THREAD

**Issue by aloneguid** [Azure/azure-libraries-for-net#864]
**Query/Question**

I'm trying to use this library for authentication to Azure from a command-line application. My goal is to list all storage accounts in all tenants and all subscriptions using fluent libraries with no success.

`FromDevice` method is actually working well, if I use `common` as tenant ID:

```csharp
	var azureNativeCreds = SdkContext.AzureCredentialsFactory.FromDevice(
		AzureCliClientId,
		"common",
		AzureEnvironment.AzureGlobalCloud,
		code =>
		{
			Console.WriteLine(code.Message);
			return true;
		});

var auth = Azure.Authenticate(azureNativeCreds);
```

however any call to `auth.Subscriptions.ListAsync` returns empty list of subscriptions for any account that has access to more than one tenant or more than one subscription.

I can list the tenants user belongs to with `auth.Tenants.ListAsync()` and that returns valid list of tenants, however I can't find a way to now use a particular tenant and subscription to make a subsequent call.

One way to achieve what I want is to create another instance of `IAzure` but that pops up authentication dialog again, i.e.:

```
foreach(var tenant in await auth.Tenants.ListAsync())
{
		//create creds for tenant?
		//throws authentication dialog for every tenant
		
		var tcreds = SdkContext.AzureCredentialsFactory.FromDevice(
			AzureCliClientId,
			tenant.TenantId,
			AzureEnvironment.AzureGlobalCloud,
			code =>
			{
				Console.WriteLine(code.Message);
				return true;
			});

  var tazure = await Azure.Authenticate(tcreds).WithDefaultSubscriptionAsync();

  var storageAccounts = await tazure.StorageAccounts.ListAsync();
}
```

so the user gets constantly annoyed with popups. Another issue that `FromDevice` won't remember that the user has already logged in previously, regardless whether I save token cache to disk or not (`TokenCache.DefaultShared.BeforeWrite` etc).

***Why is this not a Bug or a feature Request?***
There is no documentation, i'm not sure it's a but or not.

**Setup (please complete the following information if applicable):**
 - OS: Windows/Linux
 - IDE : VS2019
 - Latest
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Query Added
- [ x] Setup information Added

**Comment by yaohaizh** [comment]
@xccc-msft please help with the case. Thanks.

**Comment by xccc-msft** [comment]
@aloneguid for now, we will not provide any APIs to list all tenants and subscriptions as per the service side didn't expose any REST APIs like that. What we can do here is to find a way to enable silent login from device so you could avoid the frequent popups based on your workaround on this.

**Comment by nickzhums** [comment]
@aloneguid let us know if you still support
