### ISSUE TITLE
[FEATURE REQ] Batch restart for IVirtualScaleSetVms does not exist but delete/get/update do

### ISSUE THREAD

**Issue by leonjunwei** [Azure/azure-libraries-for-net#866]
Hi,

I'm using the Microsoft.Azure.Management.Fluent and Microsoft.Azure.Management.Compute.Fluent libraries to manage Virtual Machine Scalesets on Azure. I have a `IVirtualMachineScaleSet` vmss containing a bunch of Vms I want to delete, and a bunch I want to restart. For the deletions, using `vmss.VirtualMachines.DeleteInstancesAsync(List<string> instanceIds)` is an option to delete them all at once, but there is no corresponding method for batch restart. The only method available to restart more than one Vm is `vmss.Restart()` which restarts all Vms in the scaleset.

Given that the REST API calls for [batch restarts](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/restart) as well as [batch deletes](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/delete) appear to have almost identical functionality, would it be possible for a function `vmss.VirtualMachines.RestartInstancesAsync(List<string> instanceIds)`  to be included in a future version of the SDK? 

Thank you!

Leon
Thank you!

**Comment by nickzhums** [comment]
@leonjunwei Thanks for opening the issue. We'll look into it
