### ISSUE TITLE
[BUG] Storage account creation missing 'FileStorage' kind

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-libraries-for-net#867]
**Describe the bug**

It is not possible to use the [Storage Fluent SDK](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage.Fluent) to create a storage account of kind 'FileStorage'.

Looking at the interfaces for [Microsoft.Azure.Management.Storage.Fluent.StorageAccount.Definition](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.fluent.storageaccount.definition?view=azure-dotnet), we see that there exists IWithBlobStorageAccountKind and IWithGeneralPurposeAccountKind but not IWithFileStorageAccountKind.

Also, the 'FileStorage' kind is listed in the Models here so I'd expect to be able to create a storage account of that kind. https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.kind?view=azure-dotnet

**Comment by derekbekoe** [comment]
Okay so it is possible to do it with:
```
StorageAccountCreateParameters storageCreateParams = new StorageAccountCreateParameters()
{
    Kind = Kind.FileStorage,
    Location = azureRegion,
    Sku = new SkuInner(SkuName.PremiumLRS),
};
await azure.StorageAccounts.Inner.CreateAsync(azureResourceGroup, storageAccountName, storageCreateParams);
```

But not:
```
await azure.StorageAccounts.Define(storageAccountName)
                    .WithRegion(azureRegion)
                    .WithExistingResourceGroup(azureResourceGroup)
                    .WithFileStorageAccountKind()
                    .CreateAsync();
```

So this isn't a blocker.

**Comment by yaohaizh** [comment]
@derekbekoe thanks for reporting this. As you w@xccc-msft, could you take a look at this to see in which milestone we can support this?

**Comment by xccc-msft** [comment]
@derekbekoe we will plan to support this with current/next sprint. I will update once we release it in new version. Thanks.

**Comment by xccc-msft** [comment]
Close this as it got supported in release 1.28.0
