### ISSUE TITLE
Can you add more Event Hub rules to a Shared Access Policy than one?

### ISSUE THREAD

**Issue by tlorton** [Azure/azure-libraries-for-net#877]
**Query/Question**
After I create my Event Hub, I am applying rules. Am I able to apply, for example, and Send and a Listen rule to the same shared access policy?

The code I am trying to use seems to "overwrite" the previous rule. Is there a better way I should be doing this?

`await eventHub.Update()
   .WithNewSendRule(sendListenRuleNames)
   .WithNewListenRule(sendListenRuleNames)
   .ApplyAsync();`
The code above will end up applying only the Listen rule to the Shared Access Policy.

***Why is this not a Bug or a feature Request?***
I'm not sure if I'm creating the chain correctly.

**Setup (please complete the following information if applicable):**
 - OS: Windows 10
 - IDE : VS 2019 Enterprise
 - Version 1.27.2
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by yaohaizh** [comment]
@weidongxu-microsoft  could you help take a look at this issue?

**Comment by tlorton** [comment]
I posted on SO as well. And there is currently ongoing discussion. 
https://stackoverflow.com/questions/58737137/can-you-add-more-event-hub-rules-to-a-shared-access-policy-than-one

As it states, I originally tried applying AccessRights.Listen and AccessRights.Manage to the same Access Policy, and it failed with the error you will see in the post. And then I tried ONLY AccessRights.Listen and it seemed to work. And then right after I tried ONLY AccessRights.Manage and it failed with the same error. 

Please see the SO post.

**Comment by tlorton** [comment]
Any help on this?

**Comment by xccc-msft** [comment]
@tlorton For your concern about AccessRights.Manage, please refer [shared-access-authorization-policies](https://docs.microsoft.com/en-us/azure/event-hubs/authorize-access-shared-access-signature#shared-access-authorization-policies). When you try to apply Manage rule there, you need to put all of Send, Listen, Manage inside. Thanks.

**Comment by tlorton** [comment]
@xccc-msft Thank you for your help. It works as expected now.
