### ISSUE TITLE
[BUG] A managed disk snapshot of premium SSD disk in Germany Central cannot be found.

### ISSUE THREAD

**Issue by qub1n** [Azure/azure-libraries-for-net#880]
**Describe the bug**
A managed disk snapshot of premium SSD disk in Germany Central cannot be found.

***Exception or Stack Trace***
11/7/19 12:33:16 PM   23 (23) Error: The subscription 'xxxxxxxxxx' could not be found.
11/7/19 12:33:16 PM   23 (23) Type: Microsoft.Rest.Azure.CloudException
11/7/19 12:33:16 PM   23 (23) Stack:
11/7/19 12:33:16 PM   23 (23)    at Microsoft.Azure.Management.Compute.SnapshotsOperations.GetWithHttpMessagesAsync(String resourceGroupName, String snapshotName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at MyProject.Extensions.SnapshotExtension.GetSizeByComputeManagementClientAsync(ISnapshot snapshot, IAzureContext azureContext, CancellationToken cancellationToken)

**To Reproduce**
1. Create an Ubuntu VM with Premium SSD Disk
2. Create snapshot of the disk
3. List the snapshot by ResourceGroupName and snapshot.Name

***Code Snippet***
private static async Task<long?> GetSizeByComputeManagementClientAsync(ISnapshot snapshot, IAzureContext azureContext, CancellationToken cancellationToken)
        {
            var snapshotsOperations = azureContext.CreateComputeManagementClient().Snapshots;
            var snapshotWithSize = await snapshotsOperations.GetWithHttpMessagesAsync(snapshot.ResourceGroupName, snapshot.Name, cancellationToken: cancellationToken);            
            return snapshotWithSize.Body.DiskSizeBytes;
        }

**Expected behavior**
return the snapshot. It works for another type of disk (standard SSD)

**Setup (please complete the following information):**
 - Windows or Ubuntu (I tried both)
 - IDE : [e.g. IntelliJ]

    <PackageReference Include="Microsoft.Azure.Management.Compute" Version="29.1.0" />
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.27.2" />
    <PackageReference Include="Microsoft.Azure.Management.ManagedServices" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.0.1" /

**Additional context**

GET https://management.azure.com/subscriptions/yyyyyyyyyyyyyyyyy/resourceGroups/xxxxxx/providers/Microsoft.Compute/snapshots/My.Snapshot.2e0f03a1-bb98-4a4a-b033-145c77ea7e20?api-version=2019-03-01 HTTP/1.1
x-ms-client-request-id: 39d19311-6260-438f-ab73-1afacbe0aa0f
Accept-Language: en-US
Authorization: Bearer xxxxx
User-Agent: FxVersion/4.6.27617.05 OSName/Windows OSVersion/Microsoft.Windows.10.0.17763. Microsoft.Azure.Management.Compute.ComputeManagementClient/29.0.0.0
Request-Id: |bcc8b80d139cb24a96e2b718af343612.3ac7e978_61.
Host: management.azure.com

----------------------------------

HTTP/1.1 404 Not Found
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
x-ms-failure-cause: gateway
x-ms-request-id: 71296f08-8d3c-431c-a6ec-a077a1c1cbb7
x-ms-correlation-request-id: 71296f08-8d3c-431c-a6ec-a077a1c1cbb7
x-ms-routing-request-id: GERMANYWESTCENTRAL:20191107T132520Z:71296f08-8d3c-431c-a6ec-a077a1c1cbb7
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Date: Thu, 07 Nov 2019 13:25:20 GMT
Content-Length: 129

{"error":{"code":"SubscriptionNotFound","message":"The subscription 'xxxxxxxxxxxxxx' could not be found."}}

**Comment by yaohaizh** [comment]
Thanks for report this issue. We will look into the issue.

**Comment by qub1n** [comment]
I tried to prepare a simple example to reproduce it, but I cannot reproduce it anymore. It works for me.
