### ISSUE TITLE
[BUG] LoadBalancer does not allow backend to be configured.

### ISSUE THREAD

**Issue by cao934** [Azure/azure-libraries-for-net#898]
**Describe the bug**
ILoadBalancer does not allow backend to be updated.

***Exception or Stack Trace***
NA

**To Reproduce**
var lb = azure31.LoadBalancers.GetById(
                "/subscriptions/cbd70ea3-bd35-40cf-84dc-c59d65bd3c18/resourceGroups/xcrg1/providers/Microsoft.Network/loadBalancers/xclb4");
            lb.Update()
                .UpdateBackend("backend1")
                .
There is no With method following this to allow backend to be updated.

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
Should be .NET SDK bug.

**Comment by yaohaizh** [comment]
@weidongxu-microsoft  could you help be more specific about your investigation? Thanks.

**Comment by weidongxu-microsoft** [comment]
@yaohaizh We do not have the interface for this. Hence this is not about service.

**Comment by weidongxu-microsoft** [comment]
Fixed in 1.29, to be release on Dec. 6.
