### ISSUE TITLE
[FEATURE REQ] Support Private DNS Zone in fluent API

### ISSUE THREAD

**Issue by cao934** [Azure/azure-libraries-for-net#899]
**Is your feature request related to a problem? Please describe.**
Private DNS Zone is available in powershell, CLI and Portal. We need fluent api support to do this programmatically.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by yaohaizh** [comment]
@xccc-msft does this supported?

**Comment by xccc-msft** [comment]
Close this as released in 1.29.0.
