### ISSUE TITLE
[FEATURE REQ]Private Link support in fluent API

### ISSUE THREAD

**Issue by cao934** [Azure/azure-libraries-for-net#900]
Support fluent API: 

> We are not sure whether you mean this https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2019-09-01/firewallPolicy.json
> If yes, it could be accessed via:
> azure.Networks.Manager.Inner.AzureFirewalls.CreateOrUpdateAsync

**Comment by xccc-msft** [comment]
Close this as released in v1.30.0
