### ISSUE TITLE
[QUERY] SqlServer.Databases.Define(name).WithEdition(null) resolves to "Standard" edition

### ISSUE THREAD

**Issue by tlorton** [Azure/azure-libraries-for-net#904]
**Query/Question**
Is this the expected behavior?

If I set `databaseEdition` to null the Edition resolves to "Standard".

`sqlDatabase = await sqlServer.Databases
                    .Define(sqlDatabaseResource.Name)
                    .WithEdition(databaseEdition)
                    .WithServiceObjective(serviceObjectiveName)
                    .WithMaxSizeBytes(sqlDatabaseResource.MaxSizeInBytes)
                    .WithTags(sqlDatabaseResource.ResourceGroup.Tags)
                    .CreateAsync();`

***Why is this not a Bug or a feature Request?***
Wondering if this is expected.

**Setup (please complete the following information if applicable):**
 - OS: [Windows 10]
 - IDE : [VS 2019 Enterprise]
 - 1.27
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by tlorton** [comment]
Also, if I make the same request as above with a valid Edition (not null), but have a null ServiceObjective then the ServiceObjective resolves to "S0".

Is this also expected? I would expect both of these to throw a NullReferenceException.

**Comment by jaredmoo** [comment]
This is intentional. These properties are not required, so if you specify null then the service will choose a default for you.

**Comment by jaredmoo** [comment]
Also FYI, you can find the defaults by using [`azure.sqlServers().getCapabilitiesByRegion(region)`.](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.management.sql.sqlservers.getcapabilitiesbyregion?view=azure-java-stable#com_microsoft_azure_management_sql_SqlServers_getCapabilitiesByRegion_Region_)
