### ISSUE TITLE
[QUERY]: How do we specify Permissions on an AccountSasParameters object

### ISSUE THREAD

**Issue by ravarnamsft** [Azure/azure-libraries-for-net#909]
**Query/Question**
Looks like the Permissions property is now and ExpandableStringEnum instead of a string within the AccountSasParameters object. If we want to combine multiple permissions, such as Permissions.R and Permissions.W, how is that set on the AccountSasParameters object? Earlier, we could just specify a string "rw". I could use ExpandableStringEnum<Permissions>.Parse("rw"), but that seems overkill and I feel I am missing something trivial.

This is the new constructor for AccountSasParameters:
public AccountSasParameters(
      Services services,
      SignedResourceTypes resourceTypes,
      **Permissions** permissions,
      DateTime sharedAccessExpiryTime,
      string iPAddressOrRange = null,
      HttpProtocol? protocols = null,
      DateTime? sharedAccessStartTime = null,
      string keyToSign = null)
)

The same question applies to SignedResourceTypes as well.

***Why is this not a Bug or a feature Request?***
The code is already present, this is just a question on how to use it.

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by yaohaizh** [comment]
@ravarnamsft actually using the `ExpandableStringEnum.Parse("rw")` is the right way to do for your case here and it is what exactly expandablestringenum works for.

**Comment by yaohaizh** [comment]
I would close this issue now. Feel free to reopen this issue if you have any other concerns. Thanks.
