### ISSUE TITLE
Thumbprint on the portal seems incorrect after calling DefineCertificateCredential

### ISSUE THREAD

**Issue by huajunzhao** [Azure/azure-libraries-for-net#915]
**Describe the bug**

I use the sample code like [this](https://github.com/Azure/azure-libraries-for-net/blob/5f85a978aaa0340e5ef9f9747d3fefe052ad2a2b/Tests/Fluent.Tests/GraphRbac/ApplicationsTests.cs) to add a certificate into a AAD application, after code executed, when looking at the portal. I see the thumbprint is "63657274", can you please check if this is bug?

***Exception or Stack Trace***
Add the exception log and stack trace if available
No

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

// certificate credentials definition
                    aadApptoCreate.DefineCertificateCredential("cert")
                                .WithAsymmetricX509Certificate()
                                .WithPublicKey(System.IO.File.ReadAllBytes(cert))
                                .WithDuration(TimeSpan.FromDays(100))
                                .Attach();
                }

**Expected behavior**

The thumbprint on the portal should be fixed.

Additional, i want to know how to change cert to anther one when updating the existing Aad application? Please share the code snippet.

**Screenshots**
![image](https://user-images.githubusercontent.com/3183325/70034376-0646f480-15ec-11ea-8965-6a3b48915695.png)

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yaohaizh** [comment]
Thanks for reporting the issue. We are looking into the issue. @ChenTanyi

**Comment by ChenTanyi** [comment]
@huajunzhao I have test about it, it just display different from what was uploaded by portal (use different key), but the values are same.
certificate can not be changed, you can only create a new one.
