### ISSUE TITLE
[BUG] Cannot apply certificates uploaded to separate resource groups

### ISSUE THREAD

**Issue by carsontwilson** [Azure/azure-libraries-for-net#917]
**Describe the bug**
The end result is the same as this bug: https://github.com/Azure/azure-libraries-for-net/issues/850#issuecomment-544833918 but the behaviours associated to it are different (so I wasn't sure if I should file a new defect, since the underlying error is not the same). 

When attempting to apply a certificate to resource group B, when that certificate was originally uploaded to resource group A   a null reference exception is returned. Note that, in the portal, I can see the certificate is present and healthy in resource group B, I just cannot make use of it using the SDK.

***Exception or Stack Trace***
"   at Microsoft.Azure.Management.AppService.Fluent.HostNameSslBindingImpl`5.<<NewCertificateAsync>b__40_0>d.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceInternalAsync>d__277.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.Management.AppService.Fluent.WebAppBaseImpl`5.<CreateResourceAsync>d__278.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.<ApplyAsync>d__3.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.Apply()\r\n  

**To Reproduce**

1. Create a resource groups with web apps
2. Manually upload a private cert
3. Using Azure SDK to apply custom hostnames and certs to multiple apps within the resource group (this will work)
4. Create another resource group with separate web apps. Confirm the same cert is showing as available for that group in the portal
5. Using Azure SDK, apply custom hostnames to multiple applications in the new resource group...
6. Get a null reference exception

Note that the custom host will still be created even though the Apply method threw a null reference exception, so that suggests it's the certificate portion that is failing (I later separated the two steps out and can confirm it's the cert portion that is throwing the null reference exception).

***Code Snippet***

Note that I am checking that WebAppRm is not null.
```
WebAppRm.Update()
                        .DefineHostnameBinding()
                        .WithThirdPartyDomain(Domain)
                        .WithSubDomain(customHostName)
                        .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
                        .Attach()
                        .DefineSslBinding()
                        .ForHostname(customHostName)
                        .WithExistingCertificate(CertificateThumbprint)
                        .WithSniBasedSsl()
                        .Attach()
                        .WithHttpsOnly(true)
                        .Apply();
```

**Expected behavior**
The certificate is applied to the custom hostnames regardless of the resource group the certificate was originally uploaded to.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 Pro
 - IDE : Visual Studio
 - Fluent Version: 1.28.1

**Additional context**

- I can't manually re-upload the cert because I get an error that it already exists...
- I tried manually adding it to a web app in resource group b and then running the script for the other apps and the behaviour was the same.
- I also tried downgrading to Fluent 1.28.0 and the result was still the same.
- When  manually uploading the cert for one resource in resource group A, I then used the script to apply the cert to all other resources in resource group A and that was successful.

I can also confirm that this is **not** a problem in Powershell. I just executed this command and it worked as expected:
Write-Host "Binding SSL Certification for hostname: $($customHostName)"
        New-AzureRmWebAppSSLBinding -ResourceGroupName $this.ResourceGroupName -Name $customHostName -WebAppName $this.Name -SslState SniEnabled -Thumbprint ([AppService]::thumbprint)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ X ] Bug Description Added
- [ X ] Repro Steps Added
- [ X] Setup information Added

**Comment by yaohaizh** [comment]
Thanks for reporting this issue.
