### ISSUE TITLE
[BUG] Changes made to SiteConfig are never propagated

### ISSUE THREAD

**Issue by carsontwilson** [Azure/azure-libraries-for-net#918]
**Describe the bug**
Changing the Azure WEb App properties and then applying that change does not seem to have any effect. Am I using it wrong, or is it a bug?

***Exception or Stack Trace***
None - no errors, just nothing happens...

**To Reproduce**
Create or get an existing web app
Make a new SiteConfig object and assign that to the app
perform an update / apply
The changes do not take effect

***Code Snippet***
```
 var app = AzureAuthentication.AzureInstance.AppServices.WebApps.GetByResourceGroup(ResourceGroupName, Name);

            var restrictions = new List<IpSecurityRestriction>
            {
                new IpSecurityRestriction("x.x.x.x/32",null,null,null,null,"Allow",null,300,"Proxy 1", null),
                new IpSecurityRestriction("x.x.x.x/32/32",null,null,null,null,"Allow",null,300,"Proxy 2", null),
                new IpSecurityRestriction("x.x.x.x/32/32",null,null,null,null,"Allow",null,300,"Offce", null)
            };
            var site = new SiteConfig(ipSecurityRestrictions:restrictions);
            app.Inner.SiteConfig = site;
            app Update().Apply();
```

**Expected behavior**
The changes made to the object should be applied.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 Pro
 - IDE : Visual Studio
 - Fluent 1.28.1

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by yaohaizh** [comment]
Thanks for report this issue. We will look into this issue.

**Comment by weidongxu-microsoft** [comment]
@carsontwilson

This one is trickier than others. `Inner.SiteConfig` is not for update.

You had to do this with `SiteConfigResourceInner`:

```
SiteConfigResourceInner siteConfig = new SiteConfigResourceInner(ipSecurityRestrictions: restrictions);

azure.WebApps.Inner.CreateOrUpdateConfigurationAsync(app.ResourceGroupName, webapp.Name, siteConfig).Wait();
```

Please use with care (since it is a PUT). I have tried a few cases and it does not overwrite any value that is not specified.

**Comment by carsontwilson** [comment]
This works great - thanks so much!

**Comment by mudith215** [comment]
> @carsontwilson
> 
> This one is trickier than others. `Inner.SiteConfig` is not for update.
> 
> You had to do this with `SiteConfigResourceInner`:
> 
> ```
> SiteConfigResourceInner siteConfig = new SiteConfigResourceInner(ipSecurityRestrictions: restrictions);
> 
> azure.WebApps.Inner.CreateOrUpdateConfigurationAsync(app.ResourceGroupName, webapp.Name, siteConfig).Wait();
> ```
> 
> Then maybe `app.Refresh()` to get latest status.
> 
> Please use with care (since it is a PUT). I have tried a few cases and it does not overwrite any value that is not specified.

Hi this work perfectly but im looking for way to remove exciting record.what is the method that i can use to remove it

Thanks in advance
