### ISSUE TITLE
[FEATURE REQ] Support Notification Hub with fluent API

### ISSUE THREAD

**Issue by nicolas-garcia** [Azure/azure-libraries-for-net#920]
Hi!

**Is your feature request related to a problem? Please describe.**
That's a shame that Notification Hubs creation and management could not be handled using the fluent API right now.

**Describe the solution you'd like**
Adding the support Notification Hubs Namespace and Notification Hubs would be great!

**Describe alternatives you've considered**
The main solution right now is to manually create those resources using Azure Portal.

**Additional context**
Not an urgent matter, but among all Azure resources we use, this one lack of fluent API is kind of frustrating.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

Thank you for your great work guys!

**Comment by yaohaizh** [comment]
This is not on the roadmap of fluent SDK API. Will close it now. Thanks.
