### ISSUE TITLE
[FEATURE REQ] Add fluent style API for Cosmos DB: SQL / MongoDB / Cassandra / Gremlin / Table

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-libraries-for-net#925]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by markjbrown** [comment]
Thanks for opening.

Can I make a suggestion? Can you change this issue to include Fluent support for all Cosmos resources, not just the SQL API ones?

Thanks.

**Comment by xccc-msft** [comment]
Close this as released in v1.30.0
