### ISSUE TITLE
[BUG] RouteTables is not exposed properly

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-libraries-for-net#928]
**Describe the bug**

RouteTables should be accessed via `Azure.RouteTables`.

Java got it right at `Azure.routeTables()`.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by xccc-msft** [comment]
Close this as released in v1.30.0
