### ISSUE TITLE
Why is batch fluent deprecated?

### ISSUE THREAD

**Issue by alch-msft** [Azure/azure-libraries-for-net#929]
**Query/Question**
I'm wondering what's the road map for azure-libraries-for-net? I'm confused by recent deprecation of the batch library(I don't see any comments in the PR). Seems like batch AI got added to the library recently while batch got deprecated in 1.27.0.  However, I see on azure portal that batch is still a supported service while batch AI is marked as "retired". Why are we deprecating fluent library for an active azure service while adding support for a retired one? 

***Why is this not a Bug or a feature Request?***
I'm leveraging this library to build management tools for my service/products, and one of the resources I need to work with is Azure batch. I originally thought the goal of this library is to mirror the azure cli, but this deprecation is signaling something different. 

I'm not asking for new features or bug fixes. Can you share some guidance on for batch? I want to determine whether I should stick with this library, given my Azure batch requirement.  

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : VS
 - Version of the Library used: 1.26.1
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Query Added
- [ X] Setup information Added

**Comment by yaohaizh** [comment]
@alch-msft there is no changed on the service side, just deprecated the fluent batch package since there is an alternative package maintained by the batch service team: https://www.nuget.org/packages/Microsoft.Azure.Batch/ for your Batch .net management.

**Comment by yaohaizh** [comment]
I'm closing this PR now. The https://www.nuget.org/packages/Microsoft.Azure.Batch/ is suggested package for Batch.
