### ISSUE TITLE
[QUERY] How to set .NET Core framework as stack on a (Windows) web app

### ISSUE THREAD

**Issue by mruf** [Azure/azure-libraries-for-net#932]
**Query/Question**
How can I set the .NET Core framework (2.2+) as stack on a (Windows) web app? I only see the .With* methods for Java, regular .NET framework etc

            var webApp = azure.AppServices.WebApps.Define(name)
                .WithExistingWindowsPlan(servicePlan)
                .WithExistingResourceGroup(resourceGroupName)
                .WithHttpsOnly(true)
                .WithHttp20Enabled(true)
                .WithoutPhp()
                .WithPlatformArchitecture(PlatformArchitecture.X64)
                .WithWebAppAlwaysOn(true)
                .WithClientAffinityEnabled(false)
                .Create();

***Why is this not a Bug or a feature Request?***
I'm assuming it is possible to set .NET Core (2.2+) as stack when using the fluent Azure library but I'm unable to find out how.

**Setup (please complete the following information if applicable):**
 - OS: Windows
 - IDE : Rider
 - 1.29
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Query Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@mruf

Try `.WithNetFrameworkVersion(NetFrameworkVersion.V4_6)` in place of `.WithoutPhp()`.

**Comment by mruf** [comment]
@weidongxu-microsoft 
I need the **.NET Core** framework. I want to set the following setting by using the fluent Azure library:

![image](https://user-images.githubusercontent.com/7147271/70984340-97bd6880-20ba-11ea-97a1-bcd94dc7416b.png)

**Comment by weidongxu-microsoft** [comment]
@mruf

I see.

Do this after you have created the web app.

```
            StringDictionaryInner metadata = new StringDictionaryInner(properties:
                new Dictionary<string, string>() {
                    { "CURRENT_STACK", "dotnetcore" }
                });
            azure.WebApps.Inner.UpdateMetadataAsync(resourceGroupName, name, metadata).Wait();
```

It is not pretty (need one additional REST call after creation). This is a pending issue in SDK, which is not fixed yet.

Another note. Do you note any difference between .NET and .NET Core web app runtime? I seems to get "dotnet --version" as 2.2 in .NET as well.

**Comment by Rookian** [comment]
> @mruf
> 
> I see.
> 
> Do this after you have created the web app.
> 
> ```
>             StringDictionaryInner metadata = new StringDictionaryInner(properties:
>                 new Dictionary<string, string>() {
>                     { "CURRENT_STACK", "dotnetcore" }
>                 });
>             azure.WebApps.Inner.UpdateMetadataAsync(resourceGroupName, name, metadata).Wait();
> ```
> 
> It is not pretty (need one additional REST call after creation). This is a pending issue in SDK, which is not fixed yet.
> 
> Another note. Do you note any difference between .NET and .NET Core web app runtime? I seems to get "dotnet --version" as 2.2 in .NET as well.

And how do I set the .NET Core framework version like 3.0 or 3.1?

**Comment by weidongxu-microsoft** [comment]
And for Windows, there seems not any difference of which dotnet core version seletected during creation (via Portal), the info is same (SDK upto 2.2, runtime upto 3.1)

`dotnet --info`

```
.NET Core SDK (reflecting any global.json):

 Version:   2.2.109

 Commit:    586f23c400



Runtime Environment:

 OS Name:     Windows

 OS Version:  10.0.14393

 OS Platform: Windows

 RID:         win10-x86

 Base Path:   D:\Program Files (x86)\dotnet\sdk\2.2.109\



Host (useful for support):

  Version: 3.1.0

  Commit:  65f04fb6db



.NET Core SDKs installed:

  1.1.14 [D:\Program Files (x86)\dotnet\sdk]

  2.1.509 [D:\Program Files (x86)\dotnet\sdk]

  2.2.109 [D:\Program Files (x86)\dotnet\sdk]



.NET Core runtimes installed:

  Microsoft.AspNetCore.All 2.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

  Microsoft.AspNetCore.All 2.1.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

  Microsoft.AspNetCore.All 2.2.7 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

  Microsoft.AspNetCore.All 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

  Microsoft.AspNetCore.App 2.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.AspNetCore.App 2.1.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.AspNetCore.App 2.2.7 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.AspNetCore.App 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.AspNetCore.App 3.0.0 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.AspNetCore.App 3.0.1 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.AspNetCore.App 3.1.0 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

  Microsoft.NETCore.App 1.0.16 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

  Microsoft.NETCore.App 1.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

  Microsoft.NETCore.App 2.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

  Microsoft.NETCore.App 2.1.14 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

  Microsoft.NETCore.App 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

  Microsoft.NETCore.App 3.0.1 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

  Microsoft.NETCore.App 3.1.0 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]



To install additional .NET Core runtimes or SDKs:

  https://aka.ms/dotnet-download
```

**Comment by mruf** [comment]
@weidongxu-microsoft 
Thank you. I can confirm that your suggestion worked.
I'm assuming that Microsoft is updating the available runtimes in a Web App behind the scenes since you cannot specify the desired version anymore.

**Comment by weidongxu-microsoft** [comment]
1.30 (scheduled to be released on 9th, Jan.) will support e.g. `WithRuntimeStack(WebAppRuntimeStack.NETCore)` to update web app runtime stack for windows OS.
It need to be used in couple with existing WithJavaVersion+WithWebContainer / WithPythonVersion / WithPhpVersion etc. to set version.

PS: Linux has existing `WithBuiltInImage` interface.
