### ISSUE TITLE
No way to resolve conflict between "Newtonsoft.Json"

### ISSUE THREAD

**Issue by vigneshrams** [Azure/azure-libraries-for-net#934]
**Describe the bug**
I am using Nuget Package 1.29.0 Microsoft.Azure.Management.Fluent and its dependent Packages for creating VM in Azure. I am having NewtonSoft.Json version 10.0.0.0. I get the below error,

> No way to resolve conflict between "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" and "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". Choosing "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" arbitrarily.
> 3>Consider app.config remapping of assembly "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from Version "6.0.0.0" [] to Version "10.0.0.0" [E:\Workspace\AzureCompute\AzureComputeLib\bin\x64\Debug\Newtonsoft.Json.dll] to solve conflict and get rid of warning.

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
I have a C++ application which make use of CLR\CLI project to access the C# project which has Azure Nuget Package added. 

***Code Snippet***
`var credentials = SdkContext.AzureCredentialsFactory
               .FromFile(@"E:\AzurePS\azureauth.properties");

                azureAuthenticate = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                    .Authenticate(credentials).WithDefaultSubscription();`

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - IDE : [VS 2019]
 - 1.29.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ x] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@vigneshrams

Could you specify .NET core version or .NET framework version in use? If possible also include a minimal project which having this issue (your packages.config if .NET framework maybe)?

I think 1.29 would normally require Newtonsoft.Json >= 1.0.3

**Comment by vigneshrams** [comment]
@weidongxu-microsoft Thanks for replying back.

>NET framework Version - 4.5.2
Adding a downloadable link for minimal sample project as well the Package.config file.
[](https://s3.amazonaws.com/vembu-bug-fix/BDR/4.1.0/Sample-Project-Issue/CreateAzureVM_JSON_Issue.zip)
[](https://s3.amazonaws.com/vembu-bug-fix/BDR/4.1.0/Sample-Project-Config/packages.config)

I tested the same with 1.13.0 Version of DLL everything seems to work. But it lacks on lot of features as its very older version. Please help me on this.
./Thanks

**Comment by vigneshrams** [comment]
https://s3.amazonaws.com/vembu-bug-fix/BDR/4.1.0/Sample-Project-Config/packages.config

https://s3.amazonaws.com/vembu-bug-fix/BDR/4.1.0/Sample-Project-Issue/CreateAzureVM_JSON_Issue.zip

**Comment by weidongxu-microsoft** [comment]
@vigneshrams 

Is it a warning or error?

I rebuild the project and would get these (none report Newtonsoft.Json, even for warning)

```
1>------ Rebuild All started: Project: CreateAzureVM, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Microsoft.Azure.KeyVault.Core" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Microsoft.IdentityModel.Clients.ActiveDirectory" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(71,30,71,32): warning CS0168: The variable 'ex' is declared but never used
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(52,39,52,53): warning CS0169: The field 'AzureCloudUtil.m_ReourceGroup' is never used
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(50,30,50,43): warning CS0169: The field 'AzureCloudUtil.m_managedDisk' is never used
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(53,40,53,56): warning CS0169: The field 'AzureCloudUtil.m_VirtualMachine' is never used
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(48,33,48,43): warning CS0169: The field 'AzureCloudUtil.m_iNetwork' is never used
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(49,41,49,52): warning CS0169: The field 'AzureCloudUtil.m_vPublicIP' is never used
1>D:\CreateAzureVM_JSON_Issue\CreateAzureVM\AzureCloudUtil.cs(51,42,51,60): warning CS0169: The field 'AzureCloudUtil.m_NetworkInterface' is never used
1>  CreateAzureVM -> D:\CreateAzureVM_JSON_Issue\CreateAzureVM\bin\x64\Debug\CreateAzureVM.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

And it genereated `CreateAzureVM_JSON_Issue\CreateAzureVM\bin\x64\Debug\CreateAzureVM.dll`. So I assume mine is successful. Then I am not sure it is about environment or SDK.

There are several stackoverflow posts about certain conflict error https://stackoverflow.com/questions/22507189/could-not-load-file-or-assembly-newtonsoft-json-version-4-5-0-0-culture-neutr?rq=1

Maybe you can try say this?  `Update-Package –reinstall Newtonsoft.Json`

**Comment by vigneshrams** [comment]
@weidongxu-microsoft  Thanks for the time. 
It does not occur in Compilation time. that is an exception thrown when calling C# dll from C++ exe.

The issue comes when run the testsuite.exe (C++ Project). 

The project works this way,
TestSuite.exe(C++)-> CLRApp.dll (CLR\CLI) -> CreateAzureVM.dll (C#)

Try running the testsuite.exe with correct azure Auth file. You will get the issue.

**Comment by vigneshrams** [comment]
Below is the exception i am getting,
`Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Using Microsoft.Azure.Management.Fluent version 1.28.0.

Thanks

**Comment by weidongxu-microsoft** [comment]
@vigneshrams

Dirty solution:

You see `CreateAzureVM.dll.config` in build target folder (e.g. x64/Debug), copy it to name `TestSuiteApp.exe.config`,

That should work.

That config file is likely needed by system to tell it to override 6.0.0.0 to 10.0.0.0. I am not sure why VS does not do that to the exe (maybe there is a config hidden somewhere...).

**Comment by weidongxu-microsoft** [comment]
Close as I assume I've found the cause and provided the solution.
