### ISSUE TITLE
[BUG] Web App Service Logs Retention Days not set for Application Logging

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-libraries-for-net#947]
Reference this issue: https://github.com/Azure/azure-sdk-for-net/issues/9222

There are two log config classes here,  ApplicationLogsConfig stands for Application Logging, and HttpLogsConfig stands for Web Server Logging.

Code snippet to set **Application Logging**  Retention Days 
```
         .WithApplicationLogging()
                .WithLogLevel(LogLevel.Verbose)
                .WithApplicationLogsStoredOnStorageBlob("sasToken")
                .WithLogRetentionDays(30)
```

Code snippet to set **Web Server Logging** Retention Days 
```
     .WithWebServerLogging()
                .WithWebServerLogsStoredOnStorageBlob("sasToken")
                .WithLogRetentionDays(30)
```

Both above code snippets end up to call the same method **WebAppDiagnosticLogsImpl**(code as below). 

```
 public WebAppDiagnosticLogsImpl<FluentT, FluentImplT, DefAfterRegionT, DefAfterGroupT, UpdateT> WithLogRetentionDays(int retentionDays)
        {
            if (Inner.HttpLogs != null && Inner.HttpLogs.FileSystem != null && Inner.HttpLogs.FileSystem.Enabled.HasValue && Inner.HttpLogs.FileSystem.Enabled.Value)
            {
                Inner.HttpLogs.FileSystem.RetentionInDays = retentionDays;
            }
            if (Inner.HttpLogs != null && Inner.HttpLogs.AzureBlobStorage != null && Inner.HttpLogs.AzureBlobStorage.Enabled.HasValue && Inner.HttpLogs.AzureBlobStorage.Enabled.Value)
            {
                Inner.HttpLogs.AzureBlobStorage.RetentionInDays = retentionDays;
            }
            return this;
        }
```
This method updates Retention Days of **HttpLogsConfig**. It should not update Retention Days of **Application Logging**, right? Update Retention Days of Application Logging should use ApplicationLogsConfig, right?

**Comment by yaohaizh** [comment]
Thanks for reporting this issue. We will look into the problem. Thanks.

**Comment by tzhanl** [comment]
@yaohaizh how is the progress about this?

**Comment by yaohaizh** [comment]
@yungezz

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you pls have a look? thanks

**Comment by weidongxu-microsoft** [comment]
next release would be 1.34.1
