### ISSUE TITLE
How to get information about running image in linux container app

### ISSUE THREAD

**Issue by savpek** [Azure/azure-libraries-for-net#948]
**Query/Question**
To archieve my goal i need information about running image name and tag on azure container app. However when i get WebApps from library it seems it doesn't return any information about it. For example "SiteConfig" that should contain that information (attleast it contains it at ARM templates) seems to be always null. Is there way to do this?

***Why is this not a Bug or a feature Request?***
It could be feature request, but it also could possible but i don't get how to use current API correctly to get it done.

**Comment by yaohaizh** [comment]
@weidongxu-microsoft  could you help take a look at this issue? Thanks.

**Comment by weidongxu-microsoft** [comment]
@savpek 
You can take a look on IWebApp.LinuxFxVersion (the property is in base class IWebAppBase), it should contain something like "DOCKER|imageAndTag".

Let me know if you find it, and if possible provide more information (e.g. code snippet on creation of web app).

**Comment by savpek** [comment]
It's null for some reason:

![image](https://user-images.githubusercontent.com/481896/71827167-552ef080-30a8-11ea-964f-b66630ef8682.png)

```
            var servicePrincipal = new ServicePrincipalLoginInformation()
            {
                ClientId = _authOptions.Value.ClientId,
                ClientSecret = _authOptions.Value.ClientSecret
            };

            var azureCred = new AzureCredentials(servicePrincipal, _authOptions.Value.TenantId, AzureEnvironment.AzureGlobalCloud);

            var azure = Azure.Authenticate(azureCred).WithSubscription(_authOptions.Value.SubscriptionId);

            var webApps = azure.WebApps.List();

            var linuxContainerApp = webApps
                .Where(x => x.Inner.Kind == "app,linux,container").First();

            var fxVersion = linuxContainerApp.LinuxFxVersion ?? throw new InvalidOperationException();
```

Also tried to look through with `webApps.Where(x => x.LinuxFxVersion != null)` but that returns empty result.

**Comment by savpek** [comment]
`Microsoft.Azure.Management.Fluent`, version `1.29.1`

**Comment by weidongxu-microsoft** [comment]
Please do a `linuxContainerApp.Refresh()`, before calling `linuxContainerApp.LinuxFxVersion`.

`siteConfig` is retrieved from a second request done to a single webApp resource (hence it is not done for List, which retrieve all).

If you know the name, you can just use GetByResourceGroup or GetById.

**Comment by savpek** [comment]
Thanks 👍
