### ISSUE TITLE
[QUERY] How to get bearer token from Fluent SDK?

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-libraries-for-net#949]
I want use C# SDK to do below steps:
1. Use `SdkContext.AzureCredentialsFactory.FromDevice` to login, then I could get a AzureCredentials.
2. Use AzureCredentials to create Resource Group and Azure IoT Central Service
3. **I want to get a bearer token with the C# SDK**
4. I could use bearer token to call Rest API of Azure IoT Central Service

So my question is how to get bearer token from Fluent SDK? Thanks!

**Comment by qub1n** [comment]
You don't need a bearer. Just use credentials you received.

var client = RestClient
                .Configure()
                .WithEnvironment(env)
                .WithCredentials(credentials)
                .Build();

 var request = new HttpRequestMessage(HttpMethod.Get, url);
 await client.Credentials.ProcessHttpRequestAsync(request, cancellationToken);
var httpClient= new HttpClient();
var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);

**Comment by yaohaizh** [comment]
The AzureCredentials is not suppose to expose bearer token. If you need bearer token, see some examples: https://github.com/Azure/azure-libraries-for-net/blob/33261548d00322cd7795c1eaac9ca7298c94671b/src/ResourceManagement/ResourceManager/Authentication/MSITokenProvider.cs

**Comment by yaohaizh** [comment]
Close the issue as the required feature is not on the roadmap.  You can directly get token calling the REST URL with the authenticated pipeline. Thanks.

**Comment by daviddowning** [comment]
Thank you for your response.  I was able to get the Azure REST APIs working using the following code:

        private static string TestAuth()
        {
            // AzureCredentials credentials = new AzureCredentials(spLogin, TenantID, AzureEnvironment.AzureGlobalCloud);
            var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(
                ClientID,
                ClientSecret,
                TenantID,
                AzureEnvironment.AzureGlobalCloud);

            var client = RestClient
                .Configure()
                .WithEnvironment(AzureEnvironment.AzureGlobalCloud)
                .WithCredentials(credentials)
                .Build();

            CancellationToken cancellationToken = new CancellationToken();

            var request = new HttpRequestMessage(HttpMethod.Get, $"https://management.azure.com/subscriptions/{SubscriptionID}/resourcegroups/{ResourceGroupName}?api-version=2019-10-01");
            client.Credentials.ProcessHttpRequestAsync(request, cancellationToken).GetAwaiter().GetResult();
            var httpClient = new HttpClient();
            var response = httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).GetAwaiter().GetResult();

            return response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
        }
