### ISSUE TITLE
[QUERY] Create Application Insights using SDK ?

### ISSUE THREAD

**Issue by wangfeichen** [Azure/azure-libraries-for-net#952]
**Query/Question**
I see there have examples to create Application Insights on az / powershell but not for the SDK. So I questioned that is there have a way to create it using SDK ?

***Why is this not a Bug or a feature Request?***
A clear explanation of why is this not a bug or a feature request?

**Setup (please complete the following information if applicable):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Query Added
- [ ] Setup information Added

**Comment by yaohaizh** [comment]
The application insight will not be supported in the fluent lib roadmap. And it is not planned in any near future.
