### ISSUE TITLE
[BUG] Unable to get metrics for Azure SQL Server

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-libraries-for-net#962]
**Describe the bug**
When trying to get the metric definitions for `subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Sql/servers/promitor` it fails due to API version.

***Exception or Stack Trace***
`[12:54:14 FTL] NoRegisteredProviderFound: No registered resource provider found for location 'westeurope' and API version
'2018-01-01' for type 'servers'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview, 2015-05-01-preview,
2017-03-01-preview, 2017-10-01-preview, 2018-06-01-preview, 2019-06-01-preview'. The supported locations are 'australiacentral,
australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus, eastus2,
francecentral, japaneast, japanwest, koreacentral, koreasouth, northcentralus, northeurope, southafricanorth, southcentralus,
southindia, southeastasia, switzerlandnorth, uaenorth, uksouth, ukwest, westcentralus, westeurope, westindia, westus, westus2'.
`

**To Reproduce**
1. Get metric definitions for Azure SQL Server via `[].MetricDefinitions.ListByResourceAsync(resourceId);`
   2. Example`subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor/providers/Microsoft.Sql/servers/promitor`

***Code Snippet***
```csharp
var credentials = _azureCredentialsFactory.FromServicePrincipal(applicationId, applicationSecret, tenantId, azureCloud);

var monitorHandler = new AzureResourceManagerThrottlingRequestHandler(tenantId, subscriptionId, applicationId, runtimeMetricsCollector, logger);
_authenticatedAzureSubscription = Azure.Configure().WithDelegatingHandler(monitorHandler).Authenticate(credentials).WithSubscription(subscriptionId);
var metricsDefinitions = await _authenticatedAzureSubscription.MetricDefinitions.ListByResourceAsync(resourceId);
```

**Expected behavior**
Return a list of metrics for Azure SQL Server according to https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftsqlservers

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used: 1.30.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by weidongxu-microsoft** [comment]
@tomkerkhove 

Is this issue persistent or intermittent?

I tried a westeurope (`"location": "westeurope", "id": "/subscriptions/###/resourceGroups/rg-weidxu/providers/Microsoft.Sql/servers/sql1weidxu"`) sqlserver with 1.30, that works OK.

If you still see this error, could you also give me a logging (with redact)?
https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-concepts?view=azure-dotnet#logs-and-tracing

```
Method: GET, RequestUri: 'https://management.azure.com//subscriptions/###/resourceGroups/rg-weidxu/providers/Microsoft.Sql/servers/sql1weidxu/providers/microsoft.insights/metricDefinitions?api-version=2018-01-01'

Response:
{
  "value": [
    {
      "id": "/subscriptions/###/resourceGroups/rg-weidxu/providers/Microsoft.Sql/servers/sql1weidxu/providers/microsoft.insights/metricdefinitions/dtu_consumption_percent",
      "resourceId": "/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/rg-weidxu/providers/Microsoft.Sql/servers/sql1weidxu",
      "namespace": "Microsoft.Sql/servers",
      "name": {
        "value": "dtu_consumption_percent",
        "localizedValue": "DTU percentage"
      },
      "displayDescription": "DTU percentage",
      "isDimensionRequired": true,
      "unit": "Percent",
      "primaryAggregationType": "Average",
      "supportedAggregationTypes": [
        "Average",
        "Maximum",
        "Minimum"
      ],
      "metricAvailabilities": [
```

**Comment by tomkerkhove** [comment]
It must have been a transient thing then indeed, however, they only return following metrics:
- `dtu_consumption_percent`
- `storage_used`
-`dtu_used`

While the docs are saying it should return more:https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftsqlservers

But this might be more of an Azure Monitor issue than SDK?

**Comment by tomkerkhove** [comment]
Hm not there yet, will provide tracing if I get it up and running.

**Comment by tomkerkhove** [comment]
Turns out SQL Server had additional needs like a dimension requirement which I found out with the additional telemetry.

Thanks!
