### ISSUE TITLE
[BUG] While adding secrets to KeyVault, an exception occured "Operation returned an invalid status code 'Forbidden'"

### ISSUE THREAD

**Issue by WojtaX** [Azure/azure-libraries-for-net#971]
**Describe the bug**
While adding secret to KeyVault, I'm getting an exception "Operation returned an invalid status code 'Forbidden", required permissions are added to key vault access policies. This is a similar bug to https://github.com/Azure/azure-libraries-for-net/issues/367

***Exception or Stack Trace***
Exception has occurred: CLR/Microsoft.Azure.KeyVault.Models.KeyVaultErrorException
An exception of type 'Microsoft.Azure.KeyVault.Models.KeyVaultErrorException' occurred in Environment.dll but was not handled in user code: 'Operation returned an invalid status code 'Forbidden''
   at Environment.Shared.ROPHelper.GetValueOrThrow[A,a](FSharpResult`2 x)
   at Createall.clo@50-3.Invoke(TargetParameter _arg4) in \DeploymentScripts\createall.fsx:line 64
   at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target)

**To Reproduce**
-Create KeyVault resource 
-Add secret to created KeyVault

***Code Snippet***
let mutable vault = azure.Vaults.Define(name).WithRegion(region)
.WithExistingResourceGroup(group)
.DefineAccessPolicy()
    .AllowSecretAllPermissions()
.Create()

vault.Secrets.Define(name).WithValue(defaultValue).Create()

**Expected behavior**
Properly added secrets to azure key vault without exception.

**Comment by weidongxu-microsoft** [comment]
@WojtaX 

It appears that the access policy is not defined property.

Let me know the SDK version. In 1.30 SDK I think this will not even compile.

The next method after DefineAccessPolicy should be one of these. Basically it defines access for **WHO**.

```
        /// <summary>
        /// Specifies the object ID of the Active Directory identity this access policy is for.
        /// </summary>
        /// <param name="objectId">The object ID of the AD identity.</param>
        /// <return>The next stage of access policy definition.</return>
        Microsoft.Azure.Management.KeyVault.Fluent.AccessPolicy.Definition.IWithAttach<ParentT> ForObjectId(string objectId);

        /// <summary>
        /// Specifies the Active Directory user this access policy is for.
        /// </summary>
        /// <param name="user">The AD user object.</param>
        /// <return>The next stage of access policy definition.</return>
        Microsoft.Azure.Management.KeyVault.Fluent.AccessPolicy.Definition.IWithAttach<ParentT> ForUser(IActiveDirectoryUser user);

        /// <summary>
        /// Specifies the Active Directory user this access policy is for.
        /// </summary>
        /// <param name="userPrincipalName">The user principal name of the AD user.</param>
        /// <return>The next stage of access policy definition.</return>
        Microsoft.Azure.Management.KeyVault.Fluent.AccessPolicy.Definition.IWithAttach<ParentT> ForUser(string userPrincipalName);

        /// <summary>
        /// Specifies the Active Directory group this access policy is for.
        /// </summary>
        /// <param name="activeDirectoryGroup">The AD group object.</param>
        /// <return>The next stage of access policy definition.</return>
        Microsoft.Azure.Management.KeyVault.Fluent.AccessPolicy.Definition.IWithAttach<ParentT> ForGroup(IActiveDirectoryGroup activeDirectoryGroup);

        /// <summary>
        /// Specifies the Active Directory service principal this access policy is for.
        /// </summary>
        /// <param name="servicePrincipal">The AD service principal object.</param>
        /// <return>The next stage of access policy definition.</return>
        Microsoft.Azure.Management.KeyVault.Fluent.AccessPolicy.Definition.IWithAttach<ParentT> ForServicePrincipal(IServicePrincipal servicePrincipal);

        /// <summary>
        /// Specifies the Active Directory service principal this access policy is for.
        /// </summary>
        /// <param name="servicePrincipalName">The service principal name of the AD user.</param>
        /// <return>The next stage of access policy definition.</return>
        Microsoft.Azure.Management.KeyVault.Fluent.AccessPolicy.Definition.IWithAttach<ParentT> ForServicePrincipal(string servicePrincipalName);
```

**Comment by WojtaX** [comment]
I'm using 1.30 SDK. Problem is solved, I didn't add AD application to KeyVault access policies.
