### ISSUE TITLE
How do I create new 'App Service Managed Certificates' using the library

### ISSUE THREAD

**Issue by vijay-singh-16** [Azure/azure-libraries-for-net#972]
I want to automate creation and binding of SSL certificates to my website's subdomains. Currently I am doing it manually on Azure Portal using the option shown in the attached image.

![managed_cert](https://user-images.githubusercontent.com/60729120/73912255-0d36ff80-48da-11ea-9346-12cf6865e4a3.jpg)

I tried quite a bit but not able to find any api/method in the library to do so neither I am able to find any help by searching the Internet. Can some one help me on this?

**Comment by yaohaizh** [comment]
Thanks for reporting.

**Comment by weidongxu-microsoft** [comment]
@vijay-singh-16 

Please see if this help.

If you already have domain created and bound to webapp, you can start with line 125.

https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/AppService/ManageWebAppWithDomainSsl.cs

**Comment by vijay-singh-16** [comment]
@weidongxu-microsoft 
The code provided in the sample is about creating a `Self Signed Certificate` but my question is about creating some `Managed Certificates` for which a button is available on Azure Portal as shown in the picture attached in the original question.

Please Help!

**Comment by weidongxu-microsoft** [comment]
@vijay-singh-16 

I see.

The creation of Managed Certificates is not formally supported yet. I will check on the schedule for it.

Meanwhile it is possible to do it an informal way (note this is more likely to be broken when version upgrade).

Sample code, assume you have domain, sub-domain, webapp ready.

```
            // get dependent resources
            var domain = azure.AppServices.AppServiceDomains.GetById(AZURE_DOMAIN_ID);
            var appServicePlan = azure.AppServices.AppServicePlans.GetByResourceGroup(RESOURCE_GROUP, APP_SERVICE_PLAN_NAME);
            string subdomain = SUBDOMAIN;

            // bind sub-domain to webapp
            var webapp = azure.WebApps.GetByResourceGroup(RESOURCE_GROUP, WEBAPP_NAME);
            webapp.Update()
                .DefineHostnameBinding()
                    .WithAzureManagedDomain(domain)
                    .WithSubDomain(subdomain)
                    .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
                    .Attach()
                .Apply();
 
            // now create managed certificate
            var certToCreate = azure.AppServices.AppServiceCertificates.Define(subdomain)
                .WithRegion(REGION)
                .WithExistingResourceGroup(RESOURCE_GROUP)
                .WithExistingCertificateOrder(null);
            // this 3 line is informal code
            // when feature is formally supported it should to be updated
            (certToCreate as IAppServiceCertificate).Inner.ServerFarmId = appServicePlan.Id;
            (certToCreate as IAppServiceCertificate).Inner.CanonicalName = subdomain;
            (certToCreate as IAppServiceCertificate).Inner.Password = "";
            var cert = certToCreate.Create();
```

**Comment by vijay-singh-16** [comment]
@weidongxu-microsoft 
Great! this works :)
> note this is more likely to be broken when version upgrade

I will keep an eye on the version upgrade.

**Comment by anuraj** [comment]
@weidongxu-microsoft @vijay-singh-16 I tried the mentioned code. But I am getting a bad request error from `certToCreate.Create()` method.

Here is the stack trace.

> Microsoft.Azure.Management.AppService.Fluent.Models.DefaultErrorResponseException
>   HResult=0x80131500
>   Message=Operation returned an invalid status code 'BadRequest'
>   Source=Microsoft.Azure.Management.AppService.Fluent
>   StackTrace:
>    at Microsoft.Azure.Management.AppService.Fluent.CertificatesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Azure.Management.AppService.Fluent.CertificatesOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Azure.Management.AppService.Fluent.AppServiceCertificateImpl.<CreateResourceAsync>d__12.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Create()

Please help.

**Comment by weidongxu-microsoft** [comment]
@anuraj 

Please provide the logging https://github.com/Azure/azure-libraries-for-net#logging

Service behavior might changed.

**Comment by anuraj** [comment]
@weidongxu-microsoft I tried it. But I am getting the same error - Operation returned an invalid status code 'BadRequest' in the `TraceError` method. Anything else which help me to troubleshoot the problem? In the Logger I only implemented `TraceError` method.

**Comment by anuraj** [comment]
@weidongxu-microsoft I added the following code and it kind of started working 
```
(certificateToCreate as IAppServiceCertificate).Inner.HostNames = hostNames;
(certificateToCreate as IAppServiceCertificate).Inner.Kind = "SniEnabled";
```
I mean I am getting an Accepted Status code - which is throwing an exception. But it is creating the certificate. Is there any update on the official API?

**Comment by weidongxu-microsoft** [comment]
@anuraj 

It is unlikely to have new feature supported in this SDK. It is going to be replaced by the new generation of .NET SDK.

Notification

For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by ajuch** [comment]
@weidongxu-microsoft 

I have the same problem and I am not very satisfied with the workaround. Do I understand it correctly that the old Azure.Management.Fluent will not get the functionality to create App Service Managed Certificates and that the new libraries don't support App Services at all yet? At least the library overview says that: https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html Is the only solution to use the Rest API or to use Java?

**Comment by weidongxu-microsoft** [comment]
@anuraj 

You can use this API in this Fluent SDK, this is not a workaround, though you need to understand how the [REST API](https://docs.microsoft.com/en-us/rest/api/appservice/certificates/create-or-update) works. Note that api-version is not same, so there could be some property in REST API doc that you did not find in SDK.
```
azure.WebApps.Manager.Inner.Certificates.CreateOrUpdateAsync
```

The new SDK is all ready, just going to be released.
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/websites/Azure.ResourceManager.AppService

**Comment by ajuch** [comment]
@weidongxu-microsoft

The problem isn't the casting to the `IAppServiceCertificate` interface, I could live with that. The problem is that as @anuraj said, the `Create` method throws a `DefaultErrorResponseException` because the Rest API returns 202 Accepted instead of 200 Ok. So I'd have to catch that exception, check if the response status is 202 and if it is, get the location and time to wait and poll that in a loop until the response is there.

The [Rest API docs](https://docs.microsoft.com/en-us/rest/api/appservice/certificates/create-or-update) say that 200 is returned, am I doing something wrong or is there a mistake in the API docs?

Do you have an ETA for the new SDK?

Thanks!

**Comment by weidongxu-microsoft** [comment]
@ajuch

I see. If spec says 200 but service returns 202, it would be a bigger problem. And a new SDK might not able to solve that (as all SDK follow the spec on REST API).

If you can share your use case or your code, I will try to reproduce and notify service.

**Comment by ajuch** [comment]
@weidongxu-microsoft 

Yes, the code is part of our deployment script in F#. It creates a lot of azure resources and among it a webapp. This part creates ssl bindings for our domain:

``` fsharp
  let createAppServiceManagedCertificate() =
    let crtDef =
      azure.AppServices.AppServiceCertificates
        .Define(portalDomain)
        .WithRegion(location)
        .WithExistingResourceGroup(webrg)
        .WithExistingCertificateOrder(null)
    // hack, see https://github.com/Azure/azure-libraries-for-net/issues/972#issuecomment-584172414
    let inner = (crtDef :?> IAppServiceCertificate).Inner
    inner.ServerFarmId <- sp.Id
    inner.CanonicalName <- portalDomain
    inner.Password <- ""
    let cert =
      try
        crtDef.Create()
      with
      | :? DefaultErrorResponseException as exn when exn.Response.StatusCode = HttpStatusCode.Accepted ->
          printfn "Got a response with status accepted %s" exn.Response.Content
          printfn "request was: content %s uri %s headers %s" exn.Request.Content (exn.Request.RequestUri.ToString()) (exn.Request.Headers.AsFormattedString())
          // service responds with status 202, library probably expects 200
          Thread.Sleep(10000) // wait for the certificate to be created
          azure.AppServices.AppServiceCertificates.GetByResourceGroup(webrg, portalDomain)
      | x -> raise x

    cert.Thumbprint

  let crtThumbprint = createAppServiceManagedCertificate()  
  webapp.Update().DefineSslBinding().ForHostname(portalDomain).WithExistingCertificate(crtThumbprint).WithSniBasedSsl().Attach().Apply() |> ignore

```

And the corresponding output on CI is:

```
Got a response with status accepted 
request was: content {
  "properties": {
    "password": "",
    "serverFarmId": "/subscriptions/[subscriptionid]/resourceGroups/[rg]/providers/Microsoft.Web/serverfarms/[sp]",
    "canonicalName": "[domain]"
  },
  "location": "westeurope",
  "tags": {}
} uri https://management.azure.com/subscriptions/[subscriptionid]/resourceGroups/[rg]/providers/Microsoft.Web/certificates/[domain]?api-version=2019-08-01 headers {x-ms-client-request-id=System.String[],Accept-Language=System.String[],Authorization=System.String[],User-Agent=System.String[],Content-Type=System.String[],Content-Length=System.String[]}
```

The 10s wait seems to be necessary, without it (and often even with it), the `AppServiceCertificates.GetByResourceGroup` call fails with 404. I just found that the response content is empty, but probably the response headers contain the interesting information (Location, Retry-After).

Please tell me if you need more information!

**Comment by weidongxu-microsoft** [comment]
@anuraj 

Yeah, service definitely messed it up.

Response is
```
Response:
  headers:
    Cache-Control : no-cache
    Pragma : no-cache
    Location : https://management.azure.com/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/javarg-weidxu1/providers/Microsoft.Web/certificates/cert1weidxu/operationresults/f59cc0a8-725e-4ad9-ba9b-361693862593?api-version=2019-08-01
    Retry-After : 15
    Strict-Transport-Security : max-age=31536000; includeSubDomains
    Server : Microsoft-IIS/10.0
    X-AspNet-Version : 4.0.30319
    X-Powered-By : ASP.NET
    x-ms-ratelimit-remaining-subscription-writes : 1199
    x-ms-request-id : b9fe9386-5a1b-41eb-adb6-3a12f06bcb41
    x-ms-correlation-request-id : b9fe9386-5a1b-41eb-adb6-3a12f06bcb41
    x-ms-routing-request-id : SOUTHEASTASIA:20220118T123256Z:b9fe9386-5a1b-41eb-adb6-3a12f06bcb41
    X-Content-Type-Options : nosniff
    Date : Tue, 18 Jan 2022 12:32:55 GMT
```

Given `Location` and `Retry-After` header, this is definitely a long-running operation, but their spec does not define that way.

You can use this code to create the certificate without worry about the exception. This is ARM's generic solution to the CRUD of Azure resource.
```
           var cert = azure.GenericResources.Define("cert1weidxu")
                .WithRegion(Region.USEast)
                .WithExistingResourceGroup("javarg-weidxu1")
                .WithResourceType("certificates")
                .WithProviderNamespace("Microsoft.Web")
                .WithoutPlan()
                .WithApiVersion("2021-03-01")
                .WithProperties(new Dictionary<string, string>()
                {
                    { "serverFarmId", "<appservice_id>" },
                    { "canonicalName", "<domain>" }
                })
                .Create();
```

**Comment by weidongxu-microsoft** [comment]
Issue to spec https://github.com/Azure/azure-rest-api-specs/issues/17383

**Comment by ajuch** [comment]
Great, thank you for your help! That code fixes my problem!

**Comment by InteXX** [comment]
@weidongxu-microsoft 

> The creation of Managed Certificates is not formally supported yet. I will check on the schedule for it.

Is this feature available by now in 2025? I'm trying to use the new ResourcManager SDK to create a Managed Certificate and bind it to a newly-added Custom Domain, but I'm not having much luck.

My full question is [here](https://github.com/Azure/azure-sdk-for-net/issues/48323).

Thanks.

**Comment by vijay-singh-16** [comment]
Hi @InteXX,
Sometime back I created a helper class to handle the scenario you have mentioned. Putting it here so that you can pick the relevent stuff you need from it. It's in C# though.

```
using Azure;
using Azure.ResourceManager;
using Azure.ResourceManager.AppService;
using Azure.ResourceManager.AppService.Models;
using Azure.ResourceManager.Resources;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;

namespace AzureAppServiceManager.Helpers
{
	public interface IAzureAppServiceManager
	{
		Task<bool> GetHostBoundStatusAsync(string appName, string siteHostName);

		Task RestartAppAsync(string appName);

		Task<bool> StartAppAsync(string appName);

		Task<bool> StopAppAsync(string appName);

		Task<bool> BindHostAsync(string appName, string siteHostName);

		Task<bool> UnbindHostAsync(string appName, string siteHostName);

		Task<bool> GetSslCertificateBoundStatusAsync(string certName);

		Task<bool> GetSslCertificateCreateStatusAsync(string certName);

		Task<bool> CreateAndBindManagedSslCertificateAsync(string appName, string siteHostName, string certImportPassword);

		Task<bool> DeleteSslCertificateAsync(string certName);
	}

	public class AzureWebsiteManager : IAzureAppServiceManager
	{
		const string _resourceGroupName = "My-RG";
		readonly ILogger _logger;
		readonly ArmClient _client;

		public AzureWebsiteManager(ILoggerFactory loggerFactory, ICredentialProvider credentialProvider)
		{
			_logger = loggerFactory.CreateLogger<AzureWebsiteManager>();
			_client = new ArmClient(credentialProvider.GetCredential());
		}

		async Task<WebSiteResource> GetAppAsync(string appName)
		{
			SubscriptionResource subscription = await _client.GetDefaultSubscriptionAsync();
			ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync(_resourceGroupName);
			return await resourceGroup.GetWebSites().GetAsync(appName);
		}

		public async Task<bool> StartAppAsync(string appName)
		{
			var app = await GetAppAsync(appName);

			if (app == null)
				throw new ApplicationException($"Could not find app service '{appName}'.");

			var res = await app.StartAsync();
			return res.Status == 200;
		}

		public async Task<bool> StopAppAsync(string appName)
		{
			var app = await GetAppAsync(appName);

			if (app == null)
				throw new ApplicationException($"Could not find app service '{appName}'.");

			var res = await app.StopAsync();
			return res.Status == 200;
		}

		public async Task RestartAppAsync(string appName)
		{
			_logger.LogInformation($"Restarting WebApp - {appName}...");

			var app = await GetAppAsync(appName);
			await app.RestartAsync();

			_logger.LogInformation($"WebApp restarted.");
		}

		public async Task<bool> GetHostBoundStatusAsync(string appName, string siteHostName)
		{
			var app = await GetAppAsync(appName);
			var binding = await app.GetSiteHostNameBindings().ExistsAsync(siteHostName);
			return binding != null && binding.Value;
		}

		public async Task<bool> BindHostAsync(string appName, string siteHostName)
		{
			if (string.IsNullOrWhiteSpace(siteHostName))
				throw new ArgumentException("Host name cannot be null or empty.", nameof(siteHostName));

			var app = await GetAppAsync(appName);

			_logger.LogInformation($"Binding host '{siteHostName}' to WebApp '{appName}'...");

			var bindingData = new HostNameBindingData
			{
				SiteName = siteHostName,
				HostNameType = AppServiceHostNameType.Verified,
				CustomHostNameDnsRecordType = CustomHostNameDnsRecordType.CName
			};

			try
			{
				await app.GetSiteHostNameBindings().CreateOrUpdateAsync(WaitUntil.Completed, siteHostName, bindingData);
				_logger.LogInformation("Host binding completed successfully.");
				return true;
			}
			catch (RequestFailedException ex)
			{
				_logger.LogError($"Failed to bind host: {ex.Message}");
			}

			return false;
		}

		public async Task<bool> UnbindHostAsync(string appName, string siteHostName)
		{
			if (string.IsNullOrWhiteSpace(siteHostName))
				return true;

			var app = await GetAppAsync(appName);

			_logger.LogInformation($"Un-binding host '{siteHostName}' from WebApp '{appName}'...");

			try
			{
				var binding = await app.GetSiteHostNameBindingAsync(siteHostName);
				await binding.Value.DeleteAsync(WaitUntil.Completed);
				_logger.LogInformation("Host un-binding completed successfully.");
				return true;
			}
			catch (RequestFailedException ex)
			{
				_logger.LogError($"Failed to un-bind host: {ex.Message}");
			}

			return false;
		}

		public async Task<bool> GetSslCertificateCreateStatusAsync(string certName)
		{
			return await GetSslCertificateAsync(certName) != null;
		}

		async Task<AppCertificateResource?> GetSslCertificateAsync(string certName)
		{
			SubscriptionResource subscription = await _client.GetDefaultSubscriptionAsync();
			ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync(_resourceGroupName);
			try
			{
				return await resourceGroup.GetAppCertificates().GetAsync(certName);
			}
			catch (Exception)
			{
				return null;
			}
		}

		public async Task<bool> GetSslCertificateBoundStatusAsync(string siteHostName)
		{
			var cert = await GetSslCertificateAsync(siteHostName);
			if (cert is null)
				return false;

			return cert.Data.HostNames.Any(r => r == siteHostName);
		}

		public async Task<bool> CreateAndBindManagedSslCertificateAsync(string appName, string siteHostName, string certImportPassword)
		{
			try
			{
				SubscriptionResource subscription = await _client.GetDefaultSubscriptionAsync();
				ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync(_resourceGroupName);

				var app = await GetAppAsync(appName);
				if (app == null)
				{
					Console.WriteLine($"WebApp '{appName}' not found in Resource Group '{resourceGroup.Data.Name}'.");
					return false;
				}

				string certificateName = await CreateSslCertificate(resourceGroup, app, siteHostName, certImportPassword);

				await BindSslCertificateToHost(resourceGroup, app, siteHostName, certificateName);

				return true;
			}
			catch (Exception ex)
			{
				Console.WriteLine($"An error occurred: {ex.Message}");
				return false;
			}
		}

		public async Task<bool> DeleteSslCertificateAsync(string certName)
		{
			var cert = await GetSslCertificateAsync(certName);
			if (cert != null)
			{
				Console.WriteLine("Managed SSL Certificate deletion initiated.");
				await cert.DeleteAsync(WaitUntil.Completed);
			}

			return true;
		}

		static async Task<string> CreateSslCertificate(ResourceGroupResource resourceGroup, WebSiteResource app, string siteHostName, string certImportPassword)
		{
			// Define the name for the certificate
			var certificateName = $"{siteHostName}";

			// Check if the certificate already exists
			var existsResp = await resourceGroup.GetAppCertificates().ExistsAsync(certificateName);
			if (existsResp != null && existsResp.Value)
			{
				Console.WriteLine($"Certificate '{certificateName}' already exists.");
			}
			else
			{
				// Create the Managed Certificate
				Console.WriteLine($"Creating a Managed SSL Certificate for '{siteHostName}'...");

				// Define the SiteCertificateData
				AppCertificateData certificateData = new AppCertificateData(app.Data.Location)
				{
					HostNames = { siteHostName },
					Kind = "ManagedCertificate",
					CanonicalName = siteHostName,
					Password = certImportPassword,
					ServerFarmId = app.Data.AppServicePlanId
				};

				// Create or Update the Site Certificate
				// Wait until the certificate is issued
				Console.WriteLine("Managed SSL Certificate creation initiated.");
				Console.WriteLine("Waiting for the Managed SSL Certificate to be issued...");

				int retries = 5;
				int sleepTime = 5000; // 5 sec
				ArmOperation<AppCertificateResource>? certOperation = null;
				while (certOperation is null && retries >= 0)
				{
					try
					{
						var certificateCollection = resourceGroup.GetAppCertificates();
						certOperation = await certificateCollection.CreateOrUpdateAsync(WaitUntil.Completed, certificateName, certificateData);
					}
					catch (RequestFailedException ex)
					{
						Console.WriteLine(ex.Message);
						retries--;
						if (ex.Status == 202)
							Thread.Sleep(sleepTime);
						else
							break;
					}
				}

				if (certOperation != null)
					await certOperation.WaitForCompletionAsync();

				Console.WriteLine("Managed SSL Certificate successfully issued.");
			}

			return certificateName;
		}

		static async Task BindSslCertificateToHost(ResourceGroupResource resourceGroup, WebSiteResource app, string siteHostName, string certificateName)
		{
			// Retrieve the certificate
			AppCertificateResource managedCertificate = await resourceGroup.GetAppCertificates().GetAsync(certificateName);

			if (!managedCertificate.HasData)
				throw new ArgumentException($"Certificate with name {certificateName} does not exist.");

			var sitePatch = new SitePatchInfo();

			// Retrieve current hostnames with SSL states
			var hostNameSslStates = app.Data.HostNameSslStates;

			// Find the specific hostname
			var hostnameSslState = hostNameSslStates.FirstOrDefault(h => h.Name.Equals(siteHostName, StringComparison.OrdinalIgnoreCase));

			if (hostnameSslState == null)
				throw new ApplicationException($"Hostname '{siteHostName}' is not bound to the WebApp.");

			// Update the SSL binding
			hostnameSslState.SslState = HostNameBindingSslState.SniEnabled;
			hostnameSslState.ThumbprintString = managedCertificate.Data.ThumbprintString;
			hostnameSslState.ToUpdate = true;

			// Apply the SSL binding update
			sitePatch.HostNameSslStates.Add(hostnameSslState);
			Console.WriteLine("Binding the SSL Certificate to the host as SNI...");

			await app.UpdateAsync(sitePatch);

			Console.WriteLine("SSL Certificate bound to the host successfully.");
		}
	}
}
```

**Comment by InteXX** [comment]
@vijay-singh-16 

Thanks for that; I'm hopeful it'll work.

I'm unable to try it, however, due to the 404 I'm getting, as described [here](https://github.com/Azure/azure-sdk-for-net/issues/48348).

Functionally, it appears the only difference between this and what I've been trying is initialization of the `AppCertificateData` instance:

_yours_
```
AppCertificateData certificateData = new AppCertificateData(app.Data.Location)
{
    HostNames = { siteHostName },
    Kind = "ManagedCertificate",
    CanonicalName = siteHostName,
    Password = certImportPassword,
    ServerFarmId = app.Data.AppServicePlanId
};
```
_mine (previously)_
```
Dim oCertificateData = New AppCertificateData(oLocation) With {
  .Password = sPassword
}
oCertificateData.HostNames.Add(sCertificateName)
```
Unfortunately, the 404 is preventing me from proceeding. Is it working for you?

In any case, I'm VERY curious about how you obtained that `"ManagedCertificate"` value for the `.Kind` property. I'm not finding anything on that, and the [official documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.appcertificatedata.kind) is just plain wrong.

Did you discover it by accident?

**Comment by vijay-singh-16** [comment]
> Unfortunately, the 404 is preventing me from proceeding. Is it working for you?

Yes.

> In any case, I'm VERY curious about how you obtained that "ManagedCertificate" value for the .Kind property. I'm not finding anything on that, and the [official documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.appcertificatedata.kind) is just plain wrong.
Did you discover it by accident?

I don't remember now. But it took me a lot of digging through the internet, for several days, to arrive at this helper class.

**Comment by InteXX** [comment]
>> Is it working for you?
>
> Yes

Hm, actually that's even worse—a problem that only shows up here and there.

> it took me a lot of digging through the internet, for several days, to arrive at this helper class

Ugh. It's boondoggles just like that that inspired my suggestion [here](https://github.com/Azure/azure-sdk-for-net/issues/36309#issuecomment-1576696349), nearly two years ago. I don't know if there's been any progress on it, but I hope so.

Thanks again for making that code available. It's a nice piece of work.

**Comment by InteXX** [comment]
@vijay-singh-16 

I'm pleased to report that I've been able to get it working using your code. It appears that the difference between our two approaches isn't the construction of the `AppCertificateData` instance, as I'd previously suspected, but rather the way that the subscription is retrieved.

That sounds odd, I know, but there it is.

Here's the difference:

_Yours_
```
oClient = New ArmClient(oCredential)
oSubscription = Await oClient.GetDefaultSubscriptionAsync
oResourceGroup = Await oSubscription.GetResourceGroupAsync(sResourceGroup)
oCertificates = oResourceGroup.GetAppCertificates
```
_Mine_
```
oClient = New ArmClient(oCredential)
oResourceIdentifier = ResourceGroupResource.CreateResourceIdentifier(sSubscriptionId, sResourceGroup)
oResourceGroupResponse = Await oClient.GetResourceGroupResource(oResourceIdentifier).GetAsync
oCertificates = oResourceGroupResponse.Value.GetAppCertificates
```

Your version gets the default subscription for the account, whereas mine gets it by a specific Subscription ID via a `ResourceIdentifier` instance. That doesn't sound like it should make a difference, but apparently it does. 404s ensue when doing it the latter way. (The SDK is probably constructing the URL incorrectly—I'll have to check on that.)

Or perhaps it's in the way that the Resource Group instance is obtained. I don't know. All I know is that thanks to you I'm able to create and bind a managed certificate. This represents a significant milestone in my project. Thank you.

Are you on SO? I'd love to credit you for the answer if so. Here's my Q&A: https://stackoverflow.com/q/79440934

**Comment by vijay-singh-16** [comment]
@InteXX That's a great news. I am glad that my code helped you.

> Are you on SO? I'd love to credit you for the answer if so. 

Thanks, that's very kind of you but I never had an account on SO.

**Comment by InteXX** [comment]
@vijay-singh-16 

> I never had an account on SO

You're probably better off without one. It's a jungle over there.

**Comment by InteXX** [comment]
@vijay-singh-16 

I posted the answer to my own question [over at SO](https://stackoverflow.com/a/79477005).

FYI I discovered during my testing that the `Password` and `Kind` properties on the `AppCertificateData` instance aren't required for successful issuance of a Managed Certificate. Only `CanonicalName` and `ServerFarmId` are required.

BTW... the earlier `404 NotFound` I was getting went away for some reason. I don't know why—it just stopped.

In its place, however, was a `400 BadRequest`, due to the fact that I hadn't yet added a Custom Domain, which makes sense. In fact, even the error message contained that instruction.

After I added the domain, both versions of the subscription retrieval code—yours and mine—worked just fine. Go figure.

**Comment by vijay-singh-16** [comment]
> FYI I discovered during my testing that the Password and Kind properties on the AppCertificateData instance aren't required for successful issuance of a Managed Certificate. Only CanonicalName and ServerFarmId are required.
> BTW... the earlier 404 NotFound I was getting went away for some reason. I don't know why—it just stopped.
> 
> In its place, however, was a 400 BadRequest, due to the fact that I hadn't yet added a Custom Domain, which makes sense. In fact, even the error message contained that instruction.
> 
> After I added the domain, both versions of the subscription retrieval code—yours and mine—worked just fine. Go figure.

I will definitely try this. Thanks.
