### ISSUE TITLE
[BUG] IGenericResource.ApiVersion is always null

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-libraries-for-net#978]
**Describe the bug**
When retrieving an `IGenericResource `instance from `genericResources.ListByResourceGroupAsync`  `ApiVersion` property is null.

**To Reproduce**
The resource already exists and when showing ARM template in Azure `ApiVersion` is filled.
```
var resources = await genericResources.ListByResourceGroupAsync(Config.ResourceGroup);
foreach (var resource in resources)
{
    // resource.ApiVersion is always null
    await resource.Update().WithApiVersion(resource.ApiVersion).WithTags(new DefaultTags()).ApplyAsync();
}
```
**Expected behavior**
`IGenericResource.ApiVersion` should be filled with the correct `ApiVersion` that was used when the resource was created or updated.

**Setup (please complete the following information):**
 - Microsoft.Azure.Management.Fluent 1.31.0
 - Microsoft.Azure.Management.ResourceManager.Fluent 1.31.0

**Comment by yaohaizh** [comment]
@xccc-msft could you help take a look at this issue? Thanks.

**Comment by xccc-msft** [comment]
@Rookian This is not bug here. `IGenericResource.ApiVersion` is always null here because the service will not provide `ApiVersion` in the response. For your code snippet, you can still go ahead with the update operation. We will set value for `ApiVersion` from SDK side if we find the user has no information about it.

**Comment by yaohaizh** [comment]
@xccc-msft given this, the API version should not be part of the resource property, but rather the property of the endpoint(REST API). Mind about how to model this behavior? Thanks.

**Comment by Rookian** [comment]
> @Rookian This is not bug here. `IGenericResource.ApiVersion` is always null here because the service will not provide `ApiVersion` in the response. For your code snippet, you can still go ahead with the update operation. We will set value for `ApiVersion` from SDK side if we find the user has no information about it.

```
foreach (var resource in resources)
{
    await resource.Update().WithApiVersion(resource.ApiVersion).WithTags(new DefaultTags()).ApplyAsync();
}
```
The code still does not work:

> Microsoft.Rest.Azure.CloudException: Payload is not valid: 'properties' cannot be empty
>    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, GenericResourceInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, GenericResourceInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.CreateOrUpdateAsync(IResourcesOperations operations, String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, GenericResourceInner parameters, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourceImpl.CreateResourceAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.ApplyAsync(CancellationToken cancellationToken, Boolean multiThreaded)

How do I update all my resource tags within a resource group?

**Comment by xccc-msft** [comment]
@Rookian For now, you can have simple workaround as below according to the exception you met.
```csharp
foreach (var resource in resources)
{
    var res = await resourceManager.GenericResources.GetByIdAsync(resource.Id);
    await res.Update().WithApiVersion(res.ApiVersion).WithProperties(res.Properties).WithTags(new DefaultTags()).ApplyAsync();
}
```
If you don't want to take extra GET request, please refer [how we prepare ApiVersion in SDK](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/ResourceManager/GenericResource/GenericResourcesImpl.cs#L276-L293)
And use below code to update the tags
```csharp
foreach (var resource in resources)
{
    await genericResources.Inner.UpdateByIdAsync(resource.Id, "api-version", new GenericResourceInner
                        {
                            Tags = new DefaultTags()
                        });
}
```

**Comment by xccc-msft** [comment]
@yaohaizh We can handle this when the users try to get it via `resource.ApiVersion`. Otherwise, we can remove the ApiVersion from `IGenericResource` as I also agree that the ApiVersion is not resource property. It will depend on if we want to keep exposing this property to the users.

**Comment by Rookian** [comment]
@xccc-msft Thanks your workaround is working.

Is there any reason why I can't tag smartDetectorAlertRules?

Code:
```
var types = new[] {"Microsoft.AlertsManagement/smartDetectorAlertRules"};
foreach (var resource in resources)
{
    var res = await genericResources.GetByIdAsync(resource.Id);
    if (!types.Contains(res.Type))
    {
        await res.Update().WithApiVersion(res.ApiVersion).WithProperties(res.Properties).WithTags(new DefaultTags()).ApplyAsync();
    }
}
```
Error:

> Microsoft.Rest.Azure.CloudException: The client '24042968-460b-4d11-a242-16c1ace02fa6' with object id '24042968-460b-4d11-a242-16c1ace02fa6' has permission to perform action 'microsoft.alertsManagement/smartDetectorAlertRules/write' on scope '/subscriptions/2c69d0bd-f267-485e-971e-232c7d8b5b80/resourcegroups/econ-dev/providers/microsoft.alertsManagement/smartDetectorAlertRules/Failure Anomalies - swo-bit-ba-econ-ai-dev'; however, it does not have permission to perform action 'read' on the linked scope(s) '/subscriptions/2c69d0bd-f267-485e-971e-232c7d8b5b80/resourcegroups/swo-sb-oneip-dev01-rg/providers/microsoft.insights/actiongroups/application%20insights%20smart%20detection' or the linked scope(s) are invalid.

**Comment by xccc-msft** [comment]
@Rookian According to the exception, it's like your client does not have permission to perform action 'read' on the resource from Application Insight action group. You might need to use role-base access control for your client, please refer these two links 
1. [Resources, roles, and access control in Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/resources-roles-access-control)
2. [Roles, permissions, and security in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/roles-permissions-security)

**Comment by Rookian** [comment]
> @Rookian According to the exception, it's like your client does not have permission to perform action 'read' on the resource from Application Insight action group. You might need to use role-base access control for your client, please refer these two links
> 
> 1. [Resources, roles, and access control in Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/resources-roles-access-control)
> 2. [Roles, permissions, and security in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/roles-permissions-security)

It seems like that the action group is a global resource (swo-sb-oneip-dev01-rg). It is also not a part of my resource group (econ-dev).

How can I filter out global resources that are not directly belonging to my resource group?

**Comment by xccc-msft** [comment]
@Rookian You might want to use `ResourceUtils.groupFromResourceId(id)` to verify the resource group from resource ID.

**Comment by Rookian** [comment]
> @Rookian You might want to use `ResourceUtils.GroupFromResourceId(id)` to verify the resource group from resource ID.
This won't help me, because the the given resource belongs to my resource group.

I have a resource (smartDetectorAlertRules) in my resource group whose location is "global" and is "hidden" according to the Azure UI . In addition the resource has kinda "link" to a resource that does not belong to my resource group. This is the reason why my update statement fails.

I could filter out this resource based on the type "smartDetectorAlertRules", but I am not sure if this is a good idea.

Is there a better way to filter out such a resource?

**Comment by xccc-msft** [comment]
@Rookian You should be able to find IDs of other resources in 'res.Properties' before update the tags. You might want to do some patterning searching to find out those IDs and verify whether they belong to your resource group via `ResourceUtils.GroupFromResourceId(id)`.

**Comment by Rookian** [comment]
Got it working: 

```csharp
public async Task ApplyTagsToAllResources()
{
    var resources = await _genericResources.ListByResourceGroupAsync(Config.ResourceGroup);
    foreach (var resource in resources)
    {
        var res = await _genericResources.GetByIdAsync(resource.Id);

        var (hasForeignLinks, foreignResourceGroups) = HasLinkToForeignResourceGroup(res.Properties);
        if (hasForeignLinks)
        {
            ConsoleEx.WriteWarningLine(
                $"Skipped resource '{res.Name}' with Id '{res.Id}', because it has link to other resource groups ({string.Join(", ", foreignResourceGroups)}).");
            continue;
        }

        await res.Update()
            .WithApiVersion(res.ApiVersion)
            .WithProperties(res.Properties)
            .WithTags(new Dictionary<string, string>
            {
                {"environment",  Config.Environment.ToString().ToLowerInvariant()},
                {"service",  Config.BusinessServiceName},
                {"company",  "swo"},
                {"department",  "bit"},
                {"section",  "ba" }
            })
            .ApplyAsync();
    }
}

private static (bool hasForeignLinks, List<string> foreignResourceGroups) HasLinkToForeignResourceGroup(object properties)
{
    // resource format: /subscriptions/{0}/resourcegroups/{1}/providers/...

    var matches = new List<string>();

    if (!(properties is JObject props))
        return (false, matches);

    var value = props.ToString();

    if (!value.Contains("/subscriptions"))
        return (false, matches);

    var strings = value.Split("/subscriptions").Skip(1);

    foreach (var s in strings)
    {
        var list = s.Split("/", StringSplitOptions.RemoveEmptyEntries);

        if (list.Length < 3)
            continue;

        if (list[1] != "resourcegroups")
            continue;

        matches.Add(list[2]);
    }

    var hasForeignLinks = matches.Any(x => !x.Equals(Config.ResourceGroup, StringComparison.InvariantCultureIgnoreCase));

    var foreignResourceGroups = matches
        .Where(x => !x.Equals(Config.ResourceGroup, StringComparison.InvariantCultureIgnoreCase))
        .Distinct()
        .ToList();

    return (hasForeignLinks, foreignResourceGroups);
}
```

**Comment by xccc-msft** [comment]
@Rookian Great. Thanks for sharing the code snippet, I think it looks good.
