### ISSUE TITLE
[BUG] Cannot update secondary region failover priority

### ISSUE THREAD

**Issue by markjbrown** [Azure/azure-libraries-for-net#980]
**Describe the bug**
I am unable to change the failover priority for a Cosmos account by calling FailoverPriorityChangeAsync()

***Exception or Stack Trace***
N/A

**To Reproduce**
- Create a Cosmos account with regions (West US 2, East US 2, South Central US)
- Run the code snippet below.

***Code Snippet***
List<Location> failoverPolicies = new List<Location>
{
    new Location { LocationName = "West US 2", IsZoneRedundant = false, FailoverPriority = 0},
    new Location { LocationName = "South Central US", IsZoneRedundant = false, FailoverPriority = 1},
    new Location { LocationName = "East US 2", IsZoneRedundant = false, FailoverPriority = 2}
};
await azure.CosmosDBAccounts.FailoverPriorityChangeAsync(resourceGroupName, accountName, failoverPolicies);

**Expected behavior**
The failover priority should update to the policy executed above.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS 2019
 - Version of the Library used: 1.31

**Additional context**
This code is able to initiate a write region failover. It is just not able to change the priority for the secondary read regions.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ChenTanyi** [comment]
@markjbrown After my test, the request has already been sent to the server, but the service didn't deal successfully with it.

POST `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{accountName}/failoverPriorityChange`
Body:
```json
{
	"failoverPolicies": [{
		"locationName": "West US 2",
		"failoverPriority": 0
	}, {
		"locationName": "South Central US",
		"failoverPriority": 1
	}, {
		"locationName": "East US 2",
		"failoverPriority": 2
	}]
}
```

**Comment by ChenTanyi** [comment]
@markjbrown And I can update successfully, for three regions. (West US 2, West Central US, East US 2)
The following got from server. (it is originally 0, 1, 2 in sequence)
![image](https://user-images.githubusercontent.com/15213781/74818174-222f7c00-5339-11ea-82e5-96a3c30333ac.png)

**Comment by markjbrown** [comment]
Thanks @ChenTanyi will investigate with portal team.

Will close.
