### ISSUE TITLE
[BUG] Unable to update index policy on SqlContainer

### ISSUE THREAD

**Issue by markjbrown** [Azure/azure-libraries-for-net#981]
**Describe the bug**
I am unable to update a SqlContainer with a modified IndexPolicy in which I am removing an ExcludedPath from the IndexPolicy

***Exception or Stack Trace***
N/A

**To Reproduce**
- Create a Cosmos Sql Account, database and Container that has an ExcludedPath of "/myPathNotToIndex/*"
- Run the code snippet below.

***Code Snippet***
await azure.CosmosDBAccounts.GetByResourceGroup(resourceGroupName, accountName).Update()
    .UpdateSqlDatabase(databaseName)
        .UpdateSqlContainer(containerName)
            .UpdateIndexingPolicy()
                .WithoutExcludedPath("/myPathNotToIndex/*") //add back to index
                .Parent()
            .Parent()
        .Parent()
    .ApplyAsync();

**Expected behavior**
Should update the IndexPolicy to no longer have this as an ExcludedPath.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/800166/74708893-a1567000-51d2-11ea-9264-6bdf5fedf626.PNG)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : VS 2019
 - Version of the Library used: 1.31

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by ChenTanyi** [comment]
@markjbrown I cannot reproduce your problem, the without is successful in the unit test and my test again. 

In:
https://github.com/Azure/azure-libraries-for-net/blob/4a330a0a3ae401957e8c0cfc12398372014db60f/Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs#L332-L342
And:
https://github.com/Azure/azure-libraries-for-net/blob/4a330a0a3ae401957e8c0cfc12398372014db60f/Tests/Fluent.Tests/CosmosDB/CosmosDBTest.cs#L349
And My test again:
![image](https://user-images.githubusercontent.com/15213781/74823138-35464a00-5341-11ea-80e2-91279fbdf2dc.png)

Actually, I can see it at portal like your screen shot. You could contact with portal about it, I don't know the relationship between portal and service.

**Comment by markjbrown** [comment]
Thanks @ChenTanyi. Will investigate with Portal.

Closing.
