### ISSUE TITLE
[FEATURE REQ] Export to ARM template

### ISSUE THREAD

**Issue by alexwilsh** [Azure/azure-libraries-for-net#982]
**Is your feature request related to a problem? Please describe.**
We want to build a framework within a company to provide ARM templates created based on our internal practices including security concerns, naming conventions, etc. Our code is on C# .NET Core. 
Fluent can be used to define Azure resources in C# code. But we need to provide ARM template as an output. 
I couldn't find this feature existing yet.

**Describe the solution you'd like**
I want to export defined Fluent Azure resources into ready-to-deploy ARM template.

**Describe alternatives you've considered**
Alternative solution for us is to build our own ResourceManager API or create own ARM template export based on Fluent models.

**Comment by weidongxu-microsoft** [comment]
@alexwilsh 

You might want to try this:

```
            var rg = azure.ResourceGroups.GetByName(RESOURCE_GROUP);
            var template = rg.ExportTemplate(ResourceGroupExportTemplateOptions.IncludeBoth);
            string json = template.TemplateJson;
```

**Comment by alexwilsh** [comment]
@weidongxu-microsoft 

I assume this will work only if resources are already deployed.
But, is there a way to get ARM template for defined in code resources but not deployed yet?

In our case, we want to have infrastructure as a code using SDK, but at the same time we want to have the opportunity to see the result in ARM template prior to deployment.

**Comment by weidongxu-microsoft** [comment]
@alexwilsh

I am not sure it is doable in SDK.

Currently SDK creates resource by making REST API call step by step (likely multiple calls for a single resource), not by creating ARM template and deploy them.

@yaohaizh

**Comment by alexwilsh** [comment]
@weidongxu-microsoft 
Ah, I got it. 
If that is the case, then SDK won’t fit our needs. We’ll easily hit the limit of API calls like we did with the raw Rest API last time.
Thanks for the help.
