### ISSUE TITLE
[BUG] Image Gallery Version API doesn't return ReplicationStatus

### ISSUE THREAD

**Issue by chrisalexander** [Azure/azure-libraries-for-net#998]
**Describe the bug**
When requesting a Gallery Image Version from the SDK, the ReplicationStatus field is null and there is no way to request that data.

**Expected behavior**
Able to request the ReplicationStatus field be populated.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

    IAzure azure = ...;
    var galleryClient = azure.GalleryImageVersions;
    var version = await galleryClient.GetByGalleryImageAsync("ValidResourceGroupName", "ValidGalleryName", "ValidImageName", "ValidImageVersion");

Then inspect:

    version.ReplicationStatus;

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Fluent 1.30.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Functions v3 runtime (.NET Core 3.0)
 - IDE and version : Visual Studio 16.4.5 (2019)

**Comment by chrisalexander** [comment]
Thank you! Will this make it into the next release, and do you know when that will be?

**Comment by xccc-msft** [comment]
@chrisalexander We plan to release on March 20.

**Comment by chrisalexander** [comment]
Thanks

**Comment by chrisalexander** [comment]
Is this fix in [this release](https://techcommunity.microsoft.com/t5/azure-sdk/april-2020-azure-sdk-release/ba-p/1302937)? Cheers

**Comment by xccc-msft** [comment]
@chrisalexander This has been released via [v1.32.0](https://github.com/Azure/azure-libraries-for-net/releases/tag/Fluent-v1.32.0). Now the latest is [v1.33.0](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/).

**Comment by chrisalexander** [comment]
Cool thanks
